### ISSUE TITLE
"Specify building types" gets asked multiple times for same way

### ISSUE THREAD

**Issue by habi** [streetcomplete/StreetComplete#4736] opened 2023-01-06 10:22 UTC
*Not my issue*, but seen based on a note.
Looking at new notes in Switzerland, I found https://www.openstreetmap.org/note/3504850 in which the user 'complains' about being asked multiple times to specify the building type.
Looking at the history of [the building](https//www.openstreetmap.org/way/219375181/) in JOSM, I see that the user was asked to specify the building type 25 (!) times.
![Screenshot from 2023-01-06 11-20-29](https://user-images.githubusercontent.com/1651235/210984568-747083a7-d7c8-4a93-a05c-ba0ccdb17db8.png)

**How to Reproduce**
As this is not my issue (and I'm using an iOS mobile) I have no idea how to reproduce the issue.

**Expected Behavior**
Building type specification is only asked once.

**Versions affected**
StreetComplete 50.1

**Comment by Helium314** [comment] 2023-01-06 10:29
might be a duplicate of  / related to #4258

**Comment by westnordost** [comment] 2023-01-06 12:12
Hm yes, that's very very likely a duplicate of #4258. That the same quest is answered this many times is somewhat unique though - I guess the user was just persistent and the quest would just not go away.

**Closed** 2023-01-06 12:12 UTC
Labels: bug, duplicate

**Comment by habi** [comment] 2023-01-06 12:35
> might be a duplicate of  / related to #4258

Yes, probably.
Sorry I didn't look through old issues.
