### ISSUE TITLE
NAPTAN Verification: "Does this bus stop exist?"

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#2566] opened 2021-02-10 09:26 UTC
### General
Affected tag(s) to be modified/added: [naptan:verified=*](https://wiki.openstreetmap.org/wiki/Key:naptan:verified) [public_transport=platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform), [highway=bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) and [ref](https://wiki.openstreetmap.org/wiki/Key:ref) to be added if missing
Question asked: **Does this bus stop exist?**

In 2009, there was a large [import](https://wiki.openstreetmap.org/wiki/NaPTAN/Import) of bus stops in the United Kingdom which has gone largely unverified.
In the database, there are largely two types of bus stop objects which need verification;
 - [Unmarked Bus Stops](https://overpass-turbo.eu/s/13s3) (27794 at time of writing - often not tagged with `highway=bus_stop` or `public_transport=platform`, often don't render)
   - These are tagged with [naptan:BusStopType=CUS](https://wiki.openstreetmap.org/wiki/Key:naptan:BusStopType) (among other tags).
   - As per the original [import guidelines](https://wiki.openstreetmap.org/wiki/NaPTAN/Tag_mappings#Bus.2FCoach), they weren't to be tagged with `highway=bus_stop` until "confirmed in person"
   - Since many aren't verified, there are [15149](https://overpass-turbo.eu/s/13s7) (54%) nodes with `naptan:BusStopType=CUS` without a `highway=*` tag. 
- [Tagged Bus Stops](https://overpass-turbo.eu/s/13s1) (175367 at time of writing, might overlap with Unmarked Bus Stops)
  - Whilst verifying, we can upgrade the node to Public Transport v2, which is very simple in its minimal requirements.
  - PBv2 just requires [public_transport=platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform) to be added.
  - There are [105986](https://overpass-turbo.eu/s/13sa) nodes with `naptan:verified=no` + `highway=bus_stop` which have yet to be upgraded to Public Transport v2. That's 60% of the eligible nodes.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** 

1. query for [`highway=bus_stop` + `naptan:verified=no`](https://overpass-turbo.eu/s/13s1) and [`naptan:BusStopType=CUS` + `naptan:verified=no`](https://overpass-turbo.eu/s/13s3)
2. ask the end user to confirm is a bus stop exists here and to confirm the `name` (use `naptan:CommonName` as backup, filling where needed) and `ref` (use `naptan:NaptanCode` as backup, filling where needed). It's common for a bus stop to have it's name and naptan code on show in the UK.
3. If a user confirms, set the following tags: `naptan:verified=yes` + `highway=bus_stop` + `public_transport=platform`.
4. If a user denies, create a note or delete the node. Depending if they say no bus stop exists or if the data doesn't match.

**Metadata needed:** 
Only in the United Kingdom

**Proposed GUI:**

**Comment by TurnrDev** [comment] 2021-02-10 09:27
Not sure if this is going to be spam or not. I think it depends on the area.

**Comment by matkoniecz** [comment] 2021-02-11 17:55
With 240 000 https://taginfo.openstreetmap.org/tags/naptan%3Averified=no#overview it seems to be worth implementing even if limited to a single country.

> Not sure if this is going to be spam or not. I think it depends on the area.

AFAIK this import was supposed to be verified by on the ground survey, so resolving it would be always providing useful info.

**Comment by peternewman** [comment] 2021-02-12 02:35
As per previous issues here, apparently hail and ride stops need to be on OSM (I think for route routing or something apparently) but may not exist on the ground:
https://taginfo.openstreetmap.org/tags/naptan%3ABusStopType=HAR#overview

SC ignores `physically_present=no` now for shelter/bench quests, should it either skip those during this verification or add the `physically_present=no` tag or something else?

**Comment by matkoniecz** [comment] 2021-02-12 08:53
Right, that may be a problem.

How `physically_present=no` can be distinguished from nonexisting bus stop? It seems to require asking people living nearby or riding on a bus, making it far less suitable for StreetComplete.

**Comment by FloEdelmann** [comment] 2021-02-12 08:56
See also #1784. #1793 and https://github.com/streetcomplete/StreetComplete/issues/2074#issuecomment-687588876.

**Comment by peternewman** [comment] 2021-02-12 17:44
>     3. If a user confirms, set the following tags: `naptan:verified=yes`

One of the other threads @FloEdelmann links to suggests this should only be done if the naptan data itself has been checked, rather than the bus stop presence.

We could add `highway=bus_stop` + `public_transport=platform` but then what do you do if it's not actually there (to stop it re-appearing in SC forever)? Add a note?

> How `physically_present=no` can be distinguished from nonexisting bus stop? It seems to require asking people living nearby or riding on a bus, making it far less suitable for StreetComplete.

No idea, skipping HAR and CUS would avoid that issue I think, as I'd assume the other bus stops should always exist in real life.

Possibly OT/for another quest, but I wonder if there would be benefit in a general upgrade tags quest, a lot of these tags would be offered in iD automatically, but it's nice to verify in person that the item is still really there (e.g. I accept the upgrade if I've tagged shelter/bench on a stop). SC could use this as a source of existence data, I guess upgrading the tags if it exists, or deleting the item if it doesn't.

**Comment by westnordost** [comment] 2021-02-15 19:01
Okay, so this can only be done (in StreetComplete) if the British community is okay with that `naptan:verified=no` bus stop nodes are deleted if a surveyor can't find the bus stop. 

So, this needs to be discussed and decided there. I'll close this issue here for now. When you post a link to the result of a discussion that took place on this issue, I can reopen it.

**Comment by westnordost** [comment] 2021-02-15 19:03
Or is it known for all `naptan:verified=no` nodes if they are supposed to be hail and ride (not physically present) bus stops already? If that is the case, a quest could be created that only asks for those that are not supposed to be hail and ride bus stops.

**Comment by TurnrDev** [comment] 2021-02-15 20:05
@westnordost I'm planning on starting a chat on the talk-gb mailing list about the topic. I just keep getting distracted. I'll let you know when the deed is done.

**Comment by peternewman** [comment] 2021-02-16 12:48
> Okay, so this can only be done (in StreetComplete) if the British community is okay with that `naptan:verified=no` bus stop nodes are deleted if a surveyor can't find the bus stop.

Although obviously that can happen already via the shelter/bench/tactile checks.

If I'm reading it right, then 14% of naptan:verified (ignoring yes/no) have naptan:BusStopType although that's still potentially 36,000 stops (depending on how many are tagged no, which on-average is 95%):
https://taginfo.openstreetmap.org.uk/keys/naptan:BusStopType#combinations

> @westnordost I'm planning on starting a chat on the talk-gb mailing list about the topic. I just keep getting distracted. I'll let you know when the deed is done.

https://lists.openstreetmap.org/pipermail/talk-gb/2021-February/026264.html

**Comment by peternewman** [comment] 2021-02-20 21:04
> Affected tag(s) to be modified/added: [naptan:verified=*](https://wiki.openstreetmap.org/wiki/Key:naptan:verified) [public_transport=platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform), [highway=bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) and [ref](https://wiki.openstreetmap.org/wiki/Key:ref) to be added if missing

Is there any reason we shouldn't add `public_transport=platform` and `highway=bus_stop` to stops too when we answer the existing tactile, shelter and bench questions? iD also prompts to upgrade with `bus=yes` so likewise with that. I'm aware some of these are tagged to make the quest show, but often not all of them. Otherwise I normally personally try and avoid upgrading the tags until I've confirmed the stop exists and the easiest way I can tell I've done that is based on having answered the shelter/bench/tactile quests for the stop.

**Comment by TurnrDev** [comment] 2021-02-20 21:54
I can't think of any. Except `bus=yes` on the bus stop is wrong and there's currently a PR in action to resolve iD's tagging of it

**Comment by peternewman** [comment] 2021-02-20 22:11
> Except `bus=yes` on the bus stop is wrong and there's currently a PR in action to resolve iD's tagging of it

:facepalm: I'll stop upgrading then! It's been doing that for quite a while.

You mean this one I assume https://github.com/openstreetmap/id-tagging-schema/pull/132 ?

**Comment by TurnrDev** [comment] 2021-02-20 23:00
That's the one, the error is the result of an incorrect addition on the wiki page when PTv2 was added to the tagging schema, and nobody noticed or cared for a long time until I brought it up. The fix is relatively easy when it comes to bus stops but some more changes are needed (or not, I've not fully reviewed the PR yet) before it's good enough for the rest. 

Feel free to continue upgrading, the `bus=yes` doesn't cause harm, it's just not needed.

**Comment by westnordost** [comment] 2021-02-21 20:19
Could someone summarize what was the conclusion on the mailing list, if any?
See my last two posts about the eligibility of recording this information with StreetComplete.

**Comment by kymckay** [comment] 2021-02-24 22:15
This is an idea I've considered suggesting before too ever since I carried out the [more recent import](https://www.openstreetmap.org/user/TheEditor101/diary/390283) of NaPTAN data for the Aberdeen area.

Just to note, `naptan:verified` is intended to be removed upon verification - not set to `yes`. See the original source for that here: https://wiki.openstreetmap.org/wiki/NaPTAN/Surveying_and_Merging_NaPTAN_and_OSM_data.

**Comment by kymckay** [comment] 2021-02-24 22:39
Also as a general note, I think a stop should only be considered verified if the `naptan:AtcoCode`  is confirmed to match the data in OSM (acting as the primary key used to join the data sets).

Certainly in Aberdeen this was the main code present at bus stops when I surveyed them. There would be a full code on the top left of the timetable if there was one, and partial code on the sign itself - the partial part being the end since the start of the code is for the area.

**Comment by Cj-Malone** [comment] 2021-02-26 11:34
I'm ready to close this [note](https://www.openstreetmap.org/note/2383023), but I thought I'd let you know in case you wanted to save the images. The "YourNextBus" number corresponds to `naptan:AtcoCode`. (you can send an sms to get the time table) @westnordost

Personally, I think there are lots of issues with NaPTAN in OSM, if I were a benevolent dictator I'd strip it all out, and either re import it or leave it out completely. Realistically, I think StreetComplete could only do a slightly modified "Does this still exist?" quest, to check `naptan:AtcoCode`, historically I've preferred to keep the node and `naptan:AtcoCode` but remove the physical tags (`public_transport=platform` and `highway=bus_stop`) but it's like pulling teeth, if there isn't going to be wide spread automated maintenance we need to start removing it.

**Comment by westnordost** [comment] 2021-02-26 13:21
AtcoCode? Yet another new thing. Let's stick to one topic in this one thread. I still need input on whether it is okay for the British community if StreetComplete did the following:

1. Look for all `(highway=bus_stop or public_transport=platform) and naptan:verified=no and naptan:BusStopType!~CUS|HAL`
2. Depending on what the user sees, tag either `naptan:verified=yes` or **DELETE THE NODE**

To me it looks like discussions so far around the Naptan topic seemed to veer of quickly and bring into play other naptan tags so the original question still hasn't been answered. I need a concrete answer.

**Comment by kymckay** [comment] 2021-02-26 14:05
I guess this is what I was intending to say, I don't believe those two points are quite correct based on my previous research and consultation of the OSM UK mailing list:

1. Those conditions seem fine, but you'd also need to ensure there is a `naptan:AtcoCode` tag since this is what the surveyor must verify for the quest.
2. The tag should not be set to `yes` if following the original import's intention for it. It should be removed entirely.

If the bus stop is not found, it is a good idea to retain the node with the `naptan:AtcoCode` tag and tag it with another tag to indicate such so that future reimports can conflate that and not re-add a missing stop that isn't updated yet in the naptan dataset.

**Comment by westnordost** [comment] 2021-02-26 14:32
> Those conditions seem fine, but you'd also need to ensure there is a naptan:AtcoCode tag since this is what the surveyor must verify for the quest.

Ok, so it is 
`(highway=bus_stop or public_transport=platform) and naptan:verified=no and naptan:BusStopType!~CUS|HAL and naptan:AtcoCode`

> and tag it with another tag to indicate such so that future reimports can conflate that and not re-add a missing stop that isn't updated yet in the naptan dataset.

And which tag would this be?

**Comment by kymckay** [comment] 2021-02-26 14:44
> And which tag would this be?

The [original guidelines wiki page](https://wiki.openstreetmap.org/wiki/NaPTAN/Surveying_and_Merging_NaPTAN_and_OSM_data#physically_present) seems to suggest the following use of `physically_present`. However, that is a point I'm uncertain fits with its wider usage.

**Comment by kymckay** [comment] 2021-02-26 15:11
As a more concise summary of my understanding of NaPTAN data (since conversation is a bit all over the place):

- `naptan:AtcoCode` is an important foreign key to link the data with OSM (it is confirmed signed on the ground for survey in at least two regions).
- Presence of `naptan:verified=no` indicates that `naptan:AtcoCode` has not been confirmed on the ground. Under the closed world assumption, the lack of this tag should mean it is verified. However, perhaps as @Cj-Malone suggests this quest idea is better off introducing a new `check_date:` subtab and acting in that way (cannot be misinterpreted).
- `naptan:CommonName` mentioned in the OP is often analogous to the `name` tag, but not always. Personally I'd just have the quest ask for the name before verifying the Atco code.
- `naptan:NaptanCode` also mentioned in the OP is another foreign key which I don't believe belongs in `ref` as suggested. Unknown if this is signed on the ground anywhere.

As far as the OSM UK community. From previous experience I imagine floating this quest idea out would obtain approval easily enough once the details are ironed out. However, I think the main unknown is whether all regions of the UK have the same code signed on their bus stops (AtcoCode vs NaptanCode).

**Comment by TurnrDev** [comment] 2021-02-26 15:33
>     2\. The tag should not be set to `yes` if following the original import's intention for it. It should be removed entirely.

I believe their created ambiguity (has it been verified or did someone accidentally del the tag?) and that explicitly setting `yes` is better 👍

**Comment by TurnrDev** [comment] 2021-02-26 15:35
> > and tag it with another tag to indicate such so that future reimports can conflate that and not re-add a missing stop that isn't updated yet in the naptan dataset.
> 
> And which tag would this be?

I've been using `disused:highway=bus_stop` + `disused:public_transport=platform`

**Comment by TurnrDev** [comment] 2021-02-26 15:38
>     * `naptan:NaptanCode` also mentioned in the OP is another foreign key which I don't believe belongs in `ref` as suggested. Unknown if this is signed on the ground anywhere.

It's signed on many stops here (Kent) instead to of the AtcoCode. I was surprised to find out its different elsewhere. We have a text service here where you can text the NaptanCode and they'll tell you when the next bus is

**Comment by kymckay** [comment] 2021-02-27 10:17
> I believe their created ambiguity (has it been verified or did someone accidentally del the tag?) and that explicitly setting `yes` is better 👍

Yeah I think because of the historical ambiguity the removal of it and introduction of a `check_date:` subtag would make the most sense as it's much more explicit and follows an existing scheme. Obviously would need to approve with the UK community, but seems uncontroversial.

> So the answer is no. Maybe we should ask which is visible on the task and set that one to ref?

This is good to confirm. Not a bad idea, but we'd probably have to prioritise one in the case that some stops could have *both* signed. Also if neither code matches the one on the ground that complicates things too if we wanted the user to enter what they see.

I still think a quest is feasible, but all of these little considerations and edge cases are what have stopped me proposing/coding it in the past too 😄

**Comment by Cj-Malone** [comment] 2021-04-28 11:37
If we break this down some more, one actionable quest would be "Is this bus stop marked?". Asked on nodes with `naptan:BusStopType=CUS`, without `highway=bus_stop`, `public_transport=platform` and `physically_present`. If it is marked it gets `highway=bus_stop`, `public_transport=platform` and `physically_present=yes`. If it isn't marked it gets `physically_present=no`.

This is almost exactly what was wanted after the original import (excluding PTv2 tags).

**Comment by TurnrDev** [comment] 2021-04-28 12:25
Would marked include painted lines and nothing else?

**Comment by Cj-Malone** [comment] 2021-04-28 14:19
> Would marked include painted lines and nothing else?

Yeah, if it's clearly a bus stop even without a flag pole, it's still a bus stop.

**Comment by peternewman** [comment] 2021-04-28 14:41
> If it is marked it gets `highway=bus_stop`, `public_transport=platform` and `physically_present=yes`.

Any reason not to add `bus=yes` too or whatever the normal upgrade suggestion in iD is?

**Comment by matkoniecz** [comment] 2021-04-28 16:07
> Any reason not to add bus=yes too or whatever the normal upgrade suggestion in iD is?

(1) SC is in general not changing tags in such way (even discardable keys are not dropped)
(2) it is completely not needed edit anyway, `highway=bus_stop` provides all necessary info already

**Comment by Cj-Malone** [comment] 2021-04-28 22:19
> Any reason not to add `bus=yes` too or whatever the normal upgrade suggestion in iD is?

`bus=yes` goes on the `public_transport=stop_position`, not `public_transport=platform`

> (1) SC is in general not changing tags in such way (even discardable keys are not dropped)
> (2) it is completely not needed edit anyway, `highway=bus_stop` provides all necessary info already

Yeah, OK, I don't disagree. Just applying `highway=bus_stop` is good enough, `public_transport=platform` could be added if/when a stop is upgraded to PTv2.

**Comment by kymckay** [comment] 2021-04-29 10:20
> If we break this down some more, one actionable quest would be "Is this bus stop marked?"

Yeah this is a good focused task I can't see being problematic with the data in mind :+1: This issue is perhaps suffering from mixing multiple ideas. I have some thoughts on another actionable task to deal with verifying the data itself is correct on physical stops, will open a new issue.

**Comment by matkoniecz** [comment] 2021-07-15 17:57
@TurnrDev Has it been clarified with UK community what should be done with ` naptan:verified=no` bus stops with no trace found be survey? Is it OK to delete them? Or is correct solution to tag them with some tag? Something else?

Or is answer is "it depends/requires more serious research/not solvable by just field survey/requires asking people is bus stopping there"?

**Comment by TurnrDev** [comment] 2021-07-15 18:00
> @TurnrDev Has it been clarified with UK community what should be done with ` naptan:verified=no` bus stops with no trace found be survey? Is it OK to delete them? Or is correct solution to tag them with some tag? Something else?

Unfortunately nobody could come to a consensus and very few people participated to the conversation. 

> Or is answer is "it depends/requires more serious research/not solvable by just field survey/requires asking people is bus stopping there"?

I have such a bus stop outside my new house. The opposite side has a physical presence but the near side, none, but the bus still stops.

**Comment by matkoniecz** [comment] 2021-07-15 18:24
> Unfortunately nobody could come to a consensus

So no matter what would StreetComplete do people would be considering it as a mistake? It sounds like fundamental blocker for that idea.

And one more reason to never make imports with various `fixme=` stuff as it almost never gets resolved.

**Comment by westnordost** [comment] 2021-07-15 21:03
Alright then.

**Closed by westnordost** 2021-07-15 21:03 UTC
Labels: blocked, feedback required

**Comment by matkoniecz** [comment] 2021-07-16 05:35
In case that people will decide what should be done with that, and edit could be done by surveying (no checking of extra resources needed) it obviously can be reopened.
