### ISSUE TITLE
Bicycle overlay, selecting "it's a footway" does not set the tag 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5596] opened 2024-04-26 21:55 UTC
**How to Reproduce**
- Enable the bicycle overlay 
- Tap on a `highway=path` on the map
- Select the footway symbol "not designated for cyclists (cycling may still be allowed)":

![Screenshot_2024-04-26-23-37-20-546_de.westnordost.streetcomplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/614929/777a8cf5-1ca2-4054-acf4-7c666023b439)

- store it
- Select the same path again
- Observe that "path or trail" is selected again, not the footway

**Expected Behavior**
If I select that it's a footway, it should be stored and reflected when I select it again. 

**What is stored in the database?**

Actually SC only sets the check date for the cycling when I do that, which is odd, because I don't actually confirm or deny doing that, that cycling is possible. 

![Screenshot_2024-04-26-22-57-55-755-edit_org.mozilla.firefox.jpg](https://github.com/streetcomplete/StreetComplete/assets/614929/e7c52dca-2ece-4560-bc4e-09ab7d61bd85)

**Versions affected**
v57.2

**Comment by westnordost** [comment] 2024-04-27 11:50
Oh no, this definitely looks like a bug!

**Comment by westnordost** [comment] 2024-04-27 12:02
Hmm, the problem is that the first two choices overlap. A path is also not designated for cyclists. I guess the second option should be treated as primarily a footway, even though it doesn't say it explicitly, the icon looks like it.

**Comment by RubenKelevra** [comment] 2024-04-27 12:07
> Hmm, the problem is that the first two choices overlap. A path is also not designated for cyclists. I guess the second option should be treated as primarily a footway, even though it doesn't say it explicitly, the icon looks like it.

Yeah, that was my expectation, that StreetComplete would tag `highway=footway` there.

While there's an overlap I don't think a path is a footway and the other way around.

Footway is designed and build for pedestrians while a path was created by just walking there, without explicit planning.

**Comment by westnordost** [comment] 2024-04-27 12:36
What to interpret `highway = path + foot = no`, though? (On parsing, this is coerced to `bicycle=yes` + `foot=no`)

I.e. an oddly tagged path not designated for cyclists but definitely not a footway.

**Comment by westnordost** [comment] 2024-04-27 12:44
There are
- 18099 `highway = path` + `foot = no`
- 721 `highway = footway` + `foot = no`

So at least the first combination is tagged sometimes. Point being, such ways can hardly be called "footways not designated for cyclists" - they don't seem to be footways at all.

**Comment by RubenKelevra** [comment] 2024-04-27 12:51
> There are
> - 18099 `highway = path` + `foot = no`
> - 721 `highway = footway` + `foot = no`
> 
> So at least the first combination is tagged sometimes. Point being, such ways can hardly be called "footways not designated for cyclists" - they don't seem to be footways at all.

Sure. But I think it's fair to assume that access=no means actually that public access is now allowed.

Something like `access=private` or `access=permit` would be correct there, but many countries use a red circle with a pedestrian inside to show "no access" which can lead to these wrong tags.

**Comment by westnordost** [comment] 2024-04-27 12:51
Okay, my point is that the second option could not be renamed to "footways not designated for cyclists" because parsing `highway = path` + `foot = no` results in this option.

**Comment by westnordost** [comment] 2024-04-27 12:51
I didn't mention `access`.

**Comment by westnordost** [comment] 2024-04-27 12:55
Hm, or `highway = path` + `foot = no` could be parsed as "Path or Trail" instead.

**Comment by RubenKelevra** [comment] 2024-04-27 13:00
My point was, that `foot=no` on `highway=path` is likely just a mistake and should be a `access=x` tag instead. 


Anyway, question is: What **do** we want to achieve with this selection? 

I think that we should focus on what is allowed there for cyclists, not if it's a trail, path, footway etc. 

So the options are: 

1) there's no information stored in the database
2) bicycling is not allowed
3) it's a shared path
4) it's a seperated path 
5) it's a seperated path by a physical barrier
6) foot traffic is not allowed, bikes only. 

So the current option two would be switched to `bicycle=no`, while the the first option would completely remove the access tag for bicycle, if selected.

**Comment by westnordost** [comment] 2024-04-27 13:55
Eh, you are touching on another topic which has been discussed a lot, just look at this draft PR https://github.com/streetcomplete/StreetComplete/pull/5575

The options for SC should be
- not designated (could be allowed or not allowed, no sign)
- not allowed because there is a sign prohibiting it

While it is not possible to say that there is a sign or that there is no sign, there is just one option.

The "path" option has been added later, on the 12th November 2022, right now I can't find why.

**Comment by RubenKelevra** [comment] 2024-04-27 14:03
> Eh, you are touching on another topic which has been discussed a lot, just look at this draft PR https://github.com/streetcomplete/StreetComplete/pull/5575

I don't agree with @wielandb. If you're cycling you need to know where it's legal and where not. Otherwise you risk a ticket. 

I don't agree that this is "expert" knowledge, like it is not expert knowledge where it's legal to park or not, as you need to know that when you're driving a car. 

We should instead teaching users that if they are unsure they should not complete a quest and move on to something else. 

> 
> The options for SC should be
> - not designated (could be allowed or not allowed, no sign)
> - not allowed because there is a sign prohibiting it
> 
> While it is not possible to say that there is a sign or that there is no sign, there is just one option - not designated.
> 
> The "path" option has been added later, on the 12th November 2022, right now I can't find why.

Given that, it's completely irrelevant if there's a sign or not. E.g. if there's a footway in Germany it's always not for cycling. There doesn't need to be a sign which says "footway" just the absence of a sign saying "bicycle traffic allowed" means it's not allowed. 

It's even not legal to put a sign there saying "just a footway" in most cases, as there's a law which forbids putting up unnecessary signs. 

I bet there are many similar cases in many different states like this. Otherwise the world would be littered with signs.

**Comment by westnordost** [comment] 2024-04-27 14:09
You are free to disagree, but it is policy in StreetComplete to not let users tag the legal situation, but the verifiable and signed on-site situation. This has been discussed at length and I will not change this decision.

**Comment by RubenKelevra** [comment] 2024-04-27 14:24
> You are free to disagree, but it is policy in StreetComplete to not let users tag the legal situation, but the verifiable and signed on-site situation. This has been discussed at length and I will not change this decision.

My point was: There's a default assumption and then there are signs which change the default assumption.

If you cycle you know the default assumption and thus can tag it correctly with "there's no sign and thus the default is cycling is not allowed".

We do this on many occasions, like tagging "there's no cycle lane on this road". Sidewalks in Germany have usually no signs saying "hey this is a side walk" and thus given your argument we would need to say "oh I don't have an idea if there's a cycle way or not here, as there's no sign".

But instead we say "oh no sign, the default applies which is: this is a sidewalk".


I don't think there's anything inherently different about the situation on footways which are not next to a street.

**Comment by wielandb** [comment] 2024-04-27 14:24
> > Eh, you are touching on another topic which has been discussed a lot, just look at this draft PR #5575
> 
> I don't agree with @wielandb. If you're cycling you need to know where it's legal and where not. Otherwise you risk a ticket.
> 
> I don't agree that this is "expert" knowledge, like it is not expert knowledge where it's legal to park or not, as you need to know that when you're driving a car.

I'm not really sure on what you disagree with me here. I don't see anything in your statement that I don't agree with.

**Comment by westnordost** [comment] 2024-04-27 14:55
Anyway, there are two ways how to solve this particular issue:

1. Remove **both** the "Path or trail" and "Shared-use path" option, i.e. anything that is not a _segregated_ foot+cycleway or exclusive cycleway would be "non-designated". Why both? Because while I didn't find a ticket or discussion why I added the "path or trail" option later, I do vaguely remember it should prevent mistagging "just some paths or trails" to "shared-use paths" - both have "path" in the name and the difference between the two can often be just signage and paving or something. On the other hand, the tagging difference is potentially very big: ̀ highway=path` vs `highway=footway` + `bicycle=designated`+ `segregated=no`.

2. Or change `highway = path` + `foot = no` to be parsed as "Path or Trail" to make the "non-designated" specific to footways and treat the "non-designated" option also like the user selected that it is primarily a footway

It surely would probably be less confusing for users to have less choices, but this somewhat collides with the colorful world of OSM foot+bicycle tagging, so a bit of complexity I fear must be added for the data recorded to be any useful.

As I wrote, adding an option that bicycles are allowed on sidewalk explicitly is another issue.

**Comment by wielandb** [comment] 2024-04-27 15:01
> We do this on many occasions, like tagging "there's no cycle lane on this road". Sidewalks in Germany have usually no signs saying "hey this is a side walk" and thus given your argument we would need to say "oh I don't have an idea if there's a cycle way or not here, as there's no sign".

I think it's helpful to reiterate that "no expert knowledge" really means no knowledge about _anything_ is required apart from what is visible on-the-ground. 

A sidewalk is something _physically present_ I don't need any expert knowledge (e.g. legal knowledge) to know that this is a sidewalk. It's there. I can see it. So in SC, I record the physical presence of a sidewalk. Who is allowed to use it is something I cannot know without legal knowledge (wich, I agree, everyone participating in traffic should have, but most don't), but as it is nothing visible on-the-ground, we don't record it in SC.

**Comment by RubenKelevra** [comment] 2024-04-27 15:09
Option one does not work.

We got two different types of ways which bikes and cyclists can use in Germany:

![Screenshot-2022-05-23-at-12.40.09.png](https://github.com/streetcomplete/StreetComplete/assets/614929/06a65281-7944-4533-b623-8252623b33f6)

If the way were tagging is a sidewalk mapped separately next to a road we run into the issue, that we can't tag it in streetcomplete. Reason for this is, that both are explicit cycle ways which need to be used by cyclists instead of the road.

A simple "that's a footway and we got no idea if it's a cycle way" does not work here, as its a mandatory cycle way.

Instead it would lead to many wrongly tagged ways having segregation when they don't have one.

At least for me it's clear what a shared path is supposed to mean, I don't think it would be confused with a path which cyclists can't use.

I think the best option would be to remove the second option with the footway symbol and place a "no cycling allowed" or something like this there.

This would complete the available options.

The first one is fine as it is. As paths and tracks are usually are considered to be allowing cyclists.

If not the user can select "cyclist not allowed" for them, to add `bicycle=no`.

**Comment by westnordost** [comment] 2024-04-27 15:12
Alright, option two then.

**Comment by wielandb** [comment] 2024-04-27 15:23
> Alright, option two then. 

I'll try to incorporate that into #5575. Indeed, theese overlaping (but alledgedly correct) parsings are causing me quite some headache in that PR. 😵‍💫

**Comment by westnordost** [comment] 2024-04-27 15:28
Tell me about it 🤯 ... my sketch from an hour ago...

![imagen](https://github.com/streetcomplete/StreetComplete/assets/4661658/cd20ee34-c731-4507-9c45-fef82adc10f7)

**Comment by westnordost** [comment] 2024-04-27 15:29
On the upside, if you finish this PR and it is merged, you don't need to worry about it anymore because it becomes my responsibility, so, go go go 😅

**Comment by RubenKelevra** [comment] 2024-04-27 15:32
> > We do this on many occasions, like tagging "there's no cycle lane on this road". Sidewalks in Germany have usually no signs saying "hey this is a side walk" and thus given your argument we would need to say "oh I don't have an idea if there's a cycle way or not here, as there's no sign".
> 
> I think it's helpful to reiterate that "no expert knowledge" really means no knowledge about _anything_ is required apart from what is visible on-the-ground. 
> 
> A sidewalk is something _physically present_ I don't need any expert knowledge (e.g. legal knowledge) to know that this is a sidewalk. It's there. I can see it. So in SC, I record the physical presence of a sidewalk. Who is allowed to use it is something I cannot know without legal knowledge (wich, I agree, everyone participating in traffic should have, but most don't), but as it is nothing visible on-the-ground, we don't record it in SC.

We my point was: If I can see a sidewalk and map it as sidewalk I can map any other way as such as well.

If there's a sign saying it is allowing bicycles, I can map it as "there are bicycles allowed", if not you would answer: "none" cycleway existing, not "there's no sign - I don't know":

![Screenshot_2024-04-27-17-29-34-883-edit_de.westnordost.streetcomplete.jpg](https://github.com/streetcomplete/StreetComplete/assets/614929/996849b9-bc80-4189-98d2-3585009e98a3)

So the bicycle quest already requires this "expert knowledge" by asking  the users to make a deliberate choice by knowing sidewalks don't allow bicycles by default. 

Why can't we apply the same for other ways? 🤔

**Comment by westnordost** [comment] 2024-04-27 15:41
I'd blame the OSM tagging schema and practice to put cycleways and footways onto the same way instead of separating it into two ways, if this method of tagging would not also make sense in cases where w.g. bicycle and pedestrian traffic indeed share the space - implicitly or explicitly.
The difference with cycleways mapped on road-ways is that we can already assume with 100% certainty that it is a "straßenbegleitendend".

**Closed** 2024-04-27 15:56 UTC
Labels: bug

**Comment by matkoniecz** [comment] 2024-04-27 16:00
> e.g. in Poland, all sidewalks and footways in general that are broader than a certain width may by law be used by cyclists.

for sidewalks also road speed needs to be >50 km/h

**Comment by westnordost** [comment] 2024-04-27 16:05
Mh, restrictive. Probably ends up to being similar to the German situation, only that your road authority saves on some signage on the countryside.

**Comment by matkoniecz** [comment] 2024-04-27 16:07
you have also added layer of police not really enforcing it anyway
