### ISSUE TITLE
Opening hours: interface "jumps" when selecting closing time hour

### ISSUE THREAD

**Issue by pinkdroyd** [streetcomplete/StreetComplete#4763] opened 2023-01-24 19:53 UTC
Missing opening hours quest: At the moment when I click on the hour for closing time the checkbox for open end appears below the hour radial selector. With that the radial hour selector slightly moves up which leads to a misclick and a wrong hour entered.

**How to Reproduce**
Select the quest to add missing opening hours. Enter opening time and click on next. Click on an hour for closing time.

**Expected Behavior**
Checkbox for open end is visible from the start and does not appear during clicking. That way the UI does not shift and the correct hour is entered.

**Versions affected**
Android 10 (security updates from Aug 2022)
StreetComplete v50.2 installed from GooglePlay
This problem has existed for longer than the current version.

**Comment by mnalis** [comment] 2023-01-27 00:19
Indeed it does, not that I look closely, I can confirm on Android 10 / SC v50.2 !

So that's why I almost always hit opening times OK, but often miss when clicking closing times! I always though that were just my fat fingers, but here is the evidence that that is indeed this bug:


https://user-images.githubusercontent.com/156656/214979068-a15e8756-5911-403d-91b0-b6258c881b90.mp4

If you look frame by frame, you'll see that I clearly clicked on closing time `21` hour and it shows in the form, but then before I managed to remove my finger from the screen the form scrolled, and changed to `20` instead!

Great catch @pinkdroyd , this has been driving me nuts but I never noticed that it scrolls!

**Comment by matkoniecz** [comment] 2023-01-27 06:21
It seems related to how "open end" checkbox appears. I guess that it can be added earlier?

**Comment by pinkdroyd** [comment] 2023-01-27 06:59
From a usability perspective it makes the most sense to always show the "open end" checkbox in the closing time screen. Right now you have to enter a (wrong) time just to make the checkbox appear and then be able to click on the checkbox.
So I think fixing this bug solves two issues at once.

**Comment by matkoniecz** [comment] 2023-01-27 07:11
oh, that would be extra thing to improve

the selected hour combined with open end means "it will be definitely open by that time, likely open also later"

**Comment by arrival-spring** [comment] 2023-02-12 17:00
In version 51 I am still experiencing the jump as shown in the video at the top of this issue.

**Comment by westnordost** [comment] 2023-02-12 20:03
Uhh, so the issue seems to be that the "open end" checkbox is hidden for some reason before the time view is tapped

**Comment by Helium314** [comment] 2023-02-16 14:06
You could always have the checkbox in the view ("start" and "end"), but set it invisible at start, then set it to visible when switching to "end".
There is some initially useless empty space, but the jump is gone then.

**Comment by westnordost** [comment] 2023-02-16 14:09
How's that possible? The start and end views are two separate layouts.

**Comment by Helium314** [comment] 2023-02-16 14:15
You can simply use the same layout for both then.

**Comment by Helium314** [comment] 2023-02-16 20:45
If such a large empty space is acceptable, I can do a PR
![Screenshot_20230216-213825_SCEE](https://user-images.githubusercontent.com/43007630/219482694-9ec7d8a3-621c-4c2d-b4ef-d3e877431be7.png)

**Comment by mnalis** [comment] 2023-02-16 21:30
> If such a large empty space is acceptable

It  has that large empty space for me **currently** in `51.0` when I switch back from `closing time` to `opening time`  (but yeah: on first form open, it does _not_ have that large empty space)

**Comment by westnordost** [comment] 2023-02-16 21:32
I would like to have the issue solved at the root cause for this. If possible. I.e. why does the end-layout initially not show the view? After all, it is not set to gone at the moment.

Also, if you do a PR, it should probably revert the earlier attempt to fix this which made it so that the picker would be cut off in landscape mode, if I remember correctly (by removing the scrollview. I thought that would be the cause of this issue).

**Closed** 2023-02-26 13:35 UTC
Labels: bug

**Comment by westnordost** [comment] 2023-02-26 13:36
Anyway, I tried some things, but to no avail. I think the main issue is that the ViewPager2 works with a RecyclerView and a RecyclerView does not expect its elements to have different dimensions (in this case: height). So, I gave up and basically implemented what @Helium314 suggested.
