### ISSUE TITLE
Street Name selection in map is not working

### ISSUE THREAD

**Issue by vilbi** [streetcomplete/StreetComplete#3816] opened 2022-02-27 20:12 UTC
Selecting a Street in the map, when a question for the Street-name related to a new entered house number is asked, is not working in v40.1
(for the first time since over a year oft active use... 
So I know how it was working...)

**How to Reproduce**
 after setting a building without number to 'house' , the next question is the 'address number' then 'Street' regular behaviour was, click in Street to select the Street Name
Since v40.1 the Street can't be selected, but the Name can be typed in of course-.
Verified in 3 days, after reboot, in different areas, zoom levels, on different buildings...

**Versions affected**
Android 10 Streetcomplete v40.1

**Comment by arrival-spring** [comment] 2022-02-27 20:17
Duplicate of #3797

Fix has been committed and will be in next release

**Closed** 2022-02-27 20:21 UTC
Labels: bug

**Comment by vilbi** [comment] 2022-02-27 20:59
Thanks, was looking for other bug reports, but have oveseen this one ... 

Am 27. Februar 2022 21:17:16 MEZ schrieb arrival-spring ***@***.***>:
>Duplicate of #3797
>
>Fix has been committed and will be in next release
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3816#issuecomment-1053667204
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Wolfgang 
Mastodon: @***@***.***
Matrix/Element: @vilbi:fulda.social
Jabber/XMPP: ***@***.***
threema://add?id=DHN7W4AK
E-Mail: ***@***.***
