### ISSUE TITLE
In a tight situation hard to distinguish pedestrian-cycle crossings from pedestrain-car crossings

### ISSUE THREAD

**Issue by mccartney** [streetcomplete/StreetComplete#4306] opened 2022-08-23 18:29 UTC
## Real-life example
![image](https://user-images.githubusercontent.com/762437/186235191-79764f71-dfa9-46d1-9f79-f9704090660a.png)
https://www.openstreetmap.org/#map=19/52.15673/21.04461

which is an intersection where three kind of ways meet: pedestrian foot paths, cycle paths and car roads. And this happens in a very tight spot (hey, this is the infra we have).

## Problem
When answering the kerb quests (which tend to come in groups) it's hard for me to distinguish which crossing is exactly meant. Is it the foot path-cycling path or is it the foot path-car one, etc. 

The fact that the icons are not aligned with boundaries of ways doesn't help:
![image](https://user-images.githubusercontent.com/762437/186236258-3b53d34a-8329-48c7-81b5-fa93687e42a9.png)

**Comment by mccartney** [comment] 2022-08-23 18:32
Some thought for improvement which would help I think (no idea how easy they are):

1. the icons for kerbs/crossing to be different for pedestrian/cycling and pedestrian/car quests
2. the tip point of the icon kerb quest icon should be placed exactly where the ways meet - i.e. on the boundary of a zebra crossing with the street

**Comment by westnordost** [comment] 2022-08-24 09:42
I don't really understand this issue.

First of all,  know that these quests (kerb, tactile crossing) are not asked for cyclist crossings.

Second: so, the way to the right is the cycleway and the way to the left is the footway crossing? They seem to be sufficiently far from each other so they can be distinguished.

**Comment by mccartney** [comment] 2022-08-24 10:42
> First of all, know that these quests (kerb, tactile crossing) are not asked for cyclist crossings.

Aren't they asked when a foot path crosses a cycle path?

**Comment by westnordost** [comment] 2022-08-24 11:34
Mh yes I think so, but this is not the situation as depicted in the example in the thread starter, is it?

**Comment by mccartney** [comment] 2022-08-24 11:55
Yeah. Let me find another example. The problem I hit yesterday in real-life was in a different place and I was trying to find something similar. But the original one has already solved quests.

**Comment by mccartney** [comment] 2022-08-24 17:46
(Thanks for taking the time to respond)

OK. How about this example:
![image](https://user-images.githubusercontent.com/762437/186487781-3a48169b-eb50-4bf5-ba3c-2184bdfdf202.png)

which is https://www.openstreetmap.org/node/1875213385

When looking at it, it's not clear to me whether the wheelchair kerb quest is for:
- a path meeting the street to the left of the quest icon
- or (the same) path meeting the cycling path to the right of the quest icon

**Comment by matkoniecz** [comment] 2022-08-24 18:07
How it looks on the ground? If it is a single path (possible `segregated=yes` one) then it should be mapped as a single way

Google Street View image is fine

**Comment by mccartney** [comment] 2022-08-24 18:19
> How it looks on the ground? 

https://goo.gl/maps/ELeRC8PaABgZZnLY6

**Comment by matkoniecz** [comment] 2022-08-24 21:09
I would say that part of   the problem is mapping that as two lines

**Comment by westnordost** [comment] 2022-08-24 21:28
But it is OK to map it like that and some prefer it to do it like that. In any case, from the `barrier=kerb` node, I do not think that the application could infer for which crossing this kerb meant.

So, displaying a different icon is not possible because there is no context on for which crossing a kerb is meant for (except if the `kerb=*` is mapped on the crossing node, but this is not the case here). And that is maybe the misconception that causes the confusion: The quest is asked for the kerb, not for the crossing.

StreetComplete actually does (currently) not ask for the type of kerb for a crossing, see https://github.com/streetcomplete/StreetComplete/issues/3239

**Comment by mccartney** [comment] 2022-08-25 08:03
> And that is maybe the misconception that causes the confusion: The quest is asked for the kerb, not for the crossing.

Indeed. I wasn't aware we had "standalone" kerb points in OSM. That's confusing (in OSM world).

Having said and knowing what I know now, I am not sure if I have a suggestion towards SC

**Comment by westnordost** [comment] 2022-08-25 09:38
I'll close this then.

For the next version, all roads and ways are rendered a little thinner so they do not overlap that much.

**Closed by westnordost** 2022-08-25 09:38 UTC
Labels: feedback required
