### ISSUE TITLE
Use R-Tree for DB query performance improvements

### ISSUE THREAD

**Issue by smichel17** [streetcomplete/StreetComplete#3609] opened 2021-12-27 17:36 UTC
Based on preliminary testing in https://github.com/streetcomplete/StreetComplete/discussions/3603#discussioncomment-1856544, this should make queries based on element location 2-5x faster, at the cost of around 15% more disk usage.

**Comment by westnordost** [comment] 2021-12-28 00:12
[R*-Tree support is documented here](https://www.sqlite.org/rtree.html). It is an optional module that needs to be added per compiler flag at compile time.

@Helium314 has been experimenting with this.

## Research required

### R*-Tree support in platform sqlite?

Does the sqlite implementation provided by the Android platform include the R*-Tree module? [According to Android documentation](https://developer.android.com/reference/android/database/sqlite/package-summary), the app can assume an SQLite version of at least 3.8. Optional R*-Tree support was added in 3.6, auxiliary columns in 3.24. So maybe it works but without auxiliary columns?

### R*-Tree support in official android sqlite?

I noticed that SQLite has official precompiled binaries for Android. Not distributed via maven-repository but just as a downloadable AAR: https://sqlite.org/download.html
Such an official source is of course preferrable to a third party library. Not sure if that library implements the interfaces from androidx.sqlite:sqlite but it doesn't really matter. Those are as official as it can get. However, I did not check whether the binaries have been compiled with the `-DSQLITE_ENABLE_RTREE=1` flag that enable the R-Tree feature.

## Implementation / Benchmarking

If the answer to none of the above is "yes", there is also https://github.com/requery/sqlite-android which has R-Tree support but/and also depends on androidx.sqlite.

Before a complete implementation is attempted, it is worthwile to compare the speed. Maybe easiest would be to keep the current index and do every query twice - one with the current index and one with the R*-Tree index, measure the time for both.

Tables that may profit from an R-Tree-index are the element geometry table, the OSM quests table and the notes quests table.

**Comment by Helium314** [comment] 2021-12-28 07:40
> However, I did not check whether the binaries have been compiled with the -DSQLITE_ENABLE_RTREE=1 flag that enable the R-Tree feature.

Yes, it's compiled with R-tree: https://www.sqlite.org/android/doc/trunk/www/install.wiki

> R*-Tree support in platform sqlite?

It does not, see flags used in current Android: https://android.googlesource.com/platform/external/sqlite/+/refs/heads/master/dist/Android.bp
(and if I create R-tree tables with the platform sqlite, SC crashes with a log message: "no such module: rtree")

Note that there is also [spatialite](http://www.gaia-gis.it/gaia-sins/spatialite-sql-5.0.1.html) which has some potentially useful functionality. Unfortunately the Android version doesn't appear to be maintained any more.

> Before a complete implementation is attempted, it is worthwile to compare the speed. Maybe easiest would be to keep the current index and do every query twice - one with the current index and one with the R*-Tree index, measure the time for both and log them.

I'm not sure whether the different table layout with R-tree might affect performance of normal queries. Maybe it should also be compared to a non-R-tree version of SC.

**Comment by Helium314** [comment] 2021-12-28 08:51
> Before a complete implementation is attempted, it is worthwile to compare the speed. Maybe easiest would be to keep the current index and do every query twice - one with the current index and one with the R*-Tree index, measure the time for both and log them.

Virtual tables can't be indexed, so two different builds or tables will be necessary.

**Comment by westnordost** [comment] 2021-12-28 10:06
With R-Tree-Index, I actually meant that virtual table. I.e. the "r-tree-indexed" tables could be normal tables and be accompanied by a virtual table. See https://www.sqlite.org/rtree.html#using_r_trees_effectively

I.e. don't use "auxiliary columns". See also the limitations on auxiliary comuns, not die if they are relevant for us.

**Comment by Helium314** [comment] 2021-12-29 23:18
It took me quite a while to get the R-tree index for the quest table working.
For some reason (which might be that I don't understand much about SQLite) the normal `OsmQuestDao.get(key: OsmQuestKey)` stopped working after adding the R-tree index until I [changed the query a bit](https://github.com/Helium314/StreetComplete/blob/91b541ecd175786b3e3edf4fe3d17108ab126e6e/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestDao.kt#L28-L34).
Maybe there are more things broken than just this; I didn't check.

For smaller areas like the initially downloaded area there is not much gain from the R-tree index.
Download times are almost the same (within 2 seconds). `NoteDao` and `OsmQuestDao` queries using bounding box may be a bit better with R-tree index, but they mostly take few ms only anyway.
For `ElementGeometryDao` the difference was at least clear, but still small (reduction from ca 70 to 45 ms average).

With a rather large download area I expected more interesting results, as the benefits of R-tree grow with DB size. But all I got was a barely responsive app during download, followed by a crash:
```
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:422)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
at java.lang.Daemons$Daemon.run(Daemons.java:103)
at java.lang.Thread.run(Thread.java:764)
```
From the logs it looks like the crash happened between download of OSM data (in the log) and persisting the data (not in the log).

**Comment by westnordost** [comment] 2021-12-29 23:23
I can look through the code if you like, maybe I find something. Would you create a draft PR (e.g. on your repo) and link it here?

**Comment by westnordost** [comment] 2021-12-29 23:26
FYI on download, I don't think any queries are made to any of the tables that should be r-tree-indexed. Only write operations are done.

**Comment by Helium314** [comment] 2021-12-30 06:54
I could reproduce the unresponsive behavior followed by the same crash when scanning a large area, just by using the requery library, even without any R-tree related changes (just [changing DB and renaming](https://github.com/Helium314/StreetComplete/commit/66dfedad5f4599e74611ea09e49d1e75c0d8bce7), plus the rename fix)

I will try switching to the official precompiled binaries first, because such behavior should definitely not occur.

**Comment by Helium314** [comment] 2021-12-30 07:42
... and I remember why I didn't do this from the start: the option to import the module (as mentioned in https://www.sqlite.org/android/doc/trunk/www/install.wiki) was removed from Android studio, and simply adding the .aar file as a dependency crashes when trying to connect to the native library.

**Comment by Helium314** [comment] 2021-12-30 09:30
Loading the `sqliteX` library in the `AndroidDatabase.db` getter fixed this crash, but now there is a native crash triggered in `EditHistoryController_factory.java`: 
`Abort message: 'thread.cc:2155] Throwing new exception 'no "I" field "numArgs" in class "Lorg/sqlite/database/sqlite/SQLiteCustomFunction;" or its superclasses' with unexpected pending exception: java.lang.NoSuchFieldError: no "Ljava/lang/String;" field "name" in class "Lorg/sqlite/database/sqlite/SQLiteCustomFunction;" or its superclasses'
`

**Comment by Helium314** [comment] 2021-12-30 10:34
> I can look through the code if you like, maybe I find something. Would you create a draft PR (e.g. on your repo) and link it here?

Separate draft PRs for both libraries [here](https://github.com/Helium314/StreetComplete/pulls).

**Comment by Helium314** [comment] 2022-01-04 14:06
I did some performance tests, and it looks like using R-tree is much faster for queries using a bounding box, but is much slower when the R-tree index is not used.

[ElementGeometraDao](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/osm/geometry/ElementGeometryDao.kt), using the exact same queries on my ancient S4 mini:
`getAllEntries(bbox)`: 100-200 ms normal, 10-30 ms R-tree
`getAllEntries(keys)`: 1.5 s normal, 6.5 s R-tree (here it should be possible to provide a bounding box for the usual case)
And then there is `OsmQuestDao.getAllInBBox(bounds)`: 200-300 ms normal, 500 ms R-tree. I changed the table to use the R-Tree index, and I don't understand why it's so much slower... maybe because it's not only using bounding box in the query, but also quest types?

Furthermore I noticed that queries to unchanged tables are slower as well in the R-tree build.
Turns out this is actually from using the SQLite library, which is about 20% slower than using the default Android library for whatever reason.

**Comment by Helium314** [comment] 2022-01-04 16:55
I tested a bit more, and haven't been able to get the R-tree to be faster than the normal spatial index used in the quest table.
Looks like for points there is no advantage of R-trees. Which is rather unexpected...

**Comment by smichel17** [comment] 2022-01-04 17:43
> Turns out this is actually from using the SQLite library, which is about 20% slower than using the default Android library for whatever reason.

Is that true of both options you tried?

How difficult would it be to go back to your desktop setup and try the queries where R-Tree is slower there? To verify that it is an issue with r-tree and not with these specific implementations. It may not make a difference now, but in the future if we find a good implementation…

**Comment by westnordost** [comment] 2022-01-04 18:28
> I tested a bit more, and haven't been able to get the R-tree to be faster than the normal spatial index used in the quest table.

I don't understand, you wrote 4hours ago that `getAllEntries(bbox)` is ~8times faster. You mean in total?

Anyway, for a table access to be fast, you need indexes. If I remember correctly, currently there is a spatial index (index on x,y) and a id index ( index on element type + element id) on the table.

Did you remove the id index from the table in the R-Tree build?

If not, I guess the conclusion is that indices don't work well on such virtual R-Tree tables.

But then, using the solution mentioned here https://github.com/streetcomplete/StreetComplete/issues/3609#issuecomment-1001981448 should work: Keep the element geometry dao table as-is and accompany it with an R-Tree virtual table to act as an index. On querying by bbox, do the inner join as outlined in the SQLite documentation. When querying by element id + type, the runtime should be the same as before.

**Comment by Helium314** [comment] 2022-01-04 19:13
> Turns out this is actually from using the SQLite library, which is about 20% slower than using the default Android library for whatever reason.
> 
> Is that true of both options you tried?

I did not test the requery library further, the app was rather unresponsive while persisting large amounts of data and I think that's not a good start.

> I don't understand, you wrote 4hours ago that `getAllEntries(bbox)` is ~8times faster. You mean in total?

But that's not in the quest table (`OsmQuestTable`).
Here `OsmQuestDao.getAllInBBox(bounds)` is never faster with R-tree than with the current spatial index. I did some more testing using DB Browser for SQLite and still wasn't able to find bbox queries that really profit from R-tree, hence my conclusion that R-tree has no benefit over the current spatial index when the table contains points (and not bounding boxes like `ElementGeometryTable`)

> Anyway, for a table access to be fast, you need indexes. If I remember correctly, currently there is a spatial index (index on x,y) and a id index ( index on element type + element id) on the table.
> 
> Did you remove the id index from the table in the R-Tree build?

There is only a spatial index in `ElementGeometryTable`, which basically was replaced by the R-tree. The tabls I use in R-tree tests is still [this one](https://github.com/Helium314/StreetComplete/pull/288/commits/ce2d282409f8d52c8a7ae0504b2d43e072be8722)

> If not, I guess the conclusion is that indices don't work well on such virtual R-Tree tables.
> 
> But then, using the solution mentioned here [#3609 (comment)](https://github.com/streetcomplete/StreetComplete/issues/3609#issuecomment-1001981448) should work: Keep the element geometry dao table as-is and accompany it with an R-Tree virtual table to act as an index. The `ElementGeometryDao` will make sure that the two tables are always in sync, i.e. by inserting, updating and deleting the data from the two tables always in the same transaction. On querying by bbox, do the inner join as outlined in the SQLite documentation. When querying by element id + type, the runtime should be the same as before.

Ok, I'll try this.

**Comment by Helium314** [comment] 2022-01-04 19:29
Android SQLite is built with a bunch of additional compiler flags, https://android.googlesource.com/platform/external/sqlite/+/refs/heads/master/dist/Android.bp

Maybe that's a reason for the performance difference?
(I didn't have a look at what any of those flags actually mean)

**Comment by westnordost** [comment] 2022-01-04 21:37
> There is only a spatial index in ElementGeometryTable, which basically was replaced by the R-tree. 

Yeah, and a primary key. And primary keys are automatically indices

**Comment by Helium314** [comment] 2022-01-05 09:29
> The ElementGeometryDao will make sure that the two tables are always in sync, i.e. by inserting, updating and deleting the data from the two tables always in the same transaction. On querying by bbox, do the inner join as outlined in the SQLite documentation. When querying by element id + type, the runtime should be the same as before.

I stumbled upon a problem I wasn't aware of before: OSM `element_id`s are only unique for each element type. I had thought the primary key consisting of type and id was for performance reasons...
So now to keep the tables synchronized I need to use `rowid` of elements_geometry as primary key in the R-tree table, but on inserting SQLite can only tell me the last inserted rowid... not sure how to best handle this when doing mass insertion.

Anyway, tests with the SQLite browser show good performance when using join, similar to R-tree with auxiliary columns:
BBox with 1000 elements:
R-tree query for id only: 40 ms
R-tree query using join to get actual data: 110 ms
R-tree table with auxiliary columns: 110 ms
Normal query: 150 ms

BBox with 100 elements:
R-tree query for id only: 30 ms
R-tree query using join to get actual data: 50 ms
R-tree table with auxiliary columns: 45 ms
Normal query: 90 ms

(need to repeat tests on the phone, advantage of R-tree appears to be much smaller on SQLite browser / desktop, and adding further tables for testing noticeably affects performance)

Also I noticed that, while it's not possible to create an index on the R-tree table, it's still possible to create one on the table `<r-tree_table_name>_rowid` which contains the auxiliary colums.

**Comment by Helium314** [comment] 2022-01-05 13:25
> So now to keep the tables synchronized I need to use `rowid` of elements_geometry as primary key in the R-tree table, but on inserting SQLite can only tell me the last inserted rowid... not sure how to best handle this when doing mass insertion.

Bad idea. The rowid changes when replacing a row, looks like the old row is deleted and a new one inserted. So using rowid as the primary key in R-tree table doesn't replace anything, or at least not the correct row.
Maybe use something like `(element.type.name + element.id).hashCode()` as hopefully unique id?

**Comment by westnordost** [comment] 2022-01-05 14:54
Nah, that's a hacky workaround. The only way I can come up with now would be to have three tables. One for nodes (actually, not necessary), one for ways, one for relations.

**Comment by westnordost** [comment] 2022-01-05 14:57
But before you do such a refactor, I'd ignore the issue for now and see if it turns out to be worthwhile. 20% overall lower speed is not little and question is whether the R-Tree index can make up for that. Especially if the R-tree index apparently doesn't make it faster for point features(?)

**Comment by Helium314** [comment] 2022-01-06 18:44
I still tried the `(element.type.name + element.id).hashCode()` (actually, the type could be stored in the never used bits of the `elementId` long. Safe against hash collisions, but probably still considered hacky).
For comparable results I logged some function calls to element/quest/geometry/note daos and repeated the calls as some sort of benchmark. Calls were recorded while scrolling and opening some quests.

action / function | time for normal (ms) | time for R-tree (ms) | comment
--- | --- | --- | ---
`ElementGeometryDao.putAll`  | 67700 | 62200 | unexpected, as R*-tree index generation is rather slow
`ElementDao.putAll`  | 72500 | 56200 | even more unexpected, there was no change here... maybe it's the library?
creating quests | 50000 | 51800 | in several runs R-tree was always slightly slower
query bench run | 13000 | 12500 | worst runs were the same, in best runs R-tree was a bit faster
`QuestDao.getAllInBBox` | 167 | 273 | no R-tree used in the quest table, so difference is caused by the library
`ElementGeometryDao.getAllEntries(keys)` | 1598 | 1464 | this is unexpected, maybe the normal is slower because of the two-column index?
`ElementGeometryDao.getAllEntries(bbox)` | 69 | 16 | this is where R-tree really shines
`NoteDao.getAll(bbox)` | 15 | 21 | fluctuates between 7 and 39 for both, R-tree on note table has no advantage
`NodeDao.getAll` | 8 | 10 | 
`WayDao.getAll` | 32 | 47 | 

(I omitted some calls that took < 10 ms average)

When taking into account number of calls in the bench:
function | number of calls | time for normal (s) | time for R-tree (s)
--- | --- | --- | ---
`ElementGeometryDao.getAllEntries(keys)` | 3 | 4.8 | 4.4
`QuestDao.getAllInBBox` | 10 | 1.7 | 2.7
`ElementGeometryDao.getAllEntries(bbox)` | 42 | 2.9 | 0.7
`NodeDao.getAll` | 80 | 0.6 | 0.8
`WayDao.getAll`| 60 | 1.9 | 2.8

> Android SQLite is built with a bunch of additional compiler flags, https://android.googlesource.com/platform/external/sqlite/+/refs/heads/master/dist/Android.bp
> 
> Maybe that's a reason for the performance difference? (I didn't have a look at what any of those flags actually mean)

I tried with the SQL library, but compiled with the same flags as Android. Doesn't make any difference.

**Comment by Helium314** [comment] 2022-01-06 19:23
Small update:
* R-tree in quest table is even slower, now `OsmQuestDao.getAllInBBox` takes 330 ms average in the benchmark.
* returning only the relevant columns in `ElementGeometryDao.getAllEntries(keys)` decreases average to 1150 ms. This should actually work independent of R-tree

**Comment by westnordost** [comment] 2022-01-06 21:50
The performance (gain) of using an R-Tree **very much** depends on how much data you got in the database (that will not be returned by a bbox query because it is outside), though. How much data did you download before or was in the database before?

**Comment by Helium314** [comment] 2022-01-06 22:06
It's a 6 km² area with 120000 elements, giving a ca 35 MB database. Initially I tested on a larger area, but then on my slow phone the whole download process takes more than 5 minutes. Even in this larger area (10 km², 220000 elements) the R-tree quest table is slower than with a normal build (didn't compare to non-R-tree with the same library though).

**Comment by Helium314** [comment] 2022-01-06 23:09
I just tried the requery library again, and got weirdly good results... the whole bench completed in 7 seconds, and it's at least as fast as the Android library everywhere. The only "weak" point is persisting data, where the currently used library with R-tree is faster. (and during persisting I once got a crash with the requery library)

**Comment by Helium314** [comment] 2022-01-07 05:55
Reason for the speed is likely:
> The original SQLite bindings filled the CursorWindow using it's Java methods from native C++. This was because there is no access to the native CursorWindow native API from the NDK. Unfortunately this slowed read performance significantly (roughly 2x worse vs the android database API) because of extra JNI roundtrips. This has been rewritten without the JNI to Java calls (so more like the original AOSP code) and also using a local memory CursorWindow.

From https://github.com/requery/sqlite-android, section *Changes*

**Comment by Helium314** [comment] 2022-01-07 06:52
Looks like the crash has nothing to do with the database library:
* it happens before download is finished (no `MapDataDownload: Downloaded xx nodes...` message in the logs)
* it also happens on normal SC version (only change is adding the benchmark). I've never seen it there before, but I never tried downloading huge areas at once
* it only happens on my normal phone (S4 mini *plus*) not on my test phone (S4 mini). The plus version is faster and more battery efficient, but LineageOS got a few bugs on that phone (like browsers using system webview using up lots of memory that Android counts towards *System* instead of the app)
  * and the crash is likely related to memory:
```
<...>
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Clamp target GC heap from 103MB to 96MB
Background concurrent copying GC freed 5(512KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 1.279ms total 2.257s
WaitForGcToComplete blocked Alloc on HeapTrim for 3.579s
Starting a blocking GC Alloc
WaitForGcToComplete blocked Alloc on HeapTrim for 16.254s
Starting a blocking GC Alloc
Waiting for a blocking GC Alloc
<many more messages like this, every few seconds>

java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:62)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
at java.lang.Daemons$Daemon.run(Daemons.java:103)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by westnordost** [comment] 2022-01-07 12:56
Yeah, on large download, memory use is large because the elements downloaded are retained in memory until quests had been generated from those.

Regarding size and download times: A typical scenario would be that downloaded data got accumulated over the last weeks. E.g. if someone travelled a bit, he will have patches of downloaded data all over.

I am not sure what is your test setup, but maybe it would be easier and also most comparable to write it as a "test" in the androidTest/ folder, do downloading of (some) fixed bounding box(es) there, do query of fixed bboxes there etc. It
1. runs headless, without you having to tap around in the UI
2. it always does exactly the same thing

**Comment by westnordost** [comment] 2022-01-07 12:59
Regarding https://github.com/streetcomplete/StreetComplete/issues/3609#issuecomment-1007159957 , if you find a way to reliably come to the conclusion that the official sqlite-android library is ~20% slower (because of this), maybe it would be a good idea to post an issue at the sqlite issue tracker about this.

**Comment by Helium314** [comment] 2022-01-07 15:23
The strange thing is that both subtypes of the S4 mini have the same amount of memory, and Android is built from the same sources (minus some hardware-specifc parts), but the crash occurs only on one of them. and it even has enough free memory when the crash occurs. But whatever...

> Regarding size and download times: A typical scenario would be that downloaded data got accumulated over the last weeks. E.g. if someone travelled a bit, he will have patches of downloaded data all over.

I thought about this, and basically it means that I need to log queries done in real use to get good data. This will take some time.

2. is already achieved the way I use it, 1. is probably a good change because more convenient.

**Comment by Helium314** [comment] 2022-01-07 15:50
> Regarding [#3609 (comment)](https://github.com/streetcomplete/StreetComplete/issues/3609#issuecomment-1007159957) , if you find a way to reliably come to the conclusion that the official sqlite-android library is ~20% slower (because of this), maybe it would be a good idea to post an issue at the sqlite issue tracker about this.

It's actually mentioned in a readme inside http://www.sqlite.org/android/zip/SQLite+Android+Bindings.zip?uuid=api-level-9, so it's known already.

**Comment by westnordost** [comment] 2022-01-07 19:01
What is mentioned? I didn't find anything

**Comment by Helium314** [comment] 2022-01-08 07:20
sqlite3/src/main/jni/sqlite/README:

> The stock Android code to populate CursorWindow containers with the results of
a SELECT statement uses a C++ interface that is not available to NDK builds. So
this code is rewritten to call the CursorWindow java interface via JNI methods.
This is the largest source code change. See function 
nativeExecuteForCursorWindow() in file android_database_SQLiteConnection.cpp
for details.

**Comment by westnordost** [comment] 2022-01-08 11:14
Ah okay. But then i don't understand what requery does/can do that works around this. And why doesn't that lib use that workaround?

On 8 January 2022 08:20:43 CET, Helium314 ***@***.***> wrote:
>sqlite3/src/main/jni/sqlite/README:
>
>> The stock Android code to populate CursorWindow containers with the
>results of
>a SELECT statement uses a C++ interface that is not available to NDK
>builds. So
>this code is rewritten to call the CursorWindow java interface via JNI
>methods.
>This is the largest source code change. See function 
>nativeExecuteForCursorWindow() in file
>android_database_SQLiteConnection.cpp
>for details.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3609#issuecomment-1007901051
>You are receiving this because you commented.
>
>Message ID:
***@***.***>

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment] 2022-02-06 09:24
Some more results, basically copying my normal SC usage (download and database queries) gathered over the last few weeks:
The times are total time over all function calls, only including calls that took over 10 s in any of the tested versions.
R-tree uses R-tree index for `ElementGeometryTable` and the specified library, without changes to other database parts. The unique ID is created from element ID and type by encoding the type in two unused bits in element ID.

## Download
action / function | normal (s) | R-tree sqlite (s) | R-tree requery (s) | comment
--- | --- | --- | --- | ---
`ElementDao.putAll`  | 181 | 145 | 150 | no difference expected, maybe the library or SQLite version makes the difference
`ElementGeometryDao.putAll`  | 121 | 145 | 131 | expected, as R*-tree index generation is rather slow. Interestingly this is quite different from the single huge download tested above

## Query
action / function | normal (s) | R-tree sqlite (s) | R-tree requery (s) | comment
--- | --- | --- | --- | ---
query bench run | 1140 | 580 | 487 | difference between normal and R-tree is huge, difference between libraries is smaller than previously found, but still large
`MapDataController.getMapDataWithGeometry` | 287 | 133 | 110 | the difference comes from `ElementGeometryDao.getAllEntries(keys)`, while `ElementDao.getAll` should be more or less unchanged
`ElementGeometryDao.getAllEntries(keys)` | 472 | 22 | 16 | excluding calls coming from `MapDataController.getMapDataWithGeometry`. This is much faster than in the previous tests, probably because now the single index is used to avoid `db.queryIn` with two where columns
`ElementGeometryDao.getAllKeys` | 12 | 12 | 8 | 
`NodeDao.get` | 9 | 10 | 8 | excluding calls coming from `MapDataController.getMapDataWithGeometry`
`NodeDao.getAll` | 80 | 91 | 70 | excluding calls coming from `NodeDao.get` and `MapDataController.getMapDataWithGeometry`
`WayDao.get` | 117 | 126 | 97 | excluding calls coming from `MapDataController.getMapDataWithGeometry`
`OsmQuestDao.getAllInBBox` | 13 | 25 | 10 | here the library makes a huge (relative) difference
`OsmQuestDao.getAllForElements` | 104 | 108 | 113 | but here it doesn't...

I used `MapDataController.getMapDataWithGeometry` instead of `ElementGeometryDao.getAllEntries(bbox)` and `ElementDao.getAll` because I want to try comparing it to combined element + geometry tables for each element type.

Database size after download is 99 MB for normal, and 84 MB for R-tree. Not sure how much comes from the different SQLite version.

## Some further observations not really related to R-tree

### 1
Running the bench without downloading data takes surprisingly long
action / function | normal (s) | R-tree requery (s) | # of calls
--- | --- | --- | ---
query bench run | 188 | 133 | 1
`ElementGeometryDao.getAllEntries(keys)` | 19 | 4 | 716
`NodeDao.getAll` | 47 | 30 | 49860
`WayDao.get` | 73 | 40 | 42710
`OsmQuestDao.getAllForElements` | 15 | 10 | 2123

There might be some potential for optimization here, especially `NodeDao.getAll` and `WayDao.get` are not much faster when running with an empty database.

### 2
Looks like a lot of queries are produced when scrolling to my own position, or maybe in general while scrolling quickly.
In one case it was first 11 queries to `OsmQuestsHiddenDao.getAllIds`, then 11 queries to `NoteDao.getAllPositions`, then 11 queries to `OsmQuestDao.getAllInBBox`; all within 500 ms, with first and last bounding box being ca 40 km apart.
In a second case I found in the logs, the queries were mixed, but otherwise very similar.

Loading a lot of quests on the way is likely not good for performance, and definitely not needed. Maybe there is a way to avoid it...

**Comment by Helium314** [comment] 2022-02-06 13:46
> `ElementGeometryDao.getAllEntries(keys)` [...] This is much faster than in the previous tests, probably because now the single index is used to avoid `db.queryIn` with two where columns

And indeed, using a single primary index on the element geometry database accelerates this query to 11 s when the normal (non-R-tree) db, bench then takes 700 s.

**Comment by westnordost** [comment] 2022-02-06 21:49
> Looks like a lot of queries are produced when scrolling to my own position, or maybe in general while scrolling quickly.
> Loading a lot of quests on the way is likely not good for performance, and definitely not needed. Maybe there is a way to avoid it...

The quest pins are loaded from the database whenever the view intersects with a new zoom 16 tile that hasn't been loaded onto the map yet. It checks on every frame when the map is moved but only loads the new tile(s) **once** and only those that haven't been loaded yet. It also does not load each tile individually but tries to get the minimum bounding box of all new tiles that came into view. E.g. if the user scrolls up, then there are maybe 3 tiles like this ◻◻◻ next to each other that haven't been loaded yet, so this can be one bbox-query to the database. However, if the user scrolls diagonally ...

◻◻◻◻
◼◼◼◻
◼◼◼◻
◼◼◼◻

(black = loaded already, white = not loaded yet) ... the minimum bounding box that encloses all the white tiles is rather large, so more area is loaded from db as need to be. However, the overhead is/was quite large to make even a single bbox-query call, so it is/was faster to load a larger bbox once and have it return more data than necessary than doing several bbox-queries with each smaller bboxes.
Not sure if with R-Tree, it would be worth it to revisit that logic. I suspect that it would still be slower to have 2 queries rather than one bigger one.

Another thing that could be done is to only load the quests when the map is still. Though, this will then become visible to the user and thus will look like lag.

**Comment by westnordost** [comment] 2022-02-06 21:54
> Some more results, basically copying my normal SC usage (download and database queries) gathered over the last few weeks

Can you get it down to one number? E.g. if you managed to create a test setup that replicates the queries done of the last few weeks, then can you look at each how much "database time" was used for these queries in normal, R-tree-sqlite and R-tree-requery?
I'd like to know the performance gain (faster bbox queries) / loss (slower everything else) we are talking about here in total.

**Comment by westnordost** [comment] 2022-02-06 21:56
> The unique ID is created from element ID and type by encoding the type in two unused bits in element ID.

Uhh, this sounds extremely hacky. What bits are unused in the element ID? The element ID is a `long`, theoretically nothing is unused here. In how many years can we expect this to horribly break because node ids reach that "unused" bits?

**Comment by westnordost** [comment] 2022-02-06 22:17
> The element ID is a long, theoretically nothing is unused here. In how many years can we expect this to horribly break because node ids reach that "unused" bits?

Hmm I guess it's ok, it may be hacky but according to my calculation, it will only horribly break in 2.3 billion years.
Very roughly 1 billion nodes are created each year. (Signed) long goes up till 9223372036 billion, so minus 2 bits it's 2305843009 billion.
Unless unforeseen things happen, like OSM assigning random new ids to newly created nodes or something for whatever reasons. A hack is still a hack.

Are any of these solutions reasonable?:
- assign each ElementGeometry an own unique rowid and assign it to each element via a foreign key 
- have three tables for element geometry: RelationGeometry, WayGeometry, ... actually, make it two. Nodes already have a geometry.

**Comment by Helium314** [comment] 2022-02-07 08:07
> * have three tables for element geometry: RelationGeometry, WayGeometry, ... actually, make it two. Nodes already have a geometry.

This works quite well, reduces db size, download time and (if I avoid querying nodes twice in `MapDataController.getMapDataWithGeometry`) time for the bench. Probably would also accelerate the current DB.
Interestingly it looks like the spatial index for node, which was necessary to add, does nothing in for sqlite, but accelerates NodeDao for requery.

action / function | normal (s) | R-tree sqlite (s) | R-tree requery (s)
--- | --- | --- | ---
`ElementDao.putAll`  | 181 | 168 | 171
`ElementGeometryDao.putAll`  | 121 | 21 | 24
query bench run | 1140 | 567 | 444
`MapDataController.getMapDataWithGeometry` | 287 | 120 | 90
`ElementGeometryDao.getAllEntries(keys)` | 472 | 15 | 11
`ElementGeometryDao.getAllKeys` | 12 | 4 | 3
`NodeDao.get` | 9 | 10 | 7
`NodeDao.getAll` | 80 | 91 | 63
`WayDao.get` | 117 | 126 | 86
`OsmQuestDao.getAllInBBox` | 13 | 24 | 10
`OsmQuestDao.getAllForElements` | 104 | 107 | 109

**Comment by Helium314** [comment] 2022-02-07 08:15
> Another thing that could be done is to only load the quests when the map is still. Though, this will then become visible to the user and thus will look like lag. So, any optimization like this will make it faster, but it will **look** slower for the user.

Thanks for the explanation!
Is there a way to determine how fast the map is scrolled and set a threshold?
If there is a way and you think it could work, I'll open a new issue.

**Comment by westnordost** [comment] 2022-02-07 11:38
> Is there a way to determine how fast the map is scrolled and set a threshold?

No. Though a call is made every time the view is moved / every frame, so one could get the location at the center of the screen for each frame and calculate a velocity from  that.

**Comment by westnordost** [comment] 2022-02-07 11:41
> normal optimized (s) 

Hm, interesting! Why is the R-tree stuff now only marginally faster with bbox queries? (As I wrote before, how much more fast an R-tree index is depends very much on how much spatial data at different location there is in the database, i.e. how much data sqlite needs to go through without an R-tree index)

**Comment by Helium314** [comment] 2022-02-07 11:46
Currently I'm not sure how useful the R-tree really is...
Since preformance advantage of R-tree appears to be much less now (depending on the library used), the only clear advantage of R-tree would be querying [regions of arbitrary shape](https://www.sqlite.org/rtree.html#using_r_trees_effectively), e.g. all elements within 20 m of a road. For this, also the nodes database needs an R-tree index, which is a bit slower than a conventional spatial index accoding to previous test (currently re-testing with the "more realistic" data).

**Comment by Helium314** [comment] 2022-02-07 11:53
> No. Though a call is made every time the view is moved / every frame, so one could get the location at the center of the screen for each frame and calculate a velocity from that.

Hmm... actually getting distance between frames instead of actual velocity is not so bad.
Slow phones will probably have lower frame rate (and maybe skip more frames) and thus have larger distance between frames, while fast phones have smaller distance. Thus setting a distance threshold between frames could reduce number of queries for slow phones, but not for phones that can handle them anyway.

**Comment by Helium314** [comment] 2022-02-07 19:32
Node database with R-tree was not good, `getIdsOlderThan` is ca 10-15x slower than without R-tree (100 s instead of the usual 6-8 s).

However, having a node geometry table consisting only of id and bounding box of node is much better. So in the last column I added [above](https://github.com/streetcomplete/StreetComplete/issues/3609#issuecomment-1031177576) it's simply splitting element geometry tables into the 3 types.
Putting elements/geometries is a bit slower than without node geometry table and the database size increases from 68 to 75 MB, but both is still better than in the current version.

I think doing the optimizations for "normal" db already provides a huge preformance improvement, so it might be enough. But R-tree has some further capabilities that can turn out very useful, e.g. for #3594.

Then I noticed that tags are stored as Json, and both tested libraries contain the [json1 extension](https://sqlite.org/json1.html). I didn't look through the documentation, so I don't know which capabilities could actually turn out useful...

**Comment by westnordost** [comment] 2022-02-07 21:27
Then I propose you create a PR to just split up the element geometry table because this seems to be a very low hanging fruit. After there, I'd almost propose to drop the rest (i.e. close this issue) because the performance difference is too small.

**Comment by Helium314** [comment] 2022-02-08 13:59
Yes, I think suspect most of the difference comes from the library (because it is at calls that are not affected by any other changes)

So what is to be done?
* have the relation and way geometry tables separate, and get node geometry from node table
* spatial index for node table
* update the database version and upgrade / adjust existing tables
* update tests
* anything else?

**Comment by westnordost** [comment] 2022-02-08 15:15
> anything else?

I think that's it

**Closed** 2022-02-14 22:58 UTC
