### ISSUE TITLE
"What's the speed limit for this street?" quest does not tag UK national speed limit roads correctly

### ISSUE THREAD

**Issue by AlexT25** [streetcomplete/StreetComplete#4272] opened 2022-08-06 17:20 UTC
It seems that the "What's the speed limit for this street?" quest is not handling UK national speed limits correctly. At present the app will tag a road reported as national speed limit with either `maxspeed:type=GB:nsl_restricted`, `maxspeed:type=GB:nsl_single`, or `maxspeed:type=GB:nsl_dual`, depending on what type of road it is. However it will not add a `maxspeed=` tag to the road.

As far as I can tell this behaviour is incorrect because the [Key:maxspeed:type wiki page](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type) states "`maxspeed:type=` describes how a speed limit has been set into force. **It should be accompanied by a** `maxspeed=*` **tag**". The page [then goes on to say](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type#UK) that in the UK if `GB:nsl_restricted` is used it should be tagged alongside `maxspeed=30 mph`, if `GB:nsl_single` is used it should be tagged alongside `maxspeed=60 mph`, and if `GB:nsl_dual` is used it should be tagged alongside `maxspeed=70 mph`.

For reference the app currently works correctly when the speed of a road is determined by it being within a 20 mph zone. In such a case it adds both the `maxspeed:type=GB:zone20` and `maxspeed=20 mph` tags.

**How to Reproduce**
There are four paths the user can take to reproduce this issue.

Path 1:
1. Select a "What's the speed limit for this street?" quest while in the UK.
2. When asked "What defines the speed limit?" select "National Speed Limit"
3. When asked if the carriageways are separated select "No"
4. Observe that the road gets tagged with `maxspeed:type=GB:nsl_single`, but no `maxspeed=` tag is added to the road.

Path 2:
1. Select a "What's the speed limit for this street?" quest while in the UK.
2. When asked "What defines the speed limit?" select "National Speed Limit"
3. When asked if the carriageways are separated select "Yes"
4. Observe that the road gets tagged with `maxspeed:type=GB:nsl_dual`, but no `maxspeed=` tag is added to the road.

Path 3:
1. Select a "What's the speed limit for this street?" quest while in the UK.
2. When asked "What defines the speed limit?" select "No sign, defaults apply"
3. When asked to check if the street is within a speed zone select "Yes, no sign"
4. When asked if the carriageways are separated select "No"
5. Observe that the road gets tagged with `maxspeed:type=GB:nsl_restricted`, but no `maxspeed=` tag is added to the road.

Path 4:
1. Select a "What's the speed limit for this street?" quest while in the UK.
2. When asked "What defines the speed limit?" select "No sign, defaults apply"
3. When asked to check if the street is within a speed zone select "Yes, no sign"
4. When asked if the carriageways are separated select "No"
5. Observe that the road gets tagged with `maxspeed:type=GB:nsl_dual`, but no `maxspeed=` tag is added to the road.

**Expected Behavior**

- When the app tags a road with `maxspeed:type=GB:nsl_restricted` it also adds the `maxspeed=30 mph` tag
- When the app tags a road with `maxspeed:type=GB:nsl_single` it also adds the `maxspeed=60 mph` tag
- When the app tags a road with `maxspeed:type=GB:nsl_dual` it also adds the `maxspeed=70 mph` tag

**Versions affected**
StreetComplete version: v45.1
Android version: 12
Android Security update: 5 July 2022
Google Play system update: 1 July 2022

**Comment by Helium314** [comment] 2022-08-06 18:26
see #3281, #1179 and maybe other issues linked in there

**Comment by AlexT25** [comment] 2022-08-06 22:35
I’ve read through the linked issues and while I can see what some of the comments are getting at it doesn’t really sit right with me. According to the documentation `maxspeed=` is meant to be used to describe the maximum speed of the road while `maxspeed:type=` is intended to provide information about where that maximum speed value comes from. From that point of view it seems wrong to provide information about how a non-existent maximum speed tag was determined. Looking at roads in my area of the UK it certainly seems the standard mapping practice is to use `maxspeed=` for the maximum speed of national speed limit roads, sometimes with `maxspeed:type=` as well. Of note is that every time (without exception) I found a road which had a `maxspeed:type=` tag but no `maxspeed=` tag it came from a StreetComplete edit. If the consensus (both on the wiki and in the UK mapping community) is that `maxspeed:type=` should only be used alongside, and not instead of, `maxspeed=` it seems off that the app is intentionally designed to go against that.

From what I can tell (after diving back through the chain of linked issues) the main argument being consistently presented against having StreetComplete fill in the `maxspeed=` tag based on the user’s input is that the user may not know what the national speed limit laws are, so it would be wrong for the app to infer that information on their behalf. However from my point of view the app is already inferring the type of national speed limit based on user input. The user is not directly asked what type of national speed limit applies to the road; instead they are asked questions about the road (e.g. are the lanes separated, is the road lit, etc.) and the app infers from that what the correct value for `maxspeed:type=` is. If the value for `maxspeed:type=` is being inferred from the user’s description of the road then I don’t see why `maxspeed=` can’t be inferred as well, particularly for UK roads where the wiki clearly and explicitly states  what `maxspeed=` value should be used for each `maxspeed:type=` value.

I've also seen it stated that `maxspeed=` is redundant when `maxspeed:type=` is specified because the user of the data can infer `maxspeed=` from the value of `maxspeed:type=`. However if as a developer you are new to using OpenStreetMap data, or do not have knowledge of this debate, then you would likely go to the Wiki to find out what the tags mean and how you should interpret them. At present you would see that the speed limit of the road is given by the `maxspeed=` tag, while the page for the `maxspeed:type=` tag states it is only used in addition to `maxspeed=`. That would give you the impression that you do not necessarily need to check the `maxspeed:type=` tag in order to determine the speed limit of a road. You could argue that that is their own problem to work out, but it is hardly user friendly, and not what the tag is really intended for according to the documentation.

**Comment by westnordost** [comment] 2022-08-07 22:32
This has been discussed already, and I do not see any new perspectives here, so I'll close this. However:

> Expected Behavior
>    When the app tags a road with maxspeed:type=GB:nsl_restricted it also adds the maxspeed=30 mph tag
>    When the app tags a road with maxspeed:type=GB:nsl_single it also adds the maxspeed=60 mph tag
>    When the app tags a road with maxspeed:type=GB:nsl_dual it also adds the maxspeed=70 mph tag

Have a look at https://wiki.openstreetmap.org/wiki/Default_speed_limits to get a feel how practical inferring the correct maxspeed tags per selected road type would be to implement. (Spoiler alert: it is not practical at all.)

Specifically, note that `maxspeed:type=*` alone is often not sufficient to infer what speed limit applies. To make that work - i.e. `maxspeed:type=*` maps 1:1 to a given `maxspeed=*` value, `maxspeed:type=XX:xxxxx` would need to have defined values for all the road types in all the countries.
See for example rural dual carriageways in Belgium. It is unreasonable to expect that the Belgian community will start tagging `maxspeed:type=BE-BRU:rural_dual_carriageway_with_2_or_more_lanes_in_each_direction` on rural dual carriageways with 2 or more lanes in each direction to denote to which road class that road belongs, and so it is for the many others.

Hence, to arrive at a set `maxspeed` to set together with the `maxspeed:type`, StreetComplete would have to ask the user many different questions that each differ for each different country. This is not doable at all.

And apart of whether this is doable or not, there is also the question whether it makes sense or not. After all, StreetComplete could require its users to provide the speed limit manually in any case. It looks like you read up on that already a bit, so just regarding whether it would be wise to let users provide the speed manually: In the above mentioned wiki article, note the "note for mappers" at the very beginning: There is little information gain when the road type or other properties that lead to a speed limit has already been determined. And in doubt, it leads to wrong data.

---

So much for the bad news. But there is good news, too.

I have been hard at work during the last 2 months to research all the legislations of all the countries on speed limits and putting it in the above mentioned wiki page. I have also been working on a library that can be used by data consumers to interpret the data in that wiki page and have been in contact with router application developers for Graphhopper and Valhalla regarding that matter.
My hope is that in the future, for any data consumers interested in maxspeed data, it will be no effort at all to get the default speed limits based on other tags set on the road, even when an explicit `maxspeed` is missing.

Here is a demo:

**[https://westnordost.github.io/osm-legal-default-speeds](https://westnordost.github.io/osm-legal-default-speeds/#cc=GB&tags=lit%3Dyes)**

**Closed by westnordost** 2022-08-07 22:32 UTC
Labels: bug

**Comment by SK53** [comment] 2023-09-15 16:04
There are a substantial number of roads where `maxspeed:type` has been added without `maxspeed`. For instance [this query](https://overpass-turbo.eu/s/1Axk) shows them in South-West England. As a result an experienced OSM user was advised of a 70 mph limit in an urban area today! These may result from earlier versions of StreetComplete, but they currently represent a substantial potential set of bugs in OSM data for the UK. I don't know if it is possible to enhance the quest so that it asks for the actual speed limit when only `maxspeed:type` is set?

Also please note that in Wales from Sunday the normal speed limit in urban areas will be 20 mph (i.e., `GB:nsl_single` will almost certainly be an invalid tag from that date for that jurisdiction. Accordingly, it is very important that roads in Wales with a speed limit have it in miles per hour as otherwise updating the speed limits will be very complex. (This may need to be spun out into a separate issue).

**Comment by arrival-spring** [comment] 2023-09-15 17:36
> There are a substantial number of roads where `maxspeed:type` has been added without `maxspeed`. For instance [this query](https://overpass-turbo.eu/s/1Axk) shows them in South-West England.

The point of the library linked above is that this should not be seen as an error, and if anything is the preferred way of tagging speed limits.

> As a result an experienced OSM user was advised of a 70 mph limit in an urban area today!

If maxspeed:type was correctly tagged then I would say that is an issue with the app being used.

> These may result from earlier versions of StreetComplete, but they currently represent a substantial potential set of bugs in OSM data for the UK.

If the user says they do not see a sign the maxspeed:type is tagged and maxspeed is not, this has always been the case AFAIK.

>I don't know if it is possible to enhance the quest so that it asks for the actual speed limit when only `maxspeed:type` is set?

But what if there is no sign that the user can see?

> Also please note that in Wales from Sunday the normal speed limit in urban areas will be 20 mph (i.e., `GB:nsl_single` will almost certainly be an invalid tag from that date for that jurisdiction.

I assume you mean maxspeed:type=GB:nsl_restricted? That is roads which need no repeater signs, and have street lighting and so are 30mph for most vehicles at the moment.

> Accordingly, it is very important that roads in Wales with a speed limit have it in miles per hour as otherwise updating the speed limits will be very complex. (This may need to be spun out into a separate issue).

Rather the data would not need updating at all if only maxspeed:type was set and it is only routers or the default speed limit library which need updating.

**Comment by mnalis** [comment] 2023-09-15 20:28
> There are a substantial number of roads where maxspeed:type has been added without maxspeed. For instance [this query](https://overpass-turbo.eu/s/1Axk) shows them in South-West England. As a result an experienced OSM user was advised of a 70 mph limit in an urban area today!

@SK53 Can you link to exact road id where this happened, and what software was that mis-advised user using? (or if you can reproduce that behaviour yourself on any other road, that is good too).

**Comment by rskedgell** [comment] 2023-11-15 07:52
> Also please note that in Wales from Sunday the normal speed limit in urban areas will be 20 mph (i.e., `GB:nsl_single` will almost certainly be an invalid tag from that date for that jurisdiction. Accordingly, it is very important that roads in Wales with a speed limit have it in miles per hour as otherwise updating the speed limits will be very complex. (This may need to be spun out into a separate issue).

It's maxspeed:type=GB:nsl_restricted + maxspeed=30 mph which is now invalid in Wales, as all restricted roads are now 20 mph by default (NB lit=yes is required for the highway to be a restricted road). I don't think a consensus has yet been reached on what the value of maxspeed:type should be.

The combination of maxspeed:type=GB:nsl_single + maxspeed=60 mph remains valid everywhere in the UK.

The value maxspeed:type=GB:zone20 may be a little trickier in Wales. The legislation introducing the 20 mph limit on restricted roads does not revoke any earlier traffic orders creating 20 mph zones, but the traffic signs relating to 20 mph zones should be removed by 16 September 2024.

See:
[The Restricted Roads (20 mph Speed Limit) (Wales) Order 2022](https://www.legislation.gov.uk/wsi/2022/800/contents/made)
[The Traffic Signs (Amendment) (Wales) Regulations and General Directions 2023](https://www.legislation.gov.uk/wsi/2023/783/contents/made)
