### ISSUE TITLE
Add quest: Accepted Currencies / Payment Methods 🪙💳

### ISSUE THREAD

**Issue by bohuslav-kovalsky** [streetcomplete/StreetComplete#4396] opened 2022-09-20 10:29 UTC
### General
Affected tag(s) to be modified/added: [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity) (maybe with some filter for restaurants, shops, ...)
Question asked: **What are accepted methods of payment here?**

Answer should be some checklist of possible options:
- **Cash**: `payment:cash=yes`, maybe should be pre-selected to `yes`, but there are places that do not accept cash anymore :(
- **Bitcoin (Onchain)**: `payment:onchain=yes` (`currency:XBT=yes` should be added as well)
- **Bitcoin (Lightning)**: `payment:lightning=yes` (`currency:XBT=yes` should be added as well)
- **Bitcoin (Lightning Contactless)**: `payment:lightning_contactless=yes` (`currency:XBT=yes` should be added as well)
- **Credit Cards**: `payment:credit_cards=yes`

I am not sure if it makes sense to add more of `currency` tags (https://wiki.openstreetmap.org/w/index.php?title=Key:currency&uselang=en). This would require some local info (what currencies to offer). 
- Also important to note, that even legal tender usually requires the store to accept some currency it is not always the case. There is at least one place I know that does not accept local currency but only Bitcoin event it is illegal in that country).

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

--------

### Further readings:
- This was inspired by this project: https://github.com/teambtcmap/btcmap.org/wiki/Tagging-Instructions
- Example for Bitcoin Accepting Node: https://www.openstreetmap.org/node/296731584

**Comment by matkoniecz** [comment] 2022-09-20 11:02
> Not an overwhelming percentage of quests have the same answer (No spam)

BTC and its variants are extreme rarity. See #4228

Is there any country where say >5% places accept BTC or its variants?

**Comment by bohuslav-kovalsky** [comment] 2022-09-20 16:27
Hi, thanks for more context. I did not found those older issues, I was searching for bitcoin and not cryptocurrencies.

I also did not know there is a cash/card quest.

I really liked the proposal mentioned [here](https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922095785)

![image](https://user-images.githubusercontent.com/113983905/191310444-36400e33-2768-40c0-9117-3dffddeb52b9.png)

This is basically my proposal.

I propose to consolidate cash and card quest into something like this. Different options can be enabled in different countries.

This would address multiple issues in one quest:
1. cash only / cashless 
2. Different cards (visa/mastercard/american express/...(
3. ApplePay / AndroidPay
4. Bitcoin and Lightning Network

Please not, there are countries where Bitcoin acceptance is higher then others. Usually this is happening in hotspots like El Salvadors Bitcoin Beach, Roatan, but also Prague.

-------

Even it is clear that I am bitcoin oriented person, this proposal is not about just Bitcoin, but about payment options in general.

Here where I live (Czechia) is still quite usual that only cash is accepted. But also some places starts to be card-only. Also it is usual that American Express is **not** accepted. So event quest for just that would help here.

**Comment by mnalis** [comment] 2022-09-20 17:23
> :point_up: This is basically my proposal.

Yeah, I (as an advanced user) kind of liked that proposal too, but as SC is geared toward novice users, it is not likely to be implemented in this form; see this comment https://github.com/streetcomplete/StreetComplete/issues/3219#issuecomment-922114831

At least not in upstream StreetComplete, maybe in [StreetComplete Expert Edition](https://github.com/Helium314/StreetComplete/) fork, if proposed there...

The problem is that such UI breaks too many [quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md), e.g. probably all of those:

- ⚛️ **Atomic quests**
- 🕓 **Effort vs impact**
- 🤔 **No unanswerable quests**
- 👨‍💻 **Users are no experts**
- 🐿️ **Easy answer**
- 💤 **No spam**

> Even it is clear that I am bitcoin oriented person, this proposal is not about just Bitcoin, but about payment options in general.

I like bitcoin too, it's just that mapping it via StreetComplete `quest` is a poor choice for doing it. StreetComplete `overlay` is not a good match either. I myself would probably stick with EveryDoor to map it as mentioned before (or OsmAnd or Vespucci, but probably EveryDoor).

> This would be nice generic solution that will cover many possible options with one quest. This would create very clean and nice UI/UX.

Unfortunately, such UI would be very complex for novice mapper, and hard to answer even for advanced users, as one would have to investigate **all** accepted payment options before attempting to answer the quest (or, even with tri-state answers `yes`/`no`/`unknown`, someone who does not care about bitcoin would solve the quest for example only for cards and cash, and then the quest would be **_hidden from everyone_** (see "🤔 **No unanswerable quests**") - thus rendering quest with such UI basically **_useless for mapping bitcoin_** (as there are likely much more people who don't care about it, then those who do, so they'll likely solve such quest before you or I get to them). It has been discussed in that ticket.

Duplicate of #4228

**Comment by mnalis** [comment] 2022-09-20 17:48
> Please not, there are countries where Bitcoin acceptance is higher then others. Usually this is happening in hotspots like El Salvadors Bitcoin Beach, Roatan, but also Prague.

Yes, but StreetComplete is only able to limit quests on a per-country bases. So if in **_whole of Czechia_** say `5%` of the shops offered payment by bitcoin, adding a simple `yes/no` quest **_"Is Bitcoin accepted here?"_** quest _might_ be created but enabled **only in CZ**. Like `cash` quest is only enabled in `SE`: https://github.com/streetcomplete/StreetComplete/blob/a4d68fecc300b1062b9aaa0b961ebe847af9f598/app/src/main/java/de/westnordost/streetcomplete/quests/accepts_cash/AddAcceptsCash.kt#L56

Duplicate of #4228

**Closed by mnalis** 2022-09-20 17:48 UTC

**Comment by bohuslav-kovalsky** [comment] 2022-09-20 23:12
Thanks for info about [StreetComplete Expert Edition](https://github.com/Helium314/StreetComplete/). This looks like a good addition to the toolset.

**Comment by bohuslav-kovalsky** [comment] 2022-09-20 23:17
@mnalis Also you mentioned that quest is hidden from everyone. 

Is there some timeout after which quest reappears for update. I noticed quests like "Are opening hours this **still** correct?" Does this apply to all quests or only to some?

Is there a place where to read about how this behaves?

Thanks!

**Comment by mnalis** [comment] 2022-09-21 21:22
> @mnalis Also you mentioned that quest is hidden from everyone.

Yes, that is by design. Once a quest is solved by one user, it **must not appear to other users**, e.g. this [quest guideline](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md):

- 🤔 **No unanswerable quests**: All generated quests need to be actually answerable (no false-positives). This means that any answer given by the user must result in something being tagged. For example, a quest that asks for the website of a place must be able to tag the element somehow if the user answers that the place has no website - otherwise, the next user will be asked the same question. Sometimes, due to the nature of how things are tagged in OSM (such as the one given in the example) it is unfortunately simply not possible to fulfill this.

> Is there some timeout after which quest reappears for update? I noticed quests like "Are opening hours this still correct?" Does this apply to all quests or only to some?

Yes, some (but not all) quests do ask for resurvey after some time. You can check each quest if it contains lines like this:

https://github.com/streetcomplete/StreetComplete/blob/a4d68fecc300b1062b9aaa0b961ebe847af9f598/app/src/main/java/de/westnordost/streetcomplete/quests/smoking/AddSmoking.kt#L39

That means that this quest will be asked if:
- `smoking=*` tag does not exist, **_or_**
- the OSM object was last updated more than 8 years ago 

The interval of quest reappearance (and whether resurvey will happen at all)  is basically decided by quest author guessing how often some feature is likely to change. 

Not that resurvey would help much in this particular case: if the odds were heavily against you that you'd be the first one to solve that quest initially, they would still be heavily against you that you'd be the first one to resurvey it. Sure, you'd get _**some**_ chance every `x` years, but if that chance is small it is far more likely that you'd die from old age (or bitcoin becomes extinct/replaced by something better) before you hit that jackpot...

> Is there a place where to read about how this behaves?

There is [CONTRIBUTING_A_NEW_QUEST.md](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING_A_NEW_QUEST.md) which gives direction how to create new quest; it should thus also give an idea how most simpler quests are done too.
