### ISSUE TITLE
Do ask "Are the the collection times of this postbox still correct?"

### ISSUE THREAD

**Issue by ltog** [streetcomplete/StreetComplete#2660] opened 2021-03-14 19:54 UTC
**Use case**

I noticed that for opening hours tagged some time (years?) ago, users are asked "Are these opening hours still correct?" (or similar).

However, for collection times of post boxes that were already tagged some time ago, such a question is not asked. Instead, the quest asks to enter the collection times like they were not added previously.

**Proposed Solution**

Ask a similar question, something like "Are the the collection times of this postbox still correct?". Only when the user answers "no", ask to enter the collection times. This will both harmonize and accelerate the quest.

**Comment by westnordost** [comment] 2021-03-14 22:23
Duplicate of #2105.
In general, a PR to implement that is welcome of course, but it is probably quite some effort. Enough effort vs gain that I did not seem to deem it worth the effort to ever implement this.

**Closed by westnordost** 2021-03-14 22:23 UTC
