### ISSUE TITLE
outdoor_seating

### ISSUE THREAD

**Issue by yoasif** [streetcomplete/StreetComplete#1176] opened 2018-08-29 16:53 UTC
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:)
Question asked: **Does this location have outdoor seating?**

https://wiki.openstreetmap.org/wiki/Key:outdoor_seating

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
It is established, and the usefulness is pretty obvious - it is nice out, and i want to find an eatery (generally) that has outdoor seating. 
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by rugk** [comment] 2018-08-29 17:00
I guess the "Question asked" is a bit off. :wink: 

Anyway, I can imagine the question and I'd say it's a good idea. 

So for which elements would you like to ask this quest?

**Comment by yoasif** [comment] 2018-08-30 04:08
Oops!

Updated the question to: *Does this location have outdoor seating?*

I think that:

amenity=restaurant
amenity=fast_food
amenity=food_court
amenity=cafe
amenity=pub
amenity=bar

would be good candidates to ask this question for. 

Unsure how this looks for other quests, but ideally, it would be a two step process: User answers yes or no, and if no, the input is accepted, but if yes, is presented with 

pedestrian_zone
terrace
balcony
veranda
roof
garden
beach

with images or descriptions of those, along with "not sure", which would populate "yes" (but not more specific).

**Comment by ENT8R** [comment] 2018-08-30 04:29
I think a simple Yes/No question might be sufficient for this quest because why do you think is the other information useful? And also: if we would implement it with the second step, why don't include it as the first and only question?

**Comment by yoasif** [comment] 2018-08-30 14:09
For the second question -- yeah, it does make sense to make it just one question. 

For the yes/no vs. more specific answer -- rooftop vs. street or balcony feels significant, especially if someone is physically at the POI and can capture that information on the spot, but I wouldn't have any real issue falling back to yes or no, especially as a first step.

**Comment by westnordost** [comment] 2018-09-05 12:26
Though, how would on be able to determine this during times where the outdoor seating is not available? (Winter)

**Comment by yoasif** [comment] 2018-09-05 14:20
@westnordost That seems to be a question for the OSM community - there doesn't seem to be a reference to this on the wiki page. In the [leisure=outdoor_seating](https://wiki.openstreetmap.org/wiki/Tag:leisure=outdoor_seating) page, however, it is said that:

> In the small areas of cafes (often ice-cream parlors), pubs and snack restaurants, the outside seating is always reopened only in good weather at the opening times, the registration of the outside area is to be dispensed with. Here only the main day with outdoor_seating=yes. Another possibility is to record the approximate season with seasonal = *. 

I'm not sure that there is a real consensus here.

**Comment by rugk** [comment] 2018-09-05 14:45
BTW, this is a dupe of https://github.com/westnordost/StreetComplete/issues/538

**Comment by matkoniecz** [comment] 2018-09-22 05:03
> Though, how would on be able to determine this during times where the outdoor seating is not available? (Winter)

Usually one would not be able to do that (though in rare cases there is permanent outdoor seating in my region, I guess that it is more typical in warmer regions and less typical in Finland or Alaska).

It would require special handling to not show this quest during time when outdoor seating is usually seasonally hidden.

**Comment by rugk** [comment] 2018-09-23 18:33
> It would require special handling to not show this quest during time when outdoor seating is usually seasonally hidden.

I think this type of "filtering" cam up before: The "lit" quest may also be only shown in the night (especially as you theoretically cannot really distinguish the automated light from always lit, easily at least) or at least preferred (with some kind of higher priority) in the night. At least, this has been discussed before…

**Comment by andrewharvey** [comment] 2020-10-27 11:02
Not sure if it makes sense to ask a combined indoor/outdoor seating question here, https://wiki.openstreetmap.org/wiki/Key:indoor_seating, or if that is best done as a separate quest.

**Comment by Cj-Malone** [comment] 2021-03-07 20:41
Maybe it should be a regional quest then, since it doesn't make sense everywhere/colder places. In England it's typically very obvious if a place has outdoor seating, even in the middle of winter.

The conditional of when outdoor seating is available seems secondary to me, I don't think it should be a blocker to this.

This data is about to be more useful in England as it effects COVID lockdown rules, specifically with `amenity=pub`.

**Comment by andrewharvey** [comment] 2021-03-07 20:54
> Not sure if it makes sense to ask a combined indoor/outdoor seating question here, https://wiki.openstreetmap.org/wiki/Key:indoor_seating, or if that is best done as a separate quest.

eg,
Question: Does this place have seating?
Answers:
- no seating (`takeaway=only`?)
- only indoor seating (`outdoor_seating=no` + `indoor_seating=yes`)
- only outdoor seating (`indoor_seating=no` + `outdoor_seating=yes`)
- both indoor and outdoor seating (`indoor_seating=yes` + `outdoor_seating=yes`)

Ask on places that lack `outdoor_seating`.

**Comment by Strubbl** [comment] 2021-06-14 20:34
I would also the question asked for outdoor seating for `amenity=ice_cream` :ice_cream:

**Closed** 2022-03-07 21:57 UTC
Labels: new quest
