### ISSUE TITLE
Group pins overlaped

### ISSUE THREAD

**Issue by mdtrooper** [streetcomplete/StreetComplete#4060] opened 2022-05-25 00:05 UTC
**Use case**
Sometimes I have some pins over a building and I want add quest that I know it is under others for example number of building.

**Proposed Solution**
A pin with a number of quest there is in this place. And when I press show a such as a "Speech balloon" show the pins that overlaped to choose one to fill.

**Pin shows 3 quest overlaped**
![example](https://user-images.githubusercontent.com/1285451/170151268-9e0480de-513e-4172-9648-96fa7b6b7cb9.jpg)

Press this pin and the app shows as:

**The "speech ballon" show 3 quest overlaped**
![example2](https://user-images.githubusercontent.com/1285451/170151301-7a8aeea7-0e32-4be6-8b9c-ccb49f8d5e73.jpg)

**Comment by peternewman** [comment] 2022-05-25 00:33
I'll close this @mdtrooper as it's a duplicate of #124 . Please see the discussion in there for some of the issues with implementing this.

**Closed by peternewman** 2022-05-25 00:33 UTC

**Comment by mdtrooper** [comment] 2022-05-25 10:17
Oh sorry @peternewman I look for the strings "groups", "overlaped", "pins" and I didnt find this issue.

Thanks it is ok.
