### ISSUE TITLE
Tactile paving yes/no answers are switched between crossing and steps quests

### ISSUE THREAD

**Issue by dbdeanrmit** [streetcomplete/StreetComplete#5029] opened 2023-05-16 01:34 UTC
**How to Reproduce**
Attempt to answer a tactile pavings quest for a crossing and then steps. You'll see that the yes/no answers are swapped. For those of us used to answering these quests, the need to change our muscle memory each time makes it easy to answer wrong by accident.

![image](https://github.com/streetcomplete/StreetComplete/assets/131218289/b1570c46-ff2b-4cb2-9d43-3284f18be344)
![image](https://github.com/streetcomplete/StreetComplete/assets/131218289/8af9addc-2674-436c-a9d6-700925f56fab)

**Expected Behavior**
Both quests should have the yes and the no in the same position.

**Versions affected**
StreetComplete v53.0 on Android 11

**Comment by dbdean** [comment] 2023-05-16 01:37
Now that I look at it, The tactile paving steps images should probably be showing steps, not road crossings too, but that might be another issue.

**Comment by HolgerJeromin** [comment] 2023-05-16 04:34
Duplicate of #5021

**Closed** 2023-05-16 04:44 UTC
Labels: bug
