### ISSUE TITLE
How many units are there in this apartment building?

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#3076] opened 2021-07-18 21:29 UTC
### General
Affected tag(s) to be modified/added: [building:flats](https://wiki.openstreetmap.org/wiki/Key%3Abuilding%3Aflats)
Question asked: **How many units are there in this apartment building?**
Or in royal English: how many flats in this block geez

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
Although the key is valid on building=house,  I suggest limiting it to building=apartments to reduce spam.
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
Usually by a sign or by counting door buzzers
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

On building=apartments, ask how many flats/units exist in the apartment block.

**Comment by andrewharvey** [comment] 2021-07-18 22:13
Duplicate of #1152 it was already rejected, but because I'd still really love to stop manually typing this into OSMAnd and want a quest for it I put together 

I worked on the code for this a few days ago by coincidence, but so you can see I opened a PR at #3077

**Closed** 2021-07-19 16:13 UTC
Labels: duplicate
