### ISSUE TITLE
Height limit asked for underground parking exit

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#5507] opened 2024-02-26 19:28 UTC
I was asked for the height limit at this node https://www.openstreetmap.org/node/11579888534 which is connected to a one way service road away from that node. This means that the node is an "exit only" entrance that is unlikely to have a height limit sign.

**Expected Behavior**
Height limit should not be asked for underground parking exits.

**Versions affected**
10/v56.1

**Comment by mnalis** [comment] 2024-02-26 19:43
and those are defined (per [amenity=parking_entrance](https://wiki.openstreetmap.org/wiki/Tag:amenity=parking_entrance#How_to_map) wiki) as:

> The distinction between entrances which function as exits, entrances or both is defined by the [oneway](https://wiki.openstreetmap.org/wiki/Key:oneway)=* tag of the [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=* connected to the parking_entrance node.

I'm not sure how hard such check would be to implement in SC, though... (certainly seems beyond _my_ abilities)

**Comment by Helium314** [comment] 2024-02-26 20:10
see #2575

**Comment by rhhsm** [comment] 2024-02-27 06:56
> see #2575

I did a search but didn't find that one :(

I thought it wouldn't be too difficult to add a check on whether the `highway` connecting to the `parking=underground` node has `oneway=yes` and its direction, but if it is difficult, then don't bother to fix this.

**Comment by westnordost** [comment] 2024-02-27 11:11
Closing as duplicate of #2575

**Closed by westnordost** 2024-02-27 11:11 UTC
Labels: duplicate
