### ISSUE TITLE
Quest proposal: reference value of minor distribution substations in Norway

### ISSUE THREAD

**Issue by zabop** [streetcomplete/StreetComplete#6033] opened 2024-12-02 22:13 UTC
### General
Affected tag(s) to be modified/added: [ref](https://wiki.openstreetmap.org/wiki/Key:ref) for [minor distribution substations](https://wiki.openstreetmap.org/wiki/Tag:substation%3Dminor_distribution).
Question asked: **What is the identifier displayed on this substation?**

Initially, I would like this quest to be turned on for Norway. I'll answer the questions below with Norway in mind.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose

Established: yes, see [taginfo page for `ref`](https://taginfo.openstreetmap.org/keys/ref#overview).

Useful purpose: having reference values for substations eases identification of them (mapping other values might become easier once we have a reference - this is location dependent). I asked in #osm-infrastructure IRC channel what infrastructure-related StreetComplete quests there could be:
<img width="970" alt="image" src="https://github.com/user-attachments/assets/ecef3c70-c614-4dbd-bfc8-f8e8da5c7782">

- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

Yes. If the substation has a reference value, then that, if it does not, then `ref:signed=no`, just like it is the case for [fire hydrant references](https://github.com/streetcomplete/StreetComplete/blob/cfa0fd1fb0b0d68149831fe88a69d8660705ffc6/app/src/main/java/de/westnordost/streetcomplete/quests/fire_hydrant_ref/AddFireHydrantRef.kt#L32C43-L32C68).

- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary

Both yes. It's not possible to see these values from aerial or satellite imagery. It is very easy to read off these values once someone is standing next to such a substation. Some examples.

[Node 9842353095, tagged: `ref=1760`](https://www.openstreetmap.org/node/9842353095):
<img width="849" alt="image" src="https://github.com/user-attachments/assets/accc99af-a82a-436d-8930-781c21a19b53">
[Image source](https://www.google.com/maps/@59.9298042,10.7650232,3a,37.2y,157.41h,82.13t/data=!3m7!1e1!3m5!1seXM-dDosOs0JSYyHHFcBhA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D7.872904829456985%26panoid%3DeXM-dDosOs0JSYyHHFcBhA%26yaw%3D157.4107851011094!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTEyNC4xIKXMDSoASAFQAw%3D%3D).

[Way 681412608](https://www.openstreetmap.org/way/):
<img width="885" alt="image" src="https://github.com/user-attachments/assets/fc0a15f7-db7f-4135-b9ff-b8f42482d01a">
[Image source](https://www.google.com/maps/@58.66764,6.7099443,3a,25y,92.09h,81.02t/data=!3m7!1e1!3m5!1sQ62mYgcKWmbNd2vkdC7AaA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D8.977235280546267%26panoid%3DQ62mYgcKWmbNd2vkdC7AaA%26yaw%3D92.09155795261103!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTEyNC4xIKXMDSoASAFQAw%3D%3D).

[Way 1063991898](https://www.openstreetmap.org/way/1063991898)
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/eb419189-9e69-46b1-b521-6b1ffad46fb3">
[Image source](https://www.google.com/maps/@58.4284481,8.7011755,3a,18.6y,289h,76.95t/data=!3m7!1e1!3m5!1sh46P7LQqfwaRjDGn4MLwig!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D13.051790638960256%26panoid%3Dh46P7LQqfwaRjDGn4MLwig%26yaw%3D289.0026263697147!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTEyNC4xIKXMDSoASAFQAw%3D%3D)

[Way 1036467202](https://www.openstreetmap.org/way/1036467202)
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/93d6b754-0019-4377-ba15-1c4ff4d2251a">
[Image source](https://www.google.com/maps/@60.8529257,11.3629275,3a,15y,120.66h,78.55t/data=!3m7!1e1!3m5!1skjMPJpqDDBHDY33Pm34GDA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D11.451096211132608%26panoid%3DkjMPJpqDDBHDY33Pm34GDA%26yaw%3D120.66286633619029!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI0MTEyNC4xIKXMDSoASAFQAw%3D%3D).

I can go take images with my own camera if we need it due to restrictive Google Street View licencing. Not mapping from them, but seeing that substations tend to have a reference value is I believe ok.

- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)

We should take care not to enable this quest in countries where lots of substations are without a reference. I think Norway is a good start. Mappers knowledgeable on their countries' substations could suggest to expand the countries this quest is enabled for.

- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

I am confident I can make a reasonable PR for this quest - I hope the effort required by others is close to 0. There are [16296 cases in Norway where this quest is relevant](https://overpass-turbo.eu/s/1V5f).

### Ideas for implementation

**Element selection:** 

```
nodes, ways with
substation = minor_distribution
and !name and !ref and noref != yes and ref:signed != no and !~"ref:.*"
```

**Metadata needed:** 
I don't think this is needed.

**Proposed UI:**

Below are some screenshots form a mockup in Android Studio. (This being a demo there are imperfections - like "Marked Crossing" - but I can fix them. I'll leave some work for after this is approved.)

![image](https://github.com/user-attachments/assets/5c6731a2-e158-43ea-affc-1064745a3b29)
![Screenshot_20241202_230212](https://github.com/user-attachments/assets/0fbe8ef6-9b4c-4dfc-8483-1b75d88fe0d8)
![image](https://github.com/user-attachments/assets/a579c571-3378-4d9c-ba55-7c35b275f069)

Icon suggestion:
<img width="463" alt="image" src="https://github.com/user-attachments/assets/3df24979-4284-424d-9498-6dc1b1b35256">

**Comment by HolgerJeromin** [comment] 2024-12-02 22:25
Thanks for taking the time for this suggestion with very much input.
Still this is a duplicate of closed #4106

See this for explanation of rejection:
https://github.com/streetcomplete/StreetComplete/issues/4106#issuecomment-2289974399

**Comment by zabop** [comment] 2024-12-02 22:34
Oh I see, thank you!

I copy the [rejection reason](https://github.com/streetcomplete/StreetComplete/issues/4106#issuecomment-2289974399) so that we have it here as well:

> I am going to reject this quest suggestion because it would be difficult to ascertain for users whether "some number" / "some letters" on a substation would be the ref, or something else. There could also be several numbers on it, or none.
> Also, the useful purpose of this information is somewhat unclear.

**Would it be possible to save this quest proposal if we find a region which has a consistent substation reference format?**
Ie `ABC-123`. Then hopefully it is pretty clear which value is the reference and which is "something else".

**Comment by Gazer75** [comment] 2024-12-02 22:34
Not to be rude or anything, but that is a silly reason to reject it.
If people can't see the difference between a name and an ID they got issues.

It could also be added in a note or the change should add a flag to have the edit reviewed by someone.

**Comment by zabop** [comment] 2024-12-02 22:46
I edited the title to better reflect the text I've written.

**Closed** 2024-12-02 23:25 UTC

**Comment by matkoniecz** [comment] 2024-12-03 06:55
> It could also be added in a note or the change should add a flag to have the edit reviewed by someone.

no, sc edits (except exceptional situations where usual answers are not viable) are supposed to require no fixup/completion from other mappers

**Comment by mnalis** [comment] 2024-12-03 15:43
Just to notify interested parties that [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) ***also has*** the **generic** _"What's the identification number here?"_ quest, which (among other things) by default asks for `ref=*` on `building=service` + `power=substation` (IIRC came as a part of https://github.com/Helium314/SCEE/issues/531). And, it also can be customized (when _"expert mode"_ is enabled) to trigger on _any_ tag combination (like the exact element selection query suggestion in this issue by @zabop, or e.g. recent request https://github.com/streetcomplete/StreetComplete/issues/6031 etc).


So people who are confident they can reliably identify a reference number, are not bothered by potential spamminess and believe such data is useful and worth their time can peruse SCEE to add those `ref=*` on anything they like.  

By default SCEE looks almost exactly the same as regular StreetComplete (until one starts enabling more and more of the extra functionality, of course) so there should not be much barriers to try it out.
