### ISSUE TITLE
New Feature: Skip single quests during a session

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#3514] opened 2021-11-18 12:29 UTC
**Use case**
It may happen that I use StreetComplete during a walk and try to answer as many quests as possible without stopping or changing the side of the street.
I often have the problem that I "fail" at quests, which I can't answer in passing, but know exactly that in my defined quest order there would be a quest after that, which I could answer.
There could be numerous examples of this. For example, at a bus stop: I can tell if there is a shelter from across the street, but I can't tell if there is Tactile Paving from across the street in the dark. However, I would be able to answer the following quest "Is this bus stop lit" in the dark. Anyway, I can't get to that without answering the Tactile Paving quest. As I said, there are several such sequences.

Also, questions regarding a restaurant can sometimes be answered well from the outside, but others only from the inside.
If I don't want to enter the restaurant at the moment, I would want to skip the indoor questions for now. Maybe I'll make it inside at another time, but not now.

**Proposed Solution**
Long story short: **Why can't you just skip single questions?**
The solution I have in mind seems quite simple. It should be possible to skip each question. This could be, for example, a prominent button with an icon or the lettering "skip" above the question. Or it could also be in the dialog of "Not answerable". Whereas I would consider the latter too complicated for UX reasons.

If a question is skipped, it will not be displayed again within the current session. Restarting the app would display the question again at any time. Thus, nothing would have to be stored for a long time.

A global setting whether quests can be skipped or not I think is unnecessary, but might make sense for others.

_I tried to find an existing issue but could not find one for myself. If there is already one, feel free to link and close it here._

**Comment by smichel17** [comment] 2021-11-18 13:29
I think #124 is a different solution to address the same problem. Specifically https://github.com/streetcomplete/StreetComplete/issues/124#issuecomment-755492391

For now, you can have a "manual" version of this (aka workaround) by choosing `Other Answers` > `Can't say` > `Just hide`; answering the quest "underneath"; and then opening the undo menu and restoring the hidden quest.

**Comment by mcliquid** [comment] 2021-11-18 13:59
@smichel17 Thanks for the link. No question, a very valid feature request!
However, the workaround only works mediocre for a skipped question and an underlying question.
As soon as you want to skip a question and numerous other questions appear afterwards, the workaround with undo is not really clear anymore.
The workaround would be workable for me if the quest would reappear on restart. But currently it does not reappear even after a restart. For the sake of completeness, I would like to link #2466 here. That's what I was looking for.

Anyway, the functionality in #124 looks very promising. For all I care this can be closed, I will be following #124 with high expectation 👍

**Comment by smichel17** [comment] 2021-11-18 14:39
Okay, then I'll close this as a duplicate of #2466 and to-be-addressed by #124.

**Closed by smichel17** 2021-11-18 14:40 UTC
