### ISSUE TITLE
Shoulder quest selection screen is opposite of pictorial representation (leading to incorrect tagging in OSM)

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#4137] opened 2022-06-19 01:42 UTC
In the latest version (v45.0-alpha1), when you answer a shoulder quest the answer you select in the selection window is opposite to what it draws on the pictorial representation of the road in the lower half of the screen.

It appears that the actual tagging is taken from the selection, so if you decide that the pictorial representation is correct, you will end up getting the exact opposite in the OSM data (shoulders where there aren't any, and no shoulders where there are)

**How to Reproduce**
Answer a shoulder question in the latest version of StreetComplete

**Versions affected**
StreetComplete v45.0-alpha1

**Comment by legofahrrad** [comment] 2022-06-19 06:04
duplicate of #4116

**Closed** 2022-06-19 06:31 UTC
Labels: bug
