### ISSUE TITLE
Add dropdown with street name selection also to add:street quest

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#3178] opened 2021-08-17 18:49 UTC
**Use case**
I recently had lots of quest either where I entered the house number (walked by, confirmed it) or where the street name itself was not known. In the first case I was asked next to enter the street name, in the second case I was asked this immediately. 

After this the second house number is not known either or a branch *of the same street with the same name* is asked (e.g. at junctions several branches are asked, or sometimes streets are mapped in parts). Now I have to (fully and manually) reenter the street name. And sometimes I needed to to this a dozen times in a row.

This has two disadvantages: I have to retype possible difficult and long street names (causing time and not pleasant on a small display) and I'm highly likely to introduce typos. I sometimes reverted the answer because I spotted the typo too late, especially after the quest cleared the window and I could read the map (fully) again on the mobile device (and thus notice the correct spelling).

If the connecting or "close" streets already have a name, then it is highly possible that this name applies for this specific part or house number as well, especially for the house number use case. So instead of having to (repeatedly) reenter the same name over and over, I would have preferred some smart history, which would simply allow me to tap on the right one. (see below).

**Proposed Solution**
If technical possible, then the quest "street name" should be accompanied by a few "close" streets. If entering the street names (use case two) it could simply be those connecting ones (if known). For house numbers (use case one) this might be more tricky. Then I could select the appropriate one from the list with one tap + ok. The last entry would be "other", where I could enter the correct one (if really missing or new). For new streets names, "other" would be used once, and then this name would appear in the list as well.

If the first solution is not possible (at least for house numbers) then a small history would be a great improvement. So if I walk down a street, capturing house number by house number (and then subsequently the street name), I would need to manually enter the street name once (the first time), and in subsequent questions the last N street names would be shown (where most likely the top one is the correct one). This is "second best" as I would need to enter each street name at least once, even if the name has already been recorded.

**Comment by 10992-osm** [comment] 2021-08-17 18:53
You should already be able to tap on the street on the map in order to fill in the street name quest by copying the streets name into the field, there's no need to type it out.

**Comment by Helium314** [comment] 2021-08-17 18:57
> You should already be able to tap on the street on the map in order to fill in the street name quest, doing so copies the streets name into the field, there's no need to type it out.

This only works for the addr:street quest. For the street name there is a small arrow which opens a dropdown with nearby street names.

**Comment by 10992-osm** [comment] 2021-08-17 19:00
> > You should already be able to tap on the street on the map in order to fill in the street name quest, doing so copies the streets name into the field, there's no need to type it out.
> 
> This only works for the addr:street quest. For the street name there is a small arrow which opens a dropdown with nearby street names.

You replied just as I edited my comment, @Helium314.

It seems that everything is already implemented in the app, for both addresses and street names (just in slightly different ways for each).

**Comment by Helium314** [comment] 2021-08-17 19:02
Not sure why the difference in UI, currently I'm too lazy to read through #2160

**Comment by 10992-osm** [comment] 2021-08-17 19:14
> Not sure why the difference in UI, currently I'm too lazy to read through #2160

I've just read through it, and I'm not sure it says what the rationale is.

**Comment by hmartink** [comment] 2021-08-17 19:26
> You should already be able to tap on the street on the map in order to fill in the street name quest (for addresses), doing so copies the streets name into the field, there's no need to type it out.

I was not aware of this, thanks for the hint. This is, however, not always easy, as most of the screen is covered by the quest, but I will try it next time (which might be some time, because my area is reasonably tagged, I don't know when I will discover such next time).

**Comment by Helium314** [comment] 2021-08-17 19:32
> This is, however, not always easy, as most of the screen is covered by the quest

This seems like a good reason to add the dropdown to the address street quest... from #2160 I don't understand why this wasn't done.

**Comment by matkoniecz** [comment] 2021-08-17 19:42
I renamed the title to match what was intended

**Comment by westnordost** [comment] 2021-08-17 20:27
> I was not aware of this, thanks for the hint.

It is indicated as a hint in the edit text to add the street name though. Closing as invalid.

**Closed by westnordost** 2021-08-17 20:27 UTC

**Comment by 10992-osm** [comment] 2021-08-17 21:05
> > I was not aware of this, thanks for the hint.
> 
> It is indicated as a hint in the edit text to add the street name though. Closing as invalid.

Are you able to shed light, though, on what reason (if any) there is for not having a street selection dropdown for this quest?  If there was that could help with the issue described in [this comment](https://github.com/streetcomplete/StreetComplete/issues/3178#issuecomment-900570756) (that there is little space on the screen, making selecting a road difficult).
