### ISSUE TITLE
Things-Layer: mail box missing 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5699] opened 2024-06-22 14:14 UTC
Maybe I'm missing something here, but I tried to add a not yet mapped mail box and couldn't find it in the "Things"-Layer. 

Is there a reason for that? 🤔 

**Screenshots**

![Screenshot_2024-06-22-16-08-00-595_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/614929/679b54e1-44a2-4022-879e-ad0bb0330498)
![Screenshot_2024-06-22-16-08-05-711_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/614929/81a88e42-e292-4c27-8b48-5b145ec8ca5b)
![Screenshot_2024-06-22-16-08-10-598_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/614929/3d24a61d-a1cd-49a4-aaa1-c0fc01846c24)
![Screenshot_2024-06-22-16-08-15-853_de westnordost streetcomplete](https://github.com/streetcomplete/StreetComplete/assets/614929/00ba8f25-3e8a-4ab0-8b08-59dff5374d1d)

**Versions affected**
58.0

**Comment by westnordost** [comment] 2024-06-22 14:18
Duplicate of #4916 

(It is a missing feature in a library - https://github.com/westnordost/osmfeatures/issues/23)

**Closed** 2024-06-22 14:18 UTC
Labels: bug

**Comment by RubenKelevra** [comment] 2024-06-22 14:21
Hey @westnordost,

It's not a duplicate of #4916 because this issue is also closed.

I've searched for open issues before creating this one, and there are none.

**Comment by westnordost** [comment] 2024-06-22 14:23
It is a duplicate. https://github.com/westnordost/osmfeatures/issues/23 is where the issue needs to be dealt with.

(Yes, I could keep an issue here open and effectively have two issues for the same thing, but I don't see why I should do that.)

**Comment by RubenKelevra** [comment] 2024-06-22 14:27
Yeah please reopen #4916 for tracking purposes. There have been 4 people invested time to write an additional bug report now.

**Comment by goldfndr** [comment] 2024-09-02 18:34
Note that, if you're using SCEE (an *Expert Edition* fork of StreetComplete), you can long-press a spot then choose Add POI and find post box (US: mail drop box) in its list.
