### ISSUE TITLE
Unable to attach a photo to notes

### ISSUE THREAD

**Issue by FlocutierOSM** [streetcomplete/StreetComplete#5555] opened 2024-03-25 17:07 UTC
I cannot attach photos to notes. It is possible to take the photo with the photo button but all it does is show the picture without any options to actually attach it to the note. Screenshot below:
![photobug](https://github.com/streetcomplete/StreetComplete/assets/164913720/1ee093be-1b62-4d45-adcc-00552b23a5f1)

**How to Reproduce**

1. Tap a quest.
2. Choose: Impossible to answer and add a note
3. Tap the photo button
4. Take a picture
5. At this point all you can do is press return and thus discard your photo. No way to attach it to the note.
I can provide a video if necessary but it should be obvious what I mean with "photo button":
![photobutton](https://github.com/streetcomplete/StreetComplete/assets/164913720/cf217318-d088-4930-af54-e1d5264b14ca)

**Expected Behavior**
After taking a photo it should either automatically attach to the note or present a button/dialogue to attach it to the note.

**Versions affected**
Android 13 (LineageOS 20)
Streetcomplete 57.1

**Comment by westnordost** [comment] 2024-03-28 21:40
The screen you see there is actually not StreetComplete, but your default camera app. StreetComplete asks your default camera app to please take a picture and return it to StreetComplete when the user confirmed it.

Usually, the camera app should show something like a "ok" or checkmark button or similar. That it is not shown or invisible is a bug in your camera app. You need to report this issue to LineageOS folks.

That said, I do have exactly the same problem with the default camera app of LineageOS. However, the button seems to be there on the lower side of the screen (either centered or slightly to the right, not sure), it is just invisible.

Anyway, I am closing this as not a bug of the app, feel free in case you open a bug report at LineageOS to link back here.

**Closed by westnordost** 2024-03-28 21:40 UTC
Labels: bug

**Comment by mnalis** [comment] 2025-04-24 23:09
ref. [SC FAQ: How do I attach a picture to the note?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_do_I_attach_a_picture_to_the_note?)  and https://github.com/streetcomplete/StreetComplete/issues/5841#issuecomment-2308991888
