### ISSUE TITLE
Main road / highway on dark mode are not readable

### ISSUE THREAD

**Issue by brateq** [streetcomplete/StreetComplete#3492] opened 2021-11-07 12:34 UTC
The dark layout is using a transparent line for highways and it's a mess at exits and tunnels. In addition, is not consistent with the day layout. 
Some examples:
![2021-11-07 13 19 28](https://user-images.githubusercontent.com/5649199/140644916-ea500b8f-4055-4e23-974b-b8d6bd54822e.jpg) ![2021-11-05 17 41 26](https://user-images.githubusercontent.com/5649199/140644974-961efba2-e2db-4fda-8eaa-fae932aca533.jpg)

**How to Reproduce**
Check highway=primary and highway=trunk

**Versions affected**
Android 11, StreetComplete v37

**Comment by westnordost** [comment] 2021-11-07 22:35
Sure it is not a motorway / trunk?

**Comment by brateq** [comment] 2021-11-07 23:12
It is motorway/trunk, my only suggestion would be to remove transparency from the line and/or change the color of the road.

**Comment by westnordost** [comment] 2021-11-08 11:13
I don't think any quests are asked for motorways, so that motorways are displayed at all is more for orientation purposes than anything. Also, if you actually tap on a road, it will be highlighted independently.

I'd not like to change the style here, the additive drawing is a nice cool effect I wouldn't want to miss. Different color - maybe, but how would that improve the clarity here? With it being turqoise, you can at least tell apart normal roads from motorways easily.

**Comment by peternewman** [comment] 2021-11-08 13:57
Isn't this just a duplicate of https://github.com/streetcomplete/streetcomplete-mapstyle/issues/84 ?

**Comment by matkoniecz** [comment] 2021-11-08 14:07
yeah, duplicate of an open issue

**Closed by matkoniecz** 2021-11-08 14:07 UTC
