### ISSUE TITLE
Panel opens by default below navigation bar

### ISSUE THREAD

**Issue by carstenhag** [streetcomplete/StreetComplete#5861] opened 2024-08-30 22:15 UTC
**How to Reproduce**
Open app, tap on task. Maybe specific to "what parking type is it" task?

**Expected Behavior**
Handle all cases of navigation bars (3 buttons, gesture...) on all android levels.

In this specific case, "Äh" is hidden below the navigation bar, without a reason

**Versions affected**

Poco F5 Android 14, StreetComplete v58.2

https://github.com/user-attachments/assets/b30abfb2-9a0e-49e5-97dd-ba50f9741f3f

**Comment by carstenhag** [comment] 2024-08-30 22:18
On this "what house number is it task" it opens correctly.
![Screenshot_2024-08-31-00-17-44-015_de westnordost streetcomplete](https://github.com/user-attachments/assets/5e81b07a-6d2a-4077-8fa6-0eb48cdfb4d6)

**Comment by westnordost** [comment] 2024-08-31 16:51
Can't reproduce (Samsung 10e+, Android 13). Is this an Android 14 specific issue? Can someone else with an Android 14 confirm?

**Comment by riQQ** [comment] 2024-08-31 18:52
Can confirm the issue on Android 14 on a Pixel 6a:

![Screenshot bug navigation bar overlap](https://github.com/user-attachments/assets/10008ea3-04a3-461e-a890-a9486052cd92)

**Comment by mnalis** [comment] 2024-08-31 19:11
@riQQ that in on StreetComplete `v58.2` or ... ?

on my Android 14 (Samsung Galaxy S23+) on SC `v59.0-alpha3`, the parking is initially shown under navigation bar, but can be scrolled up without issues (and few other quests display themselves above navigation bar automatically,: as expected):


https://github.com/user-attachments/assets/b690cd20-c370-4b3e-9702-c39bda17f427

**Comment by riQQ** [comment] 2024-08-31 20:17
> @riQQ is that screenshot of yours on StreetComplete `v58.2` or ... ? And can you move it manually, or does it always bounces back / hides itself again when you try to show it?

Yes, it's 58.2 and behaves as it does for you, i.e. it doesn't bounce back automatically.

**Comment by westnordost** [comment] 2024-09-01 17:48
Oh, so you can confirm that you can _not_ reproduce the issue on your Android 14? 🤔

**Comment by riQQ** [comment] 2024-09-01 20:06
> Oh, so you can confirm that you can _not_ reproduce the issue on your Android 14? 🤔

Well, I can reproduce the 'issue' that is reported in the title and the opening post but I can't reproduce the bouncing from the video. So maybe it should be clarified what this issue is about.

**Comment by carstenhag** [comment] 2024-09-01 20:09
Sorry, maybe my video was unclear. There's no automatic bouncing. I moved the panel with my fingers, to show that it's draggable to a good state.

**Comment by mnalis** [comment] 2024-09-01 22:45
> Sorry, maybe my video was unclear. There's no automatic bouncing

Oh, so the issue is just that it is covered by default. It probably has to do with quest window height - some quests (e.g. _Surface quest_ or _Recycling quest_) will always be too big to show on the screen so will be under navigation bar and require (a lot of) scrolling.  Some require just a few lines of scrolling on most devices (e.g. _Curb height_ quest). 

So it may be that _Parking type quest_ is just of the right size so it requires just a tiny (one-line) scroll. 

If that is so, then I guess this is not a bug at all, but a simple coincidence.

**Comment by westnordost** [comment] 2024-09-01 22:53
Oh, I get it now. I viewed the video of the issue starter again. Actually, it doesn't seem to bounce back at all but the issue starter moved it back manually. So, it's actually not a bug. 

Quest forms have a certain maximum height that are initially displayed in the bottom sheet. Quest forms smaller than that certain height shown fully from the beginning. For quest forms that are larger than that, for example the quest that asks for the surface, only the upper part is shown and to see all the options, the user needs to scroll down further.

For the quest that asks for the type of parking, it is just barely higher than the maximum height at which it would be shown fully from the beginning, just "hiding" the other answers bar below the navigation buttons. It so well aligns with the navigation bar, that it looked like a bug to the user.

Anyway, with this explanation, I will close the issue as not-a-bug.

**Closed by westnordost** 2024-09-01 22:53 UTC
Labels: bug, feedback required
