### ISSUE TITLE
No quests if building has incomplete data but is of type "flats"

### ISSUE THREAD

**Issue by codeinabox** [streetcomplete/StreetComplete#2720] opened 2021-04-03 16:21 UTC
I've noticed that quite a few buildings in my area don't appear as quests even though they have incomplete data and on further inspection it is because they have the tag `building=flats`

**How to Reproduce**
Find a building of type `flats` but with incomplete data eg https://www.openstreetmap.org/way/197881319

**Versions affected**
StreetComplete version 31.1

**Comment by matkoniecz** [comment] 2021-04-03 16:24
`building=flats` is a rare duplicate of `building=apartments` https://taginfo.openstreetmap.org/tags/building=flats

I would consider asking local community for permission and mass-retagging them to `building=apartments` ( https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct )

**Comment by codeinabox** [comment] 2021-04-03 17:22
Thank you for the quick reply. I had considered retagging them as `apartments` but I was hoping a solution was these buildings were treated like `building=yes` and StreetComplete would present the building type quest.

**Comment by matkoniecz** [comment] 2021-04-03 17:38
Note that anything else caring about `building` value also will be confused, and that there is over 100 more popular `building` values.

And it seems, at least to me so clear duplicate that it is likely viable bot edit target.

**Comment by westnordost** [comment] 2021-04-03 21:25
"Unknown" buildings cannot be treated as `building=yes` because `building` is essentially a free-form tag. It is considered completely OK to make up your own tag value (as opposed to f.e. `highway=*`) as far as I know. But if StreetComplete would ask "what kind of building is this?" for buildings it doesn't know, the app would propagate a certain consolidation of tag values that is not wanted and also has the potential to destroy data. 

Why could it destroy data? For example, if a building was tagged as `building=post_office` and a StreetComplete user would re-tag that to `building=civic`, it would be a loss of data. I chose the example for posts because I know 3 buildings in the city center of Hamburg which were constructed by the post. They might have a more specific tag than simply `building=office` or `building=civic` and that's completely ok:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Alte_post_by_gray_1860_sub.jpg/381px-Alte_post_by_gray_1860_sub.jpg"/>
<a href="https://de.wikipedia.org/wiki/Alte_Post_(Hamburg)">Alte Post</a>

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Oberpostdirektion_%28Hamburg-Neustadt%29.phb.ajb.jpg/640px-Oberpostdirektion_%28Hamburg-Neustadt%29.phb.ajb.jpg"/>
<a href="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Oberpostdirektion_%28Hamburg-Neustadt%29.phb.ajb.jpg/640px-Oberpostdirektion_%28Hamburg-Neustadt%29.phb.ajb.jpg">Alte Oberpostdirektion]</a>

<img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Postamt_Hamburg-H%C3%BChnerposten_1904.jpg"/>
<a href="https://de.wikipedia.org/wiki/H%C3%BChnerposten">Altes Bahnpostamt Hühnerposten</a>

**Closed by westnordost** 2021-04-03 21:25 UTC
Labels: question

**Comment by matkoniecz** [comment] 2021-04-03 22:01
And maintaining list of all `building` values that can be safely retagged would be a monstrous time sink and is not feasible.
