### ISSUE TITLE
foot, bicycle, motor_vehicle access for highway=track,path

### ISSUE THREAD

**Issue by andrewharvey** [streetcomplete/StreetComplete#2930] opened 2021-05-30 09:24 UTC
This needs to be fleshed out in more detail, but in general for `highway=track` it's useful to explicitly tag foot, bicycle and motor_vehicle access, and for `highway=path` foot and bicycle access.

Maybe we decide that many places it can be hard to determine legal bicycle access if not signed, but many places are signed. Likewise for track usually you can tell if it's on a private farmland, or if gated (therefore motor_vehicle=private).

### General
Affected tag(s) to be modified/added: [access=*](https://wiki.openstreetmap.org/wiki/Key:access), `foot=*`, `bicycle=*`, `motor_vehicle=*`.
Question asked: **Who can walk|cycle|drive here?**

- It is open to the public `*=yes`
- It is inaccessible to everyone `*=no`
- Only individuals with special permission `=private`

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
**Element selection:** `highway=track`, `highway=path`.

**Comment by matkoniecz** [comment] 2021-05-30 10:14
> but in general for highway=track it's useful to explicitly tag foot, bicycle and motor_vehicle access, and for highway=path foot and bicycle access.

Is it really useful to ask and tag it for every single `highway=track`?

I have doubts here, and I have no ideas how to restrict it so some subset would be always worth asking.

**Comment by mnalis** [comment] 2021-05-30 20:08
I'd agree with @matkoniecz here; in Croatia for example it is extremely rare for a path and track to be signposted with vehicle type access, so it would be spammy. Only times where I did see it outside of town was for mountainbike DH routes over forest paths, and even there it was only `bicycle=designated` + `foot=discouraged`.

For in-town uses, problem simply does not arise - it is never marked as bare `highway=track` in the first place (instead being for example `highway=residential` + `surface=dirt`), nor as bare `highway=path` (instead being `highway=footway` or `highway=cycleway` or upgraded to `bicycle=designated`+`foot=designated`+`segregated=*` if they are combined).

**Comment by andrewharvey** [comment] 2021-05-30 23:47
> Is it really useful to ask and tag it for every single highway=track?

Yes it's really useful for every single highway=track, otherwise routers don't know if they can send a car/bike/walker down the track.

> in Croatia for example it is extremely rare for a path and track to be signposted with vehicle type access, so it would be spammy.

It can be either disabled for Croatia or enabled for selected countries, I don't see this as justification for not allowing the quest to appear in regions where it would be useful.

**Comment by cyclingcat** [comment] 2021-05-31 06:28
In Germany it's just the other way round than in Croatia: There are myriads of traffic signs (plus even more supplementary signs) ruling the access of roads including (agricultural) tracks. There is even a [German website specialised in OSM tagging based on traffic signs](http://osmtools.de/traffic_signs/). Of course you can expect any kinds of combinations of the supplementary signs and I haven't mentioned conditional restrictions yet...

To make things even worse, you can find in the wild tracks with different signposts in both directions and even contradicttory signages. My personal favourite: Sign 250, "All vehicles prohibited" (this includes bicycles, official penalty for cyclists: 15 €!) plus a green bicycle sign leading a popular touristic cycleway over this track.

(Never underestimate German bureaucracy! :laughing:)

So I'd strongly discourage to present this quest in Germany also!

The cycling cat

**Comment by matkoniecz** [comment] 2021-05-31 07:03
> Yes it's really useful for every single highway=track, otherwise routers don't know if they can send a car/bike/walker down the track.

Well, in Poland it means  tagging various entrance barriers and surface info and occasional `vehicle=private bicycle=yes` signage is necessary to handle cars. Or avoiding `highway=track` in general that are typically without asphalt, likely to be randomly blocked due to logging and not a main road into village anyway.

Note that `vehicle=private bicycle=yes` signage is on forest entrance - so to tag it you need to visit all forest entrances around forest (or forest section). You will not get this info from surveying say https://www.openstreetmap.org/way/261896953

As bikers/walkers are allowed on basically all `highway=track` adding it on every single one would be mostly waste of time and massive effort. And likely annoy other mappers (`cycleway=separate` / `cycleway:both=no` is already considered as irritating by some).

**Comment by andrewharvey** [comment] 2021-06-01 12:43
>  surface info

That's irrelevant for motor_vehicle/bicycle/foot legal access.

> barriers

The barrier can be mapped (though not with StreetComplete), and access tags can go on that barrier, but it's not a replacement for tagging the way with access tags, and sometimes there is no physical barrier just signage indicating legal use.

 > Or avoiding highway=track in general in routing that are typically without asphalt, likely to be randomly blocked due to logging and not a main road into village anyway.

Yeah if you're building a general purpose car navigation software, then yes I'd agree you'd want to avoid highway=track unless explicitly tagged as accessible, but if a 4WD enthusiast is looking for places to go 4WDing or a cyclist looking for places to cycle to, it's helpful to know where they can go.

> Note that vehicle=private bicycle=yes signage is on forest entrance - so to tag it you need to visit all forest entrances around forest (or forest section). You will not get this info from surveying say https://www.openstreetmap.org/way/261896953

That's a fair argument, that typically you might only be able to tell from the start of the track, but unless you're helicoptering or parachuting in then you're probably also passing the entrance.

> As bikers/walkers are allowed on basically all highway=track adding it on every single one would be mostly waste of time and massive effort.

Fair enough for your country, but around me there are some tracks on public land you can't walk on (though these are very rare), some tracks you can't cycle on (less rare). Then there are tracks on private farmland that by default are access=private, but need to be tagged this way.

I'm also suggesting this quest for highway=path, where bicycle access cannot be assumed usually.

**Comment by matkoniecz** [comment] 2021-06-01 14:19
> That's a fair argument, that typically you might only be able to tell from the start of the track, but unless you're helicoptering or parachuting in then you're probably also passing the entrance.

The problem is that sometimes passage is blocked on five entrances and sixth allows access. So one needs to check all of them.

> I'm also suggesting this quest for highway=path, where bicycle access cannot be assumed usually.

At least in Poland it is tricky for a different reason: in many cases legal access is unclear, noone really knows and noone really cares :)

**Comment by andrewharvey** [comment] 2021-06-01 23:21
There is always "can't say", but the problem is there is no tag to say I've surveyed and access is unclear.

**Comment by westnordost** [comment] 2021-06-07 13:18
Yeah, thhis is a WNF, see @matkoniecz. Tagging `access` on every single track will not be accepted by the community and if it was, it would still be a vers spammy quest as in my experience, the usual track does not have any signs that would indicate that it is publicly accessible or not.

**Closed by westnordost** 2021-06-07 13:18 UTC

**Comment by andrewharvey** [comment] 2021-08-23 11:57
Some discussion took place at https://lists.openstreetmap.org/pipermail/talk-au/2021-August/014917.html so following up with some more thoughts about how we could implement this.

So I'm still of the view that access on every track is or can be accepted at least for some countries, and while some areas might all have the same answer, on a wider geographical area there will be a variety of answers so the quest is worth it.

On the lack of signage, it varies a lot, some tracks would have good signage but many not, lacking signage sometimes the local knowledge of being on the ground will make it clear the implied access, other times it might be safe to assume access unless there is specific signage forbidding access or barriers. There is always the can't say response.

My skewed personal experience is that highway=track is either:

1. An agricultural track on private property (eg. a farm) and so access=private as no mode is allowed.
2. A fire trail or forestry track on public land. It's almost always accessible by foot, and usually accessible by bicycle, and could go either way for motor_vehicle, so these would generally not have access=* and instead have foot=*, bicycle=* and motor_vehicle=* set.

So based on this my thoughts on a possible quest flow. I'm not terribly happy with it, seems too complex, so will need to work on refining it. Need to then expand outside my narrow view to make sure it's inclusive of other scenarios.

We would also need to consider if we support all possible values or not https://wiki.openstreetmap.org/wiki/Key:access#List_of_possible_values

Q1. Can the public use this track?
- It varies based on mode of transport. (goto Q2)
- Yes, the public can access by any mode of transport. (goto A1)
- No, the public can't access it, regardless of mode of transport. (goto A2)

Q2. What is the access situation for motor_vehicles? (combination of A1/A2)
Q2. What is the access situation for bicycles? (combination of A1/A2)
Q2. What is the access situation for pedestrians? (combination of A1/A2)

A1. Is this access signposted or implied (no barriers or forbidding signage)?
- Signposted (access=designated)
- Implied (access=yes)
- other access values?

A2. If there is no public access, then who can access it?
- Nobody (it's physically inaccessibly) (access=no)
- Individuals with permission from the owner or operator (access=private)
- other access values?

**Comment by SomeoneElseOSM** [comment] 2021-08-23 12:10
>  Tagging access on every single track will not be accepted by the community 

It really depends on "which community" - default access rights vary hugely around the world.  Some places by default allow access, perhaps within a set of "terms of use" (e.g. https://www.outdooraccess-scotland.scot/practical-guide-all et al in Scotland).  In some places (e.g. England and wales) the reverse is true - the default is "no access" unless something is explicitly signed.  In still others access is legal, but often signed "at your own risk".

It would absolutely make sense to ask "something about access" in most places, but what that question is would vary completely between jurisdictions (e.g. even between Scotland and England).

For more details about "what people think the defaults should be worldwide" just look about some of the discussions around Amazon logistics mapping - they're remotely adding last-mile access tracks, and in different countries have been asked to:

- ensure that they add them as private
- ensure that they add them NOT as private
- (by different people) ensure that they add them as private AND as public

A suggestion of questions to ask for e.g. Australia (as above) will be great for Australia, but won't make sense everywhere - for example in England and Wales I think that most people - including most experienced OSMers - would get the answer to the initial "Can the public use this track" wrong most of the time, unless they were guided to look for specific signage and it was explained what that signage specifically meant.

**Comment by matkoniecz** [comment] 2021-08-23 12:18
> It would absolutely make sense to ask "something about access" in most places

Would it be possible to always tag something? Note that in StreetComplete something must be tagged as result of quest, so given area would need to be 100% fine with explicit tagging of also public access. (though maybe this quest can be limited to ways with `access=unknown`?)

> We would also need to consider if we support all possible values or not https://wiki.openstreetmap.org/wiki/Key:access#List_of_possible_values

definitely not all, there needs to be an escape hatch "access rules here are not fully covered by this limited form? Leave a note!".

> So based on this my thoughts on a possible quest flow. I'm not terribly happy with it, seems too complex

It seems sort of viable, but I am a bit scared by it :)

**Comment by SomeoneElseOSM** [comment] 2021-08-23 12:46
> Would it be possible to always tag something?

(answering for England and Wales only) 

It depends how the community reacts to tagging "the absense of signage".  Taking a simple English example, https://www.openstreetmap.org/way/78823305 has "foot=yes" on it because there's legal access there by virtue of a public footpath sign (and it also has a "designation" tag to reflect that).  A little further to the south there's no signage for https://www.openstreetmap.org/way/738969335 (but actually it probably has the same legal status).  In England and Wales the actual existence of on the ground signage (as in the northern example) is only rarely tagged on the object itself.  

An implicit "foot=yes" can come from a few different places:

- on the ground public footpath signage
- on the ground access land signage
- OSM-licence-compatible data from the local council (in the case of some local councils)
- interpolation - if the only way of getting between a known public footpath at A and a known public footpath at C is via B, then it's reasonable to assume that the path at B is a public footpath too.

>  "access rules here are not fully covered by this limited form? Leave a note!"

I'm not convinced that adding notes here is helpful.  It's easy as a human to determine which ways need surveying for access rules - those without access tags but without a note explaining why, those with inconsistent access tags but without a note explaining why, and those _with_ access tags but without a designation or a note.  What's hard is how to explain this to a computer  :)

So far I'm not aware of widespread opposition to "new StreetComplete tags" (like e.g. https://wiki.openstreetmap.org/wiki/Key:check%20date?uselang=en-GB - that's not a new tag, but widespread usage is due to StreetComplete), but I suspect that some people would object to a tag for "the absence of a public footpath sign on a footpath".

**Comment by matkoniecz** [comment] 2021-08-23 12:58
> I'm not convinced that adding notes here is helpful. It's easy as a human to determine which ways need surveying for access rules - those without access tags but without a note explaining why, those with inconsistent access tags but without a note explaining why, and those with access tags but without a designation or a note. What's hard is how to explain this to a computer :)

An useful note would include explanation and photo of a location what may have a decent chance to provide info for a remote edit (not sure how likely it is for UK access tags).

> So far I'm not aware of widespread opposition to "new StreetComplete tags"

I prefer to avoid it appearing in the first place :)
