### ISSUE TITLE
Lanes quest and oneway roads

### ISSUE THREAD

**Issue by Mannivu** [streetcomplete/StreetComplete#3867] opened 2022-03-11 09:42 UTC
I find the "Lanes quest" a bit confusing when I have to answer about oneway roads. For multiple lanes ways there's no issue (it's pretty clear how to answer), but when I see a oneway road with only one lane I am always unsure how to answer the quest. I think that answering "No marked lanes" is wrong since there can't be any lane marking on a oneway road (see these examples: these are clearly oneway roads with only one lane)
![image](https://user-images.githubusercontent.com/42747216/157842055-5cac9c60-2107-494f-9d71-ce124a2161ef.png)
![image](https://user-images.githubusercontent.com/42747216/157842065-8256c798-9973-44ca-89e6-ba3782428819.png)

Therefore, I think that should be added one more type of answer for oneway roads only that gives the user to bypass the doubt about road markings and adds the `lanes=1` tag to the oneway road

**Comment by andrewharvey** [comment] 2022-03-11 09:49
I would say that the two solid white lines are the lane markings and therefore lanes=1, if you had the same road in your photos but without any paint then that would be no markings.

**Comment by Mannivu** [comment] 2022-03-11 09:51
Those are not lane markings, though. Those are external marking that separates the shoulder from the proper roadway.

**Comment by HolgerJeromin** [comment] 2022-03-11 14:45
duplicate of #2778

> it doesn't matter what you answer there, it will be tagged the same if there is just one lane.
> Or well: If you answer "is has no markings", it tags lane_markings=no and nothing more. If you answer "it has lanes: 1" it removes any lane_markings tag and sets lanes=1.

**Comment by Mannivu** [comment] 2022-03-11 14:50
Knowing that a road is a one lane street it's different from saying that I can't establish how many lanes there are.

**Comment by westnordost** [comment] 2022-03-13 22:22
Bypass the doubt... hm well what is your suggestion? An other-answer? What should be the wording?

**Comment by Mannivu** [comment] 2022-03-14 13:35
So I would suggest (for one way road only) an additional answer for a one-lane oneway road; something like this
![photo_2022-03-14_14-17-39](https://user-images.githubusercontent.com/42747216/158182803-5aafe186-a89a-416c-be4f-f62e3db9be6f.jpg)

**Comment by valerio-bozzolan** [comment] 2022-03-14 16:38
I'm generally inclined in sustaining this solution but without a picture of a car travelling in both direction or in just one direction, the proposed solution can be confusing at the moment.

**Comment by MaestroGlanz** [comment] 2022-03-15 08:56
> So I would suggest (for one way road only) an additional answer for a one-lane oneway road; something like this ![photo_2022-03-14_14-17-39](https://user-images.githubusercontent.com/42747216/158182803-5aafe186-a89a-416c-be4f-f62e3db9be6f.jpg)

Kudo +1

**Comment by westnordost** [comment] 2022-03-17 12:14
FYI for oneway streets, the "lane count differs for each side" option is not shown. Only marked lanes + no marked lanes.

**Comment by Mannivu** [comment] 2022-03-18 09:37
@westnordost I understand that the wording "One lane oneway road" can be obscure, but maybe working on a specific image this could help the user better understand what we mean. So, what if we use something like this
![bitmap](https://user-images.githubusercontent.com/42747216/158978439-c6ae734b-8cbd-4dcf-877f-5d35f88c0d9b.png)

**Comment by westnordost** [comment] 2022-03-21 20:38
I don't see how this would help. The uncertainty mentioned is not that whether it is a oneway road but that someone may want to say "there are no lanes at all".

Anyway, what about removing the edge lines from the picture for "no marked lanes"? Would that make it (slightly) clearer?

**Comment by Mannivu** [comment] 2022-03-22 17:24
> Anyway, what about removing the edge lines from the picture for "no marked lanes"? Would that make it (slightly) clearer?

@westnordost yes, I think that this might help users.

**Closed** 2022-03-23 14:16 UTC
Labels: feedback required
