### ISSUE TITLE
Quest icons not shown until zooming out (or maybe other map interaction), happened only on emulator so far

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#2780] opened 2021-04-21 18:00 UTC
Scan for quests in afd4dcedb
Wait long time. Wait longer.
Zoom out - and quests finally appear.

**Versions affected**
afd4dcedb

![Peek 2021-04-21 19-58](https://user-images.githubusercontent.com/899988/115599653-260fb300-a2dc-11eb-8183-4c11ac910730.gif)

**Comment by matkoniecz** [comment] 2021-04-21 18:03
Curiously it is not reproducible on my phone. Emulator is Android 10 (API 29), Nexus S.

Physical device is Android 10 Mi A2 Lite, so maybe it is emulator bug - not SC bug.

**Comment by tiptoptom** [comment] 2021-04-21 18:09
I have the same phenomenon when I leave the app and return after a while. Or is this an other issue?

I have a Sony Xperia ☓

**Comment by westnordost** [comment] 2021-04-21 18:14
Could this be a tangram-es issue?

You can add a breakpoint at `PinsMapComponent::showPins`. Is it reached?

**Comment by matkoniecz** [comment] 2021-04-21 18:34
It may be something random, but it appears to me that bug is no longer happening if I build it in a debug mode :)

And once again:

Debug with breakpoint: triggered, works
Debug without breakpoint: works
Normal mode: broken

Wonderful.

**Comment by westnordost** [comment] 2021-04-21 18:40
What do you mean broken? Does the code reach `shoPins` or not?

**Comment by matkoniecz** [comment] 2021-04-21 18:47
> What do you mean broken?

like in the original report - icons not shown until zoom in/out

> Does the code reach showPins or not?

In debug mode: yes, and it works

In normal mode: not sure. And it does not work (icons not shown until zoom in/out)

I added logging to that function to make it visible without breakpoint. With that addition it is logged and it works as expected.

Once I removed logging - I lost ability to check is it running and guess what? New quest pins are not visible until I zoom in, zoom out or move map.

Is it happening on your computer? Maybe I should run RAM check or something.

**Comment by westnordost** [comment] 2021-04-21 18:52
I also sometimes observed that. I think. But also already before v32.0,

Sometimes one had to move the map or zoom so that newly added pins to the map become visible.

**Comment by matkoniecz** [comment] 2021-04-21 19:01
I also had some like that earlier, but never reproducible and consistent. Even if that one is behaving weirdly.

And idea how it can be attacked if both `Log.wtf` and enabling debug mode changes app behavior?

**Comment by westnordost** [comment] 2021-04-21 23:33
No, no idea. Surely the log has nothing to do with that you can't reproduce it. Better maybe show a toast message instead so you see it also when casually using it or testing something else

**Comment by Helium314** [comment] 2021-04-22 05:28
> I also sometimes observed that. I think. But also already before v32.0,
> 
> Sometimes one had to move the map or zoom so that newly added pins to the map become visible.

Same for me.
Never bothered no report, since pins appear after the next interaction, and I couldn't reproduce it.

**Comment by westnordost** [comment] 2021-04-22 13:22
That you can rather reproduce it on an emulator than on a real device might have this reason:

On a real device, you have a compass which changes its direction all the time. Since the compass direction is shown on the map, whenever you hold the smartphone just a little bit different (or because of background noise of the sensor), the direction that is displayed on the map is updated every few frames. So when the map is redrawn, tangram-es tells its listeners that the map view changed which is the same callback as when rotating or zooming the map.
What the app does when it receives that callback is to check for the displayed area if the quest pins have been pulled from DB already and if not, pull them from DB for that area and display them.

So anyway, since this is an old back and one where I am relatively certain that it is not even be related to STreetComplete (but don't have the energy to "prove" that so that I can create an issue at tangram-es), I'll close this.

For anyone wanting to get to the bottom of this, the best way would probably be to build a custom version of StreetComplete where a toast message is displayed every time `PinsMapComponent::showPins` is called. If after download, the map view stays empty **and such a message appears**, the culprit is at tangram-es. If after download, the map view stays empty but no message appears, the culprit is at StreetComplete.

**Closed by westnordost** 2021-04-22 13:22 UTC
Labels: bug

**Comment by westnordost** [comment] 2021-04-22 13:24
That the compass updates all the time and thus triggers a re-render of the map view might also be the source of some battery drain. You are welcome to try out removing this direction marker from the map view and compare how this affects the battery lifetime.

**Comment by riQQ** [comment] 2021-04-28 17:31
To add another data point:

On a Nokia 2.2 (device doesn't have a compass sensor) with Android 10 and StreetComplete 31.3 I have the following reproducable behaviour:

At a certain zoom level with StreetComplete in the foreground, when you turn off the display and then enter the PIN to unlock, StreetComplete briefly show the pins and then hides them all. Moving the map around fixes this.

Is this the same issue / root cause or something separate?

**Comment by westnordost** [comment] 2021-04-28 17:44
I don't know. I didn't close this bug because it's not a valid issue, but because of https://github.com/streetcomplete/StreetComplete/issues/2780#issuecomment-824837485

You are welcome to try to get to the bottom of this.

**Comment by Helium314** [comment] 2023-03-15 17:07
In case this is still worth fixing: calling `KtMapController.requestRender()` after setting features does the trick.

**Comment by westnordost** [comment] 2023-03-15 20:44
Sounds good,  if this does not lead to a performance detriment 

Am 15. März 2023 18:07:37 MEZ schrieb Helium314 ***@***.***>:
>In case this is still worth fixing: calling `KtMapController.requestRender()` after setting features does the trick.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2780#issuecomment-1470422676
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment] 2023-03-15 21:02
If so, it's not noticeable. I guess it's just forcing what happens on every interaction with the map.
