### ISSUE TITLE
SC 40.0 still not available on Google Play Store

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3748] opened 2022-02-11 14:38 UTC
Hi there,

Google Play Store still shows v39.1 as the current version of StreetComplete although SC 40.0 was released on 07 February 2022. In the past new versions were available just a few hours after the release. On F-Droid the latest version is v40.0. (See https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete.)

Anything went wrong with the SC release on Play Store?

The cycling cat

**Comment by matkoniecz** [comment] 2022-02-11 14:50
It is being reviewed. Likely it got selected for review by a human, or this time some automated process is flaky on Google side.

**Comment by peternewman** [comment] 2022-02-12 22:43
Is it not worth leaving this open until it's available @matkoniecz (maybe even pinning it), given the likelihood others will ask the same question.

**Comment by matkoniecz** [comment] 2022-02-12 23:42
I hope they will be able to find it by searching, if not maybe pinning can be a good idea

**Comment by peternewman** [comment] 2022-02-13 09:13
I'm not sure pinning will work if closed. It was more about having closed it when it hasn't been resolved in any sense (although I appreciate it's out of your hands/there's nothing you can do to fix it).

**Comment by westnordost** [comment] 2022-02-15 01:20
It has been rejected.

**Comment by westnordost** [comment] 2022-02-15 01:24
It looks like Google Play now even disallows displaying donation links in the app that lead anywhere else than their own billing system (where they get their hefty commission). Their policies don't seem to make any difference between "in-app-payment" and donations (to FOSS software, at that) except if the donation goes to a non-profit organization. StreetComplete displays links to Patreon, Liberapay and Github Sponsors in-app, so I'll have to remove this.

Furthermore, it was rejected because they write I need to supply login credentials for them. I.e., login credentials for an openstreetmap account. This is a problem, because I cannot agree to the OpenStreetMap terms of service in their name. And who knows what kind of vandalism they'll do when they "test" the app. And it's kind of absurd. Will they request login credentials for an email client too? Or an app that enables you to connect with your google account?

Issue is, it will be very hard up to impossible to make them understand this. Google Play support is really really bad, I think I never even talked with a human there. Last time I have been in contact with them about an alleged issue, I eventually gave up (#3466)

**Comment by cyclingcat** [comment] 2022-02-15 06:00
How do other OSM editing apps (Vespucci, OsmAnd, ...) handle this?

The cycling cat

**Comment by matkoniecz** [comment] 2022-02-15 06:40
Arghh.

> donation links in the app
And presumably even mentions that you can donate elsewhere, without Google taking large part? 

> Furthermore, it was rejected because they write I need to supply login credentials for them. I.e., login credentials for an openstreetmap account.

"for them" as in "for Google employee testing the app"? What about special mode where edits are made on dev server?  ( https://master.apis.dev.openstreetmap.org/ )

If we would know where they test it (=location of google HQ, default location of emulator) we could prefill it with data exactly matching real one so it would not mismatch background map.

> How do other OSM editing apps (Vespucci, OsmAnd, ...) handle this?

In OsmAnd editing mode is just one of plugins so presumably it could be never noticed/tested. Vespucci allows changing API root.

**Comment by HolgerJeromin** [comment] 2022-02-15 09:10
@simonpoole 
Do you have similar experience with Vespucci?

**Comment by westnordost** [comment] 2022-02-15 14:14
Please know that I'll handle this, so no need to panic. I'll just use this ticket to inform.

### Message from Google Play

![image](https://user-images.githubusercontent.com/4661658/154077493-bacb4301-99ba-4e6e-bb3c-a875fbb9b188.png)

#### Links:
- [Payments](https://support.google.com/googleplay/android-developer/answer/9858738/) policy

### Actions taken

I already prepared to change the donate dialog to this

![image](https://user-images.githubusercontent.com/4661658/154078311-c69046b6-905a-441c-894e-40faacc46c07.png)

for installs from Google Play only. However, I read the payments policy again today and decided to appeal first because in my opinion, "payment" in paragraph 3 clearly refers to how payment is defined in paragraph 2, not any exchange of money.

#### Appeal

> Issue 1: 
>
> I presume the payment policy you are referring to is
>
>> 2. [...] apps [...] accepting payment for access to in-app features or services, including any app functionality, digital content or goods (collectively “in-app purchases”), must use Google Play’s billing system for those transactions
>> 3. [...] apps may not lead users to a payment method other than Google Play's billing system. [...] 
>
> The donation links do not violate this policy, because no features, services, functionalities, content or goods are exchanged: they are not payments but donations. I.e. all functionality is available without any donations.
>
> Issue 2:
>
> No account is required to use this app. The donations are also not connected with an account. Also, the account is at a third party (OpenStreetMap, e.g. like a Wikipedia account). However, I don't expect you to take me by my word, so I created an OpenStreetMap account for you and provided the details in the prelaunch report settings.

**Comment by westnordost** [comment] 2022-02-16 17:23
I promoted / documented this in an own ticket after all, because it is easier to refer to for futuer reference than a ticket where we only eventually found out what the issue is:

3768

**Closed** 2022-02-16 17:23 UTC
Labels: question

**Comment by FloEdelmann** [comment] 2022-02-22 21:33
Version 40.2 seems to be available in Google Play again.
