### ISSUE TITLE
Feature idea: local notes

### ISSUE THREAD

**Issue by holgerschurig** [streetcomplete/StreetComplete#2942] opened 2021-06-02 14:16 UTC
**Use case**
Today I was using Streetcomplete and noticed a hedge in the map, that didn't exist in the real life (anymore). But it happened previously that I noticed something in the map that wasn't true anymore. 

Streetcomplete however can only add things --- and this is good so. That makes it so simple. So removing things, or modifying random attibutes should not be done by StreetComplete. But I could do that in JOSM.

**Proposed Solution**
So if I would have the ability to add local notes, that would be nice.

OSM has notes, but I'd like local ones better. First, they are just for me. And second, removing Notes in JOSM isn't possible (or I don't know how), so I'd need to login into openstreetmap.org again. Using 3 different programs starts to get cumbersome.

So, long press: Dialog "Add Note" appears, with Text field, cancel & save buttons. When saved, some icon appears on the map. When clicking this icon, one sees the text, but this time with cancel & delete & save buttons.

That should be fairly simple for end-users.

**Comment by FloEdelmann** [comment] 2021-06-02 14:23
see #1992

**Comment by smichel17** [comment] 2021-06-02 15:04
I'll close this as a duplicate of #1992.

**Closed by smichel17** 2021-06-02 15:04 UTC
