### ISSUE TITLE
"What type of crossing" quest is confusing (inaccurate?)

### ISSUE THREAD

**Issue by awebeer256** [streetcomplete/StreetComplete#5088] opened 2023-06-22 21:53 UTC
When asked, "What type of crossing is this?" the options are, "Controlled by traffic lights," "Marked," and, "Without road markings."

Having looked a bit at the tags' pages on the wiki, it seems to me that this should be split into three separate quests.

1. Is this crossing controlled by traffic lights? (Yes, No)
2. Does this crossing have road markings? (Yes, No)
3. [Only appears if the previous question is answered Yes] What kind of markings does this crossing have? (Surface, Lines, Paired Lines, Dashes, Dots, Rainbow Lines, Rainbow Zebra, Other Rainbow, Single Zebra, Double Zebra, Paired Zebra, Bicolour Zebra, Straight Ladder, Skewed Ladder, Paired Ladder, Pictograms).

**Versions affected**
StreetComplete 53.1

**Comment by mnalis** [comment] 2023-06-22 22:31
> Is this crossing controlled by traffic lights? (Yes, No)

What tag should be added here when `Yes` is chosen, and what tag when `No` is chosen?

> Does this crossing have road markings? (Yes, No)

What tag should be added when `Yes` is chosen, and what tag when `No` is chosen to such quest?


(Note that every answer must have adequate tagging, and that that users can choose to to only solve some quests, but not others.)

**Comment by awebeer256** [comment] 2023-06-23 02:20
I didn't know what to answer if a crossing had both signals and markings; I had to consult the wiki to learn that "marked" implies no signals, so the correct answer in this case was signals.

> (Note that every answer in StreetComplete must have adequate tagging that suits it, and that that users can choose to to only solve some quests, but not others.)

Good point! So I'll revise my proposal: change the existing quest to have two mandatory questions within it: is this crossing controlled by traffic lights, and does it have road markings? A double Yes will submit `crossing=traffic_signals` and `crossing:markings=yes`. Yes-No will be `crossing=traffic_signals` and `crossing:markings=no`. No-Yes means `crossing=uncontrolled`, and No-No is `crossing=unmarked`.

I'll open a separate issue requesting a new quest for specifying the type of markings.

**Comment by matkoniecz** [comment] 2023-06-23 11:43
For context: this quest was created and designed before some improvement to OSM tagging become more widely used

(not blocking potential improvements, but want to express that it definitely made sense to design it this way when it was created)
(also, I seem to remember a similar issue)

**Comment by westnordost** [comment] 2023-06-23 14:07
Duplicate of #4886

**Closed by westnordost** 2023-06-23 14:07 UTC

**Comment by mnalis** [comment] 2023-06-23 20:33
> So I'll revise my proposal: change the existing quest to have two mandatory questions within it: is this crossing controlled by traffic lights, and does it have road markings?

That is however not ideal as it goes against [quest guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md) which say (among other things) _":atom_symbol: Atomic quests: Per quest, only one thing should need to be answered by the user."_

> I didn't know what to answer if a crossing had both signals and markings; 

I see! What language are you using, English or something else?

Looking at English, the answers to _"What kind of crossing is this?"_ are:
- `Controlled by traffic lights`
- `Marked`
-  `Without road markings` 

Which I agree is not ideal.  One problem is lack of space; ideally the answers would say:
- `Controlled by traffic lights (regardless of road markings, if any)`
- `Only road markings (without traffic lights)`
-  `Without road markings (and without traffic lights)` 
 
But those would obviously be way too long (text would completely cover the pictures).

Currently, the quest tries to be clarify it by **ordering** (from most control to least control of crossing) is too subtle indicator, and **clever picture** (i.e. hiding irrelevant detail - angle of photo for traffic lights does not show if there are road marking or not) **might be too clever for its own good** (it might be less confusing if it showed both traffic lights and road markings; even if that need not always be the case - but that might cause more problems than it solves, though).

---

**Here are the few small ideas for improvement** that come to my mind, until (or unless) this quest is replaced: 
- the second answer `Marked` could be **renamed to `Marked (only)`** or `Only road markings` or something similar (actually, in Croatian translation, I did exactly that)
- the picture for second answer could be retaken from more zoomed-out angle to clearly show not only road markings, but that there are **also no traffic signals** present at the crossing.

Would one or two of those been enough to clear confusion for you @awebeer256? Or do you have other suggestion (while it issue is still fresh in your mind) what might have 

> I had to consult the wiki to learn that "marked" implies no signals, so the correct answer in this case was signals.

That is however definitely a problem, IMO. People should be able to answer quests in StreetComplete without any knowledge of OSM Tags (much less the fact that tags have documentation, or where that documentation is, or to have to go there and read and understand it!)

**Comment by awebeer256** [comment] 2023-06-24 02:44
> I see! What language are you using

English.

> Here are the few small ideas for improvement

The first suggestion would be good, but I think not good enough; I probably would have _guessed_ the correct answer, but I don't think I would've been _confident_ about it.

The second suggestion, I might not have even noticed 🫤.

Frankly, I think that the clarity and conciseness of my two-question idea is sufficient justification to depart from the quest guidelines here. It would certainly be more justified here than in the already-existing quest about how many floors a building has; that one could very easily be split into two separate quests, but it isn't.
