### ISSUE TITLE
Inappropriate icon for traffic_calming=island

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#4841] opened 2023-02-23 17:22 UTC
When highlighting nearby traffic calming, StreetComplete displays a nice but confusing beach-and-palm icon for `traffic_calming=island`.
Example: open road width quest for https://www.openstreetmap.org/way/286248390

**Comment by mnalis** [comment] 2023-02-23 20:35
![small_Screenshot_20230223_213417_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/221024054-91551469-3960-436f-85d2-c03ecb13e85e.jpg)

**Comment by matkoniecz** [comment] 2023-02-23 20:48
I see how this pun (intentional or not) can be confusing, but do you have idea for a better icon?

**Comment by HolgerJeromin** [comment] 2023-02-23 22:12
Thanks for moving my issue here.

Vespucci icon is a little bit nicer:

![Screenshot_20230223-231024_copy_196x250](https://user-images.githubusercontent.com/2410353/221042397-4690d006-4deb-4bbe-9140-2d4fdae11453.png)

**Comment by westnordost** [comment] 2023-02-24 14:16
It's not a bug as it is deliberate. Is there any language in which the pun wouldn't be understood?

**Comment by westnordost** [comment] 2023-02-24 14:29
I checked in all the languages into which the iD preset traffic_calming=island is translated. It is really quite universal to call it something like "traffic island", even in completely different languages like Chinese, Korean etc.

Only in very very few languages it is not called like that - according to the iD translations that is. Could as well be that aliases were not added by translators.

**Closed by westnordost** 2023-02-24 14:29 UTC

**Comment by HolgerJeromin** [comment] 2023-03-03 15:25
My idea was: 
Who the hack tagged `place=island` on that city street node.

**Comment by FloEdelmann** [comment] 2023-10-26 14:07
This should now be fixed with https://github.com/streetcomplete/StreetComplete/commit/4d3cc8e9ab79e360f49d5695599fa1015ecfda79 in https://github.com/streetcomplete/StreetComplete/releases/tag/v55.0.
