### ISSUE TITLE
Ask if house-tags apply to the connected buildings

### ISSUE THREAD

**Issue by nicorikken** [streetcomplete/StreetComplete#2858] opened 2021-05-07 10:33 UTC
**Use case**

Mapping in the Netherlands, I typically encounter row houses. Most blocks of about 10 houses have the same number of levels and the same roof type. Even with the shortcut of using the previous tag, it takes a lot of time to tag all the houses in the block. I can do most quests just at walking speed, but I have to pause in order to tag a housing block. So typically I just tag 1 house of the block and finish the rest at home.
Apart from houses, neighborhoods built around the 70's typically have connected sheds. They could also be tagged the same.

Here is a screenshot [in my area](https://www.openstreetmap.org/search?query=de%20laar#map=19/51.95038/5.86842) to give you an impression what I encounter:
![Schermafdruk van 2021-05-07 12-23-36](https://user-images.githubusercontent.com/7458098/117436610-74a18c00-af2f-11eb-85ab-ceddf528e443.png)

**Proposed Solution**

_Interface_
The usability feature I am thinking of, is that after tagging it, you get asked if this tag is true for the entire block. And that then all connected houses are highlighted to show you what will be effected if you press 'yes'.

So the process would be:
1. select one quest in the block
2. answer the question
3. answer if this applies to the entire block/row

_Quests_
I think this would work for the following quests:
* building type
* building levels
* building roof type

_Technical side of things_
I was thinking to match all connected buildings. I'm not sure if the quality of the data is sufficient for it, and if it is easy to implement.

**Comment by smichel17** [comment] 2021-05-07 10:53
See #73.

This is a little different from previous proposals as it's not proposing the ability in general, but only for row houses in particular.

**Comment by westnordost** [comment] 2021-05-08 12:47
Yeah, this is a duplicate of a feature request that will not be implemented, sorry.
In your case, if all those buildings really have the same property, maybe just take a few photos instead and add this information later in JOSM / iD.

**Closed by westnordost** 2021-05-08 12:47 UTC

**Comment by nicorikken** [comment] 2021-05-10 06:41
@westnordost Thanks for replying. That is what I do now, but to save myself some time I'd rather deal with it on the spot than having to work on it some more when I'm back home. Oh well, no need to reiterate comments from #73 I guess.
