### ISSUE TITLE
Orientate map in move direction ?

### ISSUE THREAD

**Issue by vincegre** [streetcomplete/StreetComplete#3006] opened 2021-06-28 19:39 UTC
When I'm walking in street I find it a lot easier and a lot less source of errors too to get map displayed in direction of move as most maps apps are offering now as option !

Perhaps add an option in Settings for that ;)

**Comment by riQQ** [comment] 2021-06-28 19:48
Likely a duplicate of #3006

**Closed** 2021-06-28 19:56 UTC
Labels: duplicate

**Comment by mnalis** [comment] 2021-06-29 09:26
Also maybe this FAQ entry: [How to use 2D/3D and GPS following/rotation? ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_to_use_2D.2F3D_and_GPS_following.2Frotation.3F)
