### ISSUE TITLE
Building Overlay: sixth recently-used button is covered by checkmark button

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#5538] opened 2024-03-15 13:15 UTC
When working in the building overlay, it is difficult to tap the last recently-used option in the row, because it seems that the checkmark button has a buffer around it which is covering part of the recent button.

**How to Reproduce**

In building overlay, tap the right-most building icon in the last-used row. 

**Expected Behavior**

Should be able to tap anywhere on the button, but for me it seems to be over half obscured, so I need to tap the top 2/5ths or so. 

**Versions affected**

57.1 on Moto X4 (which is generally a smaller screen)

**Comment by westnordost** [comment] 2024-03-15 19:55
Can you provide a screenshot? This is likely a will not fix, though.

**Comment by Helium314** [comment] 2024-03-15 20:16
On my phone the rightmost building button is not covered by the ok button, but I can only use the top half of the building button. On touching the bottom half, nothing happens.

**Comment by pkoby** [comment] 2024-03-15 20:19
That's how mine is too. Photo below.

The tiny phone is sometimes annoying, but I have tiny hands.

![2024-03-15 15 59 07](https://github.com/streetcomplete/StreetComplete/assets/7786285/6d80b67c-6c17-4365-b515-41eebec51cc1)

**Comment by riQQ** [comment] 2024-03-15 20:39
Can reproduce on a Pixel 6a on Android 14:

https://github.com/streetcomplete/StreetComplete/assets/3404787/e5a4c0ce-8aa0-4e95-9ce8-d60f40a637e4

**Comment by westnordost** [comment] 2024-03-16 11:16
I see, hmm, do you have a suggestion for a solution?

**Comment by matkoniecz** [comment] 2024-03-16 16:49
limit number of displayed last used values so it will not be displayed? Though detect it reliably in various screen sizes may work poorly.

Or maybe that blocking panel can be nontrasparent to make the block more obvious? Or maybe it can be smaller?

**Comment by pkoby** [comment] 2024-03-21 13:31
Yeah, I'd be okay with only five buttons, but that might look awkward to have a gap. Also not sure how this would differ on different screen sizes.

Alternatively, could the whole roe of buttons move upward? I feel like there's a lot of whitespace in this box.

**Comment by westnordost** [comment] 2024-04-08 13:54
Limiting the items wouldn't make sense, as there are always yet smaller devices. In the end, we would end up with only 3-4 suggestions that fill only 50% of the screen on most devices, which looks equally bad but on a larger number of devices (because most devices have 6" and larger displays).
The same with making it smaller .

I think what would solve this issue mostly is to make the buttons scrollable (already is) and also allow a larger number of previously selected values. The user can just scroll to the building he wants to select, then. However, without a visual indicator that it is scrollable, it would look weird if there was just half-a-button visible on the right side on many screen sizes. I previously tried to add a visual indicator but it turned up too much work, especially keeping in mind that I have to redo the UI in compose soon anyway.

So, I will close this as will not fix, but will probably look at this again after I redid the UI in Compose.

**Closed by westnordost** 2024-04-08 13:54 UTC
Labels: feedback required, usability
