### ISSUE TITLE
Open keyboard for quests that always(-ish) require it

### ISSUE THREAD

**Issue by thany** [streetcomplete/StreetComplete#4134] opened 2022-06-18 15:42 UTC
**Use case**
When opening a quests that always require the keyboard to fulfill it, I have to tap the input field first in order to open the keyboard.

**Proposed Solution**
This could be improved by opening the keyboard straight away, when tapping a quests that always requires it. For example, for the width of a street/road/path. In most cases it's perfectly viable to have the correct answer at hand, without having to take a survey picture, for example when walking through a neighbourhood where all streets are equal in width.

This solution would not impede the ability to tap the survey picture button, or to use the "other answers" option. At the same time it would reduce completing such quests from a minimum of 4 (tap quest, tap input field, tap a number on the keyboard, tap OK), to a minimum of 3 taps (tap quest, tap a number on the keyboard, tap OK).

**Comment by westnordost** [comment] 2022-06-18 22:04
Duplicate of #2389 etc.

**Closed by westnordost** 2022-06-18 22:04 UTC
