### ISSUE TITLE
In the preset settings, you can't hide the pop-up window using the Back button

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5815] opened 2024-08-19 11:37 UTC
**How to Reproduce**
1. Settings->Manage presets
2. Tap on the three dots. 
3. Tap the Back button at the bottom of the screen

https://github.com/user-attachments/assets/dfecbd5b-fe5a-408d-8489-05c4461387fa

**Versions affected**
v59.0-alpha1
Android 14 OneUI 6.1
Samsung A52

**Comment by westnordost** [comment] 2024-08-19 13:17
Well, I don't know about this. Is this even expected behavior? If it was expected behavior, then certainly the Jetpack Compose people would have implemented that. I am just using the standard components.

**Comment by FloEdelmann** [comment] 2024-08-19 13:51
I just checked some other apps, and three-dot menus close when pressing the back button there.

In StreetComplete's quest selection screen, the three-dot overflow menu also does not close when pressing the back button.

So it seems like actually the Jetpack Compose component is missing that standard behavior and it should be reported/fixed there.

**Comment by westnordost** [comment] 2024-08-19 18:20
However, when I place that minimum example into this project, the back button does not work. So... *something* in this project is triggering this *probably* bug in Jetpack Compose, but no idea what.

Anyway, I posted a bug in the Jetpack Compose Material issue tracker where I explained it in more detail: https://issuetracker.google.com/issues/360888467

If anyone has an idea why `KeyEvent.DispatcherState::mDownKeyCode == 0`, which causes the back-press-issue, feel free to contribute to that issue.

I could keep this issue open because it is obviously not fixed yet, but I'd rather close it as it is not actionable for the time being. (Can always be reopened if new information surfaces.)

**Closed by westnordost** 2024-08-19 18:20 UTC
Labels: bug, usability
