### ISSUE TITLE
Unavailable house number for public toilet marked as problem

### ISSUE THREAD

**Issue by penguineer** [streetcomplete/StreetComplete#4601] opened 2022-11-02 23:07 UTC
https://www.openstreetmap.org/note/3422708

The app asket me for the house number of a public toilet. I marked this as not answerable, as this building has no number (at least no visible markings for a number). Unknown to me this was marked as an issue in the map and I only realized when I got a response stating that, based on the annotations, a number should not have been expected.

**How to Reproduce**

Please check on the above link.

**Expected Behavior**

* I did not expect to open an issue. My expectation was that saying "no number available" would close the question.
* Depending on the tag semantics this should not be a quest in the app.

**Versions affected**

v48.0

**Comment by westnordost** [comment] 2022-11-02 23:15
The building has been mapped as [`building=public`](https://wiki.openstreetmap.org/wiki/Key:building).

The app asks about housenumbers of public buildings because it is reasonable to assume that public buildings may have housenumbers.

Toilet buildings should be tagged as `building=toilets`. The reason why the app did not offer you to re-tag that building is because it does not recognize `building=public` as it is kind of a duplicate of `building=civic`.

**Closed by westnordost** 2022-11-02 23:15 UTC

**Comment by penguineer** [comment] 2022-11-03 17:19
I see, that's something I will report back to that issue. Thank you for the quick response!

**Comment by westnordost** [comment] 2022-11-03 21:38
Well, actually I now made it so that StreetComplete understands what a building=public is (treating it as synonymous to "civic"). So in the future (you can try out with the next released version), the usual "The building has been tagged as .... [a civic building icon+description shown]. Is this correct?" dialog will be shown.
