### ISSUE TITLE
Download data along a gpx track

### ISSUE THREAD

**Issue by jmaspons** [streetcomplete/StreetComplete#5997] opened 2024-11-01 18:54 UTC
**Use case**

Using StreetComplete in areas with poor network connection or abroad with roaming requires downloading the data in advance. I often do it when hiking in the mountains. Manual scrolling and downloading the data is boring and time-consuming.

**Proposed Solution**

Add and options in the menu to download the data along a gpx track. Select a gpx file and StreetComplete will download all the data along the track. Warn the user if the data doesn't fit in the cache size. In such case, offer to increase the cache size or recommend using a shorter track.

As an alternative to the gpx file, a user could draw a line manually.

**Comment by mnalis** [comment] 2024-11-01 19:46
- Duplicate of https://github.com/streetcomplete/StreetComplete/issues/473, https://github.com/streetcomplete/StreetComplete/issues/5057, https://github.com/streetcomplete/StreetComplete/discussions/5345

**Comment by riQQ** [comment] 2024-11-01 20:02
There is an unfinished PR: #5369

**Comment by matkoniecz** [comment] 2024-11-01 20:16
closing as duplicate of #473, see https://github.com/streetcomplete/StreetComplete/issues/473#issuecomment-1777889099

**Closed by matkoniecz** 2024-11-01 20:16 UTC
