### ISSUE TITLE
Cycleway with surface shows red on surface overlay

### ISSUE THREAD

**Issue by tjur0** [streetcomplete/StreetComplete#5877] opened 2024-09-07 13:09 UTC
Given a `highway=cycleway` with `sidewalk=`, `surface=` and `segregated=` the surface overlay shows a red color indicatin that no surface is present.

https://www.openstreetmap.org/way/365900455

![084a19d65568179999c7c7d34c412d27308c6d22_2_243x500](https://github.com/user-attachments/assets/130821e4-d3f0-4daa-b167-2ee0597f5fcc)

**How to Reproduce**
Look at surface overlay, on a cycleway with `sidewalk=`, `surface=` and `segregated=` tagged.

**Expected Behavior**
It is expected that if the surface of a cycleway is filled in that the color is blue.

**Versions affected**
58.2

**Comment by matkoniecz** [comment] 2024-09-07 14:22
That is basically the same as #5878

**Comment by jdhoek** [comment] 2024-09-07 14:50
> That is basically the same as #5878

Potentially same cause, different outcome. Ways tagged with `surface=*` should not be marked as incomplete. The issues are related, not duplicates.

**Comment by mnalis** [comment] 2024-09-07 17:55
> The issues are related, not duplicates.

That is technically correct; but the reasoning behind it (why current behaviour is intended and not a bug) and thus the outcome come from the same decision. 

I've added several links to https://github.com/streetcomplete/StreetComplete/issues/5878#issuecomment-2336259986 which give background and history why `segregated=yes`  way without `footway:surface=*` and `cycleway:surface=*` is considered incomplete.

**Comment by westnordost** [comment] 2024-09-07 23:46
Duplicate of linked issue

**Closed by westnordost** 2024-09-07 23:46 UTC

**Comment by westnordost** [comment] 2024-09-07 23:51
By the way, it appears that at the location shown, the tag `surface=asphalt`  is actually wrong. The footway part of the segregated cycle+footway is not asphalt but paving stones.

**Comment by tjur0** [comment] 2024-09-08 07:21
As a local i know that this cycleway has recently been fully repaved into red asphalt, while the sidewalk is made from paving stones that is correctly mapped with sidewalk=right.

In the Netherlands ether something is a cycleway with a sidewalk, or it is a cycleway on itself. In the rare few cases that a path is a shared footway cycleway, the surface is almost always the same.

This makes ‘cycleway:surface’ and ‘footway:surface’ unwanted on cycleways.

The users of SC do not know the damage that they are causing, and the fact that you are not willing to understand and work with local tagging is damaging to OSM.

Please make SC follow guidelines and disable this feature in the Netherlands.

**Comment by jdhoek** [comment] 2024-09-08 08:11
This is happening because StreetComplete thinks a way with `segregated=yes` and `sidewalk=right` has some hidden extra lane for pedestrians between the sidewalk and the cycleway. The presence of a sidewalk implies `segregated=yes`, and StreetComplete should first look at the sidewalk tags before going down the shared-bicycle-footway route.

In this case `segregated=yes` is redundant, and StreetComplete is tripping up because of that tag. That's a bug.

> By the way, it appears that at the location shown, the tag `surface=asphalt` is actually wrong. The footway part of the segregated cycle+footway is not asphalt but paving stones. (And some of them are actually both paving stones.)

`surface=asphalt` is correct. That is the surface of the cycleway. Sidewalks mapped as attributes can have their surface tagged with something like `sidewalk:right:surface`, never `footway:surface`.

Please make StreetComplete follow OpenStreetMap conventions and disable this feature in the Netherlands.

**Comment by matkoniecz** [comment] 2024-09-08 08:50
> you are not willing to understand and work with local tagging is damaging to OSM

Handling sidewalk tagging was added specifically after requests from NL

StreetComplete supports enormous amount of local peculiarities

**Comment by westnordost** [comment] 2024-09-08 09:25
https://community.openstreetmap.org/t/tagging-of-adjacent-cycleway-footway-sidewalk/108404/126

Am 8. September 2024 09:21:58 MESZ schrieb Mart ***@***.***>:

**Comment by westnordost** [comment] 2024-09-08 09:59
@mcliquid checking something for `sidewalk` but not for `sidewal:<side>` seems like a bug to me. I will check it out, thanks for pointing it out.

**Comment by westnordost** [comment] 2024-09-08 10:07
> To this:
> and (!sidewalk or !sidewalk:left or !sidewalk:right or !sidewalk:both)

By the way, this wrong. Look again :->
