### ISSUE TITLE
Page of 'slider' option settings per location

### ISSUE THREAD

**Issue by goetzk** [streetcomplete/StreetComplete#3160] opened 2021-08-14 10:33 UTC
Hi,
I'm wondering if you have considered a mode/view where all quests for a particular point are displayed at the same time.

**Use case**

Examples I've experienced:

Walking past the end of a cul de sac I can see all the information I need to answer about surface, lighting, footpaths or bike paths. Needing to step through all the views one by one is time consuming and I have to wait for the star to sync. Having sliders would let me answer the questions in one batch.

Parked in a car opposite (say) a bus stop where I can't answer one question. I know the questions which come after this and could leave a 'cant see' note but it would be much quicker to just yes/no the quests that I can.

**Proposed Solution**

I'm envisaging all binary options as a list defaulting to a neutral/null state which can then be set to yes or no. I haven't fully thought through the implications of accidentally choosing yes/no and how to revert it or how listing view would support non binary options (like path surfaces) but it might be harder.

**Comment by smichel17** [comment] 2021-08-14 12:11
I think this is a duplicate of #124.

What SC version are you using? As of v32 (released 2021-05-23), the next quest will appear immediately, no need to wait for any syncing.

**Closed by smichel17** 2021-08-14 12:11 UTC

**Comment by goetzk** [comment] 2021-08-15 10:57
#124 looks like the same problem, different suggested solution. I've subscribed to that one now, thanks.

Just for the record, running vv33.2.

**Comment by smichel17** [comment] 2021-08-15 12:55
Feel free to add your solution there as well, if you like it more than any of the others suggested there.

> it would be much quicker to just yes/no the quests that I can

Missed this the first time around, but also the next major release will re-order the quests to place more emphasis on how quick they are to solve. See https://github.com/streetcomplete/StreetComplete/issues/2565#issuecomment-872584909 and https://github.com/streetcomplete/StreetComplete/commit/c1336a4ca5dbd6368d75c2c3332caeac172416ad ([via](https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-646707))
