### ISSUE TITLE
404 error with attached pictures on various streetcomplete notes

### ISSUE THREAD

**Issue by qugebert** [streetcomplete/StreetComplete#6041] opened 2024-12-11 08:24 UTC
Hi,

I'm not sure where to report this, but I'm getting 404 errors on various images attached to (still open) notes with streetcomplete.
So far I have not been able to recognize any real pattern, sometimes it concerns pictures with low numbers and sometimes more recent ones

A few open example notes:
https://www.openstreetmap.org/note/4325307  -> https://streetcomplete.app/p/223229.jpg
https://www.openstreetmap.org/note/4027127 -> https://streetcomplete.app/p/189098.jpg
https://www.openstreetmap.org/note/4362583 -> https://streetcomplete.app/p/229342.jpg
https://www.openstreetmap.org/note/4401974 -> https://streetcomplete.app/p/235524.jpg
https://www.openstreetmap.org/note/4508499 -> https://streetcomplete.app/p/249845.jpg

**How to Reproduce**

**Expected Behavior**

**Versions affected**

**Comment by matkoniecz** [comment] 2024-12-11 09:52
For possible nonbuggy reasons: Maybe it was closed & reopened by now deleted account?

**Comment by map-per** [comment] 2024-12-11 11:17
A two more examples from Munich:
- https://www.openstreetmap.org/note/4546976
- https://www.openstreetmap.org/note/4546897

It looks like only newer Notes are affected, the images of older nodes still work fine.

**Comment by Bormoglot** [comment] 2024-12-11 11:28
Hi!
I'm in a similar situation with images attached to still open notes in Tbilisi, Georgia.
A few examples:
- https://www.openstreetmap.org/note/4475257 -> https://streetcomplete.app/p/245658.jpg
- https://www.openstreetmap.org/note/4475208 -> https://streetcomplete.app/p/245633.jpg
- https://www.openstreetmap.org/note/4475205 -> https://streetcomplete.app/p/245632.jpg

**Comment by Jean-BaptisteC** [comment] 2024-12-11 12:11
I think it's caused by server migration
Now photos are stocked on streetcomplete.app server because they was stocked on wesdornost.de server

**Comment by matkoniecz** [comment] 2024-12-11 12:37
Actually it looks like all images are broken. See say https://www.openstreetmap.org/note/3551383

Maybe redirect was disabled/redone to handle #6040 what broke redirects elsewhere?

**Comment by mnalis** [comment] 2024-12-11 16:05
I've also seen that on one note today: https://www.openstreetmap.org/note/3631178 linking to https://westnordost.de/p/140720.jpg, which is being redirected to https://streetcomplete.app/p/140720.jpg which returns `404 Not found`.

> Actually it looks like all images are broken

well, **some** (even majority?) still seem to work for me, e.g. all three pictures linked in https://www.openstreetmap.org/note/4156505 redirect to e.g. https://streetcomplete.app/p/202009.jpg and seem to work fine :man_shrugging: 

---

Hopefully @westnordost just made that redirect before _all_ the pictures have finished copying to new location, and there will be less and less errors with time. Otherwise something has broken in the process.

**Comment by westnordost** [comment] 2024-12-11 19:44
I didn't copy any pictures, I just moved the directory from one location to another on the same webspace. The operation completed in few milliseconds.

I will have a look.

**Comment by westnordost** [comment] 2024-12-11 21:08
So for some reason the photo-cleanup job that runs every night at 2:20 UTC deletes loads of pictures because it thinks the notes have been closed or deleted. Still investigating...

**Comment by westnordost** [comment] 2024-12-11 21:30
I've deactivated the cleanup job and have a backup from the evening before I fiddled around with my webspace, so I should be able to restore (almost) everything as soon as I've found the cause.

**Comment by westnordost** [comment] 2024-12-12 16:28
The error was that the cleaner looked for links to photos in notes now only under the new URL https://streetcomplete.app/p/... 

Since all the existing notes link to photos via https://westnordost.de/p/... , those notes were thought to not contain any links to photos anymore and thus the photos were deleted. The only reason why not *all* photos have been deleted yet is because the cleanup job only runs for a little while and postpones work to the next day after some minutes.

This is fixed now by introducing an option to specify several urls so that the old URL is recognized, too: https://github.com/streetcomplete/sc-photo-service/commit/32cb1ffbc3408bb26bdfe2e460c910bba73fbe5d

**Comment by westnordost** [comment] 2024-12-12 16:32
The photos are now restored from backup.

**Note**: The backup was from the night before I changed the configuration to point to streetcomplete.app. So, photos uploaded on the 8th of December that were deleted by the cleanup job are lost. Looking at the code, this should be unlikely though, as the cleanup job was checking photos first that were checked the longest time ago.

**Comment by westnordost** [comment] 2024-12-12 17:30
Anyway, thanks for reporting this!

**Closed by westnordost** 2024-12-12 17:30 UTC
Labels: bug
