### ISSUE TITLE
Quest: What is the maxstay for this parking area [access=customers|public]

### ISSUE THREAD

**Issue by CloCkWeRX** [streetcomplete/StreetComplete#102] opened 2017-04-06 03:45 UTC

**Comment by westnordost** [comment] 2017-04-06 21:37
Most parking areas, especially out of town centers will have no max stay. This would give many false-positives.

**Comment by HolgerJeromin** [comment] 2017-04-09 10:51
Also note that access = public is only defined for toilets. Use access yes for all other poi types.

**Comment by matkoniecz** [comment] 2017-06-09 08:05
Given that https://wiki.openstreetmap.org/wiki/Key:maxstay has no defined value for unlimited maxstay it would result in massive amount of false positives.

I think that it would be better to close this issue - to stop encouraging making PR that would introduce this quest as it would be probably refused anyway.

**Comment by westnordost** [comment] 2017-06-18 11:55
Well, it is a valid possible quest, but as @matkoniecz said, as long as no heuristic can be determined to exclude those parkings that most likely will not have a maxstay, this cannot be implemented. I am closing this, feel free to reopen if you have an idea about this.

**Comment by andrewharvey** [comment] 2019-12-23 22:07
https://wiki.openstreetmap.org/wiki/Key:maxstay now says to use `maxstay=unlimited` for no parking limit. These are not false positives because it's useful to know when there is no maxstay limit, just as much as where there is.

**Comment by westnordost** [comment] 2019-12-24 00:48
Finding the right tag for this situation was not my primary concern, but littering every parking space with  a `maxstay` tag. 
Anyway, not sure if `unlimited` isn't technically incorrect. As far as I know, no public parking lot has "unlimited" parking even if there is no sign. It would be more accurate to tag something like `maxstay:signed=no` or similar in the case that there is no sign indicating the maxstay.

**Comment by andrewharvey** [comment] 2019-12-24 01:16
This is what I'm thinking...

- Does this parking area have a time limit?
  - yes during certain times only `maxstay:conditional=X hours @ (time)`
  - yes all the time `maxstay=X hours`
  - no `maxstay:signed=no` or `maxstay=unlimited` (might need to think about this some more since the first implies there could be a limit but just not signposted, the latter says you can really park here as long as you want, or at least until your car is considered dumped)

**Comment by westnordost** [comment] 2020-09-06 10:13
Some more thoughts about it:
- to not spam, one may want to only show it only for customer parking (f.e. supermarket), but then again it is common sense that you may not park your car forever on a supermarket parking (or any other private parking), so the value of this information is questionable 
- expanding on the previous point, a max parking duration for a privately owned parking is often not signed but assumed implicitly. If this is then tagged as `maxstay=unlimited` because there is no sign, this can result in wrong information. So if this was implemented, using `maxstay:signed=no` is obligatory in that case.
- there seem to be no data users currently(?)
- there was the suggestion to offer specifying the maxstay in the "has it a fee" quest as an other answer option. Though, having a fee and having a maxstay are not mutually exclusive (only slightly less probable)

**Comment by andrewharvey** [comment] 2020-09-06 11:21
> to not spam, one may want to only show it only for customer parking (f.e. supermarket), but then again it is common sense that you may not park your car forever on a supermarket parking (or any other private parking), so the value of this information is questionable

I kind of disagree this is spamming, while in some areas the answer would mostly be no, in other areas the answer would mostly be yes. Without actually asking this quest and explicitly tagging it you'll never know if it's just not mapped yet or really has no stay duration limit. So it's very useful to have this mapped.

Other quests already ask things which most mappers didn't bother to tag since they assumed this was the default (eg. is there a cycleway here -> cycleway=no).

> expanding on the previous point, a max parking duration for a privately owned parking is often not signed but assumed implicitly. If this is then tagged as maxstay=unlimited because there is no sign, this can result in wrong information. So if this was implemented, using maxstay:signed=no is obligatory in that case.

There is already a quest about who can park here which sets the access tag, so if we don't ask where access=private that should cover most of the cases here.

> there seem to be no data users currently(?)

I don't see that as a reason not to map it, data users would only come if there we start mapping it. Personally I use the query tool on osm.org to check parking lots first hand (would love to see an OSM powered parkopedia). This quest could help improve OSM for car drivers.

> there was the suggestion to offer specifying the maxstay in the "has it a fee" quest as an other answer option. Though, having a fee and having a maxstay are not mutually exclusive (only slightly less probable)

It's best to keep these two separate, in my opinion. You could have:

1. You can only stay for 2 hours, but you don't have to pay `maxstay=2 hours + fee=no`
2. You can only stay for 2 hours and you have to pay `maxstay=2 hours + fee=yes`
3. You can only stay for 24 hours, the first 2 hours are free, but you have to pay if you stay longer than 2 hours. `maxstay=24 hours + fee=yes + fee:conditional=no @  (maxstay<2 hours)`.

These are all fairly common scenarios. Other scenarios also exist where you have different maxstay or fee based on if you're a paying customer or not, but if it get's that complicated, a free form "other" should be fine. 

 #1969 would help make both quests swift to answer in the same session.

**Comment by westnordost** [comment] 2020-09-06 11:40
> I kind of disagree this is spamming

I agree with you there, but I also reckon that there are many people who want to be frugal with tags that are not applicable. So it is also about acceptance of having this tag potentially on every parking. `fee` for example is tagged on 14% of all parkings, but `maxstay` is tagged only on 0.5% of all parkings.

Any way, I didn't close this issue, I just noted reasons why it is (currently) problematic.

**Comment by smichel17** [comment] 2020-09-08 13:23
What if we started just trying to map these?

![image](https://user-images.githubusercontent.com/6563664/92478591-e32c1f80-f1d1-11ea-8cdf-a00340a6af3b.png)

I think most (or all?) of these are *public, no-fee* parking spots. They're signed, so they're easy to answer and not likely to change frequently. Without fees, there's fewer tagging corner cases to worry about. And it would be very useful for navigation apps (like OsmAnd, which already has a "find parking" prompt at the end of navigation) to avoid directing you to a "15 minute max parking" spot (intended for pick-up/drop-off).

**Comment by westnordost** [comment] 2020-09-08 15:41
Are you arguing for implementation of #981 ?

If you would like this quest implemented (maxstay as new quest), I think it is possible to campaign for it somewhat due to what I wrote in my last comment : Unlike `fee`, the tag is used on very few parking areas, so people may object that it is spam if this information was added to all the parkings.

**Comment by smichel17** [comment] 2020-09-08 17:29
First, to clarify:

- I agree with your initial impression in #981 — it should be closed as a duplicate of this issue, and max-stay should be implemented as a separate quest.
- There are some complications implementing the max-stay quest, discussed above.
- I suggested an initial implementation that avoids (some of) those complications by excluding private and paid parking.
- I shared a use case for showing why this partial implementation still adds useful information.

However, a caveat:

In https://github.com/westnordost/StreetComplete/issues/1717#issuecomment-581188710, we talked about a new variant of quest, that answers two tags at once (`AddBuildingTypeOrHousenumber`). At the time, you decided it would not be worth the implementation effort. If you change your mind about this, then my opinion also changes; in that case, I think it would make sense to ask for fee and max-stay in one quest (`AddFeeOrMaxstay`), since they often overlap ("Free for first hour").

**Comment by RubenKelevra** [comment] 2020-10-12 20:50
By @westnordost 
> [...] I also reckon that there are many people who want to be frugal with tags that are not applicable. So it is also about acceptance of having this tag potentially on every parking. `fee` for example is tagged on 14% of all parkings, but `maxstay` is tagged only on 0.5% of all parkings.

While fee might be nice to have, maxstay is actually much more important for data consumers. When a navigation app shows the parking lots the maxstay could be displayed in the details. This way a user doesn't choose a parking lot where he can only park for an hour when he/she wants to stay for longer.

At least for Germany, it's very common to have parking lots or parking spots in the city which are 'werktags' (means `Mo-Sa; PH off`) for a timeframe like 9 am till 6 pm limited to 1-2 hours.

When designing the quest for Germany it would be important to guide users what 'werktags' means, since most people understand `Mo-Fr; PH off` with this term.

Here's an example of such a parking lot, with a bit experimental tags stolen from `parking:lane` for the disc requirements:

https://www.openstreetmap.org/way/171503029

**Comment by westnordost** [comment] 2020-10-12 22:53
See https://github.com/westnordost/StreetComplete/issues/102#issuecomment-687765792 , you don't have to tell me how important the tag is. Better discuss it in community channels.

**Comment by stalker314314** [comment] 2020-11-08 11:13
Hi,
As I promised on [last mail in tagging mailing list](https://lists.openstreetmap.org/pipermail/tagging/2020-October/055897.html) around how to tag parking with limited time before you need to pay, I am contacting you to let you know that we reached a consensus here. It basically boils down to what @andrewharvey wrote here (https://github.com/westnordost/StreetComplete/issues/102#issuecomment-687761605), with an exception that on tagging list, we ended up with little bit different conditional restriction for limited parking with conditional fee:
```
fee=yes
fee:conditional=no @ (stay < 2 hours)`
```

Now, regarding possible implementation - I read all of said above, but I am trying to focus here on conditional fee *only* (let me know if another issue beside this and #981 should be opened, not to pollute here, maybe reopen #101 ). That being said, maybe it might be best to extend question "Does it cost a fee to park here?" with another answer tucked among "other answers" something like "Depends how long you plan to stay" and then ask for number of hours after which fee applies. Pardon my ignorance if this is not feasible, I am better at solving quests than writing them:)

**Comment by westnordost** [comment] 2020-11-08 12:56
Does this really appear often? - a parking lot that costs nothing if you stay less than x hours and after that starts to cost something? I think I have never seen such a parking lot.

**Comment by stalker314314** [comment] 2020-11-08 13:22
Check that thread too, but lot of shopping mall have that policy (time allowance, time limit, call it what you want). Not sure how prominent this is worldwide, but I couldn't tag fee with StreetComplete for 3 time in radius of 3km from me (urban area, lot of shopping malls, but not lot of parking spots). I think most shopping malls (small and large) in my city (Belgrade, Serbia) have this policy. This is basically way to deter people not to use shopping mall for regular parking, I guess.

Additional note: (if you think it is worth adding) special care should be taken on wording of question to differentiate between cases "it is allowed to park here, but you pay after N hours", "it is allowed to park here only for N hours and no pay" and "it is allowed to park here only for N hours and you pay" (case I wanted added is only for first one, but I think second/third case is not covered with StreetComplete too)

**Comment by smichel17** [comment] 2020-11-08 13:43
Not uncommon. Here's a parking garage with the first hour free https://www.openstreetmap.org/way/24444898

**Comment by tux2000** [comment] 2021-08-05 17:11
Came here since I missed a quest for `maxstay` on parking lots. I met quite many such parkings in the wild regionally in western Sweden were it could be anything from 2-12 hours maxstay without fee. 

I get the point about not spamming OSM with "default" tags but on the other hand the data on how common this kind of restriction is might get better when it can be tagged with Streetcomplete.

What if we would implement it as a start as an "other" option for the fee quest to gain some insights on how commonly this is in the wild in different regions and then take it up again as separate quest?

**Comment by peternewman** [comment] 2021-08-08 09:35
> Does this really appear often? - a parking lot that costs nothing if you stay less than x hours and after that starts to cost something? I think I have never seen such a parking lot.

It depends on your definition of pay, but pretty much all UK service stations and most big supermarkets have something like this, where you can park for free for a couple of hours, if you stay longer there's often a "fine" which I guess is equivalent to a payment. I don't know if that's a straight maxstay, or a conditional fee, but that's probably semantics.

It also regularly leads to stories similar to this one:
https://www.theguardian.com/money/2021/jul/12/shell-issues-60-penalty-after-woman-stops-to-breastfeed-baby

**Comment by andrewharvey** [comment] 2021-08-08 10:01
> Does this really appear often? - a parking lot that costs nothing if you stay less than x hours and after that starts to cost something? I think I have never seen such a parking lot.

Yes very common, especially for shopping centres,

**Comment by westnordost** [comment] 2022-03-04 14:36
Implemented #981, to add a proper quest that explicitly asks about maxstay might be revisited in a few years, depending on whether the future usage (numbers) justify if asking for all parking spots make sense and whether there'll be an accepted solution how to tag parkings that have no maxstay-signs at all.

**Closed by westnordost** 2022-03-04 14:36 UTC
Labels: new quest

**Comment by andrewharvey** [comment] 2023-02-20 00:18
>  but maxstay is tagged only on 0.5% of all parkings

Of the 734 `amenity=parking` + `access=yes` in Sydney without a `maxstay` or `maxstay:conditional`, 85 have a `maxstay` or `maxstay:conditional` ie. 12%.

`maxstay=unlimited` has about 6600 usages compared to 0 for `maxstay:signed=no`, so seems pretty clear on the tagging preference in use.
