### ISSUE TITLE
Arab Language in app

### ISSUE THREAD

**Issue by NavMapping** [streetcomplete/StreetComplete#3960] opened 2022-04-12 20:57 UTC
**How to Reproduce**

**Versions affected**

**Comment by 10992-osm** [comment] 2022-04-12 21:01
What exactly is the problem?

**Comment by andrewharvey** [comment] 2022-04-12 21:21
probably a duplicate of #3926

**Comment by westnordost** [comment] 2022-04-12 21:24
Support for Arabic has been added in v32.0 and has since been maintained by mostly 4 different people. If you would spotted an issue with the translation or spotted some missing translations, see here how to contribute: https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app

If you are using the en-AU locale and see some Arabic strings, this will be fixed in the next release.

**Closed by westnordost** 2022-04-12 21:24 UTC

**Comment by NavMapping** [comment] 2022-04-12 21:41
Cheers for the response 👍. The issue is i don’t want it. I have always
used the English version and I have Arabic creeping in. If I’m editing or
creating a node I will have it randomly appear to the point where i don’t
know what some text will say, making creating a node or an edit impossible

**Comment by NavMapping** [comment] 2022-04-12 21:46
> probably a duplicate of #3926

That’s the one @andrewharvey , thanks for finding that

**Comment by NavMapping** [comment] 2022-04-12 21:48
> Support for Arabic has been added in v32.0 and has since been maintained by mostly 4 different people. If you spotted an issue with the translation or spotted some missing translations, see here how to contribute: https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app
> 
> If you are using the en-AU locale and see some Arabic strings, this will be fixed in the next release.

Thanks @westnordost , i shall patiently wait and see if the release fixes it

**Comment by mnalis** [comment] 2022-04-12 22:04
@NavMapping as a temporary workaround while you wait for new release, you can in StreetComplete go to `Settings` / `Select language` and select `English` or `English (United Kingdom)` instead of `System default` (you can return to `System default` of course after the upgrade when the issue is fixed). 

While US or UK variant is not at nicely sounding to you as `English (Australia)`, it's probably still much better match than Persian :smile:

**Comment by andrewharvey** [comment] 2022-04-12 22:05
That's a good suggestion, though "Settings" is not in English, so you need to know to use the gear button :wink:
