### ISSUE TITLE
New quests: BBQ

### ISSUE THREAD

**Issue by michalgwo** [streetcomplete/StreetComplete#4831] opened 2023-02-20 18:34 UTC
### General
We can add 3 quests for [amenity=bbq](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbbq)

1. [covered](https://wiki.openstreetmap.org/wiki/Key:covered)=yes/no 
- Question asked: Is this place protected from rain? 
- Answers: yes/no

2. [fuel](https://wiki.openstreetmap.org/wiki/Key:fuel)
- Question asked: What is this grill powered by?
- Answers: wood/electric/charcoal

3. [wood_provided](https://wiki.openstreetmap.org/wiki/Key:wood_provided) (in case of fuel=wood)
- Question asked: Is wood provided by the operator of this bbq?
- Answers: yes/no

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

**Comment by FloEdelmann** [comment] 2023-02-20 18:48
Duplicate of #4832

**Closed by FloEdelmann** 2023-02-20 18:48 UTC
