### ISSUE TITLE
new Quest: surface smoothness

### ISSUE THREAD

**Issue by Katzenstreu** [streetcomplete/StreetComplete#1630] opened 2019-11-08 09:48 UTC
Hi,

I didn't found this feature request. What about a new qeust? Could we rate the quality of surfaces (ways, roads)? 

Best regards,
Tim

**Comment by westnordost** [comment] 2019-11-08 10:23
Can it be rated by an objective measure?

**Comment by Katzenstreu** [comment] 2019-11-08 11:52
Your're right. It's not easy. 
https://wiki.openstreetmap.org/wiki/Proposed_features/Surface_Quality is inactive. But we could use smoothness=* https://wiki.openstreetmap.org/wiki/Key:smoothness. There are eight grades.

But I understand the Problem. Its a little bit subjective. Could we vote for a smoothness? The Quest can be awnswerd three times. The average value could be transmitted to OSM.

**Comment by Katzenstreu** [comment] 2019-11-08 11:57
Do you know if (bike) routing software and web services (like http://brouter.de/brouter-web/) using smoothness=*? brouter doesn't.

**Comment by westnordost** [comment] 2019-11-08 12:25
I don't know. Also, voting is not possible, the app always tags directly.

**Comment by Katzenstreu** [comment] 2019-11-08 13:57
https://taginfo.openstreetmap.org/keys/smoothness (or http://overpass-turbo.eu/s/NUW) shows the coverage on a map for smoothness=*. It's used. You think its not useful?

**Comment by ferdinand0101** [comment] 2019-11-08 16:13
> It's used. You think its not useful?
I can definitely see a use for general routing and especially routing for people in wheelchairs

**Comment by westnordost** [comment] 2019-11-08 19:30
It's used, the problem is that it is quite subjective. If this is implemented, the app needs to make it easier for the user to decide by providing a good and clear UI and providing a short and clear description when something is A or B.

**Comment by Katzenstreu** [comment] 2019-11-08 20:05
Or allow tagging of smoothness only with a photo (to verify)?

Tobias Zwick <notifications@github.com> schrieb am Fr., 8. Nov. 2019, 20:30:

> It's used, the problem is that it is quite subjective. If this is
> implemented, the app needs to make it easier for the user to decide by
> providing a good and clear UI and providing a short and clear description
> when something is A or B.
>
> On November 8, 2019 5:13:13 PM GMT+01:00, ferdinand0101 <

**Comment by davidbaumann** [comment] 2020-01-02 20:48
Same problem while pushing the stroller.
Actually, the smoothness of a road get less by time, but might suddenly be perfect if the road is repaired...
I remember there is a way to mark changes to be revised before applied, maybe this would be a way?

**Comment by westnordost** [comment] 2020-01-02 20:50
This is rather a case where the surface quality should be asked again every few years or so, but this is another topic.

**Comment by westis** [comment] 2020-05-21 11:34
Has there been any more thoughts put into this? I realize that smoothness is not always easy to tag, but it can be really useful to distinguish paths of different surface quality (and therefore relevant/passable for different wheeled vehicles). Maybe there can be one set of example images for highway=track and another set of example images for highway=path? With each photo possibly combined with a photo of the wheeled vehicle(s) that are supposed to be able to pass there.

Personally I'm interested in attributes for forest and mountain paths that will aid data consumers targeted at (trail) runners and hikers. Smoothness is one of the few existing tags that can actually be very useful for that.

Two others are mtb:scale and trail_visibility, but I suppose each of those should have separate issues for discussion.

**Comment by westnordost** [comment] 2020-05-21 13:17
I'd say if this is implemented, it would best use the "eligible for XXX" descriptions on the wiki page.

So the user does not select "smoothness: excellent" but select something like "eligible for roller blades, skateboards". So for example perhaps something like this:

![image](https://user-images.githubusercontent.com/4661658/82562723-1b9de400-9b76-11ea-8432-45d9e9c9a2e5.png)

where the user should select for which vehicle type it is still usable.

**Comment by westnordost** [comment] 2020-05-21 13:23
Though this slider would need 8 stop points for all the eight values of smoothness. So, difficult to fit it into one line. It could be made vertical but then the user always has to pull up the bottom sheet to properly answer this question.

**Comment by westis** [comment] 2020-05-21 13:48
Agree that "Eligible for..." is much better than "Excellent" etc.

Some kind of vertical slider with image examples?

I'd say use different images for track and path, as 2-track vehicles can't travel on a path anyway and then the images may not be relevant for a forest path.

**Comment by davidbaumann** [comment] 2020-07-15 07:30
Actually, there could be 8 boxes to select from, like road surface.
It should be asked after road surface, as the images presented to select smoothness should depend on surface.

**Comment by Identitaet** [comment] 2020-07-26 11:51
I just saw this on weekly OSM and I thought it might be interesting

https://www.openstreetmap.org/user/Supaplex030/diary/393565
Smoothness-Ermittlung über Vibrationsmessung mit Smartphone und Fahrrad
(It seems to be only in German now but you can use software to translate it)

**Comment by westnordost** [comment] 2020-07-27 00:34
I read it, it is very interesting. Though, I do not see how this could be used. In StreetComplete, such measuring could not be made directly. As the author writes himself, how big of a vibration equals which smoothness would need to be calibrated for each individual (bicycle, driving style,...) and can only serve as a helper to decide about the smoothness. This is not how the app works, the app won't ask the user "please cycle down this road" and even if it did, what should then happen - it could only display some number to the user that shows the average level of vibrations, not make an automatic answer about the smoothness of the road.

But: Imagine there would be a QA tool that for a given (cycle)way would have the (average) amount of vibrations recorded by users of another app. This QA tool would be able to find those places where the smoothness=* value doesn't seem to fit to the level of vibrations recorded and show them on the map. Similarily to how osmose flags warnings. If that tool had an API, StreetComplete could ask for any suspects and ask StreetComplete users to (re-)survey those places. The "is this a oneway quest" works very similar to this idea.

**Comment by michaelblyons** [comment] 2020-09-08 18:03
I support this quest<sup>1</sup>. It's also one of the most interesting ones for maintaining with the #1998-style questions.

There's a little bit of difficulty with the "Eligible for&hellip;" method, although it may still be the best option. The `smoothness=excellent` roads do not have any car-like sample vehicles. Some people may misinterpret "Eligible for skateboards" to mean "Skateboards allowed on the street" and record a different answer. I notice that the English wiki now says "Usable by" which is better. Maybe we can say "Smooth enough for&hellip;" ?

I dislike several of the pictures on [`key:smoothness`](https://wiki.openstreetmap.org/wiki/Key:smoothness). The `very_bad` and `horrible` images are very similar looking, and the example for `impassable` looks very ridable on a mountain bike.

Someone talked about different options depending on the path type and/or access. I like that for similar reasons to the "Eligible for"/"Usable by" problem, but splitting into path and road/track leaves some holes in the available examples. I split MTB into front- vs. full-suspension so that paths didn't have two `smoothness` levels without examples back-to-back. I think that is a reasonable distinction to make (but I still have nothing great for "High clearance").

### Path smooth enough for

- Tiny wheels 
    + roller skates
    + skateboard
- Very thin wheels
    + racing bicycle
    + child's wagon? (May belong in "wheels," instead)
- Wheels
    + "city" bicycle
    + wheel chair
- Robust wheels
    + trekking bike
    + rickshaw
- High clearance 
    + ???
    + Ox-drawn cart? (May belong in "robust wheels," instead)
- Off road wheels
    + front-suspension mountain bike ("hardtail")
- Specialty off road wheels (Needs better name if name is shown)
    + full-suspension mountain bike
- No wheeled vehicles
    + A hiking boot

### Road/Track smooth enough for

- Tiny wheels
    + ???
- Very thin wheels
    + racing bicycle, if bicycles allowed
- Wheels
    + "city" bicycle, if allowed
    + sports car
- Robust wheels
    + trekking bike, if allowed
    + car
- High clearance
    + pickup truck / utility vehicle
- Off road wheels
    + front-suspension mountain bike, if allowed
    + Land Rover or Jeep
- Specialty off road wheels
    + full-suspension mountain bike, if allowed
    + ATV or motocross
    + tractor (possible alternative: tank)
- No wheeled vehicles
   + ??? Why is this a "road?"
    + A hiking boot

<sup>1</sup> &hellip;having recently discovered a bicycle "path" that turned out to be a dirt track covered in roots with 4 stream crossings. Very fun for MTB. Not as fun for a road bike.

**Comment by mnalis** [comment] 2020-10-25 21:25
I'd really like this too, and  "Smooth enough for…" wording seems best to me

**Comment by westnordost** [comment] 2020-10-25 22:00
I do agree that defining the smoothness by with which vehicles it can still (comfortably) be used is a good step towards making this tag more objective and thus precise. However, there is a problem with this approach which I think has been mentioned somewhere in this thread:

To accurately measure the smoothness with this method, you'd theoretically have to have every of the mentioned modes of transportation (skates, racing bike, city bike, trekking bike, hardtail, full-suspension mountain bike) with you or at least have a very good understanding how smooth a surface has to be to classify as usable for this or that method of transportation.
I for example have never used in my life either skates, a racing bike or any kind of mountain bike. So, I have no idea how bad a surface can be that it can still be conveniently used. Sure, I can not be the only one. And of course, this method does not completely do away with the subjectiveness with this tag - the more die-hard bicyclists may classify roads that would be completely unusable from my point of view as still okay-ish.

**Comment by michaelblyons** [comment] 2020-10-30 21:05
> I do agree that defining the smoothness by with which vehicles it can still (comfortably) be used is a good step towards making this tag more objective and thus precise.

Hooray! I am hopeful that we can work something out.

> The more die-hard bicyclists may classify roads that would be completely unusable from my point of view as still okay-ish.

That makes sense. I once took a rented sedan on a trip in Idaho. The highway was boring, so we found an "alternate route" on the handheld GPS. We drove through a ghost town (cool), but wound up on a perilous forest road and came out the other side in Montana. The Montana side had a warning sign saying "No articulated vehicles. High clearance only." The Idaho side had no such sign.

Objectively, one _can_ drive an ordinary car through those woods (I did it), but nobody would _recommend_ that one do so.

> And of course, this method does not completely do away with the subjectiveness with this tag

We _could_ try to make the surface smoothness objective instead of subjective by mimicking `surface=pebblestone`, where you have to measure the pebbles (although mud might make this more complicated):

- `smoothness=excellent` has a maximum surface discontinuity of 2 cm.
    + i.e. gaps in any direction, including vertical, are <2 cm
- `smoothness=good` has a maximum surface discontinuity between 2 cm and 6 cm.
- etc.

I have suspicions that a standard like that would annoy people more than help them, but it would definitely make things rigorous.

**Comment by Identitaet** [comment] 2020-10-30 21:25
So if I understand you correctly you'd like different questions with different pictures etc. for each surface type ?

I think that sounds good at least it would allow one to show examples which might be applicable

**Comment by ohrie** [comment] 2021-04-24 21:09
Maybe this table is useful: https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness (only in german currently). They also have images, which could be used, since they are CC-BY*.

**Comment by TurnrDev** [comment] 2021-04-25 06:00
Not sure if you've decided where you'll ask this yet but, may I suggest any road with on street cycle path, all service roads and footpath/cycleways?

Can be quite spammy if marked on every road

**Comment by mnalis** [comment] 2021-04-26 19:09
@ohrie if you check [Talk:Key:smoothness](https://wiki.openstreetmap.org/wiki/Talk:Key:smoothness#Making_smoothness_more_verifiable) you'd (eventually) find [User:Rhhsmits/Smoothness_details](https://wiki.openstreetmap.org/wiki/User:Rhhsmits/Smoothness_details) which is work in progress copy of that german page, translated to english and with added information. At least I think it is still work in progress, @rhhsm ?

@TurnrDev as I understand it, quest is considered spammy if **vast majority** of the answers to the quest have **same answer**, and **not if there are many questions** to be asked (or all building, roof, surface, etc. quests would be extremely spammy). 

In Croatia for example, not only service roads, but even tertiarty and unclassified as well as residential roads might not only vary between `smoothness=excellent` and `smoothness=very_bad` (and worse), but even `surface` is not to be taken for granted to be asphalt or even concrete, but quite a few are unpaved (especially outside major cities), even if classified by government as official inter-city roads. [Worldwide taginfo](https://taginfo.openstreetmap.org/keys/smoothness#values) shows fairly well distributed values, so spamminess should not be an issue (and if the user is overwhelmed by number of quests, they can be turned off in preferences - for this or any other quest).

**Comment by rhhsm** [comment] 2021-04-27 09:22
I very much hope smoothness will be included as a SC quest, but it's a tricky one. I think "smoothness" is a map property where OSM can beat Google maps, see here for an interesting background [https://www.bbc.com/news/business-52650856](url) ("Google and Apple maps do not differentiate between a good road and a bad road - but that's so important,"). SC could be of great help to realise this. But there have been lengthy discussions, not only here, about how to implement it and ensuring some degree of objectiveness and consistency. I've read most of the discussions on OSM wiki, and tried to summarise and come to some conclusion here [https://wiki.openstreetmap.org/wiki/Talk:Key:smoothness#Making_smoothness_more_verifiable](url). Comments have been few (if you have any, please add them there), so I've implemented it about a month ago, adding a description column and new photos to [https://wiki.openstreetmap.org/wiki/Key:smoothness](url). Since then I've not seen any feedback, so I thought to give it some time to become established before proposing it as a quest here. The user page that @mnalis refers to is just some additional guidance, and waiting to be linked to from the main key description page (not sure how to name it).
Smoothness as a SC quest needs some special care, as it needs some background knowledge and some experience to use it properly (consistently). Maybe the quest could be deactivated by default, and only be activated after the user has gained a minimum number of stars, has read the OSM wiki page on it, and maybe pass a little quiz/exam before it can be activated? It would also be good to be able to follow a link back to the wiki page at all times when surveying (needs to be online while in the field) to check in case of doubt, and to add a "I would like someone to review my edits." checkbox (like in ID) that a user can check if he's in doubt. Good photos are also essential.

**Comment by westnordost** [comment] 2021-04-27 09:37
Something is wrong with the urls you linked

**Comment by rhhsm** [comment] 2021-04-27 09:45
> 
> 
> Something is wrong with the urls you linked

should work now

**Comment by mnalis** [comment] 2021-04-27 10:31
@rhhsm I thought you were going to add extra columns ("horrible", "very_horrible", "impassable") and extra rows "speed (for cars)", "speed (for SUVs)" to that [page](https://wiki.openstreetmap.org/wiki/User:Rhhsmits/Smoothness_details)? I've added comments now at [User_talk:Rhhsmits/Smoothness_details](https://wiki.openstreetmap.org/wiki/User_talk:Rhhsmits/Smoothness_details). That would help a lot to remove little remaining ambiguity. When columns at least are added, I can help split "bicycle" row into "racing bicycle" / "MTB", and then we can ask for moving that page into main wiki namespace.

And more to the point of this issue specifically, we'd have nice pictures and exact explanations to remove subjectivity in order to implement this quest.

**Comment by rhhsm** [comment] 2021-04-28 06:59
> 
> 
> @rhhsm I thought you were going to add extra columns ("horrible", "very_horrible", "impassable") and extra rows "speed (for cars)", "speed (for SUVs)" to that [page](https://wiki.openstreetmap.org/wiki/User:Rhhsmits/Smoothness_details)?

Yes, you suggested it, but I don't think it's a good idea. Let's discuss this at OSM wiki Key:smoothness talk

**Comment by timor** [comment] 2021-08-09 11:47
This would be awesome for starting to map sidewalk smoothness, both for wheelchair access and recreational purposes (skateboarding, inline skating, etc.).  I did a quick check on overpass for 2 larger cities, and there was basically next to no information available about smoothness on sidewalks.  If there was any information, it was available for designated footpaths/sidewalks, but basically nonexistent for the sidewalks attached to the `highway=*` ways.

This should probably be deactivated by default. I haven't used SC for that long, but is there maybe a sensible way to limit/randomize the number of "spammy" quests (should be deactivatable by user, I guess) which are presented to regular users?  That could make it easier to get started with collecting the information bit by bit...

**Comment by Helium314** [comment] 2021-09-03 05:21
I'm currently working on implementing this quest in my personal SC fork for a bit of "live testing".
So far I wasn't happy with any kind of (text-based) list, even though possible answers only contain answers suitable for the tagged surface.

So how about using images based on the tagged surface? 
The images could be like in https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness, so e.g. if `surface=asphalt` the quest shows the 5 images for asphalt, maybe with some short descriptive text. This text could depend on the highway type (avoids mentioning inappropriate vehicles, like cars when asking about a cycle path).

This approach is more work (finding suitable images) and doesn't entirely solve the problem of the answer being subjective, but in my opinion it's a massive improvement over simply providing some list of "excellent, good, ...", example vehicles or more generic images.

@westnordost would this approach be acceptable for use in SC? (I don't want to look for good images if it's just for myself)

**Comment by westnordost** [comment] 2021-09-03 08:36
Yes, absolutely!

Am 3. September 2021 07:21:21 MESZ schrieb Helium314 ***@***.***>:
>I'm currently working on implementing this quest in my personal SC fork
>for a bit of "live testing".
>So far I wasn't happy with any kind of (text-based) list, even though
>possible answers only contain answers suitable for the tagged surface.
>
>So how about using images based on the tagged surface? 
>The images could be like in
>https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness, so
>e.g. if `surface=asphalt` the quest shows the 5 images for asphalt,
>maybe with some short descriptive text. This text could depend on the
>highway type (avoids mentioning inappropriate vehicles, like cars when
>asking about a cycle path).
>
>This approach is more work (finding suitable images) and doesn't
>entirely solve the problem of the answer being subjective, but in my
>opinion it's a massive improvement over simply providing some list of
>"excellent, good, ...", example vehicles or more generic images.
>
***@***.*** would this approach be acceptable for use in SC? (I don't
>want to look for good images if it's just for myself)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/1630#issuecomment-912263540

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment] 2021-09-03 10:01
When trying to determine smoothness on some nearby roads/paths I encountered a few difficulties:
* I often wasn't sure how to decide between good and intermediate, or intermediate and bad. So some short description will definitely be necessary.
* sometimes there are small obstacles, like "strong" tactile pavings, or expansion joints at bridges. In my interpretation of the [wiki](https://wiki.openstreetmap.org/wiki/Key:smoothness#Variations_in_smoothness) these obstacles can be ignored, but this needs to be communicated to the user.
* what about kerbs? Simply ignore as well? Ideally the user would have the possibility to add kerbs, but this would require display of already tagged kerbs (#2354)

**Comment by michaelblyons** [comment] 2021-09-03 23:41
> sometimes there are small obstacles, like "strong" tactile pavings, or expansion joints at bridges. In my interpretation of the wiki these obstacles can be ignored, but this needs to be communicated to the user.

Isn't that the job of a point with tags? I know I've made them for speed bumps and cattle grids.

> So how about using images based on the tagged surface?

Brilliant!

**Comment by Helium314** [comment] 2021-09-04 05:16
> > sometimes there are small obstacles, like "strong" tactile pavings, or expansion joints at bridges. In my interpretation of the wiki these obstacles can be ignored, but this needs to be communicated to the user.
> 
> Isn't that the job of a point with tags? I know I've made them for speed bumps and cattle grids.

Yes, but SC is mainly designed for users who are not aware of this.
Maybe an _other answer_ like "there  is some obstacle/speed bump/kerb/..." could be added, which then shows a dialog that tells the user to ignore it.

**Comment by rhhsm** [comment] 2021-09-04 06:59
> So how about using images based on the tagged surface?
The images could be like in https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness, so e.g. if surface=asphalt the quest shows the 5 images for asphalt, maybe with some short descriptive text. This text could depend on the highway type (avoids mentioning inappropriate vehicles, like cars when asking about a cycle path).

The Verkehrswende pictures are nice, but I don't think they show the difference between bad and very_bad very well: the very_bad pictures don't appear to need additional ground clearance. The very_bad roads pictured can still be used by normal cars without risk of damage to the undercarriage.
I think "inappropriate vehicles" should still be mentioned if they are used to describe the difference between smoothness categories. A very_bad cycle path, for instance, should be imagined as passable for an SUV but not a normal car if it was wide enough for a car.
> 
> When trying to determine smoothness on some nearby roads/paths I encountered a few difficulties:
> 
>     * I often wasn't sure how to decide between good and intermediate, or intermediate and bad. So some short description will definitely be necessary.

It was me who recently added the description column to the wiki. I'd say the criterion to decide between good and intermediate is the size of the roughness: would it affect someone riding a racing bike (with tyres 2-3 cm wide)? The difference between intermediate and bad is how much the surface roughness would slow down a normal car: "intermediate" slows it down a bit, "bad" slows it down considerably.

>     * sometimes there are small obstacles, like "strong" tactile pavings, or expansion joints at bridges. In my interpretation of the [wiki](https://wiki.openstreetmap.org/wiki/Key:smoothness#Variations_in_smoothness) these obstacles can be ignored, but this needs to be communicated to the user.

If the obstacles would not cause the user to make a detour to avoid them, they can be ignored.

**Closed** 2022-01-08 15:30 UTC
Labels: new quest
