### ISSUE TITLE
Sometimes when clicking on quest nothing happens

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3673] opened 2022-01-24 17:23 UTC
**How to Reproduce**
- see map with quests
- click on one quest
- notice nothing happens at all, as if quest wasn't clicked
- click on other quests, and quest forms normally opet
- clicking on problematic quest agaiin, nothing happens
- after few minutes and  switching app out/in the problematic quest fixes itself automatically and produces form normally when clicked

https://user-images.githubusercontent.com/156656/150830666-5092177f-42c4-436a-8f92-b746e7a238fa.mp4

(problematic building was this one: https://www.openstreetmap.org/way/698891862, I haven't uploaded quests yet)

**Versions affected**
- SC 39.0-beta1 [based](https://github.com/mnalis/StreetComplete/commit/b1c3d885a8076fe275a33c2b52bef8a90739e91a)
- Android 10 (EMUI 11.0.0)

**Comment by mnalis** [comment] 2022-01-24 17:28
`adb logcat --pid=2446` (hopefully correct one? i have also saved full logcat if needed) for `10:13` :

<details>

```
01-24 10:13:00.473  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:01.152  2446  2768 I VideoEnhancing: stateType:1 eventType:1
01-24 10:13:01.495  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:02.521  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:03.548  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:04.569  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:05.599  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:06.616  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:07.648  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:08.667  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:09.688  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:10.711  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:11.736  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:12.765  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:13.785  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:14.812  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:15.838  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:16.856  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:17.880  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:18.908  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:19.930  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:20.952  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:21.746  2446  2768 I VideoEnhancing: stateType:1 eventType:2
01-24 10:13:21.976  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:23.001  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:23.141  2446  2768 I NetworkQoeChr: checkForegroundApp timer start
01-24 10:13:23.141  2446  2768 I NetworkQoeChr: end qoe report
01-24 10:13:23.142  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:23.147  2446  2768 I SmartDualCardConfig: getAppType,pkgName=com.huawei.android.launcher,appType=28
01-24 10:13:23.147  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:23.147  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10088
01-24 10:13:23.151  2446  2768 I VideoEnhancing: pkg:com.huawei.android.launcher class:com.huawei.android.launcher.unihome.UniHomeLauncher
01-24 10:13:23.152  2446  2768 I VideoEnhancing: pkg:com.huawei.android.launcher/com.huawei.android.launcher.unihome.UniHomeLauncher
01-24 10:13:23.152  2446  2768 I VideoEnhancing: name:com.qiyi.video/org.iqiyi.video.activity.PlayerActivity
01-24 10:13:23.152  2446  2768 I VideoEnhancing: name:com.youku.phone
01-24 10:13:23.152  2446  2768 I VideoEnhancing: name:com.tencent.qqlive
01-24 10:13:23.574  2446  2768 I HidataAppQoeP: foregroundUidRemove uid: 10371 name: de.westnordost.streetcomplete.mn.debug
01-24 10:13:23.574  2446  2768 I HidataAppQoeP: sendKernelAppUid, Uid = 0, period = 0 name = null
01-24 10:13:23.577  2446  2769 I CommBoosterRequest: mModemId = 0slot id = 1
01-24 10:13:23.577  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:23.580  2446  2768 I SmartDualCardConfig: getAppType,pkgName=de.westnordost.streetcomplete.mn.debug,appType=-1
01-24 10:13:23.580  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:23.580  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10371
01-24 10:13:23.584  2446  2769 E OllieTelephony: sendFullData err:1
01-24 10:13:23.876  2446  2768 I HidataAppQoeP: foregroundUidAdd uid: 10016 name: com.android.calendar activity state: true
01-24 10:13:23.879  2446  2768 I HidataAppQoeP: sendKernelAppUid, Uid = 10016, period = 2000 name = com.android.calendar
01-24 10:13:23.879  2446  2768 I NetworkQoeChr: checkForegroundApp timer end
01-24 10:13:23.880  2446  2769 I CommBoosterRequest: mModemId = 0slot id = 1
01-24 10:13:23.884  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:23.888  2446  2769 E OllieTelephony: sendFullData err:1
01-24 10:13:23.888  2446  2768 I SmartDualCardConfig: getAppType,pkgName=com.android.calendar,appType=5
01-24 10:13:23.888  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:23.888  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10016
01-24 10:13:23.888  2446  2768 I VideoEnhancing: pkg:com.android.calendar class:com.android.calendar.AllInOneActivity
01-24 10:13:23.888  2446  2768 I VideoEnhancing: pkg:com.android.calendar/com.android.calendar.AllInOneActivity
01-24 10:13:23.888  2446  2768 I VideoEnhancing: name:com.qiyi.video/org.iqiyi.video.activity.PlayerActivity
01-24 10:13:23.888  2446  2768 I VideoEnhancing: name:com.youku.phone
01-24 10:13:23.888  2446  2768 I VideoEnhancing: name:com.tencent.qqlive
01-24 10:13:23.888  2446  2768 E ForegroundAppTypeDb: onAppStateChanged send app type failed
01-24 10:13:24.070  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:24.071  2446  2768 I SmartDualCardConfig: getAppType,pkgName=com.huawei.android.launcher,appType=28
01-24 10:13:24.071  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:24.071  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10088
01-24 10:13:24.892  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:25.590  2446  2768 I VideoEnhancing: pkg:com.android.calendar class:com.android.calendar.event.EditEventActivity
01-24 10:13:25.590  2446  2768 I VideoEnhancing: pkg:com.android.calendar/com.android.calendar.event.EditEventActivity
01-24 10:13:25.590  2446  2768 I VideoEnhancing: name:com.qiyi.video/org.iqiyi.video.activity.PlayerActivity
01-24 10:13:25.590  2446  2768 I VideoEnhancing: name:com.youku.phone
01-24 10:13:25.590  2446  2768 I VideoEnhancing: name:com.tencent.qqlive
01-24 10:13:25.911  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:26.934  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:27.962  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:28.983  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:30.011  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:31.031  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:32.054  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:33.079  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:34.110  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:35.127  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:36.152  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:37.179  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:38.200  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:39.223  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:40.247  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:41.043  2446  2768 I VideoEnhancing: pkg:com.android.calendar class:com.android.calendar.AllInOneActivity
01-24 10:13:41.043  2446  2768 I VideoEnhancing: pkg:com.android.calendar/com.android.calendar.AllInOneActivity
01-24 10:13:41.043  2446  2768 I VideoEnhancing: name:com.qiyi.video/org.iqiyi.video.activity.PlayerActivity
01-24 10:13:41.043  2446  2768 I VideoEnhancing: name:com.youku.phone
01-24 10:13:41.043  2446  2768 I VideoEnhancing: name:com.tencent.qqlive
01-24 10:13:41.270  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:42.182  2446  2768 I NetworkQoeChr: checkForegroundApp timer start
01-24 10:13:42.182  2446  2768 I NetworkQoeChr: end qoe report
01-24 10:13:42.183  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:42.187  2446  2768 I SmartDualCardConfig: getAppType,pkgName=com.huawei.android.launcher,appType=28
01-24 10:13:42.188  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:42.188  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10088
01-24 10:13:42.189  2446  2768 I VideoEnhancing: pkg:com.huawei.android.launcher class:com.huawei.android.launcher.unihome.UniHomeLauncher
01-24 10:13:42.190  2446  2768 I VideoEnhancing: pkg:com.huawei.android.launcher/com.huawei.android.launcher.unihome.UniHomeLauncher
01-24 10:13:42.190  2446  2768 I VideoEnhancing: name:com.qiyi.video/org.iqiyi.video.activity.PlayerActivity
01-24 10:13:42.191  2446  2768 I VideoEnhancing: name:com.youku.phone
01-24 10:13:42.191  2446  2768 I VideoEnhancing: name:com.tencent.qqlive
01-24 10:13:42.297  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:42.510  2446  2768 I HidataAppQoeP: foregroundUidAdd uid: 10371 name: de.westnordost.streetcomplete.mn.debug activity state: true
01-24 10:13:42.510  2446  2768 I NetworkQoeChr: checkForegroundApp timer end
01-24 10:13:42.514  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:42.517  2446  2768 I SmartDualCardConfig: getAppType,pkgName=de.westnordost.streetcomplete.mn.debug,appType=-1
01-24 10:13:42.517  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:42.517  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10371
01-24 10:13:42.521  2446  2768 I VideoEnhancing: pkg:de.westnordost.streetcomplete.mn.debug class:de.westnordost.streetcomplete.MainActivity
01-24 10:13:42.521  2446  2768 I VideoEnhancing: pkg:de.westnordost.streetcomplete.mn.debug/de.westnordost.streetcomplete.MainActivity
01-24 10:13:42.521  2446  2768 I VideoEnhancing: name:com.qiyi.video/org.iqiyi.video.activity.PlayerActivity
01-24 10:13:42.521  2446  2768 I VideoEnhancing: name:com.youku.phone
01-24 10:13:42.521  2446  2768 I VideoEnhancing: name:com.tencent.qqlive
01-24 10:13:42.521  2446  2768 E ForegroundAppTypeDb: onAppStateChanged send app type failed
01-24 10:13:42.587  2446  2768 I HidataAppQoeP: foregroundUidRemove uid: 10016 name: com.android.calendar
01-24 10:13:42.600  2446  2768 I HidataAppQoeP: sendKernelAppUid, Uid = 10371, period = 2000 name = de.westnordost.streetcomplete.mn.debug
01-24 10:13:42.601  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:42.603  2446  2768 I SmartDualCardConfig: getAppType,pkgName=com.android.calendar,appType=5
01-24 10:13:42.603  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:42.603  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10016
01-24 10:13:42.725  2446  2768 I VideoEnhancing: invalid state received default msg.what2130771969
01-24 10:13:42.726  2446  2768 I SmartDualCardConfig: getAppType,pkgName=com.huawei.android.launcher,appType=28
01-24 10:13:42.726  2446  2768 E SmartDualCardConfig: isAppInBlackList false,items==null
01-24 10:13:42.726  2446  2768 I SmartDualCardConfig: isAppInWhiteList false,uid=10088
01-24 10:13:43.320  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:44.344  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:45.373  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:46.393  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:47.419  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:48.294  2446  2768 I PreDnsQuery: setPreDnsCurrentProp is: false
01-24 10:13:48.441  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:49.467  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:50.490  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:51.521  2446  2768 I PreDnsQuery: setPreDnsCurrentProp is: true
01-24 10:13:51.524  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:52.539  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:53.563  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:54.585  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:55.609  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:56.632  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:57.659  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:58.679  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false
01-24 10:13:59.704  2446  2768 D NpdcpAliveManager: ro.odm.npdcp_alive_cfg_enable is false

```

</details>

**Comment by westnordost** [comment] 2022-01-25 10:03
There is nothing helpful in the logs. No idea what may be the cause.

**Comment by westnordost** [comment] 2022-01-25 10:21
Generally, it would be best if you reported bugs only for versions
- that are current
- that are reproduced with an original non-modified version of the app. I have no idea after all what all you changed in your fork

**Comment by mnalis** [comment] 2022-01-25 10:50
I know, and I'm sorry for that. I **do try** to reproduce it with your upstream version and report that whenever possible.

Unfortunately, with bugs like this (that occur only randomly and rarely), it's most likely I'll only catch them in my fork which I use most of the time.

And I only do that when I think my fork [should not](https://github.com/mnalis/StreetComplete/blob/mnalis-everything/CHANGES-mnalis.md) affect that behaviour - basically currently I only add few extra quests and modify few filters so some quests show more often, change colors and ordering of some icons.
(It is also usually more current, but v39.0 (compared to v39.0-beta1) changed some code, so now extra quests I have cause failure to compile until I can debug/fix them)

Anyway, I was hoping it might be something visible or suspicious, and/or that someone else who experienced the problem (hopefully with pristine upstream release) might also chime in. It's not a big deal, as it happens very rarely (I can remember it happening only once or twice before) and does not cause any data loss, you can **_close it unless you want me to add some debugs_** at this time.

**Comment by westnordost** [comment] 2022-01-25 11:37
I'd keep it around for a bit, maybe someone can reproduce it.

**Comment by matkoniecz** [comment] 2022-03-03 07:55
I think I will close it, for reasons stated above.

**Closed by matkoniecz** 2022-03-03 07:55 UTC
Labels: bug, feedback required
