### ISSUE TITLE
Nearby Note Notification

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#2590] opened 2021-02-17 13:34 UTC
**Use case**
Quite often I'm out and about and might not have StreetComplete as the top level app, I'll pass an open note which I could resolve but have no way of knowing it's there.

**Proposed Solution**
A system notification reminding me that there are open notes nearby that I could resolve. Would be especially great if I could pre-select a note and ask the app to remind me when I'm nearby.

Maybe the definition of "nearby" could be a setting

**Comment by westnordost** [comment] 2021-02-17 13:40
Pretty much a duplicate of #48, as a note is just another quest and other people might want to get notified about other things they deem very important.

**Closed by westnordost** 2021-02-17 13:40 UTC
