### ISSUE TITLE
Some text appears in Arabic

### ISSUE THREAD

**Issue by melbournefan** [streetcomplete/StreetComplete#3927] opened 2022-03-28 13:00 UTC
So I've opened street complete up and some text is appearing in Arabic, this is despite the language on my phone set to English (Australia), it's only appeared after the update to version 42.0

![Screenshot_2022-03-28-23-53-31-521_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/41057813/160402808-e727f868-2304-44c1-bb54-113b029e677a.jpg)

![Screenshot_2022-03-28-23-53-35-814_de.westnordost.streetcomplete.jpg](https://user-images.githubusercontent.com/41057813/160403045-e4a528fb-0bf4-474a-8137-b3897e9c647e.jpg)

Currently running MIUI 12.5.6 (Android 11) if that helps.

Thanks

**Comment by westnordost** [comment] 2022-03-28 13:02
It's actually Persian. Duplicate of #3926

**Closed by westnordost** 2022-03-28 13:02 UTC
Labels: bug
