### ISSUE TITLE
Check if a building is already in a 3D building relation / has building:parts

### ISSUE THREAD

**Issue by TurnrDev** [streetcomplete/StreetComplete#2544] opened 2021-02-01 09:28 UTC
Several buildings around me are 3D modeled using relations and building:part tags. [Example](https://www.openstreetmap.org/relation/12245291)

StreetComplete is asking for levels data for the outline which is not needed as it's defined by the building:part ways. 

**How to Reproduce**
1) Create a complex 3D object with outlines and parts
2) Look at object in StreetComplete

**Versions affected**
First noticed in v30.0-beta1 Android 10

**Comment by westnordost** [comment] 2021-02-01 11:49
Duplicate of  #579

**Closed** 2021-02-02 21:54 UTC
Labels: bug
