### ISSUE TITLE
Wifi detection isn't working

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2947] opened 2021-06-04 18:11 UTC
I noticed that the "Upload only on WiFi" isn't working as it's supposed to. It's not uploading at all.

Android 11
One Plus 5T
StreetComplete v32.1

**Comment by peternewman** [comment] 2021-06-05 14:01
Works for me with that setting on Android 9 on a Sony Xperia XZ1 Compact.

I assume it used to work for you @RubenKelevra ?

**Comment by RubenKelevra** [comment] 2021-06-05 14:14
Yeah it worked before updating to Android 11. Not sure if that's an bug on my device 🤔

But I also had some issues on my Android tablet some versions ago, where it won't upload anything even with autosync on. If you switched to autosync off, you could see that there wasn't any update. 

I'll check if that's still the case.

**Comment by RubenKelevra** [comment] 2021-06-06 00:20
On my Tablet this works fine.

**Comment by westnordost** [comment] 2021-06-07 13:28
Sounds like it is a problem with your phone then. Maybe there is some battery-saver option that prevents from this event being sent to the apps that request it?

**Comment by westnordost** [comment] 2021-06-07 13:28
What version does your tablet run on?

**Comment by matkoniecz** [comment] 2021-06-08 14:18
Also, have you maybe declared that this specific wifi is metered and should be treated as mobile data? (I seem to remember such setting)

Is it also happening on other wifi?

Can you use that wifi on that tablet for other purposes (try disabling data connection to ensure that only wifi is available).

**Comment by RubenKelevra** [comment] 2021-06-09 08:23
@westnordost wrote:

> Sounds like it is a problem with your phone then. Maybe there is some battery-saver option that prevents from this event being sent to the apps that request it?

No battery related options are on.

I'm using Home Assistant and the Android App can send the WiFi-Status to my Hub. So it's not a general issue with my device as far as I can see. 

![Screenshot_20210609-101630812.jpg](https://user-images.githubusercontent.com/614929/121319311-610d8a80-c90c-11eb-9c36-32989b7263eb.jpg)

@westnordost wrote:

> What version does your tablet run on?

Tablet runs fine now. It's running Android 8.1.

> Also, have you maybe declared that this specific wifi is metered and should be treated as mobile data? (I seem to remember such setting)

Actually I declared that wifi as unmetered from the beginning.

![Screenshot_20210609-100922726.jpg](https://user-images.githubusercontent.com/614929/121318935-01af7a80-c90c-11eb-9d8b-868684a5c985.jpg)


> Is it also happening on other wifi?

Yes. 


> Can you use that wifi on that tablet for other purposes (try disabling data connection to ensure that only wifi is available).

Yes. My wifi works fine on my tablet and my Phone (the device where I have the issues with right now). 

StreetComplete also happily uploads the changes when I press the button. It's just that SC seems to unable to figure out that the device has wifi.

**Comment by westnordost** [comment] 2021-06-09 16:49
So maybe it is an issue with the Android version. Anyone got Android 11 and can reproduce this problem?

**Comment by riQQ** [comment] 2021-06-09 17:55
I can't reproduce this with StreetComplete 32.1 on Android 11:
I answered some quests with disabled Wifi and "Upload only on WiFi" enabled. Then I enabled WiFi again, my phone connected to the WiFi and the answers were uploaded.

**Comment by wielandb** [comment] 2021-06-12 16:00
I also have a problem with wifi upload but I don't know if I am experiencing the same issue as @RubenKelevra 

When opening SC while connected to a wifi and having quests to upload, SC will not "notice" that wifi is connected and not start uploading the answers. Only going into a menu such as profile and going back seems to trigger the upload.

**Comment by westnordost** [comment] 2021-06-12 18:06
I wasn't able to reproduce this,  Android 11

On June 12, 2021 6:00:47 PM GMT+02:00, Wieland ***@***.***> wrote:
>I also have a problem with wifi upload but I don't know if I am
>experiencing the same issue as @RubenKelevra 
>
>When opening SC while connected to a wifi and having quests to upload,
>SC will not "notice" that wifi is connected and not start uploading the
>answers. Only going into a menu such as profile and going back seems to
>trigger the upload. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2947#issuecomment-860072834

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by RubenKelevra** [comment] 2021-06-12 21:30
> I also have a problem with wifi upload but I don't know if I am experiencing the same issue as @RubenKelevra
> 
> When opening SC while connected to a wifi and having quests to upload, SC will not "notice" that wifi is connected and not start uploading the answers. Only going into a menu such as profile and going back seems to trigger the upload.

Strange. This doesn't work for me as a trigger.

https://photos.app.goo.gl/pyjUoXpg4rLXZkP29

@westnordost not familiar with the android wifi detection for apps. But I was under the impression that an app needs "phone" access for this.

Is there a more limited access for apps to just get the type of connection?

**Comment by westnordost** [comment] 2021-06-13 08:32
I'd say it needs `android.permission.ACCESS_NETWORK_STATE` which it declares in the manifest.

The relevant code in `QuestAutoSyncer` is
```kotlin
        context.registerReceiver(connectivityReceiver, IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION))
```

I noticed that the `CONNECTIVITY_ACTION` constant is deprecated. Maybe someone would like to research into that, maybe this could be the cause.

**Comment by RubenKelevra** [comment] 2021-06-13 11:04
I guess some roms might still support it, while my AOSP one has already dropped the support? 🤔

**Comment by wielandb** [comment] 2021-06-13 11:29
> I wasn't able to reproduce this,  Android 11

I am on Android 9, SC v32.1.

> Strange. This doesn't work for me as a trigger.

It's the exact opposite for me. When SC is already open and a Wifi connects, the upload _does_ start automatically. 
Only when the Wifi is already connected the upload won't start on startup.

https://user-images.githubusercontent.com/29458682/121805320-19a83680-cc4b-11eb-8570-beac9b136a61.mp4

https://user-images.githubusercontent.com/29458682/121805322-1b71fa00-cc4b-11eb-8b2b-41f21a4da8df.mp4

**Comment by mnalis** [comment] 2021-06-16 22:30
I can reproduce this on Huawei P30 Pro (EMUI 11 / Android 10). Auto upload on wifi activates only when I enter `Settings` and come back from it. 

https://user-images.githubusercontent.com/156656/122302867-fdceba00-cf02-11eb-9c2d-6062e6a97476.mp4

**Comment by mnalis** [comment] 2021-06-16 22:54
It **might have been related to battery power saving** in my case. While phone is set to `Performance mode` (and not  `Power Saving mode` nor `Ultra Power Saving mode`), there are additional per-app settings. When I disabled them for StreetComplete, wifi autodetect worked and uploaded automatically! 

[DavX5 FAQ](https://www.davx5.com/faq/synchronization-is-not-run-as-expected) usually has good pointers for various phones on how to disable extra per-app power saving features.  In my EMUI 11 (Android 10) case, it was: `Settings` / `Apps` / `Apps` / search for `StreetComplete` / `Power usage details` / `Launch settings` and then disabling `Manage automatically` and enabling `Auto-launch` & `Secondary launch` &  `Run in background`, like this:

![Screenshot_20210617_004157_com huawei systemmanager](https://user-images.githubusercontent.com/156656/122304065-e55f9f00-cf04-11eb-98f9-58ad8fbe65a4.jpg)

After that, it detects wifi and uploads automatically. 

I say it _**might have been related to power settings**_, because when I put it back on `Manage automatically` to test the hypothesis, it still continues to work correctly (while I expected it to start failing again). I've now put it back to `Manage manually` mode for `please-disable-any-power-saving-for-this-app`, and will try to see if wifi autodetection fails to work again in the future. 

But other people with problem might try to look into that direction to see if something similar works for them.

**Comment by westnordost** [comment] 2021-06-20 11:28
Alright, then I will close this. Nothing can be done from the side of this app if the Android system interferes with normal behavior for one reason or another.

**Closed by westnordost** 2021-06-20 11:28 UTC
Labels: bug, feedback required

**Comment by mnalis** [comment] 2021-06-29 13:41
Well, contrary to my previous post, **disabling powersaving didn't really help**. Even when having all power saving globally **and** for StreetComplete in particular disabled, I've noticed at least twice now that SC didn't detect wifi. (It took switching to another app and back made it recognize wifi and autoupload).

**Comment by RubenKelevra** [comment] 2021-07-09 15:06
@westnordost okay, but why is this closed now? 🤔

**Comment by westnordost** [comment] 2021-07-09 15:30
because it is not an issue of the app

**Comment by mnalis** [comment] 2021-07-09 21:24
> because it is not an issue of the app

Is it perhaps possible that it is **issue in the app** after all, so it should be reopened? 

For example, yesterday SC again didn't detect wifi for me, but just entering the `About` SC page and clicking back it detected wifi no problem. It was the case every time so far for me - **just opening settings or about screen and going back worked 100%.**

Maybe the issue is indirect, like some activity update is triggered only on such window change? Maybe it is then possible to make the SC "simulate" what such window switch does so new wifi state is detected reliably too (I do not know enough about android programming, so forgive me if it sounds silly)

For reference, on the same phone I use [nextcloud app](https://f-droid.org/en/packages/com.nextcloud.client/) which also has feature to automatically upload pictures on wifi-only, and it seems to detect it just fine all the time, while SC works only in about 50% cases. So it is apparently possible to detect wifi reliably, but maybe they use some other method to detect it or something?
