### ISSUE TITLE
Ability to snooze or temporarily skip a quest

### ISSUE THREAD

**Issue by Vinnl** [streetcomplete/StreetComplete#5168] opened 2023-07-30 10:46 UTC
**Use case**

I want to indicate that a restaurant I ate at offers vegetarian food, but the first quest I get offered is to confirm its opening hours. I would like to go back later to confirm them, but can't complete the quest now. It would be nice to be able to complete the quest about vegetarian food without permanently dismissing the opening hours quest.

**Proposed Solution**

- Add a "Snooze quest" option that hides it for, say, a day
- Add a "Next quest" option (if there are more) - the given quest can then reappear after the other quests have been resolved/skipped

**Comment by FloEdelmann** [comment] 2023-07-30 10:49
Duplicate of

* #3952 

See also

* #124
* #3023

**Closed by FloEdelmann** 2023-07-30 10:49 UTC
