### ISSUE TITLE
Quest to add crops to farmlands

### ISSUE THREAD

**Issue by goodevilgenius** [streetcomplete/StreetComplete#3986] opened 2022-04-22 20:08 UTC
### General

In rural areas, it's common for farmlands to be tagged with the crop that is grown there. For users who live in rural areas, this would be a useful quest to add. It would be particularly easy to do the quest during the harvest season when the crop is most visible.

Affected tag(s) to be modified/added: [Crop](https://wiki.openstreetmap.org/wiki/Key:crop)
Question asked: **What crop is grown on this farm?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

Similar to the opening hours quest, it may be useful to show a quest to confirm that this hasn't changed since originally tagged after a certain amount of time, as farmers will occasionally rotate crops.

**Element selection:** 
All areas with `landuse:farmland`, but no `crop:` set.

**Metadata needed:** 
The only likely variation by country might be corn/maize. Most others already listed on the wiki page should be reasonably universal. However, since most crops only grow in certain regions, it might be useful, if possible, to have the default list (see Proposed UI below) to have the most common crops for the region. This might not be possible to tailor so specifically, however.

**Proposed UI:**
The selector would likely work similar to the building type selector. By default, it would show the most common values, and then allow other options broken down by category. The categories can be derived directly from the wiki page.

**Comment by westnordost** [comment] 2022-04-22 20:29
I believe this has been discussed before, at least it is a duplicate of  #363. Here is in detail why it has been rejected (refer to the guidelines regarding the icons):

1. 🚧/🤷/💵 The `crop` tag itself is problematic insofar as it is extremely volatile, thus either requires constant maintenance (re-checking every single field several times a year) or the data rots in the shortest amount of time, as
  * Farmland is often planted with different crops throughout one year. At the very least, it _may_ change several times during the year depending on whatever the farmer calculates would get the best profit
  * Farmland usage may vary between fallow, different crops and meadow (crop rotation), especially outside of industrial agriculture
  * Perennial crops are basically `landuse=orchard` for which there is already a quest

2. 🤔/👨‍💻/🕵️ Unless they are farmers or botanists, users will not recognize which crops exactly have been planted. Some may be recognizeable when they are almost ripe, but when they have just been planted, no. Also, you might need to go onto the field (i.e. private property) to see what exactly has been planted there.

3. 🕓 There are **lots** of crops and all of those would need representative graphics etc. Doesn't sound like it is worth it

**Closed** 2022-04-22 20:29 UTC
