### ISSUE TITLE
Keine Strassennamen

### ISSUE THREAD

**Issue by Hallenberger** [streetcomplete/StreetComplete#3448] opened 2021-10-24 15:29 UTC
**How to Reproduce**

**Versions affected**

Es werden keine Straßennamen mehr angezeigt.

**Comment by Hallenberger** [comment] 2021-11-11 17:41
With Version v37.1 the problem is still alive.

**Comment by matkoniecz** [comment] 2021-11-11 17:47
Do you have stock Android from Google or some custom ROM?

Which language is set as the system language?

Is there anything in logs?

**Comment by FloEdelmann** [comment] 2021-11-11 17:48
> Wo ist das?

Werden nirgends Straßennamen angezeigt, oder nur in einer bestimmten Gegend nicht? Kannst du einen OSM-Link zu einer betroffenen Straße teilen?

<details>
<summary>English :us:</summary>

Are street names not showing anywhere, or only in a certain area? Can you share an OSM link to an affected street?

</details>

**Comment by Hallenberger** [comment] 2021-11-11 18:20
Google Pixel 3a. Stock Android from Google.
Language is German.
Where can i find the logs?

**Comment by matkoniecz** [comment] 2021-11-11 18:29
You can grab the logs via adb logcat (https://www.siteforinfotech.com/capture-android-logs-minimal-adb-and-fastboot/), without root

But first to check: are streets in this area actually having names in OpenStreetMap? Has someone set incorrect `name:de` on them?

It is also possible that Jawg tile data is corrupted in this area, to check this you can look at https://github.com/streetcomplete/streetcomplete-mapstyle#contributing - or more specifically https://streetcomplete.github.io/streetcomplete-mapstyle/?provider=jawg&style=light If that is not showing street names either, then problem is not on StreetComplete side.

**Comment by Hallenberger** [comment] 2021-11-11 18:45
Streets are always without names in streetcomplete. The Jawg tile data are correct. In OpenStreetMap the streets have correct names.

**Comment by westnordost** [comment] 2021-11-11 22:43
So 
- it is not a data issue
- it is not a Jawg issue
- it is not a tangram issue per se (but it could be a tangram-es issue)

And since you have a standard phone with stock Android, I very much doubt that it is an Android or device issue (e.g. some broken OpenGL ES support). You also do not have any weird language set.

What German did you select in the settings? German (Germany)? Or something else?

We are really poking around in the dark here, as you seem to be the first one who can reproduce this issue. Your configuration doesn't seem to be in any way special.

**Comment by westnordost** [comment] 2021-11-11 22:44
Is text displayed at all on the map? For example, are housenumbers shown where they should be shown? (Compare with https://streetcomplete.github.io/streetcomplete-mapstyle/?provider=jawg&style=light )

**Comment by smichel17** [comment] 2021-11-11 22:46
Are you able to zoom in any further? I have noticed that sometimes I have to zoom in quite far to get names to appear.

**Comment by matkoniecz** [comment] 2021-11-12 08:00
> We are really poking around in the dark here, as you seem to be the first one who can reproduce this issue. Your configuration doesn't seem to be in any way special.

Can you try reinstalling StreetComplete? (after submitting quests if you use some manual upload mode, as all data will be reset)

Maybe there is some random corruption manifesting this way?

Do you have some weird behavior in other apps? (my previous phone was not showing toast messages in Vespucci and some other apps - due to some phone specific bug or corruption).

**Comment by Hallenberger** [comment] 2021-11-13 16:29
I have installed StreetComplete on an other Pixel3a (with Android 12). On this smartphone StreetComplete was never installed. The same issue: no street-names, no house-numbers. It seems, that _every_ text is not displayed.

**Comment by matkoniecz** [comment] 2021-11-13 16:56
Ok, that is weird.

Has anyone else got access to Pixel3a? Is it happening also to them?

Not asking you to do this, but if you have multiple phones it maybe would be feasible - but is it happening also after factory reset of a phone?

**Comment by westnordost** [comment] 2021-11-13 18:16
I think the definitive lead here is that text on Android 12 doesn't work. Next steps:
- try it in an Android 12 emulator.
- if reproducible, report issue at tangram-es

**Comment by svenpilz** [comment] 2021-11-16 23:32
I have the same issue on Android 12 (Pixel 5) with 37.2. No text is displayed on the map.

**Comment by westnordost** [comment] 2021-11-16 23:39
I think this is linked to https://github.com/tangrams/tangram-es/issues/2303#issuecomment-970685208 or even the very same issue.

**Comment by westnordost** [comment] 2021-11-16 23:43
Probably blocked by a bug upstream. If the issue cannot be resolved, maybe a workaround is possible. For now, I'll mark it as blocked.

**Comment by westnordost** [comment] 2021-11-18 12:05
Alright I'll close this as there is an issue for that upstream.

**Closed by westnordost** 2021-11-18 12:05 UTC
