### ISSUE TITLE
Bug in Themes

### ISSUE THREAD

**Issue by tintinmaster** [streetcomplete/StreetComplete#2158] opened 2020-10-12 17:48 UTC
When the System Theme differs from the selected them in the App (also in Auto mode) some elements have the theme background, but the wrong text color. So it's hard/impossible to read.
Using theme "System Default" works flawless.

It does not happen while changing the theme and a restart does not help, so it is not directly related to the other issues (which are all closed by now) 

It seems like some backgrounds are always determined by the system theme and not by the theme the app enforces.

**How to Reproduce**
Have System _Dark Mode_ **activated** and in-app _Light theme_ **activated** or
Have System _Dark Mode_ **deactivated** and in-app _Dark theme_ **activated**

**Versions affected**
v24.1 and Android 10
Black System and Light In-App:
![image](https://user-images.githubusercontent.com/36089973/95775815-648c3b80-0cc3-11eb-9264-a6592a4f91b0.png)
![image](https://user-images.githubusercontent.com/36089973/95775820-6950ef80-0cc3-11eb-8fca-a391d45619ab.png)

Light System and Dark In-App:
![image](https://user-images.githubusercontent.com/36089973/95775828-6c4be000-0cc3-11eb-8ff6-ce457a4428df.png)

**Comment by westnordost** [comment] 2020-10-13 15:54
I don't have a new phone so I do not have dark mode to reproduce it. Help would be appreciated.

**Comment by ENT8R** [comment] 2020-10-13 17:10
I'm also on Android 10 and just tried whether I could reproduce any similar behaviour, but this is the only thing I noticed which comes close to the issue described above:
<div align="center">
<img src="https://user-images.githubusercontent.com/25306497/95890052-8c42d880-0d83-11eb-8544-53f4628b6dbf.jpg" width="250px"> <img src="https://user-images.githubusercontent.com/25306497/95890048-8a791500-0d83-11eb-90c8-5fd5fea4e7b4.jpg" width="250px">
</div>
Seems weird to me that it differs that much across different devices, maybe it's the vendor's fault because they screwed something up in their dark mode implementation?

**Comment by matkoniecz** [comment] 2020-10-14 07:20
> I don't have a new phone so I do not have dark mode to reproduce it. Help would be appreciated.

I just (accidentally and with no clear info how to repeat, but may be related to opening phone after it was closed during night) reproduced it in Android 10 emulator

![screen](https://user-images.githubusercontent.com/899988/95956318-660e4e80-0dfe-11eb-9eee-209d929e149a.jpg)

**Comment by tintinmaster** [comment] 2020-10-14 12:13
To clarify, I use a Huawei Phone, but still with Android and EMUI 10.1.0.
Tried it on an emulated Pixel 3a and everything worked fine. 

Does anybody know any other apps, that are developed with Android Studio and have own themes, so I could test, if it has something to do with the vendors implementation?

**Comment by michaelblyons** [comment] 2020-11-03 15:18
FWIW, I have a physical Pixel 3a. I've never seen any of the "bad" variants. My Android system is set to dark mode, and all four of the StreetComplete theme options work as expected.

**Comment by jleedev** [comment] 2020-11-19 23:11
![Screenshot_20201119-180951](https://user-images.githubusercontent.com/23022/99735455-a3679b00-2a92-11eb-8162-eca35346a323.png)

Here's another issue with blue text on a dark background

**Comment by smichel17** [comment] 2021-04-29 01:24
I have a reliable repro for a similar bug in an Android 10 (api 29) emulator.

![image](https://user-images.githubusercontent.com/6563664/116491047-76f94b80-a888-11eb-907a-6673a81f7e17.png)

Steps:

- Stock Android emulator settings, clean install (no system dark theme)
- Open SC > Settings > Dark theme
- Click home button to minimize SC.
- App drawer > Long press on SC > App info > Storage & cache > Clear storage
- Return to home screen > app drawer > open SC > click through walkthrough > Open main menu

I wasn't able to reproduce theme weirdness anywhere other than the main menu (that I noticed). Closing the app, swiping it away in the recent apps list, and then re-opening fixes it.

**Comment by Helium314** [comment] 2021-04-29 06:22
I had this yesterday when theme was on `auto` (switched from light to dark).
Wasn't able to reproduce it with manual switch, but got a crash when switching from `auto` (light) to `system default` (dark):

```
Thread: DefaultDispatcher-worker-1
App version: 32.0-alpha1
Device: samsung serranods, Android 9
Locale: en_GB
Stack trace:
java.lang.RuntimeException: Tried to perform an operation on an invalid pointer! This means you may have used a MapData that has already been removed.
at com.mapzen.tangram.MapData.checkPointer(MapData.java:98)
at com.mapzen.tangram.MapData.setFeatures(MapData.java:36)
at de.westnordost.streetcomplete.map.components.PinsMapComponent.showPins(PinsMapComponent.kt:48)
at de.westnordost.streetcomplete.map.QuestPinsManager.updatePins(QuestPinsManager.kt:166)
at de.westnordost.streetcomplete.map.QuestPinsManager.access$updatePins(QuestPinsManager.kt:20)
at de.westnordost.streetcomplete.map.QuestPinsManager$updateQuestsInRect$2.invokeSuspend(QuestPinsManager.kt:129)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
Of course not reproducible, as usual.
SC was downloading/generating quests when the crash occurred... so I guess it's either connected to the theme bug here, or to switching theme at the "right" point of a download.

**Comment by timothywashere** [comment] 2021-10-05 20:40
I have this issue where I can't read what I've written in the bus stop name quest at night. System is dark, ST is set to auto, House name and road name quests seen ok. Phone is Google Pixel 3

![Screenshot_2021_10_05_19_53_14](https://user-images.githubusercontent.com/87654968/136099444-542bb52f-5313-4ec8-b725-e7bf9a9fb412.jpg)

**Comment by westnordost** [comment] 2021-10-05 20:50
Can reproduce

**Comment by westnordost** [comment] 2021-10-05 20:54
Will be fixed in v36.0

**Comment by bogomil** [comment] 2024-04-12 07:28
If it's worth mentioning I can't reproduce the problem on a real device.
UI: 5.1
Android 13
SC version: 57.1

**Comment by westnordost** [comment] 2024-04-12 09:54
Hm well, I don't think it is worthwhile to investigate this issue further, as we are [in the process of migrating to a different UI framework](https://github.com/streetcomplete/StreetComplete/issues/5421) anyway, for me at least. With  a different UI framework come different bugs.

**Comment by westnordost** [comment] 2024-08-14 19:43
So I am going to close this, because this bug won't be fixed anymore. Can be re-reported in case this happens in the new UI. Parts of the app currently already migrated to the new UI framework (on dev branch):

- Everything except the main screen
- all controls, dialogs, sidebars, dropdowns etc you see on the main screen

Anything that is shown in the bottom sheet (quests etc) is not migrated yet.

**Closed by westnordost** 2024-08-14 19:43 UTC
Labels: bug, help wanted
