### ISSUE TITLE
"What's new" screen unreadable in dark mode

### ISSUE THREAD

**Issue by Kangie** [streetcomplete/StreetComplete#5914] opened 2024-09-21 00:18 UTC
"What's new" screen unreadable in dark mode

![Screenshot_20240921-091908](https://github.com/user-attachments/assets/6463eb4b-87ee-4811-8c18-ccba1110b57f)

**How to Reproduce**
Have app in dark mode, receive an app update

**Expected Behavior**
Should be able to read about the changes.

**Versions affected**
V59.0

**Comment by kmpoppe** [comment] 2024-09-21 02:41
Duplicate of #5906.

**Closed** 2024-09-21 03:45 UTC
Labels: bug
