### ISSUE TITLE
Allow answering that a path/street is not accessible to the public on related quests

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#3876] opened 2022-03-14 06:08 UTC
**Use case**

When paths and/or streets are not accessible to the public (but they are not yet tagged as private in OSM), the quest often cannot be answered safely or legally. At present this can only be resolved with a note, and someone having to follow up the note with an edit.

**Proposed Solution**

On quests related to paths and/or streets, allow an answer 'The path/street is not accessible to the public' which will mark the way as access=private and not ask any other quest for that element.

**Comment by FloEdelmann** [comment] 2022-03-14 06:37
Duplicate of #2051

**Closed** 2022-03-14 06:37 UTC
Labels: duplicate
