### ISSUE TITLE
AddOpeningHours crash

### ISSUE THREAD

**Issue by starsep** [streetcomplete/StreetComplete#2979] opened 2021-06-19 07:36 UTC
I am getting a crash whenever I click AddOpeningHours quest icon.
I suppose it might be caused due to my steps:
1. Add opening hours for a POI in different OSM Editor.
2. Open StreetComplete
3. Choose opening hours quest for the same POI.

I suspect saved state is now somehow broken.

**How to Reproduce**
1. Click any AddOpeningHours quest icon.
2. Crash

**Versions affected**
Android version: 10
StreetComplete version: v32.1

**Log**
```
java.lang.NullPointerException
at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHoursForm.initStateFromTags(AddOpeningHoursForm.kt:98)
at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHoursForm.onViewCreated(AddOpeningHoursForm.kt:58)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7697)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Relevant code**
https://github.com/streetcomplete/StreetComplete/blob/3523fafa2b6789a1fe7e1799cd082caee652ec22/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHoursForm.kt#L97-L98

**Comment by westnordost** [comment] 2021-06-19 08:45
Can you say for which shop it crashes? Or does it crash for every shop?

**Comment by starsep** [comment] 2021-06-19 09:03
> Can you say for which shop it crashes? Or does it crash for every shop?

It crashes for every shop

**Comment by westnordost** [comment] 2021-06-19 11:53
Hm, whats missing is the map data from which the quest pins are generated... hm.

Do you remember when you downloaded the area in which the quests that cause a crash are situated?

**Comment by starsep** [comment] 2021-06-19 12:04
I don't remember when I downloaded the area.
I downloaded some new area just now and I cannot reproduce the crash there. 
It still crashes where I have downloaded data previously. I am not sure whether that's relevant but I tried multiple POIs spread throughout the city.

**Comment by westnordost** [comment] 2021-06-19 12:14
Yes, that's relevant. So the issue has likely  something to do with the cleaner: on app start, it deletes downloaded data that's older than two weeks. 

The quests should have been deleted too but apparently weren't. 

Odd things are:
1. Why was the map data not refreshed when you went to that area again?
2. How is it possible that the quests were not deleted too? Maybe a race condition of the cleaner vs. the downloader? 🤔

On June 19, 2021 2:04:13 PM GMT+02:00, Filip Czaplicki ***@***.***> wrote:
>I don't remember when I downloaded the area.
>I downloaded some new area just now and I cannot reproduce the crash
>there. 
>It still crashes where I have downloaded data previously. I am not sure
>whether that's relevant but I tried multiple POIs spread throughout the
>city.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/2979#issuecomment-864397373

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment] 2021-06-22 10:45
Hm, I checked this.
- on cleaning, the quests that refer to the old elements are also deleted
- execution order of deletion of old elements and inserting newly downloaded elements is serialized, i.e. no race condition should be possible

So right now, I am clueless how this could happen.

**Comment by westnordost** [comment] 2021-06-22 10:45
We'd need to monitor this, under which circumstances this could happen, maybe this will give us a clue.

**Comment by starsep** [comment] 2021-06-22 10:52
I will repeat steps which might have caused it in the evening:

0. Fetch quests for some area
1. Add opening hours for a POI in different OSM Editor.
2. Open StreetComplete
3. Choose opening hours quest for the same POI.

**Comment by mnalis** [comment] 2021-06-22 12:20
I've tried those steps on SC v32.1 on https://www.openstreetmap.org/node/5315076646/history and it seems to work normally. So there is probably some other factor involved too, so I tried to manually expire cache in the middle..

What I've noticed is that when I disabled Internet connectivity and did `Settings` / `Delete cache`, the quests did not disappear from map (even when scrolling around), but they were no longer clickable (in some other cases I've noticed them disappear from map, though). Then when I reenabled wifi, SC showed downloading icon (magnifying glass), but when I quickly disabled wifi again after a seconds (in the middle of download), icon remained animated for some seconds, and then disappeared (without displaying any error), and the quests become clickable again. 

I would have expected:
- when cache is deleted, all quests disappear immediately from map
- if area download loses internet connectivity in the middle, it fails with error and no quests are created/updated. Perhaps it might create some race condition if it doesn't? (pure guessing, I don't speak java/kotlin so can't follow the code)

**Comment by westnordost** [comment] 2021-06-22 12:54
Hm actually, if you press Settings -> delete cache, it does exactly the same thing as the cleaner does, only that it cleans everything older than "now".

**Comment by westnordost** [comment] 2021-06-22 12:55
> if area download loses internet connectivity in the middle, it fails with error and no quests are created/updated. Perhaps it might create some race condition if it doesn't? (pure guessing, I don't speak java/kotlin so can't follow the code)

Yes it should. I'd guess that the download was already complete and the app was currently processing the downloaded data.

**Comment by westnordost** [comment] 2021-06-22 14:12
@mnalis OK I found out why the quests are still being displayed after going back from the settings after deleting all the quests: They are not deleted yet. The operation is still being executed in the background. If you wait.... for a very long time (it was 70s for me), it will be updated. I found that deleting a large amount of map data is really slow. Deleting 10000 map data elements will trigger 10000 database queries (and more). I am currently working on making that 1 query, that should be faster than. But in any case, that is a separate issue.

**Comment by starsep** [comment] 2021-06-22 21:25
> I will repeat steps which might have caused it in the evening:
> 
>     1. Fetch quests for some area
> 
>     2. Add opening hours for a POI in different OSM Editor.
> 
>     3. Open StreetComplete
> 
>     4. Choose opening hours quest for the same POI.

I couldn't reproduce the crash this way. 

If delete cache is so slow maybe it's possible to kill the app when it's in progress?
I used "delete cache" some time ago.
Assuming those queries are not in one transaction (I haven't checked) - that could leave the app in broken state somehow?

**Comment by westnordost** [comment] 2021-06-22 22:00
Yes, they are not in one transaction. The deletion of the map data is in one transaction, but the subsequent update of quests (which leads to deletion of many quests) is in another. So if the app is killed in between that, than an inconsistent state is possible

**Comment by westnordost** [comment] 2021-06-23 09:04
But this is also something that cannot be changed. I'd say, in general, killing an app while it processes data can always lead to inconsistent data. Luckily here, the issue fixes itself, because if the app notices that the map data around your location is not downloaded (because it had been (incompletely) deleted before), it will download the data again.

So, right now and since I re-checked all the code paths plus added the performance improvement which reduces the time window in which such inconsistency can occur (if the app is killed in that window), I will just assume that the issue did stem from that and close the issue for now. We can continue to monitor it and reopen this issue if it happens again and we gain more information on it..

**Closed by westnordost** 2021-06-23 09:04 UTC
Labels: bug, feedback required

**Comment by peternewman** [comment] 2021-06-25 20:15
I don't know if this wants a new issue or is the same as this. On v32.2 I solved a road quest (possibly surface) and had the below:

> the quests did not disappear from map (even when scrolling around), but they were no longer clickable

It might have been picking up WiFi and expiring an old cache or something unrelated, I don't really know. I've now upgraded to the beta anyway, so will watch out for it again.

**Comment by starsep** [comment] 2021-07-16 16:57
I managed to get another crash in the same area, after cache clean app works fine.
Let me just leave logcat here, possibly useful if somebody will be able to reproduce

```
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2523)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2911)
        at android.content.res.Resources.getString(Resources.java:485)
        at de.westnordost.streetcomplete.quests.QuestUtilKt.getHtmlQuestTitle(QuestUtil.kt:27)
        at de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment.onViewCreated(AbstractQuestAnswerFragment.kt:157)
        at de.westnordost.streetcomplete.quests.wheelchair_access.WheelchairAccessAnswerForm.onViewCreated(WheelchairAccessAnswerForm.kt:16)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by westnordost** [comment] 2021-07-16 17:27
This is not related. What is your device language, @starsep ?

**Comment by starsep** [comment] 2021-07-16 18:37
> This is not related. What is your device language, @starsep ?

My languages are 1. English (Germany), 2. Polish, 3. Spanish

**Comment by westnordost** [comment] 2021-07-16 21:03
Hm, then I don't know... can you link the node with which this happened?

**Comment by starsep** [comment] 2021-07-16 21:10
It was this one https://www.openstreetmap.org/node/8359986392 (the same I linked in another issue)

**Comment by westnordost** [comment] 2021-07-17 16:36
Hm, can't reproduce that. The quest displays correctly on English and on Polish. If you next encounter this bug, please try:
1. does changing the language change anything? 
2. does re-downloading the area change anything?
