### ISSUE TITLE
[v32.0-alpha1] Quests downloading forever

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#2860] opened 2021-05-07 10:54 UTC
Hi,

I noticed a weird effect I haven't seen before with any SC version including the current alpha, and if there wasn't this alpha, I wouldn't have opened an issue for it. But I'm not sure that this effect wasn't introduced with the new quest fetching algorithm, indicating a serious bug, so I want to report this.

After having solved some quests and moved forward, new quests were fetched as usual. But this time SC didn't stop fetching quests! The icon at the bottom didn't vanish, there was constant mobile radio data traffic and during a few minutes SC has used up about 30 MB of data volume. (Normally it takes an hour to consume this amount of data volume with SC, in rural regions even more.) This all happened in a city not far from its centre and with very good 4G reception. In that state SC reacted very slowly: When I tapped on a quest icon it took some seconds until the quest dialog appeared and some more seconds before it disappeared again after I solved the quest.

So I did a test in order to check if SC was really downloading quests during this time or something different happened. I switched to OSMAnd, created and uploaded a new POI, switched back to SC and did nothing but watching the display. Less than one minute later a quest for this freshly created POI appeared. It looks like SC downloaded quests for the current region in an endless loop during this period.

Later I tried to download quests manually, but this didn't stop this behaviour. After I stopped SC completely via the Android app settings and restarted it, the quest download icon reappeared immediately but vanished some seconds later. From this moment everything was fine again.

(Of course I will report it here if this phenomenon will ever happen again.)

SC v32.0-alpha1, Android 9.

The cycling cat

**Comment by westnordost** [comment] 2021-05-07 12:51
Logs would be really helpful. Because otherwise I don't know where to start looking.

**Comment by cyclingcat** [comment] 2021-05-07 15:16
How can I provide you with such a log? Does SC write it somewhere into the Android filesystem? (I'm not an Android expert and my device is unrooted though...)

The cycling cat

**Comment by westnordost** [comment] 2021-05-07 15:51
You can use LogCatReader. However, you need to install at least `adb` on your computer and execute this command after install
```
adb shell "pm grant com.dp.logcatapp android.permission.READ_LOGS && am force-stop com.dp.logcatapp"
```

Maybe easier: Can you reproduce it at that location? I.e. if you start the app anew, clear the cache, trigger a download at that location, will it also run into that endless loop?

**Comment by cyclingcat** [comment] 2021-05-07 17:13
Ok, done. Installed Logcat Reader 1.7.2 from F-Droid, issued the adb command above, started Logcat Reader, saved a log into a .txt file (728 kB). However I cannot find the string "StreetComplete" in this file although the oldest entries are from 3 May 2001 (some crashes of another app). Does Logcat Reader has to be running in the background if the effect occurs in order to log something?

I'll go to the location soon again (probably next week) and try it there one more time.

The cycling cat

**Comment by westnordost** [comment] 2021-05-07 17:41
I think yes, I am not sure

**Comment by westnordost** [comment] 2021-05-07 17:41
You don't need to go there, you can trigger a download manually

**Comment by peternewman** [comment] 2021-05-08 02:09
Just for signposting, this is obviously **NOT** the same issue as #1821 but people might find one or the other depending on search terms hence this note.

**Comment by Helium314** [comment] 2021-05-08 06:30
I've had similar issues (not sure whether it was continuously downloading though), but couldn't reproduce it when I was actively trying to (with logging on).

@cyclingcat 
The reader should be running in background, only error messages are stored for longer time.
Log lines should look like `04-26 15:15:11.646 12261 13119 D OsmQuestController: AddPlaceName: Found 0 quests in 583ms`
You need to identify the process ID of StreetComplete, in this case 12261 (it changes after restart of SC). Simply searching for `StreetComplete` is not enough.

**Comment by cyclingcat** [comment] 2021-05-08 10:43
This morning, I tried to reproduce the phenomenon, but without luck: I deleted both the app cache in the Android settings and the quest cache in SC's settings, panned to the location where I observed the mentioned behaviour yesterday and triggered the download manually. The quests were loaded but this "endless loop" effect never occured. I did this several times, with different orders of above mentioned actions, with different map zoom levels. It always worked as it should.

So I will keep watching. As soon as this effect will occur again, I'll start Logcat Reader and keep it open for some minutes, then save the log.

The cycling cat

**Comment by westnordost** [comment] 2021-05-08 12:59
This issue is high priority and will block a beta release.

What I currently find likely is that some part of the download failed and cancelled the download as a whole. If the download as a whole is cancelled, it is not recorded that this bbox has already been downloaded. So the quest auto syncer (on getting a new GPS location, which happens every few secs) was then triggered again and again and again.
What **should** happen is:
- if an unexpected error (=likely a programming error) occurs during download, the user should be asked immediately or after next start of the app to send a crash report
- if an expected error (= connection issue, OSM API not responding etc.) occurs, a toast should be shown to the user that he should try again later. The quest auto syncer should not (immediately) try again but then again, if it is just a connection problem, there would not be any damage in it trying again

So I'll test if this really behaves the way as intended.

**But in any case, if anything unexpected occurs, there should also be a log and that would help very much.**

**Comment by westnordost** [comment] 2021-05-09 00:03
I found the following:
- if a f.e. connection error or any other error in downloading the tiles occurs, the app will just log that this and that tile could not be downloaded and otherwise there is no effect (as intended)
- if there is a runtime exception within the map tiles download (=programming error), the app will crash. This is not ideal, actually the download should be cancelled and the user should be asked to send an error report.

I'll look into the second point, but as this issue is concerned, the map tiles download doesn't look like it can be the cause.

Some more questions, @cyclingcat :
- Were you moving (fast) when you could reproduce this?
- Was the search quests icon stuck, or did it pop up, then pop out, then pop in again etc?
- Were you in a city, town, village or countryside?

**Comment by cyclingcat** [comment] 2021-05-09 07:27
> * Were you moving (fast) when you could reproduce this?

Definitely not fast. At most 5-10 km/h on my city bike rolling over a quite new parking area for mapping purposes, including a break when I noted some details on a piece of paper. As soon as I looked at the phone display again I noticed that the search quest icon was still (or again?) visible although it also was one or two minutes ago. This attracted my attention.

On my smartphone there is a small app that shows me the current upload/download speed on my home screen. The download figure was constantly above zero during this time. Most of the time it shows 0.0 KB/s, so this constant traffic was conspicious.

> * Was the search quests icon stuck, or did it pop up, then pop out, then pop in again etc?

I'm not sure. If there were breaks where the search quest icon wasn't visible, these must have been very short.

> * Were you in a city, town, village or countryside?

Inside a city, approx. 1 km from its centre. Nevertheless not too many quests on my display (but the house type/no. of storeys/roof type quests are currently deactivated).

Would it be an idea to implement some kind of very extensive logging of the tiles/quests download actions in the next alpha version into a file? This way I (and perhaps other alpha testers) could provide you with these files giving you the exact information you're interested in.

The cycling cat

**Comment by westnordost** [comment] 2021-05-09 20:17
Alright, there are a few things I changed now for alpha2:
- **an automatically triggered download will now not cancel any currently running download anymore**. Actually, it should not have before, because before automatically triggering a download, the `QuestAutoSyncer` would check if a download is currently running. But generally, if somehow a download is triggered (while a download is running), it would cancel the current one. A cancelled download will not record the downloaded area as "has already been downloaded". So theoretically, if the download is cancelled all the time just before it finished, it will never be recorded that any tile has already been downloaded. Not sure if this could ever happen, but maybe this whole bug is based on some weird race condition.
- A manually triggered download (from the menu) will cancel any currently running download. So no change here.
- The map data download and notes download are cancellable in-between downloading the data and persisting the data (+creating the quests etc). So, if a download is cancelled before the persisting starts to happen, also no quests will appear for the cancelled download. Before, basically a download could be cancelled in theory, but de-facto it still ran to completion minus the recording of the information that that area has already been downloaded.
- and what I mentioned: An exception thrown when downloading the background map tiles will not really affect the rest of the download, there will just be a log like "failed to download X tiles"

So, with this done, I will close this issue but feel free to post here again if you continue to see this issue with alpha2 or later.

**Closed by westnordost** 2021-05-09 20:17 UTC
Labels: bug
