### ISSUE TITLE
broken display od Polish diacritics 

### ISSUE THREAD

**Issue by vvizzo** [streetcomplete/StreetComplete#5061] opened 2023-06-10 13:27 UTC
**How to Reproduce**

Zoom to view street name with Polish diacritics, wg. Świdwrska street in Warsaw Poland. 
**Expected Behavior**

Expected view is ' above capital S at the beginning (first letter).
What I see is ' somewhere above w (second letter).

**Versions affected**

SC 53.1
A 13

**Comment by vvizzo** [comment] 2023-06-10 13:28
![Screenshot_2023-06-10-15-14-36-81_8a0120479a21d3140f77758520f645bd](https://github.com/streetcomplete/StreetComplete/assets/13252983/452bcfd2-bff6-446e-818a-649bdeccdad8)

**Comment by westnordost** [comment] 2023-06-10 14:07
Duplicate of  #5006 / #4554

**Closed by westnordost** 2023-06-10 14:07 UTC
Labels: bug
