### ISSUE TITLE
[Bug] open-ended opening_hours include closing time

### ISSUE THREAD

**Issue by wielandb** [streetcomplete/StreetComplete#2957] opened 2021-06-12 16:12 UTC
**Expected behaviour:** Checking "open ended" on the closing time screen on the opening hours dialogue should eliminate the time value selected on the screen. 

Entering "Open from 17 to open ended" should result in '17:00+'

**Actual behaviour:** The Value on the second screen is used nevertheless and a + is appended. Leaving the default values the result looks something like '17:00-18:00+' 

I want to add that technically writing the OHs like this is acceptable for stating "minimum opening hours", but as the changelogs seem to state no change in the quest, I suspect that this was not intended.

**Versions affected**

I am on SC v32.1, Android Version 9
(iirc, the intended behaviour did happen up until v30.x)

**Comment by mnalis** [comment] 2021-06-12 23:44
If you set both closing time and opening time to same value (eg. `17:00`), then you'll get old behaviour (`17:00+`).
(I don't know if it was intended / documented in changelog, though)

**Comment by westnordost** [comment] 2021-06-13 08:27
It is intended. As you say, it is acceptable and it also makes sense. For example, a bar that would close at 11:00 PM or after the last customer left, whatever comes last.

Also, this has been the behavior since forever, so no wonder why you don't find anything about it in the changelog.

**Comment by westnordost** [comment] 2021-06-13 08:27
Closed as "working as intended"

**Closed by westnordost** 2021-06-13 08:27 UTC
Labels: bug
