### ISSUE TITLE
Flickering quests & names

### ISSUE THREAD

**Issue by thany** [streetcomplete/StreetComplete#4598] opened 2022-11-02 10:59 UTC
Quest pointers, street names, waterway names and such may flicker while panning the map.

**How to Reproduce**
Go to any location with a reasonably dense number of quests and streets (with names).
Pan the map around.

Example:
![Screenshot_20221102-115523_Street­Complete](https://user-images.githubusercontent.com/152227/199472624-a2aa25a0-a72f-4a0e-9c56-503db4382f2e.png)

This is in Den Bosch, The Netherlands. I don't believe it matters much where exactly you go, as long as the map is "full enough".

**Expected Behavior**
No flickering of anything.

**Versions affected**

Android 10 (lineage_starlte-userdebug 10 QQ3A.200805.001 6fb7acd20c)
StreetComplete 48.0

**Comment by westnordost** [comment] 2022-11-02 11:10
Ehm, are you trying to show flickering by posting a screenshot? How would that work?

Anyway, can you please try if you can reproduce this with an earlier version? Start with v44 https://github.com/streetcomplete/StreetComplete/releases/tag/v44.1 and test your way up. Right now, the only suspect I do have would be overlays, which got introduced in v45.

**Comment by mnalis** [comment] 2022-11-02 12:17
(possibly related: https://github.com/streetcomplete/StreetComplete/issues/4556 but that one was reported as fixed in `48.0`. Maybe the problem is intermittent it so sometimes shows, and sometimes doesn't?)

**Comment by thany** [comment] 2022-11-11 11:57
That initial uninstall will throw away my data, right? I'd rather not.

As for the screenshot, that just to indicate where it is. I don't know how to link to a location from the app, and I don't think it's possible to record a screensahre on my device. So this is the best I got.

But are you saying you can't reproduce this flickering?

**Comment by matkoniecz** [comment] 2022-11-11 12:24
> That initial uninstall will throw away my data, right? I'd rather not.

Lost by reinstall/uninstall, not shared between devices:

* answers that are not yet uploaded (if any are not yet uploaded then it will be mentioned on the profile screen)
* list of ignored quests
* presets (can be shared using new QR code functionality)

Not lost and shared between devices:

* uploaded answers (stored in OpenStreetMap database)
* star count and statistics and achievements (that is only cached locally - on logging in on different phone StreetComplete statistics server will give answer based on public list of edits, it may be delayed - right now you may want about month due to https://github.com/streetcomplete/StreetComplete/issues/4625 )

**Comment by FloEdelmann** [comment] 2022-11-11 12:52
Other things that are not shared between devices: settings like language, theme, resurvey interval; recent answers in building type and fire hydrant diameter quests.

Note to @matkoniecz: I edited your comment to wrap the link in `<…>`, so GitHub recognizes that the trailing `?` still belongs to the URL; otherwise the link does not work.

**Comment by westnordost** [comment] 2022-12-03 00:24
Probably caused by this
https://github.com/streetcomplete/streetcomplete-mapstyle/issues/136

**Comment by Helium314** [comment] 2022-12-19 13:33
@thany Does this still happen in SC 50.0?

**Comment by thany** [comment] 2022-12-19 20:24
It seems to have been resolved. Cheers! 👍🏻

**Closed** 2022-12-19 20:52 UTC
Labels: bug, feedback required
