### ISSUE TITLE
Quest answers sometimes don't get uploaded automatically

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3494] opened 2021-11-08 13:45 UTC
Hi there,

every now and then my answers don't seem to get uploaded immediately, although autoupload is enabled in the settings. In these cases, the SC "My profile" screen looks like this:

![Upload](https://user-images.githubusercontent.com/32601012/140748577-634cedcd-15aa-4924-8902-170be7245207.png)

What does this message marked in the screenshot above exactly mean? Under which exact circumstances does it occur? Should it only happen if the upload fails (due to bad internet connection or a slow OSM server) or are other reasons possible? At least during the latest two occurences my internet connection was definitely excellent (WiFi at my home, full scale 4G in the city centre), so the OSM server itself the answers get uploaded to could have been the culprit here.

But whatever reason, the way SC handles this situation could be improved. If I spot the above mentioned message, my quests never get uploaded again, no matter what I try inside of SC. The only procedure that has reliably worked so far:

- Remove SC from the "recently used app screen" **(obviously this is the important step, I have never succeeded in uploading the pending quests without it!)**.
- Restart SC.
- Go to the "My profile" screen. The message "plus xxx not yet published changes" still appears.
- Close the "My profile" screen via the standard Android "Back" button.

Now the answers get uploaded innediately and the message is gone after the upload is finished; however, this aforementioned procedure can be only considered as a workaround IMHO. As the frequency of these occurances significantly increased during the past weeks (although I slowed down my SC activities a little bit), maybe some recent changes in the SC code could be involved?

SC 37.0 on a Cubot Quest, Android 9.

The cycling cat

**Comment by matkoniecz** [comment] 2021-11-08 13:50
> What does this message marked in the screenshot above exactly mean? 

That some changes are not uploaded and are stored at your phone.

> Should it only happen if the upload fails (due to bad internet connection or a slow OSM server) or are other reasons possible? 
In this case or if user enabled "upload at wifi only" or "manual upload"

> The only procedure that has reliably worked so far:

I also switched to manual upload, trigger upload and switched back.

> Under which exact circumstances does it occur? 

I also run into this bug but never managed to reproduce anything.

**Comment by matkoniecz** [comment] 2021-11-08 13:57
I also encountered case where downloading quests was not triggered, despite connection and being far away from any existing quests. But never progressed with investigating what is going on.

**Comment by peternewman** [comment] 2021-11-08 14:01
> I also switched to manual upload, trigger upload and switched back to fix it.

I was going to say does pressing the upload button work to force it, but I see it's only visible on manual and only on Wi-Fi options. Does just switching to only on Wi-Fi and pressing it do the trick?

**Comment by matkoniecz** [comment] 2021-11-08 14:08
> Does just switching to only on Wi-Fi and pressing it do the trick?

Yes. Though when I tried I was not on Wi-Fi, so not sure would it fix also in such case.

**Comment by biketeur** [comment] 2021-11-09 00:16
Ich habe diesbzgl. folgende Erfahrung gemacht:
Upload ist bei mir auf "an", d.h. Daten dürfen per WLAN und/oder Funk hochgeladen werden. SC scheint WLAN zu bevorzugen (was ich auch für sinnvoll halte). Ab und zu verbindet sich mein Smartphone mit einem WLAN, welches ich in der Vergangenheit benutzt habe, welches aber noch eine zusätzliche Bestätigung verlangt. Diese ploppt aber nicht auf (ob das an Android oder SC liegt, weiß ich nicht). Dies bedeutet, dass ich zwar physikalisch mit einem WLAN verbunden bin, meine Daten jedoch nicht weitergeleitet werden. Abhilfe: WLAN ausschalten, dann werden die Daten sofort übertragen.
biketeur

**Comment by mnalis** [comment] 2021-11-09 01:55
- possibly related: https://github.com/streetcomplete/StreetComplete/issues/2947

**Comment by westnordost** [comment] 2021-11-09 18:39
Yeah, not really a but IMO.

If the upload fails for some reason, it is cancelled. This can be not only due to a bad connection. There could be a temporary problem at the server side or whatever. StreetComplete does not retry uploading automatically. It will retry uploading the next time you solve a quest.

**Comment by westnordost** [comment] 2021-11-11 14:13
So on the basis of my last comment, I'll close this as not-a-bug/will-not-fix

**Comment by cyclingcat** [comment] 2021-11-11 17:53
Hm... are you sure it works this way? At least myself, I have **never** seen this state vanishing by itself. Quite the opposite: Once the app reached this state, the number of untransferred answers increased steadily with each solved quest until I stopped the app (haven't tried @matkoniecz's workaround so far though). And after a restart all answers were **always** uploaded, one after the other. Too many coincidences IMHO.

So I still suspect that there are circumstances where solving one more quest does **not** trigger the upload of all pending quests.

The cycling cat

**Comment by westnordost** [comment] 2021-11-11 17:54
Well, then I need logs.

**Comment by cyclingcat** [comment] 2021-11-14 15:14
Will try to post a log as soon as this behaviour appears again. (Today it didn't.)

The cycling cat

**Comment by cyclingcat** [comment] 2021-12-25 16:42
Hi there,

finally this issue happened again and I succeeded in creating a log! After some dozens of solved and successfully autouploaded quests the upload suddenly stopped working! I started Logcat Reader, solved one more quest and the "not yet published changes" counter incremented, thus no uploading happened on the next solve. (Excellent 4G connectivity inside the city centre.)

Back at home and connected to my WiFi, I solved another quest and the same happened: Both the quest counter and the "not yet published changes" counter incremented, but no upload happened. In order to rule out an OSM server problem I solved a quest from a different device, the upload worked immediately from this one

One more observation: In this state SC hasn't download any new quests automatically while I was moving forward! I had to load the quests manually. (Don't know if this behaviour is connected to this issue though.)

The log file is quite big (14 MB) and I don't want to disclose it publicly as it includes geocoordinates next to my home, so my paranoid self prefers to send it to @westnordost via e-mail.

Cubot Quest with Android 9. I will leave this phone in the current state, feel free to make me test something. I'm pretty sure that the upload will start working again once I have removed SC from the recent app list and reopened it but I will refrain from this until you tell me to do so.

The cycling cat

**Comment by matkoniecz** [comment] 2021-12-25 17:17
> prefers to send it 

Have you found the email or do you need it?

**Comment by cyclingcat** [comment] 2021-12-25 17:29
Yes, I sent the log some minutes ago.

The cycling cat

**Comment by westnordost** [comment] 2021-12-26 10:56
Where die you send it to? I'm still on christmas holidays so I won't be able to look at it before the 27th and thus not be able to give you any feedback on what you could try to do. 

On 25 December 2021 18:30:08 CET, cyclingcat ***@***.***> wrote:
>Yes, I sent the log some minutes ago.
>
>The cycling cat
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3494#issuecomment-1001049028
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cyclingcat** [comment] 2021-12-26 14:46
To osm@westnordost.de, yesterday, 18:21 MEZ.

Unfortunately, SC is no longer in this state on my Cubot phone. When I brought SC to the foreground today, SC seems to have restarted. And a complete restart has solved this problem each time so far, also this time :-/  (I suspect some aggressive energy saving mechanism here which killed the app after some time without actively using it.)

I will keep watching the "not yet published changes" counter and am quite optimistic that the issue will reappear sooner or later. Enjoy your holidays :+1: 

The cycling cat

**Comment by westnordost** [comment] 2021-12-27 15:06
I think I found something. ´QuestAutoSyncer` is a singleton but is bound functionally to the lifecycle of the `MainActivity`. In particular, if the `MainActivity` gets destroyed and later created again within the frame of the application's lifetime, it looks like the `QuestAutoSyncer` currently stays "dead", i.e. does not re-register itself to listen to changes in position, login-status etc.

This doesn't explain why the upload button did not work, but one issue at a time.

**Closed** 2021-12-27 15:07 UTC
Labels: bug, feedback required
