### ISSUE TITLE
Maintenance quest: Are collection times of this postbox still correct?

### ISSUE THREAD

**Issue by lightonflux** [streetcomplete/StreetComplete#2491] opened 2021-01-11 15:30 UTC
### General
Affected tag(s) to be modified/added: [post_box](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box)
Question asked: **Have the collection times of this post box changed?**

Some time ago the quest for adding collection times [was added](https://github.com/streetcomplete/StreetComplete/issues/85). Not so long ago the maintenance quest "does this post box still exist" was added. 

The problem is that if the existence quest is answered which adds/updates the check_date tag. This might confuse some other mappers if they don't check the change message. They might think that all tags were checked, not just the existence of the POI.

Because we already have the quest for collection times, we should add another check if they are still valid, directly after the existence was reconfirmed by the SC user.

The quest should have the same geo limitations as the initial quest for collection times.

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

Edit: This quest should probably be triggered more often than the existence quest. Maybe every 2 years or even yearly.

**Comment by westnordost** [comment] 2021-01-11 17:38
The issue is known. As far as I understand your description, this ticket is a duplicate of #2368

The current workaround is:
- ask post box existence only every 4 years
- ask collection times every 2 years
- collection times quest has a higher priority than the existence quest

So, after a post box has been modified, nothing happens for 2 years, then for 2 years, only the collection times quest is shown, and after another 2 years also the existence quest is shown - however, at a lower priority which is why the collection times quest is still shown first.

**Closed by westnordost** 2021-01-11 17:38 UTC

**Comment by lightonflux** [comment] 2021-01-11 20:12
Ah, i guess i messed that up by changing the order of quests in the settings.
