### ISSUE TITLE
A quest similar to `building:levels` for `building:part`

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#6017] opened 2024-11-19 15:11 UTC
As a first note, I am referring to the `building:levels` quest, which is disabled by default: this whole suggestion is thus low priority.

### General
As far as I understand, the quest for `building:levels` doesn't currently consider building parts. It does state that if a building is composed of several parts, then only the highest part should count.
The practice in my area however is to leave a not asking for such buildings to be separated when this appears (e.g. https://www.openstreetmap.org/note/2890008 ). Splitting the building is easy on a desktop, but knowing the size of each building part has to be checked in-place: this is typically where StreetComplete could help.
This leads to building parts such as this one: https://www.openstreetmap.org/way/1335022784 The purpose of this building part was to emphase that the building has very different parts with different geometry (and thus it is meant to serve as a support for the `building:levels` key), but it is currently lacking any `building:levels` key as it has yet to be surveyed.

The idea here would be to have a quest very similar to the one about `building:levels` on buildings, but on building parts. It would probably be disabled by default.

I think that this is an important information for two reasons:
- First, having the heights of different building parts right can really help understanding a map like F4map. In the example above ( https://www.openstreetmap.org/way/1335022784 ), the building is quite wide, but only half of it is tall: representing it shoebox-style can hinder people to recognise the area well.
- When discussing with researchers interested about spatial representation of a city, a subject that comes frequently is the question of whether a given point is in a building's shadow. This helps understanding the value of a sensor, or where to place benches in an areas. For this, a (relatively) precise model of complex buildings can really help.

Affected tag(s) to be modified/added: [`building:levels`](https://wiki.openstreetmap.org/wiki/Key:building:levels) on [`building:part=*`](https://wiki.openstreetmap.org/wiki/Key:building:part)
Question asked: **Is there an example tag on item XY?**
Here is an example where this separation has been done, and where it (I think) adds a lot of information: https://www.openstreetmap.org/way/1329605361

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [X] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
  The four items above would basically be the same for `building:levels`.

- [ ] 🕓 Applies to a reasonable number of map data (Worth the effort)

The last item can be debated. TagInfo states that there exists more than 3 millions `building:part` in the database (compared to more than 600 millions buildings). I would say that as it becomes usual for users around me to leave notes asking to add building parts to already mapped building because the buildings differ a lot in height, this would be useful.

Furthermore, this quest would be very similar to an already existing one (about `building:levels` within `building=*`), so I suppose that this quest wouldn't require a large effort (I may be very wrong on this: do correct me).

Alternatively, it can be implemented by changing the applicability of the current `building:levels` quest to also search for `building:part` (with some UI tweaks to make it clear that we are dealing with a building part).

**Comment by mnalis** [comment] 2024-11-19 19:20
Interestingly, quest code does seem to change the title depending if it is handling `building:part`:

https://github.com/streetcomplete/StreetComplete/blob/9df8b0972aa500b998b3390a55adfbe06613b500/app/src/main/java/de/westnordost/streetcomplete/quests/building_levels/AddBuildingLevels.kt#L32-L34

That `quest_buildingLevels_title_buildingPart2` string _"How many levels above the basement does this building part have?"_ is even translated in other languages!

But the `elementFilter` does **not** seem to include `building:part`, but only `building`. 
I do not know if that is  a remnant of previous feature, or if it was perhaps intended but never fully implemented.

**Comment by mnalis** [comment] 2024-11-19 20:55
> The quest initially included building:part but it was later removed (see https://github.com/streetcomplete/StreetComplete/issues/79 / https://github.com/streetcomplete/StreetComplete/commit/e4897e9bfd46801ebae6ba080974ff857bc647cb).

Thanks for that research @riQQ (and for all the other triage / research / etc. work!) 
So yeah, it would likely be too complex / confusing for average user.  

I hope I'm not overstepping if I thus also close this one as a `wontfix`.

---

As a workaround, if @Mbodin cares a lot about that type of data and is not being confused by such building parts and is willing to try it, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) does allow setting custom per-quest `elementSelection`  so they can change that particular quest  to _also_ ask for `building:part`s levels. 
_(By default, SCEE looks pretty much like regular StreetComplete, until one starts enabling extra features in settings - like `Expert mode` needed for editing quest `elementSelection` filters)._

**Closed by mnalis** 2024-11-19 20:55 UTC

**Comment by riQQ** [comment] 2024-11-19 21:13
Duplicate of #985
