### ISSUE TITLE
Highlighted elements sometimes do not disappear

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3745] opened 2022-02-10 15:47 UTC
When I tap a quest and quickly press back (e.g. because I tapped the wrong quest), the highlighted geometry sometimes does not disapear until opening/closing another quest.
A slow phone or high load from background tasks makes it easier to reproduce.

My guess is that the highlighted geometry is deleted when the quest form is closed, but sometimes finding the geometry takes longer than the quest form is open.

**Comment by matkoniecz** [comment] 2022-02-13 09:57
I was able to reproduce it by clicking on quest as scanning for quests was running, but have not tried investigating.

**Comment by westnordost** [comment] 2022-02-16 19:17
You mean the highlighted geometry of surrounding elements right?

**Comment by matkoniecz** [comment] 2022-02-16 19:23
Yes, in my case icons of nearby bicycle parkings were stuck for some time (or until some action). I guess I can capture video if it would be useful.

**Comment by westnordost** [comment] 2022-02-28 16:27
The culprit is in `MainFragment::showHighlightedElements` - getting the elements to display from db and then displaying them is done asynchronously (`viewLifecycleScope.launch`). When exiting the quest form, the highlighted elements are cleared. But exiting the form may happen before the async operation mentioned above finishes.

What would need to be done to fix this issue would be to memorize the `Job` object returned by `launch` and `cancel()` it wherever the highlighted elements are cleared.

I've looked at the code and it is a bit too interwoven to be simple to fix, I do not think a fix is worth the implementation / refactor effort considering its very low severity.

**Comment by Helium314** [comment] 2022-03-01 11:56
I guess the bug is rare and negligible enough to justify this decision. Should the issue remain open?

**Comment by westnordost** [comment] 2022-03-01 12:04
I didn't immediately close it because I thought maybe someone would like to have a look at that despite that. I'll close it now then.

**Closed by westnordost** 2022-03-01 12:04 UTC
Labels: bug
