### ISSUE TITLE
No -1 in the world after log-in

### ISSUE THREAD

**Issue by DoggoOfSpeed** [streetcomplete/StreetComplete#5141] opened 2023-07-14 14:16 UTC
![image](https://github.com/streetcomplete/StreetComplete/assets/28051112/71764dfc-c955-4145-a789-e0e3c8a607d3)

I changed the username, password and email address of my osm account and after logging in with the new info the app claims that I'm number -1 in the world (which is a pretty bad place to be imo)

**How to Reproduce**
Change your OSM profile so that you have to renew your StreetComplete log-in.

Log-in to street complete

**Expected Behavior**
I am placed where I should be

**Versions affected**
53.2

**Comment by westnordost** [comment] 2023-07-14 15:43
Well, you are even in front of the first guy, you are so lucky! ;-)

**Comment by westnordost** [comment] 2023-07-14 15:50
What is your OSM username?

**Comment by westnordost** [comment] 2023-07-14 15:55
> How to Reproduce
> Change your OSM profile so that you have to renew your StreetComplete log-in.
> Log-in to street complete

Cannot reproduce.

**Comment by DoggoOfSpeed** [comment] 2023-07-14 16:22
Hmm... After some time it has gone normal. Should I close the issue?

**Comment by westnordost** [comment] 2023-07-14 16:26
So, the rank can be `-1` if not determined yet (server-side) and also not set yet locally. And this rank is unconditionally written into the text field.

However, the item is made invisible if the `rank <= 0`. So, I have no idea how this is possible. Maybe something to do with animations (being off on your device?), but I just checked that too, still not reproducible. 

So at the moment I just assume it is some bug in the Android API on the distribution used on your particular device 🤷 and I do not really want to implement workarounds for such assumptions, so I'd indeed close this. If this happens for other people too, it could be revisited.

For reference, what's your Android version and device name?

**Closed by westnordost** 2023-07-14 16:26 UTC
Labels: feedback required

**Comment by DoggoOfSpeed** [comment] 2023-07-15 11:23
> For the record, what's your Android version and device name?

Android 11, Samsung Galaxy S4 and my OSM nickname is leekleak (also, sorry for the late reply 😓)
