### ISSUE TITLE
New Quest "When is the defibrillator accessible?"

### ISSUE THREAD

**Issue by Timonade** [streetcomplete/StreetComplete#4835] opened 2023-02-21 18:31 UTC
### General
Affected tag(s) to be modified/added: [`opening_hours=*`](https://wiki.openstreetmap.org/wiki/Key:opening_hours) for [`emergency=defibrillator`](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddefibrillator)
Question asked: **When is the defibrillator accessible?**

I think it is important that [`opening_hours`](https://wiki.openstreetmap.org/wiki/Key:opening_hours) should be registered at each defibrillator to see when it is accessible.

### Checklist
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** `nodes with
         emergency = defibrillator
         and !opening_hours`

**Metadata needed:** None

**Proposed UI:** Unfortunately I have no idea how the selection menu could look like.

**Comment by rhhsm** [comment] 2023-02-22 07:18
This is a potentially life-saving application of SC that I would be happy to contribute to! I think it should be one of several quests to be developed for this, together with quests for its location (indoor or not, description of location). I'm not good at analysing the statistics for the use of this tag, but it seems that they are about equally located indoor and outdoor. Should we first ask for indoor/outdoor location, and then assume that those outdoor are accessible 24/7, or should we first ask if it is accessible 24/7, and if not, what the opening hours of its location are?

**Comment by matkoniecz** [comment] 2023-02-22 07:24
See also https://github.com/streetcomplete/StreetComplete/issues/1756 - have not reread discussion there (if anyone will do this: please post summary here)

**Comment by matkoniecz** [comment] 2023-02-22 07:25
There was https://github.com/streetcomplete/StreetComplete/pull/2066 - maybe it was reverted for some reason? If yes, which one?

**Comment by matkoniecz** [comment] 2023-02-22 07:28
See https://github.com/streetcomplete/StreetComplete/commit/677ac5ae60452f248d8a88c448a4e7202ed6abf1 and https://github.com/streetcomplete/StreetComplete/issues/2135

Are issues raised there fixable?

**Comment by Timonade** [comment] 2023-02-22 12:00
But you also have to keep in mind that there are defibrillators that are outside but only available at certain times, e.g. on company premises.

**Comment by westnordost** [comment] 2023-02-24 14:39
That does not make sense. Neither does it have to be publicly known when the gates of company premises close, nor is it really relevant if in some office building there is a defi when nobody is there anymore.

As for the general idea, it is a duplicate of #1756 as @matkoniecz pointed out.

**Closed by westnordost** 2023-02-24 14:39 UTC
Labels: feedback required
