### ISSUE TITLE
Improve UX of street lighting overlay (direct display of options instead of "select" button)

### ISSUE THREAD

**Issue by FieteO** [streetcomplete/StreetComplete#5539] opened 2024-03-15 13:18 UTC
**Use case**

When answering the street lighting quest, there is currently one dropdown with a proposed lighting type.
If the currently selected answer is not the right one, two clicks are necessary to change it before clicking okay.
![Screenshot_20240315-131134_Street­Complete](https://github.com/streetcomplete/StreetComplete/assets/41323592/f88ddcc2-08be-40e9-a1a1-4b0f21122f94)

**Proposed Solution**

The dropdown could be replaced with the four buttons being directly layed out from left to right (similar to the house level/roof combinations in the house level quest).
That way, answering would be much easier

**Comment by matkoniecz** [comment] 2024-03-15 13:36
See also  #5020 #4622

And #4741

**Comment by FieteO** [comment] 2024-03-15 15:48
I did do a brief search for street lighting and didn't find anything. Shall I close this issue?

**Comment by westnordost** [comment] 2024-03-15 19:54
Yes, it should be closed as duplicate. Thanks for triage @matkoniecz , it is fine to close duplicates.

Note that you have the button to the lower left which lets you select the last answer you provided.

**Closed by westnordost** 2024-03-15 19:54 UTC
Labels: usability

**Comment by rhhsm** [comment] 2024-03-16 20:18
#4622 was closed because "This is the default interface for overlays and I want to keep it that way for consistency." However now we have a row of 6 option buttons below the "select" button in the building overlay. If the building overlay interface is also used for the lighting overlay, it would only show 4 buttons because there are only 4 answer options. For consistency the "select" button could still be shown but it won't be needed any more :)

**Comment by matkoniecz** [comment] 2024-04-29 10:09
Hard to say for me. But if issue is created and it requests the same as already closed issue - then it should link to each of them and explain why it is not duplicate of each.
