### ISSUE TITLE
Reversed movement indicator (opening in the opposite direction)

### ISSUE THREAD

**Issue by sjvudp** [streetcomplete/StreetComplete#6011] opened 2024-11-16 00:37 UTC
If I understand things right, and also remember things right, the sector-shaped blue movement indicator "opened" in the direction of movement.
Today however, the direction was reversed over a longer time, while the absolute position was updated correctly.
This happened while riding a bus within a town, so movements should have been "significant enough" to know the direction of movement.

![Screenshot_2024-11-15-](https://github.com/user-attachments/assets/e2f9dc58-65b7-4bd6-ab13-d79076c29597)

**How to Reproduce**

Don't know, just activated GPS, started the app, and watched for quests to appear.
Only experienced once so far.

**Expected Behavior**

Movement indicator should point in the correct direction when moving significantly.

**Versions affected**

Android 13 (ColorOS 13.1 on CPH2371) using SC v59.3

**Comment by mnalis** [comment] 2024-11-16 01:38
> If I understand things right, and also remember things right, the sector-shaped blue movement indicator "opened" in the direction of movement.

Um, I don't think so. IIRC that blue sector shape should be pointing in **your viewing direction**, not in the **direction of movement**.
What you might be remembering is that whole map orients so _"moving forward is moving towards the top of the phone screen"_ which is active in that particular _"arrow icon"_ tracking mode at the bottom-right (and which seems to be correct in your picture, as dotted trail is towards bottom of the screen, thus your direction of movement ***is*** towards the "top" of the screen)

In other words, even if you're standing perfectly still at exactly the same place, and just rotate your body to move your phone from left to right, that blue **sector-shaped viewing direction indicator** should be rotating too.

Why it points "backward" has several possible reasons:
- you were sitting in the bus in the backwards seat (i.e. looking towards the end of the bus and not towards the front), so it is pointing just as it should
- your sensor might need recalibration (sometimes phone warns about it, sometimes not) -- it is famous _"wave your phone in figure-of-8 motion"_ (which makes people look at you like you've gone crazy :smile_cat: )
- there is magnetic interference (especially happens in some places of some trains/buses) which prevents the sensors (which are in part requiring sensing magnetic north) from working correctly (no reliable workaround for that one, except perhaps changing your location in the vehicle).

**Comment by matkoniecz** [comment] 2024-11-16 03:11
please comment if "your viewing direction, not in the direction of movement" does not explain situation

> This happened while riding a bus within a town

makes it quite likely

**Closed by matkoniecz** 2024-11-16 03:11 UTC
Labels: bug

**Comment by sjvudp** [comment] 2024-11-16 22:35
> Why it points "backward" has several possible reasons:
> 
>     * you were sitting in the bus in the backwards seat (i.e. looking towards the end of the bus and not towards the front), so it is pointing just as it should

No, I was sitting looking forward, the phone being "top forward" orientation.

> 
>     * your sensor might need recalibration (sometimes phone warns about it, sometimes not) -- it is famous _"wave your phone in figure-of-8 motion"_ (which makes people look at you like you've gone crazy 😸 )

Actually I did a test: Opened a compass app, and north looked roughly OK. Then I turned the phone quickly, and north was about 90° off. The I turned the phone rapidly again, and north was almost opposite direction.
So I recalibrated the compass. After that I cross-checked in SC, and things looked normal then (not moving this time, because I was inside the house).

>     * there is magnetic interference (especially happens in some places of some trains/buses) which prevents the sensors (which are in part requiring sensing magnetic north) from working correctly (no reliable workaround for that one, except perhaps changing your location in the vehicle).

Interesting question (I always wondered about that): My cover has a magnet to keep the top lid closed, and I always had wondered how much that magnet would interfere with the compass of the phone...

**Comment by matkoniecz** [comment] 2024-11-17 09:30
> After that I cross-checked in SC, and things looked normal then

oh, so still not a bug

nice that it got fixed for you!
