### ISSUE TITLE
Quest: service times for places of worship

### ISSUE THREAD

**Issue by krzyk** [streetcomplete/StreetComplete#232] opened 2017-05-13 20:20 UTC
This is very similar to post box collection times (#85) and opening hours.
Churches (and I assume other places of worship) can have [service_times](http://wiki.openstreetmap.org/wiki/Key:service_times) that specifies what time a mass takes place.
This is visible when one is near given place (service times are usually shown somewhere near).

**Comment by westnordost** [comment] 2017-05-13 22:03
The app should show as few false positives (=unanswerable quests) as possible. I fear that not the vast majority (and probably not even a simple majority) of all places of worship have some publicly available service time table next to the door.

**Comment by Etua** [comment] 2017-05-13 23:15
@westnordost How did you make such estimate? I know that it may be a matter of country but virtually every place of worship in Poland has such timetable available outside of the building.

**Comment by westnordost** [comment] 2017-05-13 23:23
From travelling the world.

Even in developed countries, I would expect churches on the countryside not to have timetables because they are only used by locals who know the times.

**Comment by Etua** [comment] 2017-05-13 23:58
@westnordost Still I don't know how such lack can create false positives. If data is present the quest can be resolved, in other case simply rejected. I don't think the surveyor would make a random guess in any case.

**Comment by westnordost** [comment] 2017-05-14 00:53
That is not what I mean with false positives. With false positives, I mean in the broadest sense quests that the user cannot answer. As far as I see, the "service_times" tag does not allow a value like "irregular/unknown/not applicable".

**Comment by krzyk** [comment] 2017-05-14 06:24
But same applies to opening hours, in developed countries cities you will have those and in non-developed or rural places not necessarily. And that's why even now there is an option to specify when given place is open using simple text (a comment in http://wiki.openstreetmap.org/wiki/Key:opening_hours#Syntax), service_times has same syntax so one could answer it the same way.

It could also be limited to "religion: christian", because I don't know if others have regular religious activities.

**Comment by matkoniecz** [comment] 2017-05-14 13:23
From my experience in Poland catholic churches always have schedule posted somewhere, almost always at the church location.

**Comment by Jotam** [comment] 2017-05-25 22:04
Many churches in the UK and in Germany will have their service hours displayed publicly outside their buildings. They want people to come and attend, after all. :-)
**Therefore, I strongly support this request for service times quests.**

**Comment by westnordost** [comment] 2017-05-29 20:18
Guys, for these proposals, you must think globally, because these quests will be shown globally. Only because it is the case in your town or (you assume) it is the case in your country, you cannot assume that the quest will make sense everywhere.

@Jotam claims many churches in Germany have service time quests. So I went to a church and checked. This is how the service time table looks:
![dsc_0099](https://cloud.githubusercontent.com/assets/4661658/26561094/ccf090e6-44bb-11e7-94e9-cda57228ea4c.JPG)

It is more like an event calendar. To have service times as a quest is out of question if the above picture is not a gross exception to the norm. And I went by a couple of other churches, they all had this event calendar.

What we _can_ talk about is to include christian churches in the opening hours quest. At least for this, every church I went by had opening hours posted. I don't know about other religions and other places & countries though.

**Comment by krzyk** [comment] 2017-05-29 20:24
Opening hours is tricky, because most of the christian churches I've seen in Poland don't have those clearly posted in front.

**Comment by krzyk** [comment] 2017-05-29 20:31
So this quest looks more like a country specific, or if we are talking only about christian churches maybe you could consider just the Mass on Sundays.
This has much smaller amount of exceptions, from your picture I can see that those are at 9:00, 10:30 and 18:00.
That would be a start and if we would get some more input from others we could extend it to other religions/days.

**Comment by matkoniecz** [comment] 2017-05-30 07:17
And I am fully aware that what is true in my region may be untrue in other - it was intended solely as small piece of data (that is why I explicitly mentioned that I know that it is true for Catholic churches in my country).

**Comment by Etua** [comment] 2017-05-30 09:11
@krzyk I think that because how the specification for opening hours is made in OSM, writing opening hours just for sundays would suggest that it is the only day during which the church us open.

**Comment by Jotam** [comment] 2017-06-07 22:59
@westnordost: I think your example is indeed a gross exception to the norm. What's in your picture is a specific event calendar for pentecost festivities. But apart from the big holidays, almost every church will have regular service times, like "Sunday, 10am" or "every second Saturday, 6pm." I checked this out myself in my vicinity and have taken a picture as an example, which I can't post right now because of limitations on the mobile website. I will upload it later.

**Comment by Jotam** [comment] 2017-06-07 23:03
![tmp_4601-img_20170530_1925042100245072](https://user-images.githubusercontent.com/15984044/26905153-e9eee5b8-4be5-11e7-83ac-7291bc7cbec5.jpg)
Alright, here's my example which I believe to be more of the norm than the other example. I would still like to see a quest for service times implemented therefore.

**Comment by westnordost** [comment] 2017-06-08 18:42
Well okay, this quest could start with only including churches (christian faith), _but_ it must be possible to somehow tag that there are no regular service times. There is nothing defined in the wiki, perhaps service_times="irregular" (localized string)?

**Comment by Jotam** [comment] 2017-06-08 19:17
I agree (for the beginning) with limiting this quest to the combination "amenity=place_of_worship" and "religion=christian". I also agree to have an option for irregular service times.

IMHO the best way would be to model this quest exactly after the one for opening_times, which has the option to add a string for those cases where regular times cannot be established. So similar to the option "No regular opening times" ("Keine regemäßigen Öffnungszeiten") we could have an option called "No regular services times" ("Keine regelmäßigen Gottesdienstzeiten").

Oh, and thanks for implementing this!

**Comment by westnordost** [comment] 2017-06-08 19:35
> Oh, and thanks for implementing this!

What, I haven't yet. I just marked it as "okay, is a valid request for a new quest type" :-P

**Comment by Jotam** [comment] 2017-06-08 21:08
This is actually what I meant. I assume since you have marked this as a valid quest request, you will be implementing this soon. So I wanted to thank you in advance. :-)

**Comment by matkoniecz** [comment] 2017-06-09 00:12
Note that "valid proposal" includes issues that will not be implemented by the main author - but PR are welcomed.

For group closer to " you will be implementing this soon" see https://github.com/westnordost/StreetComplete/issues?q=assignee%3Awestnordost+is%3Aopen (note - closer, that is intention - not a promise. Also, things may be blocked for various reasons)

**Comment by rugk** [comment] 2018-01-22 22:29
This could be made as a disabled-by-default quest, if you think it cannot be seen from the outside (ref https://github.com/westnordost/StreetComplete/issues/558).

**Comment by matkoniecz** [comment] 2021-04-18 08:24
> but it must be possible to somehow tag that there are no regular service times. There is nothing defined in the wiki, perhaps service_times="irregular" (localized string)?

Or maybe `service_times:signed=no`? Would it be counting as "use of `:signed` namespace" or "we should check is use of such new tag OK" ( https://taginfo.openstreetmap.org/search?q=service_times%3Asigned ) ?

**Comment by westnordost** [comment] 2021-04-18 13:10
I guess that would be ok, as there is also opening_hours:signed=no and collection_times:signed=no. This is not a new scheme, even though that particular key is not used that.

**Comment by matkoniecz** [comment] 2021-04-19 09:11
@krzyk Is it established/documented somewhere what should be tagged in `service_times` in case of church having various services, not only Mass?

For example [adoration](https://en.wikipedia.org/wiki/Eucharistic_adoration)/[vespers](https://en.wikipedia.org/wiki/Vespers) etc

There is https://taginfo.openstreetmap.org/keys/service_times%3Amass but used 2 times worldwide

**Comment by Cj-Malone** [comment] 2021-04-19 21:59
@matkoniecz I don't know if it's established but I've done [this](https://www.openstreetmap.org/way/423104245) and it passes JOSM validation.

**Comment by michaelblyons** [comment] 2022-05-24 16:05
> @krzyk Is it established/documented somewhere what should be tagged in `service_times` in case of church having various services, not only Mass?
> 
> For example [adoration](https://en.wikipedia.org/wiki/Eucharistic_adoration)/[vespers](https://en.wikipedia.org/wiki/Vespers) etc

I imagine all of those are just "service times." 🤷‍♂️ If someone wants to go to a service on Sunday, cool. If they want one on a weekday, also cool.

The one thing I've tried to do that might be novel is when there are separate services per language with a language suffix (`service_times:fr`) versus the main local language.

**Comment by matkoniecz** [comment] 2022-11-01 07:07
I half-implemented it (trigger only) and it was not working well

**Comment by michaelblyons** [comment] 2022-11-05 14:21
I don't think I understand. Is this "done," or "not planned?"

**Comment by matkoniecz** [comment] 2022-11-05 15:28
It is closed as I tried test version of it and it is was not working well.

**Comment by matkoniecz** [comment] 2022-11-05 15:28
I so dislike this two versions of closure.

**Closed by matkoniecz** 2022-11-05 15:28 UTC
Labels: feedback required, new quest

**Comment by michaelblyons** [comment] 2022-11-05 17:12
I was less confused by the two GitHub close statuses than by the message. 🙂 I wasn't sure if he meant "I don't like the implementation, and another one should be done," or "... And it's not worth doing after all."

I think I understand now that it's the second one.

**Comment by 1ec5** [comment] 2022-11-05 17:38
> claims many churches in Germany have service time quests. So I went to a church and checked. This is how the service time table looks

Anecdotally, my trip to Heidelberg for State of the Map 2019 was eyeopening because the Catholic churches and diocese there posted no schedules anywhere online, only a complicated event calendar (an opportunity to learn some German, I suppose). I had never encountered that situation anywhere else. Even so, an option of “It’s complicated” resulting in `opening_hours="It’s complicated"` would’ve sufficed. 😉

I suspect that it would be difficult for anyone, even a well-traveled individual, to make an informed generalization across all geographies and religions. But I have participated in a MapRoulette campaign to [comprehensively map](https://maproulette.org/browse/challenges/15281) the places of worship in my county, which happens to be the [fifth most religiously/denominationally diverse county](https://www.prri.org/research/2020-census-of-american-religion/#page-section-1) in the United States. I haven’t systematically mapped service times – this is my reason for following this issue – but I have verified each one in street-level imagery. This is a heavily urbanized county, but it aligns with my experiences growing up in a more rural part of the country.

Even in an urban environment, my general impression is that there is a distinct difference among religions as to whether service times are posted. In this mostly Christian country, an outdoor schedule seems to be more common among Christian places of worship than among those of other religions. Among Christian churches, it’s most common among Protestant churches, slightly less among Catholic and Orthodox churches, and never posted for some smaller denominations like Jehovah’s Witnesses. The Islamic Center doesn’t post its times outside. Maybe it’s a reflection of how much a given church would welcome “walk-ins”.

This is a also one of the most linguistically diverse counties in the country. Most of the places of worship that post service times do so in multiple languages; advertising multilingual services may in fact be a major reason for posting times. Other kinds of qualifiers are common among Protestant churches, for example the youth services mentioned above.

Note that some places of worship do post their times, but not on the main signage visible from the street; you may have to walk up to an entrance on the side or enter the vestibule to see it. Some Jewish Chabad houses don’t even post their addresses online, let alone their service times, for privacy/security reasons (so I refrained from mapping them). If desired, I can provide more details from my experience participating in this MapRoulette challenge somewhere else without derailing this conversation.

**Comment by krzyk** [comment] 2022-11-05 20:12
@matkoniecz So, why close this one if it is not implemented and not rejected altogether? If the issue will be closed it will be harder for someone to see the possibility of a PR.

**Comment by matkoniecz** [comment] 2022-11-05 23:40
>  and not rejected altogether

it is rejected

Based on my testing it is harder to survey than expected and far more obnoxious and time consuming than I predicted and data is less stable than I thought.

**Comment by krzyk** [comment] 2022-11-07 10:35
I get that it might be harder to survey in some countries (or areas) where it is not popular. In my surveying of cities in Poland I have seen times I think each time, in case of villages it is less common (because "everyone knows").


So this would be a good candidate to disable by default, but it would be very useful to be able to enable it and do a quick sweep of a city center full of churches.

The added difficulty is that some times are dependent on the season, not sure how to deal with that in a clean way.
