### ISSUE TITLE
Leaving custom notes location still have random location error sometimes (#2)

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3312] opened 2021-09-22 00:10 UTC
Original problem was reported and was supposed to be fixed (thanks @smichel17!) in: https://github.com/streetcomplete/StreetComplete/issues/3284

However, I still (sometimes) experience a problem. 

**How to Reproduce**
This time it seems (at least sometimes) to happen even when "follow gps" is disabled? Maybe related to adding pictures to note?

Example, all three of those notes are supposed to be at the same location (crossing of path and street):
- https://www.openstreetmap.org/note/2861754 (ok)
- https://www.openstreetmap.org/note/2861752 (ok)
- https://www.openstreetmap.org/note/2861753 (bad)

While first two are at the correct location, third one is off.

Another example; all three of those notes were marked at the path crossing where the third one is, but they differ if GPS follow was on, and at what moment was picture added. Only the first one is positioned correctly. 
- https://www.openstreetmap.org/note/2861756 (ok)
- https://www.openstreetmap.org/note/2861757 (bad)
- https://www.openstreetmap.org/note/2861758 (bad)

And yet, sometimes everything looks like it's working perfectly (for example, all of those notes correctly ended up at the same location: [2863118](https://www.openstreetmap.org/note/2863118), [2863119](https://www.openstreetmap.org/note/2863119), [2863120](https://www.openstreetmap.org/note/2863120), [2863113](https://www.openstreetmap.org/note/2863113), [2863116](https://www.openstreetmap.org/note/2863116), [2863117](https://www.openstreetmap.org/note/2863117) - even when I tried different things while taking them)

**Versions affected**
 Android 6.0.1 (MIUI 10.2), SC 34.2

**Comment by westnordost** [comment] 2021-09-22 15:45
So, you can never reproduce it when you create a note, tap OK. Only if there is something in between, like taking a photo, leaving the form open etc?

**Comment by westnordost** [comment] 2021-09-22 17:48
I've prepared a special version of StreetComplete that puts all kind of debug data (regardin position) into each created note. Would you try it with that version? Maybe that will shed some light:

https://www.westnordost.de/misc/StreetComplete-v35.0-beta1-create-note-debug.apk

**Comment by mnalis** [comment] 2021-09-23 18:47
Sure. Does that debug APK contains 


 Do you have that debug code as source patch (or public git commit id) somewhere? I'd like to pull it into my fork, as it seems to be happening much more rarely since #3284. 
I found it 3 times

**Comment by mnalis** [comment] 2021-09-23 19:04
Sure, I'll try. Does that debug APK contains any changes that might have fixed that problem,  besides adding debug info?

I'm asking because today I tried opening 40 notes with that `35.0-beta1-create-note-debug` in various ways, and have not found even one error. And two days before with `v34.2` (which should containt @smichel17 fix) I did found that 3 misplaced notes (mentioned above) out of 25 total notes made.

Of course it might be that looking for a bug specifically makes it hide better. (like, making a screenshot before pressing OK might fix a bug, as I did try today to make a screenshot before taking each note). Or might have been just luck. 

Do you have that Notes debug code as source patch (or public git commit id) somewhere? I'd like to pull it into my fork, as it seems to be happening much more rarely since #3284, so it might take more time before I manage to reproduce it (and among other things, my personal fork shows note immediately as it is created, so I might catch problem much sooner and write down exactly what I was doing when it happened).

**Comment by mnalis** [comment] 2021-09-23 19:18
> So, you can never reproduce it when you create a note, tap OK. Only if there is something in between, like taking a photo, leaving the form open etc?

Maybe. The sample size is too small (I could have mislabeled some due to copy/pasting) and I do not have such a good memory to make such a claim. But all 3 notes where I did reproduce the problem had a common factor of having a photo added. Two other things seem to have been different while the bug happened in `v34.2` (moving/staying still, gps lock on/off).

**Comment by westnordost** [comment] 2021-09-23 20:29
Sure, it is on the `debug-issue-3312` branch.

Well, a lot of things changed for v35 but nothing in this regard should have changed. It was mostly refactorings etc

**Comment by mnalis** [comment] 2021-09-26 00:16
Thanks, I'll try to add that debug to my `34.2` fork and see if I can get it to reproduce there.

So far, in this `35.0-beta1-create-note-debug` I have only **been able to forcefully reproduce** changing of note position by manual intervention. 

If user is in `GPS follow` mode, turning the GPS reception `off` and then back `on` while the note is being created will cause the note pointer to move around the map:

for example, this note: https://www.openstreetmap.org/note/2867719
![Screenshot_2021-09-24-15-36-03-203_de westnordost streetcomplete2](https://user-images.githubusercontent.com/156656/134788875-38d15b5b-ea44-4105-a14b-d49d001b925c.png) ![Screenshot_2021-09-24-15-36-18-933_de westnordost streetcomplete2](https://user-images.githubusercontent.com/156656/134788877-a08101a2-b7cc-4afe-9795-1503ff317fc7.png)

I'm wondering if that reposition can also happen automatically (without manual user intervention) if we lose and then reacquire GPS signal (eg. weak GPS signal)? If so, that seems like one bug - but _probably not the only one_, as comments of the notes indicated at the top of the this issue do not all fall into that category.

**Comment by smichel17** [comment] 2021-09-26 01:50
> If user is in `GPS follow` mode, turning the GPS reception `off` and then back `on` while the note is being created will cause the note pointer to move around the map

:rofl: Line 548

https://github.com/streetcomplete/StreetComplete/blob/fe895b7a5d20339cf920e90b0629f1b565897c3f/app/src/main/java/de/westnordost/streetcomplete/map/MainFragment.kt#L545-L552

When you toggle gps like this, it re-enables tracking position, because "is the map frozen" isn't actually tracked anywhere. I don't think this should cause miscalculation, though; it would only be the wrong location if you didn't notice it.

**Comment by mnalis** [comment] 2021-09-26 18:50
I've managed to catch another way the wrong note location happens in `v34.2 with backported debug note patch`.
It has to do with how quickly one clicks `OK` after adding picture, so it does seem to be heisenbug (ie. explains me being unable to reproduce it when I was meticulously taking screenshots before taking each note).

It seems that when I take a picture, and click a checkmark to confirm it is a picture I want to take, there are very often (but not absolutely always, especially if adding 2nd, 3rd etc pictures) some small delays that follow the following pattern, specifically on this device (Redmi Note 3 Pro):

1. first it remains about one second with picture on screen, like the checkmark to confirm picture was not yet pressed
2. then whole screen goes white, and stays white for about 2 seconds (FYI I'm using dark mode in SC here)
3. upper half of the screen remains white, and dark grey dialog for adding note appears at bottom half of the screen, including `OK` button
4. red exclamation mark for note appears (very quickly or at the same time as above grey dialog)
5. then GPS location pointer appears very quickly (taking fraction of the second?)
6. then the one map view is shown in upper half of the screen (replacing white screen) quickly (taking fraction of the second), and stays for almost a second
7. then the another map view replaces previous map view in upper half of the screen

It seems, that if I press `OK` to finish the note somewhere between steps `3`-`6` (inclusive), the note will end at wrong location. If I wait until step `7` completes, then note ends up at correct location. Unfortunately this devices lacks the `record screen video` feature, so I have to resort to manual explanations like that.

Here is real-life example:
- I'm physically located at this location: https://www.openstreetmap.org/note/2870470 
- I'm trying to leave a note at this crossing https://www.openstreetmap.org/note/2870471. GPS lock is off.

What happens:
- if I wait for step 7 to complete before I click `OK`, note ends at correct place: https://www.openstreetmap.org/note/2870404
- if I click on `OK` sometime between steps `3`-`6`, note ends at wrong location: https://www.openstreetmap.org/note/2870405

**Comment by westnordost** [comment] 2021-09-26 20:18
> then whole screen goes white, and stays white for about 2 seconds (FYI I'm using dark mode in SC here)

When you start StreetComplete fresh, is the screen also white while SC boots up?

> then the another map view replaces previous map view in upper half of the screen

What do you mean, which map view replaces which map view? There is only one map view!

**Comment by smichel17** [comment] 2021-09-26 21:24
> Unfortunately this devices lacks the record screen video feature, so I have to resort to manual explanations like that.

Perhaps you could go analog and take a video with another device?

**Comment by mnalis** [comment] 2021-09-26 23:29
> > then whole screen goes white, and stays white for about 2 seconds (FYI I'm using dark mode in SC here)
> When you start StreetComplete fresh, is the screen also white while SC boots up?

Yes @westnordost - when I start SC and it wasn't cached before, I firstly get whole white screen, then white screen with button elements (compass, zoom, gps, map copyright text...),  then whole screen turns dark like dark SC background, then it shows dark map quite zoomed-out eg. showing whole continents, and then it finally shows dark map of very zoomed-in location of where I am. Complete startup process takes about 5 seconds; some steps take longer (like white screen), some shorter (like whole-world view).

> > then the another map view replaces previous map view in upper half of the screen
> What do you mean, which map view replaces which map view? There is only one map view!

I've phrased it confusingly; what I meant is the upper half of screen (which contains map view when making note) is displaying map at one location in step `6` and at different location in step `7`.

Location shown in map view in final step `7` is the correct one (the one on which I did long press and want to leave note on), but I cannot tell you which is the location being shown in step `6` - it gets replaced too quickly for my brain to get a fix on it (I suspect it might be either the location the note gets incorrectly left on, or the location on which I am physically, but it could be something else too).

> Perhaps you could go analog and take a video with another device?

Ah, usually yes, but... :thinking:  I'll try @smichel17, but I can't promise if I'll be able to arrange that before weekend.

**Comment by westnordost** [comment] 2021-09-27 09:52
Alright, so I think what is happening is that your Android system actually destroys the view of the StreetComplete app when you switched to the camera app. When you then come back to StreetComplete, your Android system recreates the view, which takes some time. While the view is created, I figure, the dimensions of the elements are not correct yet (much like a HTML site that is loading), so if you fire away your note at that moment, the offset is not calculated correctly.

If this is really the only way this issue can be reproduced, I don't think anything can be done about this.

**Comment by mnalis** [comment] 2021-09-27 11:15
@westnordost Now that you mention HTML site loading (in which I have much more experience than with Android) perhaps same kind of safety mechanisms can be employed in SC - when user presses the camera button on note screen, first disable (grey-out) the Note `OK` button (so note cannot be finished), then invoke the camera, and only when camera returns and everything is rendered, picture thumbnail is prepared and shown etc, then re-enable the `OK` button. 

Would something like that be possible in Android? Such programming (HTML elements `disabled`/`hidden` by default,  and only later reenabled programmatically via JS only when they are ready) is common tactic is HTML5 world, to avoid exactly this kind of race conditions.

(I can of course run any test version on this device to see if it works.)

**Comment by westnordost** [comment] 2021-09-27 11:47
Not really, I'd say. There is not one callback that is like "now everything is rendered". There is a callback for when the view has been created (i.e. probably when the view turns from white to displaying **something**) but it may take - usually just one frame - to settle.

**Comment by smichel17** [comment] 2021-09-27 11:52
@mnalis Try #3325 and see if that does the trick? In a few minutes there should be a debug apk here: https://github.com/streetcomplete/StreetComplete/actions/runs/1278093838

**Comment by smichel17** [comment] 2021-09-27 12:51
At the least, there's [`View::isInLayout`](https://developer.android.com/reference/kotlin/android/view/View#isInLayout()) which could tell us if this is a problem we need to worry about.

**Comment by mnalis** [comment] 2021-09-27 17:42
> @mnalis Try #3325 and see if that does the trick? In a few minutes there should be a debug apk here: https://github.com/streetcomplete/StreetComplete/actions/runs/1278115207, or you can pull that commit over into your fork.

Thanks @smichel17; I've tried `.apk` from https://github.com/streetcomplete/StreetComplete/actions/runs/1278115207 debug build, and I can still reproduce the problem by clicking on `OK` too soon.

Actually, with `v35` (both this debug version, as well as previous `debug-issue-3312` branch) the error seems to be much greater than it was in `v34.2` (both official upstream, and my fork). I don't know if this is just a random chance or something to do with refactoring, but while in `v34.2` the errors were tens to hundreds of meters, with `v35` versions notes end up in wrong countries (https://www.openstreetmap.org/note/2871298), and even wrong continents (https://www.openstreetmap.org/note/2871654). 
Both buggy notes mentioned above were supposed to end here: https://www.openstreetmap.org/note/2871297

**Comment by mnalis** [comment] 2021-09-27 18:35
> Perhaps you could go analog and take a video with another device?

@smichel17 I've also managed to capture analog video as requested - here is how it looks in `v34.2` (on which this bug was initially reported) when I wait long enough and it ends at correct position https://www.openstreetmap.org/note/2871279

https://user-images.githubusercontent.com/156656/134964381-b7433860-71a6-4748-a174-a3c76fea6cc4.mp4

Note how at `10` seconds mark  the form appears and it is possible to click `U REDU` (= `OK`) button, at `11` seconds map is shown at invalid location, and only at `12+` seconds maps shows correct location.

If I didn't wait and pressed `OK` between `10-12` seconds in the video, the note would end up at the wrong location, like https://www.openstreetmap.org/note/2871278

**Comment by mnalis** [comment] 2021-09-27 19:47
And this is how it looks with the `.apk` from https://github.com/streetcomplete/StreetComplete/actions/runs/1278115207, when `OK` is pressed too soon, resulting in incorrectly placed note https://www.openstreetmap.org/note/2871298.

https://user-images.githubusercontent.com/156656/134974032-4b728950-fa83-4d8b-9513-13d498804a14.mp4

**Comment by mnalis** [comment] 2021-09-27 20:11
@smichel17 I know nothing about android programming, so I'm sorry if this is not helping, but trying to look at the docs, maybe [onViewComplete()](https://tangrams.readthedocs.io/en/latest/API-Reference/android-sdk/0.11.0/com/mapzen/tangram/MapChangeListener.html#onViewComplete--) is something that could perhaps be used to re-enable `OK` button?

Docs  say:
> void onViewComplete()
>
> Called on the UI thread at the end of whenever the view is stationary, fully loaded, and no camera animations are running.

**Comment by smichel17** [comment] 2021-09-27 22:31
@mnalis Thank you a bunch for the videos, they're *really* helpful. It looks like it's not really a problem with the layout: the form and all is in the correct location. Instead, it seems that ***tangram*** is still re-initializing the map when you press OK; that we ask for the coordinates of that point on the screen, but the map is simply displaying some wrong location at that point. So, I'd guess the solution would be to look at Tangram's docs and see if there is a way to tell whether the map is finished restoring its state yet; rather than prevent clicking OK in the note dialog, the main fragment could wait until Tangram is finished loading.

**Comment by mnalis** [comment] 2021-09-28 18:54
> I guess the solution would be to look at Tangram's docs and see if there is a way to tell whether the map is finished restoring its state yet; rather than prevent clicking OK in the note dialog, the main fragment could wait until Tangram is finished loading to request the coordinates.

@smichel17 Hm, isn't it exactly what [onViewComplete()](https://tangrams.readthedocs.io/en/latest/API-Reference/android-sdk/0.11.0/com/mapzen/tangram/MapChangeListener.html#onViewComplete--) Tangram callback mentioned [above](https://github.com/streetcomplete/StreetComplete/issues/3312#issuecomment-928232701)  is supposed to do? Or am I misreading it when it says ***"Called on the UI thread at the end of whenever the view is stationary, fully loaded, and no camera animations are running"*** ?

I'm not versed in object/classes model, much less android programming specifically, but my C-based mind had crude idea about something like this pseudocode (which I'm totally sure should be done differently in object-oriented-kotlin-model, but if it is possible to do in one way, it should be possible to do it in other too, right?):

```
global volatile bool isCameraFinished;  // I'm sure there is better solution than global variables, but I have no idea how Kotlin does it 

// called when "Add picture" button in note dialog is pressed (this function already exists in current code)
void SC_take_picture {
    [...]
    isCameraFinished = false;
    NoteForm.okButton.isEnabled = false;        // disable OK button on Note form (as soon as user has indicated they want to take picture)
    set_callback (tangram.onViewComplete, SC_ViewComplete_handler);     // setup Tangram callback
    pic = SystemCameraTakePicture();            // actually take the picture (exists in current code)
    [...]
    NoteForm.CreateAndAddThumbnail(pic);        // creates the thumbnail of picture and adds it to Note form (exists in current code)
    isCameraFinished = true;
}

// called by Tangram callback onViewComplete(): https://tangrams.readthedocs.io/en/latest/API-Reference/android-sdk/0.11.0/com/mapzen/tangram/MapChangeListener.html#onViewComplete--
void SC_ViewComplete_handler() {
    // quoting Tangram docs: "Called on the UI thread at the end of whenever the view is stationary, fully loaded, and no camera animations are running."
    // so it should be safe to reenable OK button on Note form

    while (!isCameraFinished) { sleep (1) };    // just in case camera postprocessing code is not done yet, wait some more

    clear_callback (tangram.onViewComplete);    // disable Tangram callback
    NoteForm.okButton.isEnabled = true;         // re-enable OK button on Note form
}

```

Could something like this work (when converted to kotlin way of doing things)? 

I'd try it myself, but I'm totally out of my depth here,  even the basics (for example how to disable `OK` button when I'm not a child of that object/class/whatever - I'm guessing some indirect object method needs to exists to access object private parts like `isEnabled`, or something)

**Comment by smichel17** [comment] 2021-09-28 22:42
Ah, I misread it as `OnViewCreated`, which is part of the [Fragment](https://developer.android.com/reference/androidx/fragment/app/Fragment#onViewCreated(android.view.View,android.os.Bundle)) lifecycle, and we already use it. So I did not click the link in your comment and skimmed over the description. Sorry about that. It does indeed look like the right callback.

So, we either need to listen to that callback and disable the OK button until it happens, or allow tapping the OK button but wait until the map is finished moving to ask for coordinates. The first one is probably safer in this instance; the second is probably more amenable to avoiding future bugs of a similar type.

…and/or we could fix it with #3123

**Comment by westnordost** [comment] 2021-09-28 22:57
> …and/or we could fix it with #3123

Not in the short term.

This issue is probably fixable by only allowing a OK click after `onMapInitialized` on `MainFragment` has been called. This is the time when the camera position and zoom should have been restored on tangram-es (unless tangram-es does this asynchronously).

**Comment by mnalis** [comment] 2021-09-28 23:25
Well, I'm sure willing to try anything that comes my way - this one have been driving me crazy!

**Comment by westnordost** [comment] 2021-09-29 06:36
Then you might try using a different camera app or looking at power saving features you might have enabled. 

It is not normal that the app's view basically restarts every time you switch to the camera. 

Am 29. September 2021 01:25:41 MESZ schrieb Matija Nalis ***@***.***>:
>Well, I'm sure willing to try anything that comes my way - this one
>have been driving me crazy!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3312#issuecomment-929695726

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mnalis** [comment] 2021-09-29 12:22
I was thinking more about helping you guys and gals (who can produce such more delicate SC code) as a betatester to produce a software fix that will **ensure that SC always produce the correct data** at the correct place, no matter how slow or resource starved some device may be in some situation, or how much inventive power saving functions get with different Android versions.

<details>

So, I'm not worried about finding workarounds for that particular older Android 6 phone where the error happen very often (but not always). It is mostly useful to me for testing, **exactly** because of that it is slower and has lower resources, so it has much better chance of catching such race conditions,  and I much prefer when I can reproduce bugs in a few hours of trying (instead of in a few months of trying). (Another reason for this particular device being used last few weeks is that I won't shed _too much_ tears if it gets broken on rougher terrain, or stolen)


IOW: what has been bugging me is that even when I see even my own StreetComplete note, I cannot _ever_ be sure if it is really where it is supposed to be (even if I _was_ sure when I was making note), or if I am going to enter wrong data in the OSM as a result of SC bug.  So what I really am after is the having _**a peace of mind**_ that I can **always trust** StreetComplete. (And not having to worry, for example, if my mapping session is going to be producing bad data because I was using phone resources to also listen to some music while I was mapping, or because I run some other app like OsmAnd at the same time etc). It is a gnawing doubt which won't go away until the bug is proven fixed, even when (or: especially when) it happens much more rarely on some other device.

</details>

**Comment by HolgerJeromin** [comment] 2021-09-29 15:30
We had a correct position on "take photo" timestamp.
Perhaps SC should remember this (and lock it) and use it when OK is pressed too fast (10-12 s in first video).
And then unlock the position variable again when map/tangram is ready again.

**Comment by westnordost** [comment] 2021-10-01 22:09
@mnalis I added a commit to the `debug-issue-3312` branch that may fix the issue. Would you like to test it? I presume you'll pull it into your fork so I didn't build an APK for you.

**Comment by smichel17** [comment] 2021-10-01 23:48
Note that (if I'm reading it right) it will prevent the note from being created, but will not prevent you from clicking the OK button. But I think that can be added easily enough after verifying that the fix works.

**Comment by mnalis** [comment] 2021-10-02 23:06
Quick test on [debug-issue-3312 build](https://github.com/mnalis/StreetComplete/actions/runs/1296881809) seems to indicate it works, here is the video:

https://user-images.githubusercontent.com/156656/135733589-2ea59d67-d6c2-44fd-8ed9-f4f7fe1723a3.mp4

Trying to open a note at a crossing of `Ulica Dragutina Golika` and `Ulica Franje Hanamana`, produces https://www.openstreetmap.org/note/2878523 at expected location. Note animation seems to happen at wrong map location at about `12 sec` in the video, but that is not important as one correct Note was created at desired place, even when my finger was rapidly clicking the area where `OK` button should appear.

**I'll try to do some more testing in the following days, but so far it looks good.**

Also in related news: while firstly dutifully trying to confirm I can still reproduce the bug in _unpatched_ SC, I seem to have managed to trigger another interesting related bug - while **rapidly and repeatedly pressing the area where OK button** should appear after taking a pictures, I've managed to **create 3 separate notes** (two without picture at slightly wrong location:  [2878518](https://www.openstreetmap.org/note/2878518) and [2878519](https://www.openstreetmap.org/note/2878519), and third [2878517](https://www.openstreetmap.org/note/2878517) with picture at even more wrong location) - all just by quickly clicking on that one Note form dialog! 

I'm glad that the above `debug-issue-3312` patch seems to have patched that related manifestation of the (same?) race condition, as rapidly clicking there created only one note (and that one at correct location).

**Comment by westnordost** [comment] 2021-10-03 23:31
So, I applied the patch  you tested to the master branch and will close this issue now.

I think the other issue you encountered is the following:
When you press OK,  couple of things happen, one of these is that the fragment that shows the create-note-dialog is closed. This happens as far as I know asynchronously. So theoretically it is possible to tap the "OK" button or anything else in that form several times, especially if it is a slow smartphone and/or other things are happening in the background or in the UI at the same time whch may slow things down. Since the complete app seems to be re-starting in your case when you tried to reproduce the issue described in the OP, it seemed to slow down enough for you to be able to reproduce this behavior.
A possible fix/workaround for this would be maybe to add an invisible (alpha=0) View on top of the whole create-note-fragment so that nothing is tappable in the form, similar to what is done for the quest-answer fragment because of a similar issue. However, when it is not guaranteed that the fragment will be removed on the next frame, will it be guaranteed that that view will be on top of the whole create-note view on the next frame?

**Comment by matkoniecz** [comment] 2021-10-04 06:04
> So theoretically it is possible to tap the "OK" button or anything else in that form several times

See also  #1902 

> it is possible to open cycleway selection menu multiple times

I have also managed to encounter it with setting menu and in some other places.

Triggered on slower phone (with battery saving enabled or when some other app has CPU-heavy work or when my phone decides to demonstrate why it was inexpensive and randomly lags).

**Comment by westnordost** [comment] 2021-10-04 09:41
Yeah well, this is an Android issue in general. The solution can not, should not be, to disable all controls after one tap and then enable them again after something happened

**Closed** 2021-10-15 16:02 UTC
Labels: bug
