### ISSUE TITLE
Rendering bug for mirror of water and swimming pool

### ISSUE THREAD

**Issue by Domefemia** [streetcomplete/StreetComplete#5156] opened 2023-07-20 09:14 UTC
When the app try to render a mirror of water or a swimming pool it render in a broken way. 
See below images.
![swimming pool](https://github.com/streetcomplete/StreetComplete/assets/50798132/ea83e155-9e3b-414f-97b5-07e6e22075a0)

![mirror of water](https://github.com/streetcomplete/StreetComplete/assets/50798132/2ce22665-0126-4655-b650-1b37267f14f1)

This are the two way: 
https://www.openstreetmap.org/way/1181174483/
https://www.openstreetmap.org/way/1177627305/

**How to Reproduce**
Download data from a city with a swimming pool, go with the app on where the swimming pool is located

**Expected Behavior**
To render them in a normal way

**Versions affected**
Android 13, LineageOS 20 microg.
StreetComplete ver 53.3

But it was happening before with an older version of StreetComplete on Miui 13 with Android 12.

**Comment by FloEdelmann** [comment] 2023-07-20 09:40
Duplicate of https://github.com/streetcomplete/StreetComplete/issues/4542,see https://github.com/streetcomplete/StreetComplete/issues/4542#issuecomment-1287796776

**Closed by FloEdelmann** 2023-07-20 09:40 UTC
