### ISSUE TITLE
Have an option to "compress" all changes into one changeset

### ISSUE THREAD

**Issue by ScriptForAll** [streetcomplete/StreetComplete#3096] opened 2021-07-26 19:23 UTC
**Use case**
While surveying a small area but with a lot of data missing (e.g. road's surface; lit: POI names; access) several changesets are created when in my opinion should there only be one or two. 
Thus, I believe that having a ton of different changesets for small edits (be it in the same area or over a small period of time) creates a lot of unnecessary clutter.   

**Proposed Solution**
My proposal that tackles this issue is to have the option to include all changes into one changeset. One possible implementation of this could be by a long-press in the upload button to show this option.
 
The comment of this "composite" changeset would be the same as the "combined" changesets (i.e. the descriptions of all the specific changes made at the time of upload). 
For example: If I were to upload road's surface and street names at the same time then the comment would be "Added roads surface; Added street name")

I reckon this feature is useful for those who like to manually upload changes.

**Comment by BalooUriza** [comment] 2021-07-26 19:41
I'm personally a little wary of this idea, I find that the smaller,
thematic changesets are much easier to QA than a random mash of changed
objects.

If anything, splitting changesets further along geographic lines.  Like if
there's a 20+km (number arbitrarily chosen) gap in objects, create a
separate changeset to cut down on situations where someone uses SC in an
airport or train station, checks out for five hours and then continues
using SC, and then finally uploads.  Currently this can make extremely
geographically large changesets that are often tricky to QA, with a really
annoying edge case that any editor that crosses the 180th meridian creates
a globe-spanning changeset.

**Comment by matkoniecz** [comment] 2021-07-26 19:42
> The comment of this "composite" changeset would be the same as the "combined" changesets (i.e. the descriptions of all the specific changes made at the time of upload).

And what when merged description stops fitting?

> a lot of unnecessary clutter.

Why merging different ones would be better?

See #2498 #21 

especially https://github.com/streetcomplete/StreetComplete/issues/21#issuecomment-292709936

> Thus, The only gain I see from grouping all solved quests within a survey together is to have less changesets. But it is not the goal to have as few changesets as possible, but to lay them out in a meaningful, descriptive way. The type of changeset that must be avoided are those that seem to hide certain (very different) changes within a larger set of harmless changes. Not saying that would be the case, my point is that the goal should be to have as meaningful changesets as possible, not as few as possible.

> The type of change can be told apart on first glance by people doing QA: they can focus on checking those quests that are known to sometimes be misunderstood and/or critical things such as street names

> Possibility of programmatically and reliably reconstruct what changes (what =quest type) any user exactly did from the OSM change history alone, without the need to either add "proprietary" tags to elements (god forbid) or somehow transfer analytics data to a third party. A must for statistics and (thus) finding systematically introduced errors (don't need to be bugs, may be systematic misunderstandings).

**Comment by westnordost** [comment] 2021-07-26 22:54
This is a duplicate of some other ticket, too lazy to find it. But I think @matkoniecz found it.

**Closed by westnordost** 2021-07-26 22:54 UTC

**Comment by smichel17** [comment] 2021-07-26 23:10
I added an index entry for these, in the future: https://github.com/streetcomplete/StreetComplete/discussions/2789#discussioncomment-1058716
