### ISSUE TITLE
Quest suggestion: Solar generator (photovoltaic, thermal) roof-top installations

### ISSUE THREAD

**Issue by tobylorenz** [streetcomplete/StreetComplete#2489] opened 2021-01-11 14:12 UTC
**Use case**
When mapping houses, there are already questions, on number of base and roof levels, roof format, etc.
Another good visual detail are roof-top solar generator installations, or more precise photovoltaic or thermal installations.
In our area (Germany, Hesse), approximately every 10th house has it.
This would give a better picture in OSM infrastructure map: https://openinframap.org/

**Proposed Solution**
With the same conditions, roof forms are quested, there should be a question, whether the roof has a solar installation in general, or more precise, if it has photovoltaic, or just water thermal installation.
The main tags for this are documented here: 

- https://wiki.openstreetmap.org/wiki/Tag:power%3Dgenerator
- https://wiki.openstreetmap.org/wiki/Tag:generator:method%3Dphotovoltaic
- https://wiki.openstreetmap.org/wiki/Tag:generator:method%3Dthermal

**Comment by FloEdelmann** [comment] 2021-01-11 14:54
Related: #1383

**Comment by matkoniecz** [comment] 2021-01-11 15:17
>  if it has photovoltaic, or just water thermal installation.

How can you distinguish that for roof mounted ones while you walk? See https://github.com/streetcomplete/StreetComplete/issues/1383#issuecomment-486299774

**Comment by HolgerJeromin** [comment] 2021-01-11 15:45
Furthermore SC can not add new elements. Adding them on the building outline is not good.

**Comment by tobylorenz** [comment] 2021-01-11 17:46
> How can you distinguish that for roof mounted ones while you  walk?

PV-modules are usually flat and thin and sometimes you seen thin cables.
Thermal modules usually consist of tubes and have two big isolated tubes going to it.
But, if you cannot differentiate, then just leave power:type empty and only set power=generator, generator:source=solar.

The images shown in #1383 can be clearly distinguished, mainly based on the connecting tubes/wires.

> Furthermore SC can not add new elements. Adding them on the building outline is not good.

It's allowed to either use this tag with a point, or with an area, so I guess the building outline is ok.
But, often I see houses that have both types on the same roof, and this cannot be set within the same area then, but only with two distinct points.

**Comment by westnordost** [comment] 2021-01-11 17:49
This is a duplicate of #1383 which has been closed as will not fix. If you have anything to add, please add it to #1383

**Closed by westnordost** 2021-01-11 17:49 UTC

**Comment by tobylorenz** [comment] 2021-01-11 17:52
Ok, I wasn't aware of #1383.
I checked the ~80 open issues, and not all ~2500 total issues.
Yes, maybe I'll add it there.

**Comment by HolgerJeromin** [comment] 2021-01-11 18:02
I would love to have this implemented. 
But must confess that in the wild there are many unclear objects.
I think even very much data entered are wrong in OSM or right by chance. I propose most small objects mapped (from aerial image) on a roof are wrong because most mapper do not know how common thermal collector are.

**Comment by westnordost** [comment] 2021-01-11 18:14
I think it makes sense and is quite possible to collect locations where there are `power=plant + plant:source=solar`, however `plant:method` is something many people will not be able to answer (correctly). The former (add nodes etc) is not possible with StreetComplete (no new data is added, only data is enhanced). But since this is visible from aerial, it is completely possible to map this information with JOSM from home.
