### ISSUE TITLE
Ignore conveying way or steps in the surface overlay.

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#5728] opened 2024-07-08 13:20 UTC
**Use case**
In the surface overlay, an escalator was displayed red. When selecting in, I was told by the StreetComplete interface that it was steps, and I was asked what its pavement was.
I left a note as it felt odd: I was assuming that it was mapped as steps and not as an elevator.
But when later checking the tags of the way, it was actually mapped as an escalator:
```
conveying=forward
highway=steps
incline=down
```

**Proposed Solution**
I would suggest to ignore the ways with `conveying=*` in the surface overlay, or otherwise rephrase a bit the associated quest to explicitly name it an escalator and not steps.

**Comment by westnordost** [comment] 2024-07-08 13:33
I think not displaying this at all would also look like a bug to some. After all, there is no reason why one shouldn't be able to tag the surface. (There are wooden elevators too, by the way, here is one in Antwerp
![2023-11-13-14-12-34-178](https://github.com/streetcomplete/StreetComplete/assets/4661658/9b406b93-a891-4ba7-9aef-4b14e9cec602)
https://www.openstreetmap.org/way/693777313

So anyway, to correctly display this as an escalator, there needs to be an iD preset for that. And indeed there is, but it is not used by StreetComplete because of this missing feature here: https://github.com/westnordost/osmfeatures/issues/16

So, since there is already an issue for this over at the osmfeatures repository, I will close this issue.

**Closed by westnordost** 2024-07-08 13:33 UTC

**Comment by FloEdelmann** [comment] 2025-02-23 07:31
https://github.com/westnordost/osmfeatures/issues/16 is now implemented

**Comment by mnalis** [comment] 2025-03-04 02:16
> So anyway, to correctly display this as an escalator, there needs to be an iD preset for that. And indeed there is, but it is not used by StreetComplete because of this missing feature here: https://github.com/westnordost/osmfeatures/issues/16

Hm, did #6140 really fix this though?

I've compiled the [latest master](https://github.com/mnalis/StreetComplete/actions/runs/13644266417), went to [way 1011315458](https://www.openstreetmap.org/way/1011315458) (which is tagged as `highway=steps` + `conveying=yes`), selected the surface overlay and clicked on that (invisible) way, and it is still being (incorrectly) identified as ***"Steps"***.

If I'm reading https://github.com/westnordost/osmfeatures/issues/16#issuecomment-2214093457 and  [steps/conveying.json](https://github.com/openstreetmap/id-tagging-schema/blob/2763fbd500c85b494c45940fa9201b760866eeb0/data/presets/highway/steps/conveying.json#L28-L32) correctly, it should've now been displayed as ***"Escalator"*** in StreetComplete instead, right?

![Image](https://github.com/user-attachments/assets/44f95274-a707-47b9-bd2d-1ae9aca15d12)

**Comment by westnordost** [comment] 2025-03-04 12:11
I tested that, and it shows escalator. See the linked PR. But I will test it another time with the way you linked.

**Comment by westnordost** [comment] 2025-03-04 12:14
Yeah, can't reproduce. Tested on current master, in English and in Spanish, with exactly this way.

**Comment by mnalis** [comment] 2025-03-04 13:48
> Yeah, can't reproduce. Tested on current master, in English and in Spanish, with exactly this way.

You're right, it seems to work when I try now, so I've probably managed to open it in wrong SC. Sorry for the noise. 😢 

<details>
<summary>screenshot</summary>

![Image](https://github.com/user-attachments/assets/3bb54325-b537-47f5-ab9f-0c49b8fa2835)

</details>
