### ISSUE TITLE
no map background 

### ISSUE THREAD

**Issue by jochen-01** [streetcomplete/StreetComplete#5554] opened 2024-03-25 15:57 UTC
In StreetComplete there is no map displayed.
All tasks from StreetComplete are shown at the right places (as far as I can see) but without any streets.

**How to Reproduce**
On the somewhat old smartphone LG G4 with Android 6 the issue exists. Tried current version 57.1 as well as an old 34.2.

**Versions affected**
All versions of StreetComlete, at least the 2 I tried (see above).

**Comment by matkoniecz** [comment] 2024-03-25 15:58
Which version of map you are using? Are quest appearing? Is internet working for other apps?

**Comment by matkoniecz** [comment] 2024-03-25 15:59
Can you open https://www.jawg.io/en/ ?

**Comment by jochen-01** [comment] 2024-03-25 16:18
Hi,

yes, I can open
> https://www.jawg.io/en/
> Seems to be a site making money with maps. But if I navigate to the examples (e.g. île de la cité de Paris) the 3d map is shown.
> 
Google Maps is not installed, just Osmand with offline maps (works as expected).
>  

-- 

-- 
regards
Jochen

25.03.2024 16:00:14 Mateusz Konieczny ***@***.***>:

**Comment by Helium314** [comment] 2024-03-25 16:21
I edited the issue text to remove the `<!-- ` at the beginning

**Comment by matkoniecz** [comment] 2024-03-25 16:35
Oh then it is https://letsencrypt.org/2023/07/10/cross-sign-expiration and #5528

See https://github.com/streetcomplete/StreetComplete/issues/5528#issuecomment-1987035269 and https://github.com/streetcomplete/StreetComplete/issues/5528#issuecomment-1987140773

**Comment by jochen-01** [comment] 2024-03-25 16:39
> What is your Android version? (see #5528 )
It's 6.0.

> if #5528 is not an answer: Which version of map you are using? Are quest appearing? Is internet working for other apps? Can you open https://www.jawg.io/en/ ?

Thank you for pointing me to that issue. I checked the mentioned let's encrypt certificates, the answer was "Die Zertifikatskette ist bereits vertrauendwürdig. Es muss kein Zertifikat importiert werden". 

So, I think it's ok?
What do you mean with "which version of map you are using"?

**Comment by matkoniecz** [comment] 2024-03-25 16:47
> "which version of map you are using"?

Answered by screenshot (which was hidden).

I see on screenshot airplane logo in top right. Have you enabled airplane mode?

**Comment by jochen-01** [comment] 2024-03-25 17:01
Ok, what I have learned is: Android 7.1.1 is the minimum version required to use StreetComplete. 

Would you please update the minimum required Android version of the apk from 5+ to 7.1.1?
Without background maps the app is useless. 

> autotranslates to
> 
> > The certificate chain is already trusted. No certificate needs to be imported

Sorry, the phone is owned by a person from Germany. 

> And you are still not seeing the background map?

No. The phone has been in airplane mode but internet access was enabled. I checked again with airplane mode disabled - no difference. 
I updated the screen shot.

**Comment by jochen-01** [comment] 2024-03-25 17:07
![Uploading signal-2024-03-25-16-59-21-547.png…]()

**Comment by jochen-01** [comment] 2024-03-25 17:07
Updated screen shot. Sorry...

**Comment by jochen-01** [comment] 2024-03-25 17:08
![signal-2024-03-25-16-59-21-547](https://github.com/streetcomplete/StreetComplete/assets/28684535/ef32ed4f-71a4-4e01-924c-1ba33b41c312)

**Comment by jochen-01** [comment] 2024-03-25 17:13
![signal-2024-03-25-17-12-05-626](https://github.com/streetcomplete/StreetComplete/assets/28684535/2e52e0ee-f819-4c06-a5e3-b5022ab6e01e)

**Comment by westnordost** [comment] 2024-03-25 17:31
This is a duplicate of #5528.

Note that you have to install that certificate for the Android system, not for your browser. (Can't offer guidance on how to do that though, I don't know where to do that.)

**Closed by westnordost** 2024-03-25 17:31 UTC
Labels: feedback required

**Comment by Helium314** [comment] 2024-03-25 17:33
> Would you please update the minimum required Android version of the apk from 5+ to 7.1.1?

This would stop users who installed the certificates from using the app (see [this user](https://github.com/streetcomplete/StreetComplete/issues/5528#issuecomment-1989243653) who is on 5.1)

**Comment by jochen-01** [comment] 2024-03-25 17:45
> Note that you have to install that certificate for the Android system, not for your browser. (Can't offer guidance on how to do that though, I don't know where to do that.)
I used CAdroid to import and install the certificate. Still not working.
Since I tried to help another user I give up now.
It's a pity that there exists such hidden dependencies. The app might be interesting for people even less experts than I am. ;-)

**Comment by westnordost** [comment] 2024-03-25 18:00
I thought there is a system setting somewhere where you can just add a (root) certificate.

**Comment by Helium314** [comment] 2024-03-25 18:11
@ironspock could you share what you did to make it work?

**Comment by jochen-01** [comment] 2024-03-26 12:48
> @ironspock could you share what you did to make it work?

Now it works!
What I have done to make it working: Following the excellent support messages here. 

I downloaded the 2 certificates ISRG Root X1 and ISRG Root X2. On the phone in question it could be done by selecting "security" --> "cerificates" in system settings, then "import from memory" (choosing the two .pem files I downloaded from Let's Encrypt).

Thank you for your help.

**Comment by westnordost** [comment] 2024-03-26 15:48
This could be a topic that may be worth adding to the FAQ on https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ

The FAQ is not maintained by me, instead everyone is free to contribute, most of the current texts are from @mnalis and @matkoniecz . For the 150+ users of StreetComplete still on Android 7.0 and below, it might be very helpful to have a brief and succinct instruction on how to solve this issue on their phone, certainly they would be thankful if you or someone else added that!

**Comment by mnalis** [comment] 2024-03-26 17:23
I've added @jochen-01 instructions to [FAQ: The background map is no longer visible after Feb 2024 (on Android versions lower than 7.0)](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#The_background_map_is_no_longer_visible_after_Feb_2024_(on_Android_versions_lower_than_7.0))

Improvements welcome, it's a wiki so feel free to contribute.

**Comment by ironspock** [comment] 2024-03-28 18:53
> @ironspock could you share what you did to make it work?

Sorry for the delay.
I've just exported the ISRG Root X1 certificate from a laptop and installed it on the Android device. However I wasn't able to import it into "Trusted system certificates". So it's (only) a "user certificate". When starting the device I get a related warning message.

**Comment by mnalis** [comment] 2024-06-12 17:45
Related in-app workaround for expired Let's Encrypt CA certificates from Vespucci: https://github.com/MarcusWolschon/osmeditor4android/pull/2577

Don't know how complicated (or even possible) would it be to implement it in StreetComplete, though.
