### ISSUE TITLE
Disabble animations and 3D buildings

### ISSUE THREAD

**Issue by StyXman** [streetcomplete/StreetComplete#3866] opened 2022-03-10 22:22 UTC
I live and move áround an area with lots of quests. Sending 50+ answers in one session is not unheard of. I have the impression that between the 3D building effect and all the animations, SC drains my phone's battery quite quickly. Could something be done here?

**Comment by FloEdelmann** [comment] 2022-03-10 22:39
Duplicate of #966 and #1260 (see also #2206).

**Closed by FloEdelmann** 2022-03-10 22:39 UTC

**Comment by smichel17** [comment] 2022-03-11 18:08
See also https://github.com/streetcomplete/StreetComplete/discussions/3251

tl;dr turn off auto-upload, it drains a massive amount of battery

**Comment by StyXman** [comment] 2022-03-11 19:42
It _is_ off, I only upload on wifi.

**Comment by mnalis** [comment] 2022-03-11 23:37
Two **major** battery drainers I've seen while mapping are:
- screen `on` time (and related: screen brightness). So, turn screen off when there is a gap between quests, and reduce brightness. (relatedly, might also try using dark mode if your phone has OLED display) 
- `mobile data` enabled in any capacity. When I need to conserve battery, I prefer to preload quests in advance, and then turn mobile data completely off. If I need to load more data, it's best done in batches (with mobile data turned on only for brief period why I load several areas for next 15+ minutes of walk, and then immideately turned off again. Yes, it is clunky, but it saves a huge amount of power, especially if you also have other apps on mobile phone like instant messengers, email clients, routing apps...)
