### ISSUE TITLE
Splitting a road for lanes and sticky pins

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2338] opened 2020-12-02 23:56 UTC
I managed to split a road into two during the lanes quest, then ended up with the original quest pin and the more northerly split one. On selecting the top one it worked as expected, on selecting the middle one it then revealed the southerly one and selected that bit of road. It would come and go I think as I selected and deselected it.

**How to Reproduce**

1. Split a road
2. Upload the split
3. Search for new quests
4. See it happen

Don't change the view so its off the map, or switch away from SC during the above.

I haven't tried to reproduce again since to not generate garbage data on the map. It did eventually clear when the map redrew later on having switched away from it.

**Versions affected**
SC v27.0beta3

**Comment by westnordost** [comment] 2020-12-03 00:07
Not sure if I understood your description.

Were you able to tap on the "bogus" pin?

**Comment by peternewman** [comment] 2020-12-03 00:34
Yeah, you'd tap on it and then the "correct" one (i.e. presumably the shortened original way; indeed confirmed based on ID numbers) would then appear (with it's new centred pin) and you could answer the quest if you wanted (didn't try submitting) or it could be deselected and then you were left with two or three pins (I can't remember) and you could repeat the process.

**Comment by westnordost** [comment] 2020-12-03 00:42
You tap on it, then the "correct" pin appears? It is not visible before?

**Comment by peternewman** [comment] 2020-12-03 00:57
No, certainly not the first time. I think it kept vanishing.

This is the first time I've seen it, but I normally split, wander off, upload eventually revisit the site much later.

**Comment by westnordost** [comment] 2020-12-03 23:42
I tried to reproduce it but couldn't. 

Could what you are seeing maybe be this? https://github.com/westnordost/StreetComplete/issues/2338
(Quests that have been removed already still "flicker in" while zooming)

**Comment by westnordost** [comment] 2020-12-03 23:51
By the way, regarding possible data corruption:
1. this is what beta version are for. If you are worried about data corruption, the more reason to dive right into it / try to break it when using a beta version.
2. what should happen at most if there is really such an old quest around that refers to an old version of the unsplit way, that if you answer and try to upload it, a conflict will be detected and your answer be dropped. Maybe, "worst case," your answer will be applied after all, but to the new shorter segment.

**Comment by peternewman** [comment] 2020-12-04 00:09
> Could what you are seeing maybe be this? [tangrams/tangram-es#2133](https://github.com/tangrams/tangram-es/issues/2133)
> (Quests that have been removed already still "flicker in" while zooming)

I don't believe so, I've seen that issue before and this wasn't that.

> By the way, regarding possible data corruption:

I meant more generating lots of unnecessarily split ways in the process of trying to test it.

I just did a few which are probably genuine and couldn't reproduce it, but they also weren't correctly auto-uploading until I tapped on the upload button for some reason.

**Comment by westnordost** [comment] 2020-12-04 00:14
> I just did a few which are probably genuine and couldn't reproduce it, but they also weren't correctly auto-uploading until I tapped on the upload button for some reason.

Okay, can't reproduce that either.

**Comment by RubenKelevra** [comment] 2020-12-04 08:36
@peternewman can you do a screen capture of the issue?

**Comment by peternewman** [comment] 2020-12-04 14:55
Yeah I will do if it happens again. It was currently a one off, but that might just be because of where it happened and hence how I used the app afterwards.

**Comment by rhhsm** [comment] 2020-12-06 15:34
I've seen this too. It seems to happen when trying to answer a quest on a split way while quest answers are uploading on a weak Internet connection. Might be related to #2211

**Comment by peternewman** [comment] 2020-12-06 15:50
> I've seen this too. It seems to happen when trying to answer a quest on a split way while quest answers are uploading on a weak Internet connection. Might be related to #2211

Glad it's not just me. I didn't see it a second time in similar circumstances, although I was online the whole time on the clean attempt I think.

Yeah it sounds similar to that @rhhsm although different code from the sounds of things.

**Comment by westnordost** [comment] 2020-12-08 15:26
> I've seen this too. It seems to happen when trying to answer a quest on a split way while quest answers are uploading on a weak Internet connection. Might be related to #2211

Right, this may be it.

Normal quest answers are uploaded before splitting of the ways are uploaded. (Deliberation: You want previous answers that apply to the whole way upload without conflict before splitting the way into several pieces.) However, for each uploaded element **during** the upload, it is checked whether new quests apply now for this element (`OsmQuestGiver.kt`). If I remember correctly, till v27, it was not checked whether there is already a to-be-uploaded split-way for that element. So the lane quest was simply recreated.

I changed this now in v28, so chances are very high (if my assumption about the origin of the bug is correct) that this issue is gone now. I'll close this and if it occurs again in v28.x, let me know.

**Comment by rhhsm** [comment] 2020-12-08 15:49
I think so too. I noticed it again today: during a survey I split a way and it disappeared (being offline). When I came near an open wifi connection, the un-split way re-appeared and was selectable (it looked like I failed to split it), but I didn't answer it. Some moments later, the quests for the new split parts of the way appeared while the un-split quest pin was still visible, but no longer selectable (screenshot). I answered the quests for the 2 new sections, and all quest pins disappeared. If I had split the un-split way again while it was selectable, could that have lead to the bug described in #2211? I might have done that when that bug happened.
![Screenshot_20201208-140453~2 1](https://user-images.githubusercontent.com/69100427/101505719-55510380-397d-11eb-9a80-02e8c53276ab.png)

**Comment by peternewman** [comment] 2020-12-09 01:50
> If I remember correctly, till v27, it was not checked whether there is already a to-be-uploaded split-way for that element. So the lane quest was simply recreated.

That doesn't quite tie up with me only seeing this on v27.0beta3, although I don't generally do huge amounts of way splitting, and rarely on a bit of the map that's still visible when I get to WiFi.

> I think so too. I noticed it again today: during a survey I split a way and it disappeared (being offline). When I came near an open wifi connection, the un-split way re-appeared and was selectable (it looked like I failed to split it), but I didn't answer it. Some moments later, the quests for the new split parts of the way appeared while the un-split quest pin was still visible, but no longer selectable (screenshot).

Interesting that yours finished in an un-selectable state @rhhsm when I was home and sitting on WiFi I could always re-select the middle pin until it vanished entirely when I relaunched or panned the map around or something.

**Comment by rhhsm** [comment] 2020-12-12 19:19
I got another one yesterday that is still selectable, see screenshot showing the surface quest for the whole way, and a pavement quest for part of it. After splitting the way because it has several alternating sections of sett and asphalt, I caught a wifi signal that made quests for the southern 3 sections appear (most of which I answered). However, the surface quest for the whole way stayed, and new quests for the northern section didn't appear. @westnordost , would you like me to try what happens if I split the old way again?
![Screenshot_20201211-172926~2 1](https://user-images.githubusercontent.com/69100427/101992995-9ae43800-3cbf-11eb-825f-91fd0e9ea07a.png)

**Comment by westnordost** [comment] 2020-12-13 00:55
With v28.0-beta1?

**Comment by rhhsm** [comment] 2020-12-13 06:58
No, 27.2. According to Google Play, no update is available.

**Comment by westnordost** [comment] 2020-12-13 14:23
Ok, yes it is still in beta

**Closed by westnordost** 2020-12-13 14:23 UTC
Labels: bug, feedback required

**Comment by peternewman** [comment] 2020-12-13 21:06
I know you were trying to reduce the numbers on the beta, but is it worth inviting @rhhsm to it given they seem to be far more effective at reproducing this issue than me!
