### ISSUE TITLE
Easier surveying of multi story malls/shopping centres

### ISSUE THREAD

**Issue by Dimitar5555** [streetcomplete/StreetComplete#5526] opened 2024-03-08 07:51 UTC
**Use case**

You can't choose on what level you are when you are surveying shops, located in malls/large shopping centres. If the mall has every shop on every level you can't easily see what needs to be checked on each floor individually. (The shops overlay also doesn't help, since it hides the `level` tag and can't filter based on it but that is another issue).

Examples of such places: [The Mall, Sofia](https://www.openstreetmap.org/edit#map=19/42.66077/23.38337), [Paradise Center, Sofia](https://www.openstreetmap.org/edit#map=19/42.65765/23.31481)

**Proposed Solution**

Add some way for the user to say "I've entered this mall/building. Show me shops on level X". Then hide all quests which are on the other levels.

Alternatively, group all quests to the building and show only one pin. When the mapper clicks it, say "There are X quests about things in this building. Do you want to enter the building and survey them?" If the users selects "Yes", add a level selector on the screen and show the relevant quests. Somewhere there should be a button to let the app know that you've left the building.

A third option would be to add levels selector on the shops overlay and show quests there in some way.

Reported based on https://www.openstreetmap.org/changeset/148349559
cc: @rhhsm

**Comment by rhhsm** [comment] 2024-03-08 08:02
Thanks for suggesting this, Dimitar, but I think it's a duplicate of #2874 and #3068

**Comment by Dimitar5555** [comment] 2024-03-08 08:45
I haven't seen the two issues you mentioned. The second solution is a bit different since it gives you new buttons in the UI only when needed. The last option is a lot more versatile in other situations as well (like subway stations/pedestrian underpasses with shops and buildings with store fronts on two or more levels),

**Comment by mnalis** [comment] 2024-03-08 20:33
You may want to try [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (_SC "Expert Edition"_) fork, which has (among other things) capabilities for level filtering via quick button, i.e.:

![small_Screenshot_20240308_212853_SCEE](https://github.com/streetcomplete/StreetComplete/assets/156656/28785b5f-37d7-41d6-8b32-fc063aa73d43)

You can have SCEE installed alongside regular StreetComplete to try it out without one affecting the other, and by default SCEE will look very similar to regular SC, hiding most of its features until you explicitly enable them in `Settings`.

**Comment by rhhsm** [comment] 2024-03-12 12:05
The underlying problem is that there often are overlapping quest pins even at the highest zoom level (see #2878, #2373). Would it be possible to control the display of quest pins by taking into account the value of any `level=*` tag, so that the quest pin with the highest `level` value is always shown on top when there are overlapping pins? A user could then start surveying the upper floor of a shopping mall and systematically go down until all quests are solved.

**Closed** 2024-04-08 13:58 UTC

**Comment by riQQ** [comment] 2024-04-09 05:56
See #3123 for migration to MapLibre
