### ISSUE TITLE
Add building type 'cabin'

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2524] opened 2021-01-23 14:21 UTC
**Use case**
I've searched for the right building type for a well build garden house which are pretty common in Germany in allotment gardens. 

Looks like cabin could be fitting according to the wiki, but it appears to be missing in StreetComplete. And bungalow is fitting its even better equipped like a summer house. 

**Proposed Solution**
Add some help text to  help the user to decide this case more easily and add the missing building type cabin.

**Comment by FloEdelmann** [comment] 2021-01-23 14:27
See #2047.

**Comment by matkoniecz** [comment] 2021-01-23 16:11
English description of bungalow option is following

> small detached house (summer house, holiday cottage, cabin …)

Is German translation including last word?

**Comment by FloEdelmann** [comment] 2021-01-26 08:15
The current German translation of the Bungalow option's description:

> kleines, freistehendes Haus (Gartenhaus, Ferienhaus oder -hütte)

So the last word is sort of included. You can read it as "summer house, holiday cottage, holiday cabin".
We could change it to something true to the English version:

> kleines, freistehendes Haus (Gartenhaus, Ferienhaus, Hütte, …)

**Comment by westnordost** [comment] 2021-01-26 13:00
Actually, as far as I know, bungalows are defined to be mostly these kind of holiday cabins. Current wiki definition:

> small, single-storey detached house in the form of a bungalow.
> 
> Often (but not always) the house has lightweight construction with a flat roof and a veranda. Often small cottages, summer houses, or dachas. A bungalow is often intended to be used as a tourist accommodation. 

https://wiki.openstreetmap.org/wiki/Tag:building%3Dbungalow

So, translation into German is correct. Bungalows may be a cabin, but not a _Hütte_ in general (Hütte has a wider meaning) - only a _Ferienhütte_.

Otherwise, I am closing this issue as duplicate of #2047 .

**Closed by westnordost** 2021-01-26 13:00 UTC
