### ISSUE TITLE
ability to see image large after accept

### ISSUE THREAD

**Issue by BuZZ-dEE** [streetcomplete/StreetComplete#4254] opened 2022-07-30 20:27 UTC
ability to see image large after accepted from camera.

**Comment by matkoniecz** [comment] 2022-07-30 21:06
why?

**Comment by BuZZ-dEE** [comment] 2022-07-30 21:09
To control the photo, if e.g. all the information is available that it should show.

**Comment by mnalis** [comment] 2022-07-30 21:37
duplicate of https://github.com/streetcomplete/StreetComplete/issues/2497 ?

**Comment by matkoniecz** [comment] 2022-07-30 21:43
it seems so

**Closed by matkoniecz** 2022-07-30 21:43 UTC
Labels: feedback required

**Comment by BuZZ-dEE** [comment] 2022-07-31 07:56
@matkoniecz why is it closed as completed and not closed as duplicate? What is completed?

**Comment by matkoniecz** [comment] 2022-07-31 08:07
Github has no option "close as duplicate". To keep my sanity I interpret it as "completed processing this issue".

Github has option "close as not planned", but #2497 exists.

If you dislike it, feel free to report problem to Microsoft which controls GitHub if you want.

![screen15](https://user-images.githubusercontent.com/899988/182016232-f40a4e1f-1cbb-42ba-9db1-b996ee505a74.png)

**Comment by riQQ** [comment] 2022-07-31 08:40
GitHub deems "closed as not planned" to include "duplicate" as you can see when hovering the status.

GitHub also allows to mark duplicates by writing a comment "Duplicate of #x" (no full stop, no other additional characters) as a collaborator.

**Comment by matkoniecz** [comment] 2022-07-31 08:47
Duplicate of #2497
