### ISSUE TITLE
Filter quests by building level

### ISSUE THREAD

**Issue by ScharadaValcta** [streetcomplete/StreetComplete#6005] opened 2024-11-11 00:18 UTC
**Description: **
I'd like to request a feature that allows users to set and filter quests by building levels. This would be particularly useful in complex, multi-level locations such as shopping malls, train stations, and airports.

**Use case**
This feature would be especially helpful for users mapping detailed interior spaces. With level-specific filtering, users can focus only on the quests relevant to the floor they’re on, improving mapping accuracy and efficiency in multi-level environments.

**Proposed Solution**
Set Level Information - Add a function where users can specify the current level/floor of a building.
Level-based Quest Filtering - Enable filtering options to show only the quests on a specific building level. For example, if I'm on level 2, I could filter quests to display only those located on level 2.

Thanks for considering this addition!

**Comment by riQQ** [comment] 2024-11-11 06:04
Duplicate of #3068

**Comment by matkoniecz** [comment] 2024-11-11 07:06
and #2874 :(

**Closed** 2024-11-11 07:05 UTC
