### ISSUE TITLE
Allow multi-select for certain quests

### ISSUE THREAD

**Issue by pigsonthewing** [streetcomplete/StreetComplete#3286] opened 2021-09-14 19:38 UTC
**Use case**

In some cases (see screenshot, attached), such as a row of identical houses, viewable from a single location, or by driving down a street, it is possible to determine a characteristic that can be applied to all the buildings, with the same value (e.g. "two stories", "flat roof", "residential").

It is tedious to have to apply all these identical changes sequentially.

**Proposed Solution**

The user should be able to activate a "multi-select" mode, select all the applicable targets (perhaps with a sensible maximum number, or geographic range), then apply one change to all of them in one go.

![2021-09-10 09 27 09](https://user-images.githubusercontent.com/89541/133322332-c4bb3486-85fe-482b-adcd-df33d99171a6.jpg)

**Comment by riQQ** [comment] 2021-09-14 19:50
Duplicate of #2996

**Closed** 2021-09-14 21:41 UTC

**Comment by westnordost** [comment] 2021-09-14 21:44
Please recognize that we can't have the same tickets over and over again. If you have anything to contribute, you should post it in the old ticket, not in a new one. Note that it has been closed as will not fix.
