### ISSUE TITLE
North orientation button behaviour is confusing

### ISSUE THREAD

**Issue by NoeFalque** [streetcomplete/StreetComplete#2817] opened 2021-04-28 10:52 UTC
Expected : When the map is not oriented to North, a first click on the orientation button should tilt the map to face North. When the map faces North, it should toggle the 3D view.

Bug : A few times while in 2D view with the map not facing North, clicking the orientation button triggered 3D view without tilting orientation towards North. 

**How to Reproduce**

I haven't found a systematic way to reproduce this... I'll try to record it when it happens again.

**Versions affected**

Android 10 (OnePlus 5 Oxygen 10.0.1)
SC v31.3

**Comment by smichel17** [comment] 2021-04-28 12:32
It's intentional that it will tilt when it's facing "approximately north" (within ~4%), see https://github.com/streetcomplete/StreetComplete/pull/1725
Is that maybe what you're running into?

**Comment by cyclingcat** [comment] 2021-04-28 19:34
I observed a similar (or identical?) effect a few times during the past months. I was never able to reproduce it, the phenomenon occured very intermittently and finally I blamed it to my cheap China smartphone whose sensors I suspect to behave sometimes unreliably for other reasons. So I refrained from opening a ticket until now.

But now we are three.  If I'll ever face this phenomenon again I will do some testing and post all information here.

The cycling cat

**Comment by mnalis** [comment] 2021-04-28 20:00
@cyclingcat I've also had issues with it more than a few times... Compass arrow pointing more than 5% (in some cases maybe even close to 90% or 180%) away from north, but pressing it just switched 3d / birdseye view, instead of rotating to north first. 

I always assumed it was just me never having red the docs to explain how to switch 3D, if there is combo and order or length of pressing GPS button and Compass buttons... but by the time I got home I just never remembered to file the issue that it needs to be documented (or fixed).

**Comment by NoeFalque** [comment] 2021-04-29 06:17
> It's intentional that it will tilt when it's facing "approximately north" (within ~4%), see #1725
> Is that maybe what you're running into?
It happened a few times with an orientation tilted far more than 5%

**Comment by mnalis** [comment] 2021-05-02 21:45
I've managed to capture video demonstrating this behavior when clicking compass icon, although I wasn't yet able out what exactly is causing it.

https://user-images.githubusercontent.com/156656/116828664-6276c500-aba0-11eb-818f-dc032ab7af38.mp4

**Comment by westnordost** [comment] 2021-05-02 22:52
You are in the follow-me mode, that's all

**Comment by smichel17** [comment] 2021-05-03 01:24
So it seems like this can be summarized as,

**Steps to reproduce:** enter compass mode\*, then tap the compass to exit

**Expected result:** map un-tilts and rotates so north is up

**Actual result:** map un-tilts but does not rotate

**Response:** This is currently the intended behavior.

\*aside, this is probably not the best name for it, as it does not follow the compass at all. Maybe we should call it "orientation mode" or something.

**Comment by mnalis** [comment] 2021-05-03 14:46
I'll open a new ticket (and link it here) to suggest help screen explaining that part of UI, as after a lot of time using SC I am still quite confused by how that specific part of UI is supposed to work (and vast majority of UI is ultra simple by contrast). For some time, I was even heavily convinced that there was a hidden button between `menu` and `compass` which does something differently then just pressing `compass`.

It seems to me that there are several different UI modes, many of which can be intermixed, and **same buttons do different results** depending on not only the current mode, and on status of some variable (like declination from north), but also what key/gesture was pressed before or after. Learning [vi editor](https://www.tutorialspoint.com/unix/unix-vi-editor.htm) modes was much simpler.

There seems to be:
- 3D (with several tilt levels) vs. 2D (more precisely, 3D birdseye mode which looks mostly like 2D)
- GPS location mode (screen is centered on current location with dot) vs. manual location mode (screen is moved away from current location with dot)
- orientation sensor map auto-rotation mode (whole screen rotates so the pie-sector from current location dot always points up) vs. manual rotation mode (screen does not rotate for current manually set orientation [with North is up as semi-special case], and only pie-sector from current location dot changes when user rotates around their own axis).

Especially 2 and 3 seems to be often interlinked, but so does 1 and 3. But not always (and I'm still unable to determine exact sequence to choose, much less determine if that is intended behavior, or maybe in some cases a bug?)

**Comment by smichel17** [comment] 2021-05-03 17:10
I will use slightly different terminology than you.

There is **unlocked camera mode**, where the map can be freely panned, and **locked camera mode**, which follows your location. Locked camera mode has a variation, **follow orientation mode**, which tilts the map and rotates with the pie section (aka your phone's orientation).

My understanding is that "3D birdseye" is (nearly?) the same thing as regular 3D, where there is no tilt (tilt level 0, if you like). I also don't think there's discrete levels; you can tilt as much or as little as you'd like using a two-finger vertical swipie/drag.

- The app starts with the camera unlocked.
- Pressing the location button centers the map on your location and switches to locked camera mode.
    - You can tell you're in locked camera mode because the location button disappears.
    - The compass toggles between the two variations.
- Panning the map switches back to unlocked camera mode.
    - While unlocked, tapping the compass rotates the map to be north and flat. If it already is that orientation, it tilts the camera a little instead. This is for discoverability, since two finger drag is hard to find without someone telling you about it.

**Comment by smichel17** [comment] 2021-05-03 17:26
That is, 1 and 3 are not linked in any _functional_ way, the same as 1 and 2 are not linked in any functional way. They are somewhat linked *conceptually*, in that locked camera + tilted map is not very useful without also following your orientation (try it! You'll quickly end up in a situation where the quest you're looking at is off screen because the screen is tilted the wrong way). That is, you could think of it like:

- Compass switches between flat and tilted
- Location button / panning switches between locked and unlocked

**Comment by mnalis** [comment] 2021-05-04 00:46
thanks @smichel17 for detailing! I'm trying to process that and try it in practice... so if I understand you correctly, pressing compass icon is overloaded to do one or more of the following actions:
- rotate map so North is "up"
- set 3D tilt to 0 (AKA "birdseye" / "pseudo-2D" mode)
- set 3D tilt to maximum ("full 3D")
- enable **follow orientation mode**
- disable **follow orientation mode**

And which of those action(s) will happen depends upon previous application state? No wonder it's highly confusing to me. I'll try it in practice with your cheatsheet to see if it becomes more clear with practice, perhaps it can explain confusing behaviors I (and @cyclingcat and @NoeFalque) have been noticing!

**Comment by smichel17** [comment] 2021-05-04 17:15
<details>
<summary>@mnalis That's true, with two nitpicks: it is not the maximum tilt, just an arbitrary amount (π/5) that looks nice; maximum tilt is too much to be useful, imo. And while yes, there are 5 possible behaviors, they don't happen in arbitrary combinations.</summary>

- **If the map is tilted,** set 3D tilt to 0. *If following location, disable follow orientation mode.*
- **If the map is flat**, set 3D tilt to π/5. *If following location, enable follow orientation mode.*
- EXCEPTION: **If the camera is unlocked and the map is not pointing north,** set 3D tilt to 0 and rotate to point north.
</details>

IMO, ***the main confusing part*** is that the compass has a *different "cadence"* in locked vs unlocked camera mode: If the map is flat but not pointing north, it takes one press to tilt if the camera is locked and two presses if the camera is unlocked. Otherwise, while it may have different behaviors depending on whether the map is unlocked, it's still "just" a toggle in either case.

A secondary source of confusion is that follow orientation mode changes the orientation (duh), in a different way than setting it to north, so the "tilt" action is reversed in its relationship with facing north — when the camera is unlocked, tilting never changes the orientation and un-tilting sometimes does; when the camera is locked, tilting always changes the orientation and un-tilting never does.

**Comment by westnordost** [comment] 2021-06-07 12:45
well anyway, closing as working as intended

**Closed by westnordost** 2021-06-07 12:45 UTC

**Comment by mnalis** [comment] 2021-06-07 22:23
@westnordost should I make the ticket to suggest documenting how this behaviour works?

**Comment by westnordost** [comment] 2021-06-07 23:33
I do not intend to create an in-app tutorial on how the compass button works.

**Comment by mnalis** [comment] 2021-06-07 23:48
@westnordost  OK, I understand. Perhaps you would accept an entry on https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ or a page under https://github.com/streetcomplete/StreetComplete/wiki, though?

**Comment by westnordost** [comment] 2021-06-08 00:05
Sure, I don't reign supreme over the wiki

**Comment by mnalis** [comment] 2021-06-08 12:23
Thanks, I've added (mostly) @smichel17 explanation to FAQ.

@westnordost would you consider PR which adds link to https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ in `About` screen?
