### ISSUE TITLE
Feature request: sound notification when nearby a quest

### ISSUE THREAD

**Issue by NotSoImportant** [streetcomplete/StreetComplete#2470] opened 2021-01-08 22:16 UTC
**Use case**
When going outside I don't want to look at the phone all the time. But once I get along one of my selected quests I can turn it on and contribute. 

**Proposed Solution**
Configurable sound when near a quest. Default disabled. 

I know that if you like to there is a quest every few meters. When having all quests selected it won't help. 
Alternatively this could be a setting per quest type, like giving a hint about quests I see as important.

**Comment by westnordost** [comment] 2021-01-09 00:03
Well, nice idea to have it enabled for specific quests based on user preference. This is a duplicate of #48 though

**Closed by westnordost** 2021-01-09 00:03 UTC
