### ISSUE TITLE
v59 broke dark mode

### ISSUE THREAD

**Issue by mxxcon** [streetcomplete/StreetComplete#5907] opened 2024-09-18 17:21 UTC
It seems like v59 broke dark mode on credits, privacy and changelog screens.
![Screenshot_20240918_131339_StreetComplete](https://github.com/user-attachments/assets/ac1cb9a8-d2f0-4a38-a6f1-84e8aeb8c4e9)
![Screenshot_20240918_131334_StreetComplete](https://github.com/user-attachments/assets/993352fc-6cfb-48b5-bff1-2a910a2bf4e1)
![Screenshot_20240918_131314_StreetComplete](https://github.com/user-attachments/assets/88928d28-4e47-4533-933f-b3b175b66e24)
![Screenshot_20240918_130919_StreetComplete](https://github.com/user-attachments/assets/3cb2c366-bdcc-46b7-a886-02c612e1e40f)

**How to Reproduce**
Set theme to dark

**Expected Behavior**
Text should be readable in dark mode.

**Versions affected**
v59 release. I don't remember if v59-beta1 had this problem.

**Comment by kmpoppe** [comment] 2024-09-18 18:17
Duplicate of #5906

**Closed** 2024-09-18 18:21 UTC
Labels: bug
