### ISSUE TITLE
Relation removal?

### ISSUE THREAD

**Issue by DaveF63** [streetcomplete/StreetComplete#5243] opened 2023-09-11 10:57 UTC
I've had enough of my time wasted so can't be bothered to re-explain: 

https://lists.openstreetmap.org/pipermail/talk-gb/2023-September/030651.html

**Comment by Helium314** [comment] 2023-09-11 11:02
Maybe you should turn down your laziness and bother to explain what was removed. In the linked changeset I can't see any deletions.

**Comment by matkoniecz** [comment] 2023-09-11 11:20
I am now trying to figure out what is the problem, as reporter has not bothered to specify it.

It seems to be about splitting way belonging to relation https://www.openstreetmap.org/relation/1318928 and new way not being added to this relation, right?

If yes, then it is a bug as StreetComplete is supposed to do this.

But can you specify which StreetComplete changeset damaged data? And which newly created way is problematic? You are sure that StreetComplete caused this so you found it already, right?

**Comment by matkoniecz** [comment] 2023-09-11 11:23
I am asking as it is entirely possible that data was damaged already before StreetComplete edit was done.

I am trying to track down which edit (changeset link needed!) split way (way link needed!) resulting in relation not being assigned to new way (relation link needed!). I tried to find based on complaints you linked but not found it so far.

**Comment by matkoniecz** [comment] 2023-09-11 11:34
@DaveF63 Why https://www.openstreetmap.org/way/1200830328/history linked in https://lists.openstreetmap.org/pipermail/talk-gb/2023-September/030651.html is relevant?

https://www.openstreetmap.org/way/1200830328/ is missing one of relations carried by https://www.openstreetmap.org/way/4064210

But I so far have failed to find tool which would allow me to show history of affected relation. For example https://osm.mapki.com/history/relation/1318928 crashed, history tab on OSM website has not shown anything.

Maybe I will check Overpass Turbo attic next.

(what is needed is confirmation that it was caused by StreetComplete in the first place - if you sure, please explain why so this problem can be investigated)

**Comment by Helium314** [comment] 2023-09-11 11:37
> It's not my, or anyone's, job to beta test this software.

If you want to report a problem, it's your job to report the problem.

**Comment by kmpoppe** [comment] 2023-09-11 11:46
@matkoniecz I put in my two cents in the linked talk-gb discussion, so I will try to be helpful here as well.

I **think** w/1200830328 was newly created by u/GregZ0r with the "Sidewalk" quest. And that way was only added to TWO relations out of the THREE that w/4064210 was part of (missing r/1318928).

So we **might** be looking at SC not downloading all of the relations a way is part of.

**Comment by matkoniecz** [comment] 2023-09-11 11:48
See http://overpass-turbo.eu/s/1A91 - directly after SC edit it WAS with relations.

Can you explain why you think that it was damaged by StreetComplete? Or have you randomly complained about StreetComplete without investigating situation and not bothered to check reason for missing data?

![screen01](https://github.com/streetcomplete/StreetComplete/assets/899988/ef56739f-af7e-4f50-8e1a-db26cd7fb059)

**Comment by matkoniecz** [comment] 2023-09-11 11:50
> And that way was only added to TWO relations out of the THREE that w/4064210 was part of (missing r/1318928).

Why you think this? Currently it has two relations, but according to Overpass Attic data it had three after SC edit.

I am still trying to get more readable relation history and investigate why it lost this relation.

**Comment by kmpoppe** [comment] 2023-09-11 11:52
> Why you think this? Currently it has two relations, but according to Overpass Attic data it had three after SC edit.

You're totally right, Overpass confirmed that, I was merely trying to figure out what OP was complaining about. Think I found another part of the answer, see next post.

> I am still trying to get more readable relation history and investigate why it lost this relation.

Yeah, object versions > 100 just get unusable through the website.

**Comment by systemed** [comment] 2023-09-11 11:58
Way 1200830328 is not present in the current version (v495) of relation 1318928.

It was not present in [v494](https://www.openstreetmap.org/api/0.6/relation/1318928/494), after changeset [140229519](https://www.openstreetmap.org/changeset/140229519).

It was present in [v493](https://www.openstreetmap.org/api/0.6/relation/1318928/493), after changeset [140183021](https://www.openstreetmap.org/changeset/140183021) in which it was created.

(It was not present in v492 or earlier.)

**Comment by kmpoppe** [comment] 2023-09-11 12:04
I think @DaveF63 's complaint in the comments https://www.openstreetmap.org/changeset/138855527 was that this part of the NCN4 relation has a missing part:
![grafik](https://github.com/streetcomplete/StreetComplete/assets/24451207/b33292fb-b0e1-4957-ae9f-42556118e15e)

This area corresponds with the area the changeset was in, and
way/1191428727, way/1191428728 and way/1190685472 were split off from way/6556177 - and they are NOT part of the relation as of now.

Could it be (given that the "new" way numbers are quite a few apart), that the changeset was uploaded in multiple steps (over the course of being open for an hour) and the way was split twice, which THEN lead to SC not finding all the relations (the first split not being in a closed CS or something).

**Comment by matkoniecz** [comment] 2023-09-11 12:05
So to summarize: 

OpenStreetMap user [DaveF](https://www.openstreetmap.org/user/DaveF) damages data in changeset [140229519](https://www.openstreetmap.org/changeset/140229519) and damages relation connectivity

Dave F posts on talk-gb how StreetComplete is terrible as it breaks relation connectivity and insults it

@DaveF63 Github account creates cryptic bug report how StreetComplete breaks data

I spend 40 minutes on investigating it.

@systemed confirms actual data breakage reason

-----------------

lesson to be learned from that: next time someone posts unclear bug report alleging data damage that has insults instead of bug report, close it on sight and link https://www.chiark.greenend.org.uk/~sgtatham/bugs.html rather than try to investigate it

**Closed by matkoniecz** 2023-09-11 12:05 UTC
Labels: bug, feedback required

**Comment by matkoniecz** [comment] 2023-09-11 12:08
> This area corresponds with the area the changeset was in, and way/1191428727, way/1191428728 and way/1190685472 were split off from way/6556177 - and they are NOT part of the relation as of now.

From what I see in https://overpass-turbo.eu/s/1A9b

![screen02](https://github.com/streetcomplete/StreetComplete/assets/899988/41fd2f8a-5fb2-40b4-95a3-9b05467f7e24)

it was perfectly fine after StreetComplete edit was closed

Which relation is missing there? Or maybe I misinterpret OSM data?

**Comment by matkoniecz** [comment] 2023-09-11 12:10
yep, way 1191428727 was removed (according to https://osm.virtuelle-loipe.de/history/?type=relation&ref=1318928 ) not in StreetComplete edit

**Comment by matkoniecz** [comment] 2023-09-11 12:16
@DaveF63 Can you post followup to https://lists.openstreetmap.org/pipermail/talk-gb/2023-September/030660.html clarifying what actually happened? And do the same elsewhere if you complained about this also in other places?

**Comment by kmpoppe** [comment] 2023-09-11 12:23
> Which relation is missing there? Or maybe I misinterpret Overpass data?

Nope, you're not, **I** was fooled by the history of the ways not showing which relations they were part of but only the current version, where NCN4 was missing. Darn it.

**Comment by matkoniecz** [comment] 2023-09-11 12:24
Yeah, relation membership not showing up in history mode eaten at leat 10 minutes of my investigation.

**Comment by kmpoppe** [comment] 2023-09-11 12:26
Feature request for [openstreetmap/openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website/issues)?

**Comment by Martin-Wynne** [comment] 2023-09-12 08:44
I can't follow much of this, but I do know that the best solution is to switch off the computer and have a nice boiled egg.

The next time you switch it on, the whole thing will have blown over, and the sky won't have fallen in.

cheers,

Martin.
