### ISSUE TITLE
SC asks for surface of way that already has a surface tag, and then removes other tags

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#4863] opened 2023-03-08 17:29 UTC
**How to Reproduce**
It's about this little way https://www.openstreetmap.org/way/690999884 
(highway=track
smoothness=horrible
surface=ground
tracktype=grade2)

1. After scanning for quests, a surface quest shows up for this way.
2. I answer it with "ground (generic)"
3. SC asks "This answer is not matching what is already mapped about this road. Are you sure that you are answering about the correct road? Are you sure that you personally surveyed along entire length, as always needed?"
4. I reply "Yes I'm sure"
5. I press undo: it shows that this will undo removal of `tracktype` and `smoothness` tags, update of `surface `to `ground `(which it already was) and addition of a `check_date`

**Expected Behavior**

1. Ways that already have a `surface` tag don't show up as surface quests
2. Setting the `surface` tag to what it already was will not trigger the "This answer is not matching what is already mapped..." question
3. Changing a `surface` tag will not remove `tracktype` and `smoothness` tags unless it is a major change that clearly requires requesting (i.e. change from `ground` to `dirt` should not remove other tags, while a change from `ground` to `asphalt` should).

**Versions affected**
Android 10 and StreetComplete 51.1

**Comment by matkoniecz** [comment] 2023-03-08 17:43
Do you think that this road matches both `surface=ground` and `tracktype=grade2` info? If yes, can you share a photo of it?

**Comment by mnalis** [comment] 2023-03-09 04:57
> It also fits best with grade2 track type "gravel mixed with a varying amount of sand, silt, and clay".

Hmm, to me (note that the quest asks about `Surface firmness of this track`):
- `grade1` is asphalt or concrete, so fully paved/sealed.
- `grade2` is just a level below that -- e.g. vast majority of it must be hard-packed `gravel` or good `compacted` (yeah some _small_ amount of sand/silt/clay to fix it is ok, but not loose / uncompacted) - but it should have so much gravel and be so compacted that is practically impervious to large amount of rain (i.e. mostly do not change its characteristics after a rain at all) both for e.g. bicycle and for a heavy vehicle like tractor. 
- if the amount of dirt/sand/clay increases and becomes noticeable, (and even comparable!) to amount of gravel, then it becomes `grade3` (and rain changes how it behaves noticeably) 
- if the amount of dirt/sand/clay increases even more and becomes majority, then it is `grade4` (and rain changes how it behaves hugely).
- if basically no gravel (or only trace amounts of it) remains, then it is `grade5`.

Also, I think of `surface=ground` as generic totally-unpaved (and never improved / touched by humans), i.e. combination of `dirt` / `mud` / `clay` / `grass` - to be used if it changes every few meters so it doesn't make sense to split a way thousand times. So `surface=ground` can only be `grade5` or maybe sometimes `grade4` (if it much closer to `grade5` than `grade3` - i.e. has only very tiny amounts of gravel). 

But if the track is `grade3`  (much less `grade2`!), then it (IMHO) can no longer be `surface=ground` but instead `surface=compacted` or `surface=gravel` or `surface=fine_gravel` or `surface=rock` and similar as that is their primary composition which defines most of their behaviour (even if they have _some_ impurities like dirt, clay etc.)

> One could argue that a mixture of gravel, sand and clay can't be anything but ground

Well, yeah, one could also argue that any surface not submerged under ocean and other bodies of water is "[ground](https://en.wiktionary.org/wiki/ground)". But I do **not** think that `surface=ground` in OSM is to be an equivalent of `surface=unpaved`, even if by some definitions it might be read that way. 

---

So in my opinion too, there could be **no** `surface=ground` combined with `tracktype=grade2` (or  `tracktype=grade1` or  even `tracktype=grade3`).

**Comment by matkoniecz** [comment] 2023-03-09 09:09
Is it this kind of surface?

![IMG_20210313_144242](https://user-images.githubusercontent.com/899988/223974143-44383eeb-71d3-4bcb-a6c4-08c13432ddb1.jpg)

**Comment by rhhsm** [comment] 2023-03-09 09:37
Yes, but it seems softer and smoother. I think I'd tag it with `surface=ground`, `smoothness=very_bad` (or `bad`, if my destination is just around the corner; I'd risk my normal car on this road only for a short distance) and `tracktype=grade3` because of the patches of dark mud. I've stopped tagging tracks with `tracktype`, though, because I think it's a tag with a very weak use case now that `smoothness` is available and well described. I'd propose it for depreciation if I knew how...

**Comment by matkoniecz** [comment] 2023-03-09 09:45
I guess that is a tagging discussion then, that should not take place here. Is there a chance that you can take or find a photo of such surface or similar? Google maps or photo from internet is fine, though images from Wikimedia Commons or other openly licenced one would be the best.

**Comment by rhhsm** [comment] 2023-03-09 10:48
Agreed. However I think in the meantime SC should be very careful in removing tags unless it is absolutely sure that they are the result of a change of conditions or mistake and not because of a disagreement on how to tag something. We should assume that users tag in good faith and after careful consideration of the options.

> **Expected Behavior**
> 
>     1. Ways that already have a `surface` tag don't show up as surface quests
> 
>     2. Setting the `surface` tag to what it already was will not trigger the "This answer is not matching what is already mapped..." question
> 
I'm still wondering about 1. and 2. I'd be in favour of re-questing `surface=unpaved` because it is likely that this can be improved (it's not given as an option in the surface quest), but `surface=ground` is quite likely to be the end result of a consideration. Reminds me of #2016

**Comment by matkoniecz** [comment] 2023-03-09 10:51
> 1. Ways that already have a `surface` tag don't show up as surface quests

This showed up as part of attempt to eliminate mismatching `track` and `surface` - and in some cases like `surface=sand tracktype=grade1` it definitely makes sense.

**Comment by rhhsm** [comment] 2023-03-09 11:10
> > 1. Ways that already have a `surface` tag don't show up as surface quests
> 
> This showed up as part of attempt to eliminate mismatching `track` and `surface` - and in some cases like `surface=sand tracktype=grade1` it definitely makes sense.

Maybe we should inform the user about the changes that will take place, and ask for confirmation (did this road really change?) (like we're asking "Is it a different place now?" after a major edit to a shop)

> `surface=cobblestone` is and should be reasked.

Absolutely! Plenty of them in my area, probably because of confusion with [this](https://en.wikipedia.org/wiki/Kalderimi)

**Comment by rhhsm** [comment] 2023-03-09 18:59
> Is there a chance that you can take or find a photo of such surface or similar? Google maps or photo from internet is fine, though images from Wikimedia Commons or other openly licenced one would be the best.

The picture illustrating `smoothness=horrible` on OSM wiki
![image](https://user-images.githubusercontent.com/69100427/224126795-8111f219-e1d0-4a7f-8a0c-a507dc6c787e.png)

**Comment by map-per** [comment] 2023-03-09 19:09
Here is another example: https://www.openstreetmap.org/way/345235534/history

StreetComplete deleted `smoothes=good` when concretizing the `surface` from `paved` to `asphalt`.
`smootheness=good` doesn't conflict with `surface=asphalt` in any way however.

**Comment by mnalis** [comment] 2023-03-10 01:35
> StreetComplete deleted smoothes=good when concretizing the surface from paved to asphalt.

After changing surface, user should've been immediately asked about smoothness (provided they have smoothness quest enabled, of course). 

> smootheness=good doesn't conflict with surface=asphalt in any way however.

It doesn't, but the surface **changed**, so its smoothness is expected to be highly likely to have changed too. 
Because, that previous `paved` might have been `unhewn_cobblestone` too, and now it is `asphalt`. There is no way for SC to know. Current method is to remove invalid data, so it will be asked again (hopefully of the same user, if they care about smoothness). 

Alternative would be when user tries to change the `surface` tag, that the user is force-asked about smoothness too (only in cases when smoothness tag is already present), and SC **refuse** to record **any** tags unless the user confirms **both** surface and smoothness. But that would be less ergonomic, in my opinion.

> Maybe we should inform the user about the changes that will take place, and ask for confirmation (did this road really change?)

How would that _"did this road really change?"_ question work? 

It seems to me that in such solution we be expecting users to **know** what was there previously. Except in very rare circumstances (e.g. user being asked about road in front of their own house which they see every day), they probably **wouldn't have any idea** what was that surface **at some undefined time in the past** (hey, it might even have changed 3 times in previous 10 years since user was there last - if they indeed were ever there before).

**Comment by mnalis** [comment] 2023-03-10 01:38
@matkoniecz I see you have self-assigned this; it might be good idea to discuss what change exactly you intend to implement (and if that is the best solution going forward)?

**Comment by matkoniecz** [comment] 2023-03-10 04:18
Well, the first step in this case is to look at issues raised here, at what this code was supposed to be doing and decide what, if anything, should be changed.

**Comment by rhhsm** [comment] 2023-03-12 18:26
I can't contribute to the code, but I'm happy to give my opinion on what it should do and not do :) The example I started this issue with is a clear case (I think) where the code is doing too much, trying to solve an inconsistency that isn't real. The example found by @map-per is where the code is doing what it should do (I think): **no data** is not as bad as **wrong data**, so because there is a good chance that the surface has changed so much that the smoothness tag is no longer valid, it should be deleted and re-quested. The risk of _throwing away good data_ that may take some time to add again is acceptable considering that the more likely alternative risk is _keeping false data_. Maybe the code could take into account the likeliness that the removed data will be added again soon after deletion by the same user by checking if that user has the relevant quest enabled?

**Comment by matkoniecz** [comment] 2023-03-13 05:36
@rhhsm I plan to post https://gist.github.com/matkoniecz/9f9f4ead734c3834ae82296e4e969aa9 to https://community.openstreetmap.org/ in the tagging section. Do you think this is a good description of situation (it is from my side, but I want to present both viewpoints fairly)?

(if anyone has comments about the planned post: please comment in discussion there - if you want to participate in tagging discussion please wait until it is posted to the community site, I plan to do this on evening today or tomorrow)

**Comment by rhhsm** [comment] 2023-03-13 06:55
@matkoniecz Fine with me. I'll copy-paste my argumentation from this thread on why I would tag the tracks like I did to your new post, so there's no need to make reference to this thread in your post. I hope it will lead to a good discussion about the various tags for unpaved roads (ground, dirt, earth all mean about the same to me) and the usefulness of the tracktype tag.

**Comment by matkoniecz** [comment] 2023-03-13 18:06
https://community.openstreetmap.org/t/is-tracktype-grade2-also-for-trails-with-large-naturally-occuring-pieces-of-rock/96850

**Comment by matkoniecz** [comment] 2023-04-01 17:48
@map-per I think that if mapper mapped asphalt as `surface=paved` then it is justifiable to consider other surface tags as quite suspect.

If you no not think so, please open a new issue.

What was discussed here otherwise (`surface=ground` on tracks with many stones) should be solved by https://github.com/streetcomplete/StreetComplete/commit/f7cb570ac3b58f9462a00476cfee915982524b4f as `surface=ground tracktype=grade2` will no longer trigger resurvey, once new version containing this commit is released

I am not really convinced that it tagging such ways as `grade2` is a good idea, but that rather convinces me that `tracktype` is not really working well - and that we may be missing `surface=ground_with_rocks_and_stones` or similar.

**Closed by matkoniecz** 2023-04-01 17:48 UTC
Labels: bug

**Comment by rhhsm** [comment] 2023-04-01 18:07
> that rather convinces me that `tracktype` is not really working well
Fully agree! I'm preparing a proposal to deprecate `tracktype` and "natural-state" `surface` values like `ground`, `earth`, `dirt`, `mud`, etc. and replace them by values that express surface firmness for unpaved roads where no surface-enhancing material has been added by human hand. There's just an awful lot of documentation to read before I propose this (it would be the first time I propose something this radical)...

**Comment by map-per** [comment] 2023-04-01 19:00
>@map-per I think that if mapper mapped asphalt as surface=paved then it is justifiable to consider other surface tags as quite suspect.

I regularly use surface=paved in cases where I am only sure that the way is paved but can't rememver the precise surface value any more. I don't think such correct, but imprecise values should cause a deletion of other surface related tags. To me a change form paved to a more precise (paved) value is not a strong enough indication for a change of the paths surface.

**Comment by matkoniecz** [comment] 2023-04-01 20:26
> but can't rememver the precise surface value any more

I also do that - but in such case I would not tag smoothness either (as I do not remember specific surface).

**Comment by map-per** [comment] 2023-04-01 21:02
Someone else might have added smoothness before or after

But I think all cases that confused me where SC deleted smoothness were caused by paths being tagged with surface=asphalt although on the footway side of the way paving_stones are used (e.g. version 20 of https://www.openstreetmap.org/way/94694438/history).

**Comment by matkoniecz** [comment] 2023-04-01 21:34
> Someone else might have added smoothness before or after

Is it reasonable or likely that someone is mapping smoothness without mapping actual `surface`?
