### ISSUE TITLE
Can't see again a quest after undoing it

### ISSUE THREAD

**Issue by tuxayo** [streetcomplete/StreetComplete#3829] opened 2022-03-02 23:08 UTC
**How to Reproduce**
- "is this camera still there?"
- answer no
- undo
- quest doesn't show up again

even after redownloading the area

I don't know if it happens every time.

**Versions affected**
40.2

**Comment by HolgerJeromin** [comment] 2022-03-03 02:28
Duplicate of #2861

**Comment by matkoniecz** [comment] 2022-03-03 07:54
Yes, it is ugly but right there is no good idea how to fix it.

**Closed** 2022-03-03 07:54 UTC
Labels: bug
