### ISSUE TITLE
Overlay node circle icons have a square halo at lower zooms and tilt

### ISSUE THREAD

**Issue by pkoby** [streetcomplete/StreetComplete#6048] opened 2024-12-23 16:04 UTC
At the lowest zoom that a point overlay is still visible on the map, the icons farthest away have increasingly opaque square halos, visible when the map is tilted. Zooming in slowly makes the halos more transparent until they disappear.

I opened an [issue in SCEE](https://github.com/Helium314/SCEE/issues/678) originally because I wasn't aware it was applicable to non-custom overlays.

**How to Reproduce**
- Select an overlay that looks for points (Things, for instance).
- Zoom out to the level just before the points are hidden
- Tilt the map

**Expected Behavior**
Icons should appear the same as always.

**Versions affected**
59.2 at least

**Comment by Helium314** [comment] 2024-12-24 07:30
> **Versions affected**
 59.2 at least

It also happens in SC 60.0. Maybe it's an actually issue of MapLibre.

**Comment by westnordost** [comment] 2024-12-24 12:21
Could you add a screenshot or better a video?

**Comment by westnordost** [comment] 2024-12-24 12:24
Nevermind, I can reproduce it. Definitely an upstream issue.

Anyway, I was thinking about using the solution for halos used for tangram, after all, because
1. currently it looks really odd/ugly when zooming out and a lot of icons overlap. It's just an unidentifiable mass off black
2. currently, halos are only possible for black-and-white icons

**Comment by westnordost** [comment] 2024-12-24 12:41
(reported upstream, closing, as it is not necessary to find a workaround for such a minor issue)

**Closed by westnordost** 2024-12-24 12:41 UTC
Labels: bug, upstream
