### ISSUE TITLE
Flickering on dotted lines on roads 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5822] opened 2024-08-21 11:29 UTC
This bug is minor. 

**Screenshot**

https://github.com/user-attachments/assets/563b9d50-06fa-496f-b599-a078110062cf

**How to Reproduce**
Zoom very far in on the map view, and on some specific thresholds there's some flickering/movement as the dotted lines seems to be redrawn. 

**Expected Behavior**
No flickering/movement 

**Versions affected**
Android 12
SC 59.0 Alpha 1

**Comment by westnordost** [comment] 2024-08-21 12:32
Well, this is not flickering, but a misplaced (non-disableable) animation between zoom levels. The (wrong) assumption by MapLibre is that the map style does not continuously adapt the size & distances of dashes depending on the zoom level. But the StreetComplete map style does this.

It has already been reported upstream, so I'll close this: https://github.com/maplibre/maplibre-native/issues/2433 (and https://github.com/maplibre/maplibre-gl-js/issues/4583 )

Since the issue is minor, I don't expect this to be solved soon except if someone interested in this created a PR to either remove or fix this behavior oneself.

**Closed by westnordost** 2024-08-21 12:32 UTC
Labels: bug
