### ISSUE TITLE
Confusing questions on entrace to a building which is not a residential building

### ISSUE THREAD

**Issue by mccartney** [streetcomplete/StreetComplete#5004] opened 2023-05-07 16:42 UTC
**How to Reproduce**
Let SC ask you about a Main Entrance to a building which is not residential, e.g. https://www.openstreetmap.org/node/6893598994

**Observed Behavior**
![image](https://user-images.githubusercontent.com/762437/236690759-a0b714d9-34d5-46bc-889a-094918bf17ee.png)

I find these questions confusing. It mentions some "range of flats", etc. which I find irrelevant.

**Expected Behavior**
Don't list irrelevant options.

**Versions affected**
52.1

**Comment by Helium314** [comment] 2023-05-07 16:45
most likely fixed in https://github.com/streetcomplete/StreetComplete/commit/19128100053aea52d69348f4295977a7cabe5d5e

**Comment by westnordost** [comment] 2023-05-07 22:56
Yes, could not reproduce with current master

**Closed by westnordost** 2023-05-07 22:56 UTC
Labels: bug
