### ISSUE TITLE
Uploaded images (via notes) should not have their GPS/orientation metadata removed

### ISSUE THREAD

**Issue by amandasaurus** [streetcomplete/StreetComplete#5576] opened 2024-04-07 15:16 UTC
I opened a note within StreetComplete (https://www.openstreetmap.org/note/4166071) and included a photo. When I download the photo, the exif metadata for GPS location & orientation is missing. I presume SC, or the website, removes it from the file before uploading. Can that be saved in future. Being able to see where the camera is pointing is useful for interpreting the photo.

**Comment by riQQ** [comment] 2024-04-07 15:26
See #2880, especially https://github.com/streetcomplete/StreetComplete/issues/2880#issuecomment-1586164079

**Comment by westnordost** [comment] 2024-04-07 16:01
Duplicate of #2880

**Closed by westnordost** 2024-04-07 16:01 UTC
Labels: bug

**Comment by mnalis** [comment] 2024-04-07 17:16
Now noted in [SC FAQ - It would be useful if photos from Notes had GPS + viewing direction embedded in them](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#It_would_be_useful_if_photos_from_Notes_had_GPS_+_viewing_direction_embedded_in_them).
