### ISSUE TITLE
Add lit=limited option to lit overlay

### ISSUE THREAD

**Issue by michalgwo** [streetcomplete/StreetComplete#4807] opened 2023-02-12 14:18 UTC
**Use case and proposed solution**
Currently, in lit overlay we have 4 options, I think we should add lit=limited to it. Lots of lights are not on all night, for example in my town all of them. We can add a note to it that if you don't know, whether they are on all night, you can choose lit=yes.
OSM Wiki reference: [lit page](https://wiki.openstreetmap.org/wiki/Key:lit)

(optional) We can also ask about operating times, either directly after choosing lit=limited or by separate quest (or both). The question about operating times can be disabled by default because it's hard to survey, but locals usually know what time lights are turned on and off

**Comment by westnordost** [comment] 2023-02-12 14:21
Duplicate of #2721 /#430

**Closed by westnordost** 2023-02-12 14:21 UTC

**Comment by westnordost** [comment] 2023-02-12 14:25
FYI if a way is tagged with `lit=limited`, it will not be overwritten with `yes` if the StreetComplete user selects that "yes there are lanterns" in the overlay. I.e. no data is destroyed due to the lack of support for it as a selectable option.
