### ISSUE TITLE
upload notes' images to mapillary/kartaview

### ISSUE THREAD

**Issue by pablorodz** [streetcomplete/StreetComplete#3671] opened 2022-01-24 11:55 UTC
Hi,
I normally tend to create notes using StreetComplete because I can add pictures to it and I was wondering if could be added an option to upload the image to Mapillary or other services. I think is something that could be useful and not lost in just a note.

Hope this could be done if anyone besides me think is useful 😊

**Comment by westnordost** [comment] 2022-01-24 12:15
Duplicate of #1780

**Closed by westnordost** 2022-01-24 12:15 UTC
