### ISSUE TITLE
(reproduced) Being immediately asked "is this still a cycleway situation here" after solving "cycleway type" quest

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#4124] opened 2022-06-16 00:09 UTC
This is reproduced https://github.com/streetcomplete/StreetComplete/issues/4086 with more information. I've managed to catch it in two instances

**How to Reproduce**
- autoupload is disabled
- have SC set to follow the GPS
- drive in a bus
- solve repeatedly  `cycleway type` quest  on multiple splits of the long (hundreds of km) road. 
- sometimes (in few percent of the cases) I'm **_immediately_** presented with  `Is this still the cycleway situation here?` quest. It happened at **random** (and I could not reproduce it at will).

This is how it happened twice in my latest try to capture it:

- first instance: this segment of the road https://www.openstreetmap.org/note/3218526. After answering `cycleway type`, I was immediately presented with `Is this still the cycleway situation here?` on the same road segment. I aborted that quest, opened this note, and clicked on the quest again which shower the prompt. However, before I could click an answer, the quest window closed by itself (I'm pretty sure I didn't touch anything) and map updated at new position with "loading quests" spinner

- second instance: this segment of the road: https://www.openstreetmap.org/note/3218528 . Same issue with After answering `cycleway type`, I was immediately presented with `Is this still the cycleway situation here?` on the same road segment. This time I managed to answer `no` on that question, click on the one side of the road, and select `none` answer again (otherwise SC wouldn't let me answer if I didn't select the answer). However later I found it seems it didn't upload duplicate answer, maybe because it detected the answer is the same as already existing one?

- To rule out duplicate ways (or other map data issues), **before uploading SC answers above**, I've fired up my older phone (Xiaomi Redmi Note 3 pro - android 6) with same SC version, moved map to both of those locations manually, loaded quests, and tried to answer them (also with autoupload disabled). The bug didn't show up -- i.e. after solving original `cycleway type` quest, there was **no** `Is this still the cycleway situation here?` quest. 

**Pure guesses**:
That seems to indicate that the problem is likely not underlying map data, but more likely some race condition in StreetComplete - perhaps triggered by moving bus, when new auto-download is triggered while the quest is being answered? Maybe new bbox also happens to download part of old area which contains quest being solved? This is pure speculation, of course.

**Versions affected**

 SC v43.2 vanilla f-droid upstream (still current latest there), Android 10 (on Huawei P30 Pro)

**Comment by matkoniecz** [comment] 2022-06-16 06:30
It may be case of more general "if phone is slow then you can open the same form multiple times" for example in some cases I managed to open setting menu or some popup twice or three times.

**Comment by mnalis** [comment] 2022-06-16 07:34
You mean, similar as in _"missing resource locking / not forcing needed serialization"_ somewhere? That is possible, yes. 

Although it seems to me quite different than case you mention - there are no _"multiple **quick** clicks on same UI element"_ here.

Just one normal quick on quest, and (somewhat later) one normal click on  the answer (which is on the other part of the screen), and the bug happens (sometimes). In its clicking-pattern UI behaviour, it looks more like other issues where the quest is answered but does not disappear (but becomes unclickable) like https://github.com/streetcomplete/StreetComplete/issues/3290 (although unfortunately not so easily repeatable)

**Comment by westnordost** [comment] 2022-06-16 17:39
And how does it look like in the edit history?

**Comment by mnalis** [comment] 2022-06-22 20:26
I've uploaded the quests back then so I can not say with certainty how it would have looked in SC back then.
What I am *pretty sure* is that I have answered it twice as described (first one normally, second one after confirming that situation has changed).

However, going over my OSM Edit history now does not show duplicate cycleway upload on that segment (nor nearby ones): https://www.openstreetmap.org/way/602003688/history but only `v3` - which would seem to indicate that only one of the answered cycleway quests has been recorded  / uploaded and other somehow ignored.

I've tried now some random regular old cycleway (https://www.openstreetmap.org/way/29284241) with that same SC version, and when I answer it has changed, even if I select same `no/no` answer as I did when bug occured, it still wants to record it (`Updated to cycleway:both=no / Added check_date:cycleway=2022-06-22`). It seems strange that the same did **not** happen when the bug triggered. 

Could that be the clue to the bug origin?

**Comment by mnalis** [comment] 2022-06-22 20:59
I've checked the area where that quest was answered with [overpass turbo](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnCLFgmVja19kxJRlOmN5Y2xld2F5Ij0qxYjCnQoqLwpbb3V0Ompzb25dW3RpbWXFp8WpMjVdOwovL8SPxJTEnXIgcmVzdWx0cwooCiAgxbwgcXXEksSaxKNydCBmb3I6IMWIxYrFjMWOxZDFksWUxZbFmMWaxZzFnsWgxowgbm9kZVvFi8SdxqHFkcSVxqTFl8WZxZsiXSh7e2LEqnh9fSnFusaNxqfGscagxY_GtcWTxZXGuManxrvGvca_x4HHg8eFxqvGg2zElGnFrceJxrPHi8ajx47Gpsa6xrzGvseAb8eCx4TFuseWxo9wxLduxpfGg8aFxofGicW1xJjGrnnFuj7Fuse1c2tlxL1xdDs&c=BQFZAVcE6O), and nothing got `check_date:cycleway` tag. I've also scanned the area manually as well as with OSMI, Osmose and Keepright; and they do not report suspicious data (like duplicate overlayed ways or whatever) at that location.

**Comment by westnordost** [comment] 2022-06-26 12:03
> I've tried now some random regular old cycleway (https://www.openstreetmap.org/way/29284241) with that same SC version, and when I answer it has changed, even if I select same no/no answer as I did when bug occured, it still wants to record it (Updated to cycleway:both=no / Added check_date:cycleway=2022-06-22). It seems strange that the same did not happen when the bug triggered.

> Could that be the clue to the bug origin?

I don't quite understand - what is the difference in behavior here and when you reproduced the bug?

**Comment by mnalis** [comment] 2022-06-26 12:33
After answering `no` to `Is this still the cycleway situation here?` quest, in **both** situations I'm presented with prefilled `none`/`none` answer, and asked to modify it. I clicked on one `none` to change it, selected `none` again, and then `OK` to confirm quest. The _difference_ is:

- when the bug occurred (i.e. quest `Is this still the cycleway situation here?` should _not_ have been asked, because cycleway situation was answered less than a second ago!), that **did not** record a new answer with `check_date:cycleway` 

- when I (for test) answered the quest `Is this still the cycleway situation here?` on really old way (i.e. that question was legitimately asked), it seems to record new answer **with** `check_date:cycleway` set to current date.

**Comment by westnordost** [comment] 2022-06-26 12:38
And for the former, was it actually tagged as `cycleway:both=no` before?

**Comment by mnalis** [comment] 2022-06-26 13:22
Yes, it was tagged as `cycleway:both=no` split second before that `Is this still the cycleway situation here?` was asked, see `v3` of  https://www.openstreetmap.org/way/602003688/history 

To me (as an uninitiated person regarding the codebase), when bug occurred, it seems that as although the quest `Is this still the cycleway situation here?` was **_asked_**, it's answer was completely _**disregarded**_ (as if the quest was never asked).

**Comment by westnordost** [comment] 2022-06-26 18:19
> Yes, it was tagged as cycleway:both=no split second before that Is this still the cycleway situation here? was erroneously asked, see v3 of https://www.openstreetmap.org/way/602003688/history

So this was the way for which the issue occured right? But then, are you sure that the text displayed was actually `Is this still the cycleway situation here?` in **either** the first time or the second time you answered the quest? Because, before, it was not tagged. And if your theory is correct, then the "current situation" should not have been shown the second time you opened the quest either.

**Comment by mnalis** [comment] 2022-06-26 20:27
> So this was the way for which the issue occured right? 

Yes, `602003688` is the way where the bug occurred.

> But then, are you sure that the text displayed was actually `Is this still the cycleway situation here?` in either the first time or the second time you answered the quest? 

Yes, it firstly asked me to solve normal cycleway quest (`"Is there a bicycle lane or path here? What type?"`), which I answered as `none/none`, and **as soon as I hit** `OK` it created `"Is this still the cycleway situation here?"` quest at that exact **same road segment**, which I answered `no`, and then again as `none/none`. Which it obviously shouldn't have done.

However, as you can see from way history, only one of the answers had been recorded, even as I answered `none/none` two times.

> Because, before, it was not tagged. And if your theory is correct, then the "current situation" should not have been shown the second time you opened the quest either.

I agree. Initially `cycleway:*` was not tagged at all, but as soon as I solved the quest it was (supposed to be) tagged, and `"Is this still the cycleway situation here?"` should **never** have been asked (as the quest was solved **less than a second ago**, and **not** 4+ years ago).

So yes, the fact that `"Is this still the cycleway situation here?"` quest was shown immediately after solving regular cycleway quest and **shouldn't have been shown** is the subject of this (and previous https://github.com/streetcomplete/StreetComplete/issues/4086) bug report (as it happened multiple times to me).

**Comment by westnordost** [comment] 2022-07-03 23:00
So, the first edit **was** saved. This triggered the `OsmQuestController` to update the quests for that element which in turn was reported to 
- the `MainFragment` which closed the quest form because it belonged to a quest that does now not exist anymore for that element
- the `QuestPinManager` which triggers to re-render the map without that quest

Now, figure that the first is faster than the latter, the quest form would be closed but the map is not updated yet. If in that time frame, you clicked on the quest you just solved...

...nothing should happen, according to the current v45 code, because before doing anything, it tries to acquire the clicked quest from DB which of course does not exist anymore. But if it would be able to acquire it, then what you describe should happen.

But anyway, I notice that I considerately refactored `MainFragment` for v45, in particular the behavior of 1) closing the quest form after solving a quest and 2) what happens when you click on a quest. So, any speculation about the root of the issue does not make sense with a reproduction made with v43. I am sorry, but I have to ask you to try to reproduce it with v45.

If you are able to, try looking at the quest answer first in the edit history before solving it a second time, to confirm the hypothesis that the first edit is indeed made.

**Closed by westnordost** 2022-07-03 23:00 UTC
Labels: bug, feedback required
