### ISSUE TITLE
Pointer pin sometimes cut off at bottom

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#1959] opened 2020-07-16 06:40 UTC
Sometimes the pin pointing to my position is cut of when it is at the bottom of the screen.
![pointer_pin](https://user-images.githubusercontent.com/43007630/87634441-8cf4b000-c73d-11ea-9624-08998de37651.png)

This seems to happen when the pin is moving from the left or right edges to the bottom, but not when the pin appears at the bottom first.
I was able to always reproduce it when my initial position (after start or switch to app) was off the visible map, and the pin was initially shown at left, right or top. Then I move/rotate the map so the pin moves to the bottom (without my position ever being on the visible map), and the pin is always cut off.

StreetComplete 21.0 and 21.1 (fdroid)
Android 9 (LineageOS based)

**Comment by westnordost** [comment] 2020-07-16 21:58
Can't reproduce it, Android 10.

Though, even if I could, quite unlikely I'd fix it to be honest because it is such a minor issue. Though, others are contributors and new contributors who can reproduce it are invited to investigate it. Probably the issue is related to 'padding', ' margin' and 'WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION'.

**Comment by Sequynth** [comment] 2020-07-16 22:23
Reproduced on Android 6.0 running 21.1

**Comment by cyclingcat** [comment] 2020-07-17 07:58
Can reproduce on Android 5.1 running StreetComplete v21.1.
Can **_not_** reproduce on Android 9.0 running StreetComplete v20.2.

I am wondering if this has something to do with "real" vs. "virtual" navigation keys at the bottom of the phone display - my old Android 5.1 phone has "real" touch keys which have their own place at the bottom and thus are never part of the displayed map while my newer Android 9.0 phone shows the navigation keys as a layer on top of the map.

The cycling cat

**Comment by Helium314** [comment] 2020-07-17 08:07
There could be a connection... my phone also has "real" buttons.
But when I disable the buttons and enable the navigation bar the pin is still cut off.

**Comment by westnordost** [comment] 2020-07-17 22:02
What do you mean with "real" buttons by the way? Hardware buttons?

**Comment by cyclingcat** [comment] 2020-07-18 08:42
Don't know if "hardware keys" is the correct term, but this photo illustrates the difference:

![keys_on_smartphones](https://user-images.githubusercontent.com/32601012/87848563-cd8d2e80-c8e1-11ea-86e9-d6d90a01731b.jpg)

On the left one (Cubot Quest, Android 9.0) the Android navigation keys at the bottom are displayed on a separate layer on top of the map. On the right one (bq Aquaris M4.5, Android 5.1) the navigation keys have their dedicated space and do not overlap the map (or any other app).

I'm not sure if this is relevant for this issue though, but maybe there is some pixel miscalculation on devices of the latter kind. Just an idea.

The cycling cat

**Comment by Sequynth** [comment] 2020-07-18 09:19
LG G4, no 'real' buttons

![Capture+_2020-07-18-11-19-05.png](https://user-images.githubusercontent.com/29228990/87849390-8ce4e380-c8e8-11ea-9697-93e95edb13cb.png)

**Comment by westnordost** [comment] 2020-07-18 11:58
Yes, those are called hardware buttons

**Comment by kmpoppe** [comment] 2022-03-08 20:14
Using v41.1 I cannot reproduce this behaviour on a Samsung M31 with Softkeys. @cyclingcat @Helium314 Do you still have means to reproduce this? If not, my guess it that this issue could be closed?

**Comment by Helium314** [comment] 2022-03-08 20:31
I can still reproduce it, same way as in initial post.

> I was able to always reproduce it when my initial position (after start or switch to app) was off the visible map, and the pin was initially shown at left, right or top. Then I move/rotate the map so the pin moves to the bottom (without my position ever being on the visible map), and the pin is always cut off.

**Comment by kmpoppe** [comment] 2022-03-08 20:43
How peculiar. Both variants you describe (switch to the app and after restart - moving the map away fast before the GPS lock kicks in) work for me. Thanks for clarifying! ... Btw, does the pin "work" as in moving to the correct location when you tap it while it is cut off?

**Comment by Helium314** [comment] 2022-03-08 21:16
Touching the pin moves the view to my location, even if the pin is cut off

**Comment by cyclingcat** [comment] 2022-03-09 06:13
Just tried it out with my Android device zoo (SC 41.1):

Smartphone, Android 11, softkeys: pin is okay.
Smartphone, Android 9, softkeys: pin is okay.
Tablet, Android 8.1, hardware keys: pin is okay.
Smartphone, Android 5.1, hardware keys: pin is cropped, touching it moves the view.

The cycling cat

**Comment by westnordost** [comment] 2024-08-25 21:06
This is very probably now fixed in the `compose-edithistory` branch. Anyone who encountered this interested in testing it? (I.e. ... best @Helium314 )

**Comment by Helium314** [comment] 2024-08-26 14:56
I can't reproduce it any more, even on SC before MapLibre. Maybe it was fixed by some seemingly unrelated change?

**Comment by westnordost** [comment] 2024-08-26 15:15
Thanks for testing! Well then, one issue less!

**Closed by westnordost** 2024-08-26 15:15 UTC
Labels: bug, feedback required
