### ISSUE TITLE
When no quests on screen, show pointer to closest quest at edge of screen.

### ISSUE THREAD

**Issue by dbdean** [streetcomplete/StreetComplete#2832] opened 2021-05-02 11:46 UTC
**Use case**

If I've completely mapped out the area visible on my screen, it would be great to see an indicator at the edge of the screen showing the direction of the next closest quest. This would allow me to easily drag the screen in that direction to see the closest quest I need to travel to to keep mapping.

**Proposed Solution**

Show an icon with a pointer at the edge of the screen in the direction of the closest quest. Only show once quests are loaded and if no visible quests are on the screen. Implement similar to the icon that shows the direction of your location when your location is not on screen.

**Comment by smichel17** [comment] 2021-05-02 13:01
Closest to your current location, or closest to the map center? How should it behave when there are two quests a similar distance away (eg, northeast and northwest, and you're on a road heading north) -- is it a problem if it flips between one and the other?

Note that there is a possible performance concern:

1. If I recall correctly, quest locations are calculated and then passed to tangram-es, the map rendering library we use, but they are not saved after that; tangram handles storing them and deciding which are visible, for the most part.
2. The location pin / off-screen indicator is custom StreetComplete code, not part of tangram.

So, the simplest implementation -- each time the position changes, find the nearest quest and display an off-screen pin for it -- would involve searching the db for quests every time the location updates, which might not be fast enough, especially on old phones. Nothing that can't be worked around, but it means the implementation isn't quite as simple as "just do the same thing for the nearest quest as we do for the location".

**Comment by westnordost** [comment] 2021-05-02 13:32
This is a duplicate of #871

**Closed by westnordost** 2021-05-02 13:32 UTC
