### ISSUE TITLE
Steps going up direction

### ISSUE THREAD

**Issue by nata1993** [streetcomplete/StreetComplete#4660] opened 2022-12-01 14:34 UTC
![Screenshot_20221130_225714_StreetComplete](https://user-images.githubusercontent.com/6074645/205078565-6e9736d3-ed33-4fe7-a8c0-dcda8ed8a25c.png)

Screenshot shows that the arrows are looking left and right instead of up and down despite the steps in reality are going up from bottom to up.

**How to Reproduce**
Find steps that are continuous line but are not straight line. Click on them and arrows should or might be looking some other direction instead of showing which way steps should be going.

**Expected Behavior**
Direction arrows should ignore any steps line shape changes inbetween start and end points.

**Versions affected**
Android Street Complite v49.2

**Comment by nata1993** [comment] 2022-12-01 17:20
@mcliquid The tip does not represent the whole area as I can see it on this specific case. This particular case is where the steps are one whole thing. The platform in the middle is part of the steps, not standalone thing hence the path for steps is considered as a whole, not as separate entities and the separator is the zig zag aka the platform in the middle. But since its not considered as a whole thing, the pin part is representing only the platform, not the whole steps path. Here is the photo of actual thing. 

![image](https://user-images.githubusercontent.com/6074645/205117812-86104e63-11e6-4826-8dc3-ece5779034aa.png)

**Comment by westnordost** [comment] 2022-12-02 23:28
Closing as question answered / not a bug

**Closed by westnordost** 2022-12-02 23:28 UTC
Labels: invalid
