### ISSUE TITLE
Recent map-rendering issues (disappearing maps, level-of-detail inconsistencies) Android 11

### ISSUE THREAD

**Issue by gjm11** [streetcomplete/StreetComplete#2089] opened 2020-09-11 19:54 UTC
I'm on a Pixel 3, recently updated to Android 11. I'm using version 22.3 of StreetComplete, which I believe is the most recent. Until recently StreetComplete was working fine for me. But somewhere around when I updated from Android 10 to Android 11 -- unfortunately my memory is terrible and I am not _certain_ that it was at the exact same point -- StreetComplete stopped displaying maps. The little dot showing my location and orientation are there; quest markers are there; buttons for menu, zooming, etc., are there; but no roads, buildings, etc.

If I pan far enough, then eventually I find rectangular regions within which normal maps appear, and others where they don't.

If I zoom out far enough, roads and shading (for built-up/grassy/... areas) do eventually appear, even in the region that was blank, and if I zoom in on that region again, it is not longer blank. But its roads are just thin lines, there are no road names and no buildings, etc., as if it's drawing those small regions using data from a zoomed-out rendering. Sometimes -- it depends on what exact sequence of zooms and pans I do -- I appear to get two _different_ zoom levels' roads superimposed on one another. Sometimes zooming in will make the "coarser" roads disappear, and then zooming out again will bring them back (superimposed on the "finer" ones). Sometimes coarser and finer road paths coexist however far in I zoom. I don't think I've ever seen _three_ levels of detail showing at the same time.

Switching between light and dark themes while zoomed in to a "bad" region will make all the maps disappear again; then the same procedure described above will make them (partly, as above) come back. Switching theme again again makes the maps disappear again; I can repeat this ad infinitum.

I have tried power-cycling the device, and uninstalling and reinstalling StreetComplete. Neither appears to change this strange behaviour.

**Comment by westnordost** [comment] 2020-09-11 20:09
This sounds like you still have some map tiles (on low zoom) in your cache and the map loading does not work at all.

I kind of suspect that this is due to something in Android 11?

**Comment by matkoniecz** [comment] 2020-09-11 20:17
> This sounds like you still have some map tiles (on low zoom) in your cache and the map loading does not work at all.

It can be checked by uninstalling and installing StreetComplete again - if there is no map at all it would indicate that downloading is completely broken.

**Comment by gjm11** [comment] 2020-09-11 21:37
I did uninstall and reinstall (both on general principles and because I was wondering about e.g. the possibility of corrupted cached rendered maps), and the behaviour above is what I got.

In particular, contra matkoniecz's speculation uninstalling and reinstalling _doesn't_ result in having literally no map at all.

(I realise that my earlier description was a little inaccurate. I said at the end "neither appears to change this strange behaviour", but actually I think I uninstalled and reinstalled before I first saw the weirder bits of the behaviour I described above. When I did it, I had only seen the complete absence of maps and hadn't panned or zoomed far enough to see anything different. So it's _possible_ that, e.g., before uninstalling and reinstalling there were no maps displayed anywhere. My guess, though, is that it didn't change anything.)

I share the suspicion that it's related to the Android 10 -> 11 transition. As I said, I _think_ the problems started when I upgraded but I am not certain of that.

When I do things in StreetComplete that seem like they ought to be fetching new map data, there's network traffic from my phone to 171.ip-217-182-130.eu and I'm pretty sure some responses with substantial payloads are coming back. (Only _pretty sure_ because my local network is NATted and my tcpdump-fu isn't the strongest.)

**Comment by westnordost** [comment] 2020-09-11 21:40
To confirm your suspicion, you could install an older version. Is the behavior the same?

**Comment by gjm11** [comment] 2020-09-11 21:49
Do you mean an older version of Android, or an older version of StreetComplete?

I am very much not enthusiastic about downgrading my phone's OS, even if there's a way to do it. (Is that unreasonably over-cautious? It just seems like a thing that could cause me grief in so many different ways.) I'll gladly try an older version of SC, but I'm not sure how to do that.

**Comment by westnordost** [comment] 2020-09-11 22:44
of StreetComplete

**Comment by matkoniecz** [comment] 2020-09-11 22:44
https://github.com/westnordost/StreetComplete/releases lists releases and allows you to download installable APK file.

Note that you need to enable permission

**Comment by callis** [comment] 2020-09-12 07:23
I just updated to Android 11 and tiles are loading as expected (pixel 3 as well)

**Comment by rhhsm** [comment] 2020-09-12 17:17
I'm using Streetcomplete 22.3 and Android 9, and seem to have similar symptoms, which I have blamed on being off-line so missing map tiles in cache could not be downloaded. My maps are never completely empty, just parts missing, and zooming out and in again will make them re-appear so I haven't experienced it as a problem. I've also noticed thin roads, but not superimposed zoom levels (yet). Could it be related to the switch to JawgMaps (a great improvement!)?

**Comment by smichel17** [comment] 2020-09-12 18:06
The switch to JawgMaps was in v21, which was released on June 29th. Is that around when you updated to Android 11, @gjm11?

If you want to test, you can install the apk from the [20.2 release](https://github.com/westnordost/StreetComplete/releases/tag/v20.2). I don't know whether @Atrate is still running the old map server, but it should fall back to the very-outdated nextzen maps and thus work for testing, either way.

**Comment by Atrate** [comment] 2020-09-12 20:50
> I don't know whether @Atrate is still running the old map server

@smichel17 I think you wanted to mention @Akasch, not me

**Comment by Atrate** [comment] 2020-09-12 20:51
> I don't know whether @Atrate is still running the old map server

@smichel17 I think you wanted to mention @Akasch, not me

**Comment by gjm11** [comment] 2020-09-12 21:01
Release 20.2 shows the same symptoms, for me. If anything, somewhat worse (i.e., more of the map is missing).

**Comment by gjm11** [comment] 2020-09-12 21:03
However, after upgrading back from 20.2 to 22.3 the problem appears to have gone away. I guess that's good news for me, but it may mean I can't get any further evidence to figure out what was broken :-).

**Comment by rhhsm** [comment] 2020-09-13 14:49
Hope these screenshots help: first shot where problem occurs, 2nd zooming in on trouble area, 3rd after zooming out and in again, 4th after app restart, using an LG Q60 on Android 9 being on WiFi 
![Screenshot_20200913-172758](https://user-images.githubusercontent.com/69100427/93021012-22e77280-f5e9-11ea-90d6-b941aef75a07.png)
![Screenshot_20200913-172814](https://user-images.githubusercontent.com/69100427/93021020-2844bd00-f5e9-11ea-94be-c85fe7930c12.png)
![Screenshot_20200913-172830](https://user-images.githubusercontent.com/69100427/93021027-2b3fad80-f5e9-11ea-84a3-15e1c025a878.png)
![Screenshot_20200913-172956](https://user-images.githubusercontent.com/69100427/93021030-2ed33480-f5e9-11ea-9a9d-aec0c4fda8bd.png)

**Comment by gjm11** [comment] 2020-09-13 15:21
The "bad" screenshots above look very similar to what I saw.

**Comment by westnordost** [comment] 2020-09-13 15:47
This is a feature of tangram-es: If the tiles are not available (yet) for the current zoom level, the ones from the lower zoom level(s) are shown instead. That's standard, Google etc also does this. 

As for why both zoom levels are overlayed like this, I don't know, I figure that may be posted as a bug in their issue tracker here https://github.com/tangrams/tangram-es/issues . However, I'd consider this as a very minor problem, showing the tiles from another zoom level at the current zoom level is supposed to only show up for a few (hundred) ms, until the tile is loaded. A tile will be around 1-50 kB on jawg, so it really should be loaded in a blink of an eye.

But anyway, this is not the issue here, the issue is that the tiles don't seem to load at all. Debugging this will not be easy. Here are a few angles at which we might isolate the issue:
- Maybe the issues with loading are based on the location? (=Jawg somehow doesn't have the data cached or had problems generating it at all) Verifiable by looking at the same location as within the app using https://ent8r.github.io/streetcomplete-mapstyle - Do these tiles also not load?
- Run the app with a debugger attached and look for log messages that hint at that tangram-es cannot load certain tiles

**Comment by gjm11** [comment] 2020-09-13 16:09
No obvious sign of missing tiles in the region where I am in that web UI. But then, SC is behaving OK for me too now :-). If the problem comes back I'll look into debuggering the app.

**Comment by peternewman** [comment] 2020-09-19 21:36
I was going to say I feel like I've had similar slow responses since the switch to Jawg. Certainly when offline it takes a lot longer to time out and switch to my cached tiles than it used to.

But also at times when online they seem to load far more slowly. Both SC and the web app are currently very responsive again right now, but SC seemed slow a few hours ago.

**Comment by maniackatzentier** [comment] 2020-12-09 05:18
I seem to have the same issue 😏.
No tiles loading in Fairphone 3. I try a different Location to see if it is a problem of the area.

**Comment by westnordost** [comment] 2020-12-16 17:10
@maniackatzentier Reproducible and not at all? If only sometimes and/or only delayed, this will be the same issue as #2142.

**Comment by westnordost** [comment] 2021-01-10 19:54
Closed as duplicate of #2142.

**Closed by westnordost** 2021-01-10 19:54 UTC
Labels: bug, feedback required
