### ISSUE TITLE
Button "more" move on quest selection fragment

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#4112] opened 2022-06-14 19:56 UTC
Button "more" move when you start search on quest selection fragment

**How to Reproduce**
- Open app
- Go to settings -> Quest selection
- Start search > button "more" has moved to the right

**Versions affected**
Android 12 - StreetComplete v44.1

**Comment by westnordost** [comment] 2022-06-14 20:59
There is no button "More". What do you mean?

**Comment by Jean-BaptisteC** [comment] 2022-06-14 21:01
This button ![more_vert_black_24dp](https://user-images.githubusercontent.com/87148630/173687982-dc8ae539-2c09-4518-a44e-40a8007d3f00.svg) that opens a menu

**Comment by westnordost** [comment] 2022-06-14 21:13
Ah, that one. This is deliberate. Are you even sure it moves to the right? It should actually be obscured by a X button. This is the search interface. To exit the search interface, press the X

**Comment by westnordost** [comment] 2022-06-15 20:55
Interesting. Well, this is a minor inconvenience. Let's see if a minor fix for this is possible.

**Comment by westnordost** [comment] 2022-06-15 20:59
Okay it looks like this whole search bar thing is an Android (androidx.appcompat) component, its appearance is not controlled by StreetComplete. So either this is working as intended or it is a bug in androidx.appcompat.

**Closed by westnordost** 2022-06-15 20:59 UTC
Labels: bug, feedback required
