### ISSUE TITLE
Parking lane overlay removes `parking:condition`

### ISSUE THREAD

**Issue by Mbodin** [streetcomplete/StreetComplete#4515] opened 2022-10-17 10:23 UTC
**Use case**
I’m still experimenting with the parking lane overlay (which is great by the way! ☺). I just noted that this quest removed the `parking:condition:both=ticket` in this change: https://www.openstreetmap.org/way/274763329/history
I understand the rational: if one is using this overlay, then probably something changed and we’re better reinitialising all parking-related keys.

In this case, however, it feels wrong: my answer only refined the previous `parking:lane:both=parallel` by an additional key `parking:lane:both:parallel=street_side`. The in-place situation did not change (in this specific place) from what was before.

As-is, StreetComplete removed an information without the interface telling me: it feels wrong to me.

**Proposed Solution**
As already suggested, we could keep the current behaviour and add a parking condition quest: https://github.com/streetcomplete/StreetComplete/issues/771#issuecomment-809804822
We could also keep the `parking:condition` key, but add a special quest to confirm whether it still applies (I’m not sure whether this would integrate well into the software).

I however feel that in case where the answer is only a refinement of what was already there (for instance when no key value changed: we only added new keys), then no key should be removed. This has the advantage of not needing a new quest type for parking condition. I don't know whether this is particular to the parking lane overlay or whether it could apply to other quests.

**Comment by Helium314** [comment] 2022-10-17 10:37
see #4501

**Comment by mnalis** [comment] 2022-10-17 15:03
Duplicate of #4501

**Closed by mnalis** 2022-10-17 15:03 UTC
