### ISSUE TITLE
handling of multiple quests for a single object

### ISSUE THREAD

**Issue by alotbsol555** [streetcomplete/StreetComplete#5929] opened 2024-09-26 12:33 UTC
**Use case**
if there are multiple quests for a single object you have to answer them one after another, in the order choosen in the settings. It would be very convenient to be able to solve any quest available for an object without having to sort it to the top in the settings or deactivate the other quests above.

**Proposed Solution**
show all open quests for an object on double tapping or long pressing the currently shown quest and allow solving any of these available quests. maybe add an indicator on close zoom levels to show that there is more than one quest to solve.

**Comment by FloEdelmann** [comment] 2024-09-26 12:38
Similar to

* #124
* #2710
* #1969

**Comment by westnordost** [comment] 2024-09-26 20:57
Well, in #124 various solutions have been discussed. (Will close as duplicate)

I noticed that under the title "use case", you wrote what you would like to do (sort through all quests for one object) but now **_why_**. Were you unable to answer one quest (from a distance), so you first wanted to answer another? (If yes, which one?)

**Comment by westnordost** [comment] 2024-09-27 10:42
The quests should be sorted by default by "quick and easy to solve from a distance" first, then the closer you have to get / the longer it takes to answer, the later it is displayed. So, that's why I am interested to know for which quests you wanted to reorder the quests. The default order could be changed.

**Comment by mnalis** [comment] 2024-09-28 01:16
>  sorting the list of quests in the settings or deactivating the unanswerable quest, then go back and answer the easy quests just to reset the settings to the usual state afterwards is too inconvenient in my view. maybe I'm just too lazy ;)

You're not lazy, such procedure would be a horror indeed, which is why nobody suggested that :smiley_cat: 

But are you aware that every quest has an `Uh...` / `Can't say` answer? If you choose that, current quest (which you cannot or do not want to answer for whatever reason) would be skipped on that object, and you will be presented with next quest in order for it. That should be much easier, yes? Or is it problematic for some reason for you?

**Comment by Helium314** [comment] 2024-09-28 19:41
> For me, it feels like there is just one last step of zooming-in missing in the main view.

That was already seen as solution when max zoom was 20.5 (#2878)
Reading this just a few weeks after the max zoom was increased to 25.5 makes me think there will _always_ be just one more step needed.

**Comment by westnordost** [comment] 2024-09-30 20:56
Hmm, I looked at the order of the bus stop quests:

- AddBusStopShelter
- AddBenchStatusOnBusStop
- AddBinStatusOnBusStop
- AddTactilePavingBusStop
- AddBusStopName
- AddBusStopRef
- AddBusStopLit

Stop name and ref are further below even though they might be visible more easily than the tactile paving because it requires text input and that takes long, i.e. you'll have left the bus stop already when you finished inputting it.
The lit quest is asked last because at least during day, you pretty much have to stand in it to see if there is lighting or not.

So, I think the order is fine, or at least, the best compromise.

Anyway, closing as duplicate of #124

**Closed by westnordost** 2024-09-30 20:56 UTC

**Comment by mnalis** [comment] 2024-10-01 10:05
> Thanks! I think that is currently the best working solution for me, if there are not that many quests to skip. Although skipping without hiding would be better and being able to pick in advance would be best ;) But unhiding everything again from time to time is indeed much easier

For those who might be interested, [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert edition"_ fork) has an option (in `Settings` / `UI` / `Show hide button`) which creates just such _"temporarily hide"_ button which is actually just _"skip"_ (i.e. update of the area or solving of other quest on that element will automatically unhide the quest). As an additional bonus it is available with just a single click (instead of 3 clicks).

Anyway, SCEE can be installed alongside StreetComplete if you want to try it out @alotbsol555, and (despite the name) by default looks pretty much the same as StreetComplete - until you start enabling more and more extra features (when it starts to differ more and more too, of course).
