### ISSUE TITLE
Abandoned railway bridges don't trigger the max height quest

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#4564] opened 2022-10-29 11:33 UTC
This way:
https://www.openstreetmap.org/way/131915856

Is tagged as `railway=abandoned`

The lifecycle prefixes:
https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_decay
And the railway page:
https://wiki.openstreetmap.org/wiki/Tag:railway%3Dabandoned

Suggest its significant enough the bridge should still exist, so it's not miss-tagged, so we should ask the question.

Issue seems to be here:
https://github.com/streetcomplete/StreetComplete/blob/378d0c990916f168ca44c1490637049794fe4d25/app/src/main/java/de/westnordost/streetcomplete/quests/max_height/AddMaxHeight.kt#L47

It also doesn't show on the map at all, so perhaps our map style needs tweaking too?

**How to Reproduce**
Scan https://www.openstreetmap.org/way/131915856
No max height quest is asked.

**Expected Behavior**
It should be asked

**Versions affected**
v48.1-beta

**Comment by westnordost** [comment] 2022-10-29 11:39
I don't think that abandoned railways are shown on jawg.io.

Anyhow...

**Comment by westnordost** [comment] 2022-10-29 11:44
...does speak anything against simplifying the filter to just look for any `bridge` with `layer`?

**Comment by peternewman** [comment] 2022-10-29 14:13
> I don't think that abandoned railways are shown on jawg.io.

That's a shame, given the bridges for example are still relevant.

> ...does speak anything against simplifying the filter to just look for any `bridge` with `layer`?
> 
> I.e. not specifically require a road or railway to be on it?

Well that would also cover things like canal aqueducts (e.g. https://www.openstreetmap.org/way/25589779 or https://www.openstreetmap.org/way/318039775 ) and I guess and things like pipe bridges depending on how they're tagged.

I guess the only reason not to would be for cases where the bridge itself has been removed and only the pillars remain which I think would be razed/ruins/demolished/razed but I don't know how clearly that sort of thing is clarified:
https://wiki.openstreetmap.org/wiki/Railways#Life-cycle
https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Stages_of_decay

**Comment by westnordost** [comment] 2022-10-29 15:29
But then, `bridge=yes` would be wrong, no?

**Comment by peternewman** [comment] 2022-10-29 15:36
> But then, `bridge=yes` would be wrong, no?

Ah yes, very true, it would need to be `ruin:bridge=yes` or something...

So yes, I'm for making the filter simpler!

**Comment by matkoniecz** [comment] 2022-10-29 16:20
> Is tagged as railway=abandoned

The problem is that some people (incorrectly but on wide scale) map completely and utterly gone railways, without any trace at all - as `railway=abandoned` `railway=razed` `railway=dismantled` and with other tagging.

This sooner or later will be deleted but in meantime OSM mappers would be asked about bridges that stopped existing decades ago and are gone without any trace whatsoever.

**Comment by mnalis** [comment] 2022-10-29 16:48
> This sooner or later will be deleted but in meantime OSM mappers would be asked about bridges that stopped existing decades ago and are gone without any trace whatsoever.

Well, won't incorrect data be deleted **_sooner_** if SC mapper leaves a note saying "No trace of this bridge exist anymore" with picture? Helping fix incorrect data there would be good use of on-the-ground capabilities of SC in my opinion.

(E.g. I can already answer for example that some shop does not exist anymore; I do not see problem with also answering that some bridge does not exist anymore. If anything, it would be _less_ spammy, and even _more_ useful.)

**Comment by matkoniecz** [comment] 2022-10-29 16:52
> Well, won't incorrect data be deleted sooner if SC mapper leaves a note saying "No trace of this bridge exist anymore" with picture? Helping fix incorrect data there would be good use of on-the-ground capabilities of SC in my opinion.

The problem here is that there is notable group of people trying to gaslight rest of community that railways are extraspecial and can be mapped even when fully and utterly gone.

Also, railway=abandoned bridge may look like this: https://wiki.openstreetmap.org/wiki/File:Demolished_Torwoodlee_Railway_Bridge_-_geograph.org.uk_-_750961.jpg (mapping it as `railway=abandoned bridge=yes` us actually considered acceptable)

**Comment by mnalis** [comment] 2022-10-29 17:17
> I am all for fixing that problem, but just wanted to make clear that it will result in predictable discussions with people claiming that utterly removed railway switches are mappable.

Yeah, sure, but how does that apply to _this ticket in particular_? I was under impression [the idea](https://github.com/streetcomplete/StreetComplete/issues/4564#issuecomment-1295811955) was to simplify `AddMaxHeight` quest to be asked on all `bridge=yes`+`layer=*` (while _currently it also requires_ that same way also has some `highway=*` or `railway=*` mapped on it).

If my understanding is correct, the railway fans would not come into the picture here. 

Because, either:

-  the **bridge itself exists** (regardless if it has any current or previous railway and/or highway on it, and regardless of their usability), in which case asking for `AddMaxHeight` is useful, or
- the **bridge no longer exists**, in which case:
  - the user can leave a note (simple and agnostic approach which offloads the _"railway fans"_ problem to other mappers willing to take a choice), or
  - we can even have separate option _"this bridge does not exist anymore"_ which would rename `bridge=*` to `removed:bridge=*` (if we accept [Lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) as reasonable approach in this particular quest, it would likely also be OK with railway people as we wouldn't touch other tags like `abandoned:railway=*`, but might be somewhat unpopular with people disliking such use of lifecycle prefix)

**Comment by matkoniecz** [comment] 2022-10-29 21:01
> Yeah, sure, but how does that apply to this ticket in particular? 

Currently `railway=abandoned` bridge will not trigger this quest.

This ticked it proposing to trigger it with  `railway=abandoned` bridges.

Many  `railway=abandoned` bridges are just crumbling remains of no longer existing bridge, and something not even that. 

> It seems a bit crazy to me if its considered acceptable to have identical tagging for two bridges, one where there is a section over the road and one where there isn't, surely they're at very different stages in their lifecycle?

Abandoned railway tagging is a horrific mess. Made worse by many railfans mapping things that re completely gone as existing or as having visible remains.

> one where there is a section over the road

Presence of `man_made=bridge` is actually a good fit for "is this bridge even existing", but is mapped less often.

**Comment by matkoniecz** [comment] 2022-10-30 10:23
> It seems a bit crazy to me if its considered acceptable to have identical tagging for two bridges, one where there is a section over the road and one where there isn't, surely they're at very different stages in their lifecycle?

I agree that it is a bad tagging, but sadly both bridge where rails were dismantled and bridge where only overgrown abutments are remaining can be tagged `railway=abandoned bridge=yes` and there are no tags to distinguish between them.

I would support changing this situation and introducing extra tags to record what is actually remaining from railway line. That would have many benefits, not only allowing to handle this quest in a better way (and maybe can be collected with SC? at least in part?)

**Comment by westnordost** [comment] 2022-10-30 12:34
Did you close this ticket on purpose?

**Comment by matkoniecz** [comment] 2022-10-30 13:16
yes

Unless we want to ask about heigh limit between two overgrown abutments where there is nothing above the road?

**Comment by peternewman** [comment] 2022-10-30 14:22
> yes

Do you want to close it as not-planned then, rather than complete?

> ...does speak anything against simplifying the filter to just look for any `bridge` with `layer`?
> 
> I.e. not specifically require a road or railway to be on it?

As @westnordost proposed, couldn't we simplify the filter though to something like this (looking at the blame people have been constantly adding new types of railway over the years), note I've added `man_made=bridge` as mentioned too (I know they're supposed to tag both, but...):

```
        ways with (
            // Not abandoned as some people map bridge pillars only as abandoned
            // Not construction or proposed as not necessarily present yet
            !highway or highway !~ abandoned|construction|proposed
            or !railway or railway !~ abandoned|construction|proposed
          ) and (
            bridge and bridge != no
            or man_made = bridge
            or man_made = pipeline and location = overhead
          )
          and layer
```

In fact more man_made options:
`or man_made ~= goods_conveyor|pier|torii`

Or if we want to keep it to an allow list, then we need to add various waterway variants for things like:
https://www.openstreetmap.org/way/23697870

So something like:
`waterway =~ canal|drain|ditch|fish_pass|pressurised`

I'd hope that in due course, some more sane tagging can be agreed and we can ask for abandoned and tag as `abutments_only=yes` or whatever as an other answer to resolve this issue properly.

**Comment by matkoniecz** [comment] 2022-10-30 14:28
> Do you want to close it as not-planned then, rather than complete?

argh, I keep getting tripped by that functionality

>             !highway or highway !~ abandoned|construction|proposed

I tried this things - you will keep getting bitten by long tail of things like https://taginfo.openstreetmap.org/tags/highway=planned

>  or man_made = bridge
>  or man_made ~= goods_conveyor|pier|torii
> waterway =~ canal|drain|ditch|fish_pass|pressurised

not sure should I reopen this one or is it fitting a new one

**Comment by westnordost** [comment] 2022-10-30 14:32
Or railway=station

**Comment by peternewman** [comment] 2022-10-30 16:12
> > ```
> >         !highway or highway !~ abandoned|construction|proposed
> > ```
> 
> I tried this kind of things - you will keep getting bitten by long tail of things like https://taginfo.openstreetmap.org/tags/highway=planned https://taginfo.openstreetmap.org/tags/highway=no https://taginfo.openstreetmap.org/tags/highway=abandoned https://taginfo.openstreetmap.org/tags/highway=razed
> 
> False negatives are here better than false positives.

Personally I'd disagree, if someone gets asked about a bridge height when there isn't one, they'll leave a note or maybe even open an issue and we can fix it permanently. It's much harder to catch the cases like this one and have that discussion, it was only because I spotted a bridge in real life, and wasn't asked the quest, and couldn't see a bridge on the map, then left a note, then investigated it in real life that we got to the opinion that abandoned is chaos.

Whereas there are only 160 odd highway tags, going through them and sanity checking now won't take long. If we're really worried about false positives, we could always do some complicated @mnalis style tracking of new ones and checking them manually, but I'd say 90+% of the tags are plausible that they could happen and should be asked.

> > or man_made = bridge
> > or man_made ~= goods_conveyor|pier|torii
> > waterway =~ canal|drain|ditch|fish_pass|pressurised
> 
> not sure should I reopen this one or is it fitting a new issue
> 
> maybe open a new one? So one has no need to get through pages to understand what is actually proposed? (or just make PR if you can)

I don't have easy places to test those other things (or a particularly efficient way to test) and we still seem to disagree as to how we should deal with the edge cases.

> Or railway=station

Or platform...

**Comment by matkoniecz** [comment] 2022-10-30 17:04
>  if someone gets asked about a bridge height when there isn't one, they'll leave a note or maybe even open an issue and we can fix it permanently.

the problem is that in some cases there is nothing to fix, or more specifically there is no standard way to fix it

Lets say that height limit quest was triggered between two overgrown abutments where there is nothing above the road

What should be tagged in such case on road below `railway=abandoned bridge=yes`? How this railway should be retagged?

**Comment by peternewman** [comment] 2022-10-30 21:14
> > if someone gets asked about a bridge height when there isn't one, they'll leave a note or maybe even open an issue and we can fix it permanently.
> 
> the problem is that in some cases there is nothing to fix, or more specifically there is no standard way to fix it

I'm (sadly) agreeing with you that we have to ignore `railway=abandoned` for now, until such time as there is a way to differentiate. I was meaning if someone starts tagging `railway=imaginary` we'll get issues and can then ignore that too, whereas if they add `railway=commuter` we won't get notes, but crucially people *will* get asked the question still.

> Lets say that height limit quest was triggered between two overgrown abutments where there is nothing above the road
> 
> What should be tagged in such case on road below `railway=abandoned bridge=yes`? How this railway should be retagged?

As mentioned, sadly it can't for now, but when something is agreed, we can start asking about it and offering to retag where its vague, or perhaps even adding a brand new quest.

> > Whereas there are only 160 odd highway tags, going through them and sanity checking now won't take long
> 
> new ones will appear soon

Yes, and personally I'd still argue that the best way to find and resolve them is to just ask questions and get people to leave notes/generate issues when they're clearly inappropriate, but if you feel we need to do it the other way round, I'm happy to instigate an equivalent of https://github.com/mnalis/StreetComplete-taginfo-categorize/ for highway/railway/waterway to categorise as likely to exist or not. Given we've got e.g.:
https://github.com/streetcomplete/StreetComplete/blob/7c97885cb6c24f9f7defed22e4497a495ab7e4ab/app/src/main/java/de/westnordost/streetcomplete/quests/railway_crossing/AddRailwayCrossingBarrier.kt#L28

There seems to be other wider use of this sort of classification across SC.

**Comment by mnalis** [comment] 2022-10-31 00:09
> ...  `railway=abandoned` `bridge=yes`? How this railway should be retagged?

well, if the _bridge itself_ is gone, then SC could apply the lifecycle prefix to that `bridge=*` tag. e.g. `railway=abandoned`+`abandoned:bridge=yes` (or `railway=abandoned`+`razed:bridge=yes`). 

As one **_didn't touch the railway part_**, and has in fact improved on supporting attributes of its segment (corrected bridge lifecycle), I would hope railway folks would welcome it (or at least not be aggravated by it). What am I missing?

But people leaving notes that the bridge is no longer there is also an option if we don't mind more manual work outside SC, as I [wrote earlier](https://github.com/streetcomplete/StreetComplete/issues/4564#issuecomment-1295907723).

**Comment by matkoniecz** [comment] 2022-11-01 21:30
reopening as tagging mentioned by @mnalis seems feasible - the question is now whether we are fine with some predictably confused people

@mnalis - is this tagging/solution documented somewhere? For example on wiki?

**Comment by mnalis** [comment] 2022-11-02 01:58
Yes, general usage of such prefixes is documented in [Lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) wiki page, e.g.:
> [abandoned:*](https://wiki.openstreetmap.org/wiki/Key:abandoned:*)=*
    Still visible but fallen into serious disrepair and which could only be put back into operation with considerable effort


It's [Examples section](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix#Examples) shows several examples on how it may be used on various other keys (`disused:shop`, `disused:amenity`, `disused:railway` etc.), but it cannot list all possible use cases (`number of prefixes` times `number of tags` would be huge number!)

I can add an _additional example_ in that section for `abandoned:bridge=yes` with picture https://commons.wikimedia.org/wiki/File:Abandoned_Malolos_Station_railway_bridge_Manila_Railroad_Company_30.jpg if you think it would help?

**Comment by mnalis** [comment] 2022-11-02 02:01
Also, wiki for [bridge=*](https://wiki.openstreetmap.org/wiki/Key:bridge) mentions:
> bridge=[abandoned](https://wiki.openstreetmap.org/w/index.php?title=Tag:bridge%3Dabandoned&action=edit&redlink=1) ‒ Use bridge=* + [abandoned](https://wiki.openstreetmap.org/wiki/Key:abandoned)=[yes](https://wiki.openstreetmap.org/wiki/Tag:abandoned%3Dyes) or [abandoned:bridge](https://wiki.openstreetmap.org/w/index.php?title=Key:abandoned:bridge&action=edit&redlink=1)=* instead.

**Comment by matkoniecz** [comment] 2022-11-02 05:57
> Yes, general usage of such prefixes is documented in [Lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) wiki page, e.g.:

Yes, but is distinction in meaning, allowing to express difference between "`railway=abandoned` - with tracks removed, bridge existing" and "`railway=abandoned` - with tracks removed and only faint traces of bridge existing" documented and recognised anywhere? (it makes sense to me, but I am not sure what wider community thinks about this)

**Comment by peternewman** [comment] 2022-11-02 11:26
> I can add an _additional example_ in that section for `abandoned:bridge=yes` with picture https://commons.wikimedia.org/wiki/File:Abandoned_Malolos_Station_railway_bridge_Manila_Railroad_Company_30.jpg if you think it would help?

Shouldn't that be ruins though anyway, or at least not abandoned? We don't want to perpetuate the same issue we have with the railways on the physical structure of the bridge itself, so we need to differentiate whether it can be crossed versus whether there is still a height restriction from the other cases. I guess I'd probably go as far to say a bridge is fairly unique compared to most other things in terms of the impact it has on it's surroundings by crossing another way, possibly only matched by a body of water. Compared to say a tunnel or a building, where unless you are in them, the state of them generally doesn't impact you.

From the lifecycle prefixes ( https://wiki.openstreetmap.org/wiki/Lifecycle_prefix ), with some proposed examples from me:
[disused:*](https://wiki.openstreetmap.org/wiki/Key:disused:*)=*
    Not currently in use, but could be reinstated easily - E.g. a road bridge which is no longer part of the road network, surface still in good condition, I could still walk over it.

[abandoned:*](https://wiki.openstreetmap.org/wiki/Key:abandoned:*)=*
    Still visible but fallen into serious disrepair and which could only be put back into operation with considerable effort - A metal girder bridge which is seriously rusted, or parts of bridge deck missing or similar, but still presents an "obstruction" across the road its crossing. I probably wouldn't want to risk walking over it, although it's hopefully structurally safe or they would have removed it.

[ruins:*](https://wiki.openstreetmap.org/wiki/Key:ruins:*)=*
    Only ruins are remaining - E.g. just the pillars (at the edges and or in the middle) remain, like your picture. I can't walk over it.

I guess the pillars only could also be one of these three:
[demolished:*](https://wiki.openstreetmap.org/wiki/Key:demolished:*)=*
    Not existing anymore because of active removal
    May have been used for features that are almost but not completely invisible
[removed:*](https://wiki.openstreetmap.org/wiki/Key:removed:*)=*
    Not existing anymore because of active removal (possible duplicate of [demolished:*](https://wiki.openstreetmap.org/wiki/Key:demolished:*)=*)
[razed:*](https://wiki.openstreetmap.org/wiki/Key:razed:*)=*
    Not existing anymore because of active removal

Probably not particularly relevant unless it collapsed:
[destroyed:*](https://wiki.openstreetmap.org/wiki/Key:destroyed:*)=*
    Destroyed by an event other than intentional demolition

**Comment by westnordost** [comment] 2022-11-03 17:18
So, after all points have been discussed, what would be your concrete suggestion for implementation? How should the filter look?

**Comment by peternewman** [comment] 2022-11-04 19:21
Well I'd like to go for the broader option (and a simpler list of things to exclude)

```
        ways with (
            // Not construction or planned or proposed as not necessarily present yet
            // Not destroyed or razed or removed as probably removed
            // Not no as who knows what that means!
            !highway or highway !~ construction|demolished|no|planned|proposed|razed|removed
            or !railway or railway !~ construction|demolished|no|planned|proposed|razed|removed
            or !waterway or waterway !~ construction|demolished|no|planned|proposed|razed|removed
          ) and (
            bridge and bridge != no
            or man_made = bridge
            or man_made = pipeline and location = overhead
            or man_made ~= goods_conveyor|pier|torii
          )
          and layer
```

But if it's felt we need to stick to an allow list, then as mentioned I'm happy to go through the tags and categorise the likelihood of them existing, as mentioned, maybe that's useful whether it's a list of things to include or exclude?

**Comment by westnordost** [comment] 2022-11-04 20:19
what about `railway=station` etc? Why not simply look for ` bridge and bridge != no`?

**Comment by peternewman** [comment] 2022-11-05 06:28
> what about `railway=station` etc?

It's `!~`, so that should match.

> Why not simply look for ` bridge and bridge != no`?

Because as @matkoniecz predicted, it would give false positives such as:
https://www.openstreetmap.org/way/1093993088
https://overpass-turbo.eu/s/1nqp

I'm not sure the person on the ground would be able to tell if it was proposed or abandoned to re-tag as abandoned:bridge or whatever in those cases, unless it was smart based on the other related tagging.

**Comment by westnordost** [comment] 2022-11-05 08:47
>> what about railway=station etc?

> It's !~, so that should match.

What?  Read that statement again.

**Comment by mnalis** [comment] 2022-11-07 01:15
> > Why not simply look for ` bridge and bridge != no`?

:+1: 

> Because as @matkoniecz predicted, it would give false positives such as: https://www.openstreetmap.org/way/1093993088 https://overpass-turbo.eu/s/1nqp

In my opinion, those examples show either:
- a **_bridge which is really there_**, but a highway is not yet constructed on it (in which case the `max height` quest  should be asked normally), or
- the **_bridge is only proposed_** too, so it is a mapping error made by previous mapper, as [bridge=yes](https://wiki.openstreetmap.org/wiki/Key:bridge) is intended to map `artificial construction that spans features such as roads, railways, waterways or valleys` (which is clearly wrong if there is _nothing_ there!) 
  So, if _bridge is only proposed_, it should be [proposed:bridge=yes](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) instead, so I'd actually _want_ SC user to leave a note about such error found on the map.

Of course in the second case one _might_ tweak a quest to hide the quest instead of noting an error on the map... That would create less work for the SC mapper, but would not help fix errors on the map, so is suboptimal in my opinion - SC has _"leave a note"_ functionality for a reason, and one of those reasons is IMHO pointing others to map errors so they can correct it in more fully fledged editors.

**Comment by matkoniecz** [comment] 2022-11-07 06:24
> So, if bridge is only proposed, it should be [proposed:bridge=yes](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) instead, so I'd actually want SC user to leave a note about such error found on the map.

In such case this can be detected entirely automatically (`=proposed` has clear meaning, unlike `railway=abandoned`).

See 7691 `highway=proposed` `bridge=yes` https://overpass-turbo.eu/s/1nti

**Comment by mnalis** [comment] 2022-11-07 20:47
> See 7691 highway=proposed bridge=yes https://overpass-turbo.eu/s/1nti

@matkoniecz well I did but my dillema expressed above in https://github.com/streetcomplete/StreetComplete/issues/4564#issuecomment-1304966490 still stands:

- Does `highway=proposed` + `bridge=yes` really means what it says (there **is currently physical bridge existing** there, and **in the future** there will be a highway over it too), or
-  **bridge does NOT physically exist there yet** (but bridge will be built there in the **future**, along with the highway) (i.e. it is mistagged, and should've actually been tagged `highway=proposed` + `proposed:bridge=yes`)

I would think the former, but some of the descriptions on those way seem to indicate people are often mistagging as the latter.

Or are we misunderstanding each other?

**Comment by matkoniecz** [comment] 2022-11-08 07:33
> bridge does NOT physically exist there yet (but bridge will be built there in the future, along with the highway)

it is heavily used for that, at least in areas where I edit

> i.e. it is mistagged, and should've actually been tagged highway=proposed + proposed:bridge=yes

not entirely sure about it - it is heavily used for that, to the point that I suspect that `bridge=yes` should be treated as property indicating that rail/road/footway/etc tagged with it has bridge property

**Comment by mnalis** [comment] 2022-11-08 13:18
> not entirely sure about it - it is heavily used for that, to the point that I suspect that bridge=yes should be treated as property indicating that rail/road/footway/etc tagged with it has bridge property

Yes, I can see that some (perhaps even majority, as you say) people might mark it as such, thus creating confusion/unclarity. Which lead to my comment about `detected entirely automatically` being impossible in `highway=proposed` + `bridge=yes` case.

I personally would still tag proposed bridge with `proposed:bridge=yes` to be clear, but people will do what they will...

---

However, back to this specific issue, if it is highly unlikely that `bridge=yes` on its own means that bridge actually exists at that point in time, then we should probably decide which is better:

- ask quest on any `bridge and bridge!=no`, and accept people will leave notes `there is no bridge here` (and let subsequent mapper retagging as `proposed:bridge=yes` or `ruined:bridge=yes` or whatever), or
- leave `max height quest` as-is, and accept that this quest will not be asked in all situations where it should've been asked.

I tend to prefer the former, as there does not seem to be that many proposed bridges a single mapper is likely to encounter, and it is quite easy for subsequent mapper to change tag (while we might even have a separate option  `"There is no bridge here"` that tries to auto-guess lifecycle prefix for bridge by looking at `railway=abandoned` or `highway=proposed`, I somewhat dislike such automagic)

**Comment by westnordost** [comment] 2022-11-10 19:04
So uhm... I haven't been following this thread. If you think a reasonable change can be made, feel free to create a PR. Otherwise this ticket should be closed.

**Comment by boothym** [comment] 2022-12-03 12:04
(Long thread but I've tried to follow it) Am I right in saying we've got a quest which currently asks about the maxheight for every other kind of railway line bridging a highway, except one where the rails have been removed? If so I'd like to add my support for this issue.

Along the coast from me is this old railway viaduct, which presumably would not be highlighted in SC for the maxheight quest despite being a bridge. Whereas if the rusted rails were still in place, it could be tagged as railway=disused and it would be available in SC.

https://www.geograph.org.uk/photo/5858698
https://www.openstreetmap.org/way/124190812

> The problem here is that there is notable group of people trying to gaslight rest of community that railways are extraspecial and can be mapped even when fully and utterly gone. I am all for fixing that problem, but just wanted to make clear that it will result in predictable discussions with people claiming that utterly removed railway switches are mappable.
> 
> Also, railway=abandoned bridge may look like this: https://wiki.openstreetmap.org/wiki/File:Demolished_Torwoodlee_Railway_Bridge_-_geograph.org.uk_-_750961.jpg (mapping it as `railway=abandoned bridge=yes` is actually considered acceptable)

Considered acceptable by who? If a bridge isn't there then we should be using some other tag - like demolished:bridge=yes (abandoned:/razed:/removed:/was: are other popular bridge prefixes) to differentiate between the present/not present status of the bridge. That's certainly what I've done with missing bridges on abandoned rail alignments, and will continue to do with any others I come across via overpass turbo.

(Ironically, that bridge pictured above has since been rebuilt as part of the Borders Railway)

**Comment by matkoniecz** [comment] 2022-12-03 13:01
> Considered acceptable by who?

`railway=razed bridge=yes` alone is used 1 683 times https://taginfo.openstreetmap.org/tags/railway=razed#combinations

`railway=abandoned bridge=yes` is used 31 022 times https://taginfo.openstreetmap.org/tags/railway=abandoned#combinations (though here it ranges from "bridge stands but rails were removed" to "bridge location is now 30m deep hole of open pit mine")

If you are interested in fixing data/reviewing places/contacting people who mapped this I can generate list of all people or all changesets that added this similar to https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/migrate_surface%3Dcement_to_surface%3Dconcrete_on_USA_roads_and_paths/stats

**Comment by matkoniecz** [comment] 2022-12-03 13:04
> If you think a reasonable change can be made, feel free to create a PR. Otherwise this ticket should be closed.

Is anyone planning to make PR? I am not planning as I think that it would make SC worse a bit. Though it would increase pressure on people incorrectly mapping railways despite that no trace of them remains.

**Comment by boothym** [comment] 2022-12-03 14:09
> Yes, though proposed change would result in asking also in some places where bridge was removed.

I don't see that as a problem, SC specifically asks users "Is this still here?" with lots of things including benches, telephone boxes, bus stops, etc. and provides functionality in the app to say the feature doesn't exist. 

Those `railway=abandoned bridge=yes` combination numbers will also include old railway lines converted to cycle paths, i.e. with a highway tag, so the bridge is still there and in use. Plus many more are over water, abandoned tracks alongside an already mapped railway bridge, or ones mapped on top of a man_made=bridge so 

Is there a way to generate a list of all instances of `railway=abandoned and highway!=* and bridge=*` which cross over a highway (rather than water) so we can try and fix wrongly tagged bridges?

**Comment by matkoniecz** [comment] 2022-12-19 08:05
So in conclusion:

- I think that it would make things marginally worse but it is not so bad to outright consider it as a mistake
- position of @westnordost is that "So uhm... I haven't been following this thread. If you think a reasonable change can be made, feel free to create a PR. Otherwise this ticket should be closed."

I am proposing to close this issue without rejecting potential PR.

**Comment by boothym** [comment] 2022-12-20 00:28
How can a quest that highlights more roads which are missing a maxheight value, and will highlight bridges which are wrongly tagged as still being present on the ground (allowing them to be fixed) - "make things worse"?

I can't create the PR but don't see why this needs to be closed.

**Comment by matkoniecz** [comment] 2022-12-20 05:17
> allowing them to be fixed

The problem is that decent chunk of people argues/treats that mapping stuff like https://wiki.openstreetmap.org/wiki/File:Demolished_Torwoodlee_Railway_Bridge_-_geograph.org.uk_-_750961.jpg as `railway=abandoned bridge=yes` is OK

**Closed** 2022-12-21 10:34 UTC
Labels: needs PR

**Comment by boothym** [comment] 2022-12-21 12:27
@matkoniecz I think there is a difference between people who want to map fully gone railways versus fully gone bridges. If the bridge is not present then bridge=yes is not correct, and it is that we are concerned about here rather than the abandoned or razed tags which is where the conflict usually occurs.

Even if you are not going to implement this here, it would be good if there was an overpass turbo query or other way to list all of these abandoned/razed bridges crossing highways, so they could be looked at.

**Comment by matkoniecz** [comment] 2022-12-21 13:17
> Even if you are not going to implement this here, it would be good if there was an overpass turbo query or other way to list all of these abandoned/razed bridges crossing highways, so they could be looked at.

not entirely sure how to detect it using overpass

some fancier processing may be needed

**Comment by mnalis** [comment] 2022-12-22 17:50
> not entirely sure how to detect it using overpass

maybe something along this lines https://stackoverflow.com/q/22468442/2600099 ?

**Comment by mnalis** [comment] 2022-12-23 23:55
> Even if you are not going to implement this here, it would be good if there was an overpass turbo query or other way to list all of these abandoned/razed bridges crossing highways, so they could be looked at.

@boothym  here is the overpass query that should find them: http://overpass-turbo.eu/s/1pnw
