### ISSUE TITLE
Show raw tags of quest objects

### ISSUE THREAD

**Issue by hsimpson00** [streetcomplete/StreetComplete#3815] opened 2022-02-27 10:52 UTC
In some complex situations the existing methods are not enough to figure out what object is actually meant.
For example if you are supposed to verify a tiket box in a big station, or you are asked by the foot-accessability of a small way in a complex crossing.

It would be helpful to pesent an option which allows you to see all the tags of the concerning object, so you can see the operator, the layer, level and more details to figure out where to look for the object. Maybe it would be even helpfull to see the relations the object is a member of.

**Comment by matkoniecz** [comment] 2022-02-27 11:07
The problems here are that StreetComplete should be usable without ability to understand tags.

And full access to raw data is basically remaking Vespucci.

Can you mention quests where showing `operator` would be useful and this is not shown already?

**Comment by FloEdelmann** [comment] 2022-02-27 11:14
Related: #471 and many of the issues linked there (#1513, #1326, etc.)

**Comment by matkoniecz** [comment] 2022-02-27 11:17
I will close this one as duplicate of #471, #1513, #1326 but display of `operator`/`ref` is already supported in some quests and can be added to more if needed.

Feel free to comment here or open a new issue requesting specifically that.

If other tags are worth displaying and understandable without access to full OSM data - please also comment or open a new issue.

**Closed by matkoniecz** 2022-02-27 11:17 UTC
Labels: feedback required

**Comment by FloEdelmann** [comment] 2022-02-27 11:22
`level` is also already shown above the question:

https://github.com/streetcomplete/StreetComplete/blob/ff60e6e375348d803a2bac54fb31cb6e0e076d0e/app/src/main/java/de/westnordost/streetcomplete/quests/LocationLabel.kt

**Comment by peternewman** [comment] 2022-02-27 11:50
And CheckExistence tries these:
https://github.com/streetcomplete/StreetComplete/blob/715faf4/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt#L94-L98

So you'd need to give a real world example for a ticket vending machine to see what's going wrong there.

I agree footpaths/cycleways can be a bit confusing at times, especially as the latter are mapped the same as roads but that's been raised here https://github.com/streetcomplete/streetcomplete-mapstyle/issues/94 .
