### ISSUE TITLE
Show what floor "unit" is used.

### ISSUE THREAD

**Issue by 7RST1** [streetcomplete/StreetComplete#2546] opened 2021-02-02 08:54 UTC
**Use case**
When doing quests on multistorey buildings, it gives what floor number the feature is situated on. I live in Norway, and here, first floor is ground floor. Thus, when I see "floor 3", it's hard for me to know whether you mean 0,1,2,**3**,4 or 1,2,**3**,4,5. The fact that the app is translated to a language of which we use the latter, and OSM data uses the first, makes it even harder to know.

**Screenshot:**
<details>

![Screenshot_20210202-095323](https://user-images.githubusercontent.com/16783057/106575615-93614280-653c-11eb-9a98-0a46190f5b40.jpg)

</details>

**Proposed Solution**
Maybe the range of floors can be stated in paranthathesesse after the floor; Floor 3 (in 0-4)
Or state that ground is zero (or one); Floor 3 (ground is 0)

**Comment by matkoniecz** [comment] 2021-02-02 10:12
> Thus, when I see "floor 3", it's hard for me to know whether you mean 0,1,2,3,4 or 1,2,3,4,5

The problem is that if `level` tag is used app is also unaware which numbering was used. `level` is supposed to use 0, 1, 2... and `level:ref` local scheme but it is often not followed.

**Comment by 7RST1** [comment] 2021-02-02 10:44
Okay, so if the app just uses the raw OSM value, then it should show it with e.g. "(ground floor is 0)" or similar. Some other apps using OSM translates the value to local floor unit, so it would be nice for it to show it so that the user is completely sure of the value.

**Comment by matkoniecz** [comment] 2021-02-02 10:47
>level is supposed to use 0, 1, 2 (...) but it is often not followed

**Comment by 7RST1** [comment] 2021-02-02 10:53
I think it should be shown anyway. I mapped the feature in question on the screenshot, and I didn't know if it meant the one on the 3rd or 4th floor. I don't question whether or not the actual number gotten from OSM is correct, but rather if the app alters it in any way to suit local standards, and if it doesn't; confirm it by stating it at the end of the message.

**Comment by DerDings** [comment] 2021-02-02 13:35
The app already shows `level:ref`  in favor of `level`, if this information given.

I think if `level:ref` is not given, it is very likely that someone was unaware of the difference between `level` and `level:ref`. They maybe just tagged the locally signed level as `level`, without knowing that the osm definition may be different.
So if `level:ref` is not given, there is no way for the app to know whether a previous mapper used the correct osm scheme (0, 1, …) for `level` or any other scheme.

Probably the only solution to tackle this issue is to encourage local mappers to make correct use of both tags `level` and `level:ref`.


A quest could be made for certain countries, asking for the correct values of both `level` and `level:ref` if only one of them is given. But I think this would produce more problems than it solves. With levels, what matters most is consistency in local context (a single building). This better to be edited in a more advanced editor.

**Comment by DerDings** [comment] 2021-02-02 13:41
If this is a really common problem in some countries, maybe there showing the level could be completely disabled, only showing `level:ref`?

**Comment by westnordost** [comment] 2021-02-02 14:32
I am closing this as will not fix because of the arguments given by @DerDings and @matkoniecz so far.

What you can do, @7RST1 , is to fix the Norwegian translation (Bokmal and Nynorsk):
The text should really only refer to "level 3", not "floor 3". It looks like the word used in Norwegian currently is the word for "floor", not for "level": https://enno.dict.cc/?s=etasje

**Closed by westnordost** 2021-02-02 14:32 UTC

**Comment by matkoniecz** [comment] 2021-02-02 16:33
See https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app for how app may be translated.
