### ISSUE TITLE
Text-based UI for less frequent tag values

### ISSUE THREAD

**Issue by rhhsm** [streetcomplete/StreetComplete#2921] opened 2021-05-27 17:58 UTC
There are frequent requests here to add less frequently used building types/highway surfaces/recycling categories/etc answer options. Would it be an idea for such quests to have an "Other answers" option which leads to a text based UI where the mapper can type the desired tag value? Such UI already exists for the "It does not exist…" answer option for shops that have changed. Its use can be expanded for other large groups of tag values.

**Comment by westnordost** [comment] 2021-05-27 18:24
Basically a duplicate of #471

**Closed by westnordost** 2021-05-27 18:24 UTC

**Comment by rhhsm** [comment] 2021-05-27 18:48
I didn't mean to allow any tag value, that would indeed lead to too many new tag values being created. I mean to allow only the next 10-20 most frequently used values for which there isn't an answer option now. There are only a limited number of words that can be typed in the "It does not exist…" answer option for shops that have changed, isn't it? It works very well, and I think the idea could be used more often. For instance #2889, instead of adding yet another picture of a surface to what is becoming a very long list, allow the mapper to type wood_chips , wood_chippings, wood_mulch, wood_chip, wooden_chips, wood_shavings, Bark_wood_Chip,bark_wood, wooden_chaff, etc, which all lead to surface=woodchips being added.

**Comment by matkoniecz** [comment] 2021-05-27 19:32
Interface for that would be quite complex to implement and use, using Vespucci in such rare cases or leaving note seems fine.

If such cases are not rare then one more answer can be added.

**Comment by rhhsm** [comment] 2021-05-28 10:28
OK, I thought it was a matter of copy-pasting the code for the shop type quest, and adding the 10-20 next most frequent tag values that are not represented as pictures or icons as answer options (+ any requested on this forum). I'm sorry I can't contribute to enhancing SC except with my user experience...
