### ISSUE TITLE
Selection of levels for multi-storey buildings

### ISSUE THREAD

**Issue by OpenGreenStreet** [streetcomplete/StreetComplete#4444] opened 2022-10-01 07:22 UTC
With multi-storey buildings it is incredibly difficult to orientate. A selection of the level would be very helpful.
(Prominent example: Berlin Central Station)

**Comment by FloEdelmann** [comment] 2022-10-01 08:16
Duplicate of #2874 and #3068.

**Closed by FloEdelmann** 2022-10-01 08:16 UTC

**Comment by OpenGreenStreet** [comment] 2022-10-01 08:30
"not planned": this is a great pity

**Comment by FloEdelmann** [comment] 2022-10-01 08:33
Note that this decision was done in https://github.com/streetcomplete/StreetComplete/issues/2874#issuecomment-855910833 and https://github.com/streetcomplete/StreetComplete/issues/3068#issuecomment-880264761, it might have changed by now.

**Comment by OpenGreenStreet** [comment] 2022-10-01 08:49
@FloEdelmann Danke für Deine Rückmeldungen und Hinweise. Ich empfinde die Bearbeitung solcher Objekte auch als frustrierend. Wie man am Berliner Hbf sieht, sind dort die meisten Fragen unbeantwortet . . . Herzliche Grüße

**Comment by mnalis** [comment] 2022-10-03 12:26
For those advanced users who feel comfortable with it, [StreetComplete Expert Edition fork](https://github.com/Helium314/StreetComplete) does implement level filtering, e.g.:

![small_Screenshot_20221003_142238_de westnordost streetcomplete expert](https://user-images.githubusercontent.com/156656/193575840-fbc03cc9-c8a1-46d5-98d2-577609207c5c.jpg)

**Comment by OpenGreenStreet** [comment] 2022-10-03 16:46
@mnalis hello that sounds very good. Thank you for your advice. Can I find the version in the playstore?

**Comment by HolgerJeromin** [comment] 2022-10-03 20:43
You can download it from
https://github.com/Helium314/StreetComplete/releases

**Comment by OpenGreenStreet** [comment] 2022-10-04 03:14
@HolgerJeromin Thank you very much
