### ISSUE TITLE
Does not stay logged in

### ISSUE THREAD

**Issue by stuartlangridge** [streetcomplete/StreetComplete#3254] opened 2021-09-04 07:56 UTC
When I attempt to log in to openstreetmap to publish my changes, this seems to fail, or perhaps to succeed but not stick.
In my Profile screen, I am told that I have 16 not yet published changes and I need to log in.
When I hit the login button I am taken to an OpenStreetMap OAuth-ish screen where I have to authorise access to my account, which I have done, and said Grant Access.
I am then returned to the My Profile screen and it shows that I am now logged in; I see my OSM username, a logout button, and that I have 16 not yet published changes.
However, when I return to the map, I have a popup saying "you need to authorise with your OSM user account to publish your answers. Authorise now? You can also do this later on the profile screen."
Saying OK in this dialog makes me go through the login process again.
Saying Later in this dialog and then bringing up My Profile shows that I am not logged in.
So, for some reason, logging in seems to work but not to stick.

**Versions affected**
StreetComplete v34.0
Android 10

**Comment by matkoniecz** [comment] 2021-09-04 09:38
What is your phone model? Have you installed from F-droid?

**Comment by stuartlangridge** [comment] 2021-09-04 09:40
The phone is a Nokia 8 Sirocco. I have F-droid on the phone, but I don't think I installed StreetComplete from it; I think I installed it from the Play Store. I'm not sure how to confirm that, though.

**Comment by westnordost** [comment] 2021-09-04 09:50
What's your android version? 

Am 4. September 2021 11:40:19 MESZ schrieb Stuart Langridge ***@***.***>:
>The phone is a Nokia 8 Sirocco. I have F-droid on the phone, but I
>don't think I installed StreetComplete from it; I think I installed it
>from the Play Store. I'm not sure how to confirm that, though.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3254#issuecomment-912943325

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by stuartlangridge** [comment] 2021-09-04 09:52
10. I can try to get a more accurate number with minor versions etc somehow if that's useful.

**Comment by westnordost** [comment] 2021-09-04 12:33
No, 10 is fine. There are known problems with android 4.

How about your network - maybe it blocks some traffic? Are you in a wifi? Is it your own?

**Comment by stuartlangridge** [comment] 2021-09-04 12:35
it is my wifi at home, but the problem also occurs when using mobile data, so it don't think it's a network-specific problem. I also do see the "grant access" screen, which I assume is on the web somewhere at openstreetmap.org, so that's not being blocked.

**Comment by westnordost** [comment] 2021-09-04 15:09
Hm then, to be honest, I don't have an idea right now what could be the cause. Needless to say, you are the first one to encounter this issue, so there must be something unusual about your device, connection or something. Or maybe it is a bug in v34.0 and you are just the first one to encounter it. But I don't remember changing anything in that regard.
Just to exclude this, maybe you could try downgrade to v33 to test this. Unfortunately, I think this would delete all the questions you answered so far.

**Comment by westnordost** [comment] 2021-09-04 15:10
Or maybe you are banned or something? Did you try to edit the map on openstreetmap.org, using your OSM account?

**Comment by stuartlangridge** [comment] 2021-09-04 15:14
Ooh! I've just tried editing the map on openstreetmap.org and it said:

"You have not set your edits to be public. You can no longer edit the map unless you do so. You can set your edits as public from your user page."

So I set my edits to be public on my user page, and now when I sign in inside StreetComplete, everything works!

So that was the problem. Thank you for that; it never occurred to me to try that.

Perhaps the app might be able to detect that this is the case and warn the user? I don't think you'd need to be able to set your edits public from inside StreetComplete, but if the sign-in process detected an account in this state, maybe a popup dialogue explaining that edits are not public and linking to the user profile page in the browser would be a good idea?

**Comment by westnordost** [comment] 2021-09-04 15:24
Oh ok, not sure what that means. Did you register on OSM.org a really long time ago?

I think the problem here is that osm.org responds with 403 forbidden in that case. StreetComplete interprets that as "you are not (properly) logged in", so logs you out and prompts you to log in again. Not 100% about this though, if I remember correctly, what exactly the OSM API responds in such case is not documented.

**Comment by stuartlangridge** [comment] 2021-09-04 15:25
Probably yes; my account is quite likely ten or more years old, but I don't use it (fixing that and starting to help is what prompted me to install StreetComplete in the first place!). So there may not be many people in my situation -- perhaps this issue in itself being searchable might help anyone else who ends up in this position and it could be closed.

**Comment by westnordost** [comment] 2021-09-04 15:31
Yeah, I'd also tend to close it instead of researching into what HTTP code exactly is returned and if it can be told apart from other "forbidden to edit" cases. Back in... I don't know, 10 years ago or so, OSM changed the license and all contributors till that date had to say yay or nay. (To further contribute, they had to say yay.)

So, I think this case is nowadays really rare.

Anyway, glad to have you back, go OSM and happy mapping!

**Closed by westnordost** 2021-09-04 15:31 UTC
Labels: bug
