### ISSUE TITLE
Tag implicit maxspeeds in the maxspeed tag, instead of 'maxspeed:type'

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#2450] opened 2021-01-03 09:23 UTC
**Use case**
StreetComplete is currently tagging the maxspeed as a number in `maxspeed=n` and an implicit value in `maxspeed:type=x`. This way we add unnecessary redundancies to the database. Any future edit might only include one of the values and lead to conflicts.

**Proposed Solution**
There's no need to use a specialized tag like `maxspeed:type` or `zone:maxspeed`.

Both can be tagged directly as implicit values in the maxspeed tag, like:

```
maxspeed=DE:urban
or
maxspeed=DE:zone30
or
maxspeed=DE:living_street
or
maxspeed=DE:walk
```

This is makes parsing much more easy - every data consumer has to read only one tag, instead of 4 (maxspeed, maxspeed:source, maxspeed:type, zone:maxspeed) and guess which one is the correct one. And if default speeds gets changed in a country, like it's going to be shortly in Spain[1] then there's no need to use a bot to change the `maxspeed=n` values based on some additional tag.

When we resurvey a speedlimit, we should remove the `maxspeed:type`, `zone:maxspeed`, `maxspeed:source` tags, to avoid any conflicting information. 

[1] https://www.eltis.org/in-brief/news/new-spanish-law-require-30-kmh-speed-limit-urban-areas#:~:text=in%20urban%20areas-,New%20Spanish%20law%20to%20require%2030%20km,speed%20limit%20in%20urban%20areas&text=The%20Spanish%20Minister%20of%20the,order%20to%20improve%20road%20safety.

**Comment by matkoniecz** [comment] 2021-01-03 12:00
> When we resurvey a speedlimit

There is no resurvey of speed limits. See https://github.com/streetcomplete/StreetComplete/issues/1998#issuecomment-676787192

**Comment by westnordost** [comment] 2021-01-03 15:22
Basically a duplicate of #2415

**Closed by westnordost** 2021-01-03 15:22 UTC
