### ISSUE TITLE
Crashes when selecting a way covered by an area

### ISSUE THREAD

**Issue by slasherfun** [streetcomplete/StreetComplete#5424] opened 2023-12-24 15:37 UTC
**How to Reproduce**
- Open StreetComplete
- Set either the street lighting / bike paths / street parking layer
- Try to click on https://www.openstreetmap.org/way/24817348 (in StreetComplete)
- https://www.openstreetmap.org/way/26693025 is selected instead, and StreetComplete immediately crashes

After the app is restarted, there is nothing about the crash in the app logs.

**Expected Behavior**
Should select the right way and not crash.

**Versions affected**

56.0-beta1

**Comment by Helium314** [comment] 2023-12-24 16:50
Looks like it's a duplicate of #4681, see https://github.com/streetcomplete/StreetComplete/issues/4681#issuecomment-1349747181 for an explanation

**Comment by slasherfun** [comment] 2023-12-24 19:11
Thanks, looks like it.
I agree that the tagging of the second way is badly done, yet maybe StreetComplete shouldn't crash when they exist? Even if that means just completely hiding those badly tagged ways so that they cannot be selected.

**Comment by matkoniecz** [comment] 2023-12-25 11:16
I edited https://www.openstreetmap.org/way/26693025 a bit

**Comment by westnordost** [comment] 2023-12-31 20:35
Thanks, @Helium314 , for digging up that other bug. I agree that it is sub-optimal that StreetComplete crashes in this case, but I am trusting the assessment of my past-self here.

**Closed** 2023-12-31 20:35 UTC
Labels: bug
