### ISSUE TITLE
Enable the user to "group answer" a quest over several items 

### ISSUE THREAD

**Issue by Chepycou** [streetcomplete/StreetComplete#6019] opened 2024-11-22 13:30 UTC
### **Rationale**
Sometimes several nodes/ways may be one continuous or several identical thing(s) in the real world. In this case, it would help with productivity to allow a user to select equivalent items and answer the quest for each in one click of a button. Another Advantage would be to reduce the Human Error potential. I have personally already mapped such places and the fact of doing the same quest 20 times in a row just for different part of a road increases the probability of selecting a wrong answer.

### **Use-case example**
For instance, a parking lot that is a uniform asphalt surface is sometimes broken down into tens or even hundreds of small ways (at least where I live). This results in many quests that could be solved as one. Same thing when considering a row of identical houses for instance. 

### **Proposed Solution**
Allow for the user to long press on a quest to select this one and equivalent quests. Then once the user has answered the quest, answer each of them with the chosen answer. I think it is better to treat them separately, because in the case one realizes that there's a crack in this part of the parking lot or that one house is actually a tad more yellow than the others in the row, it'd be nice to be able to undo this one specifically.

This feature allowing for a bigger impact it may be better suited for SCEE or to have a big "Warning you are about to change {numberOfQuests} items, are you sure you checked that they are all identical ?". If needed, I can file this FR in SCEE's repo.

**Comment by westnordost** [comment] 2024-11-22 16:12
This has been suggested at least one time before and rejected. I can't find the issue(s) right now, though. Maybe someone else is able to link them. Closing as duplicate.

**Closed by westnordost** 2024-11-22 16:12 UTC
Labels: duplicate

**Comment by westnordost** [comment] 2024-11-22 16:21
But just to summarize from the top of my head, this is problematic for the following reasons:
- "hidden" UI pattern, not self-explanatory
- each quest, also of the same type, has a context (kind of object, surrounding objects, name etc.), which is displayed when opening *that* quest. If you just select quests of the same type en masse, this information will never be displayed. Depending on the type of quest, this information may however be very necessary to give the correct answer.
- in general, the quest forms are very custom, i.e. what is displayed in the form, even what is selectable in the form and what is tagged is very much dependent on the element selected (depending on the quest type). So, it would even be quite difficult (or even impossible) to implement correctly in SCEE

**Comment by mnalis** [comment] 2024-11-23 20:18
Related issues:
- https://github.com/streetcomplete/StreetComplete/issues/73
- https://github.com/streetcomplete/StreetComplete/issues/2353
- https://github.com/streetcomplete/StreetComplete/issues/1303
- https://github.com/streetcomplete/StreetComplete/issues/3098#issuecomment-888255447
- https://github.com/streetcomplete/StreetComplete/issues/2968
- https://github.com/streetcomplete/StreetComplete/discussions/5922

**Comment by mnalis** [comment] 2024-11-23 20:19
Duplicate of #73
