### ISSUE TITLE
Reoccuring Surface quest cannot be solved when splitting that way

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4520] opened 2022-10-17 17:51 UTC
**How to Reproduce**
1. Select a quest which asks for the surface of a way
2. This quest must be a reoccuring one. It means the way has already a surface tagged, but after x years this is asked a again to confirm or update the way
3. Use the further option to split the way, because it has different surfaces
4. Split the way according the different surfaces and confirm the split
5. The surface quest is gone now

**Expected Behavior**
The surface quest shall be asked for all splitted parts of the way and shall not disappear. 

**Versions affected**
48.0-beta1, but this behaviour is older than this version. I do not know the first version when this happened.

**Comment by Helium314** [comment] 2022-10-17 18:27
see #3567
This has been around for some time, probably since the start or resurvey quests.

**Comment by mnalis** [comment] 2022-10-17 19:01
After rereading those, it still seems to me that it should be solvable in SC. Sure, uploading `check_date:surface` to OSM as suggested in https://github.com/streetcomplete/StreetComplete/issues/2883#issuecomment-844757944 woud be quite kludgy, but SC should be able to keep that state internally without any such changes being sent to OSM (e.g. _remembering that both parts of the split way should be eligible to all quests_, e.g. making all `surface older today -12 years` etc. succeed on ways that are internally marked as being split.)

It is a matter of how hard (and/or kludgy) such functionality would be to implement. As someone who meddled with such code recently @Helium314, do you think it would be possible to add something like `boolean wasRecentlySplit = false` to downloaded elements (and setting it to `true` when way is split, and using it later when deciding weather to show a quest)?

**Comment by Strubbl** [comment] 2022-10-17 19:11
Sorry, that i opened a topic which was already closed as wontfix. I did not find it before. If there is no easy solution and the status is still wontfix, please feel free to close this issue.

**Comment by Helium314** [comment] 2022-10-17 21:14
> do you think it would be possible to add something like boolean wasRecentlySplit = false to downloaded elements (and setting it to true when way is split, and using it later when deciding weather to show a quest)?

You could check `ElementEditsDao.getForElement` for each dowloaded element, and `wasRecentlySplit = edits.any { it.action is SplitWayAction }`. Just please don't do this on a bbox download for performance reasons.
Any actually it might be better to do this check when creating quests for a single element (`OsmQuestController.createQuestsForElementDeferred`).

**Comment by mnalis** [comment] 2022-10-19 22:08
This also seems to be fixed by https://github.com/streetcomplete/StreetComplete/pull/4523, right @Helium314 ?

**Comment by Helium314** [comment] 2022-10-20 05:12
Is it? I didn't try it with auto-upload switched on, but I expect after upload at best the "old" segment with the original id couly maybe be re-surveyed because of #4472

**Comment by matkoniecz** [comment] 2022-10-20 07:03
> This also seems to be fixed by https://github.com/streetcomplete/StreetComplete/pull/4523, right @Helium314 ?

Only with upload set to manual.

**Comment by mnalis** [comment] 2022-10-20 11:38
Yes, I only tried it with manual upload (on latest master + PR4523), and it worked there for both segments.

**Comment by westnordost** [comment] 2022-10-21 20:32
Duplicate of #3567

**Closed by westnordost** 2022-10-21 20:32 UTC
Labels: duplicate
