### ISSUE TITLE
Can we have increment button on steps counting quest?

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3807] opened 2022-02-24 00:41 UTC
When I'm counting in my head to answer the question about how many steps there are, it would be nice if SC would keep track of the number and I just hit the + button for each step

I'm sure your already know what I mean, but here is a screen shot anyway. I want these buttons from the house number quest on the step counting quest.

![Screenshot_20220224-003601](https://user-images.githubusercontent.com/87654968/155434956-6795047c-761f-453f-8455-b86b0f109a4f.png)

Thanks for reading 🙂

**Comment by smichel17** [comment] 2022-02-24 02:24
Duplicate of #2362

**Closed** 2022-02-24 02:24 UTC
