### ISSUE TITLE
app crashes when selecting highway (closed way without `area=yes`)

### ISSUE THREAD

**Issue by legofahrrad** [streetcomplete/StreetComplete#4681] opened 2022-12-11 20:45 UTC
**How to Reproduce**
Select this way in the cycleway overlay: https://www.openstreetmap.org/way/326419710

**Expected Behavior**
The app crashes immediately. It should not allow to select areas (I guess it does already excludes area=yes)
The issue might be in the OSM data and the way mentioned above should be tagged with area=yes. 

**Versions affected**
v50.0

---

Edit: happens not only in cycleway overlay but in sidewalk overlay too

**Comment by westnordost** [comment] 2022-12-13 20:42
Hm, this is actually tagged wrong. It should have `area=yes`.

Question is, should StreetComplete `highway=*` that is **also** a different map feature that is inherently an area interpret that road as an area then?

**Comment by westnordost** [comment] 2022-12-13 20:58
Hm, one and the same element cannot be an area for one feature, but not the other...

**Comment by westnordost** [comment] 2022-12-13 21:27
I've sat at this for over an hour now and I don't really have an angle how to fix this. For starters, this is not an issue that only affects the cycleway and sidewalk overlay, but pretty much every quest that works on (non-area) roads and filters the OSM elements like `highway=... and area != yes`.

This filter does not work if the element contains something in the list of tags that implicitly makes that element an area (such as e.g. `shop=*`), the assumption that above statement filters out any roads that are areas does not work anymore. But pretty much every quest and overlay that does anything with roads works with this assumption.

And it is a reasonable assumption: Data consumers that only process roads, ways and not any other stuff (such as routers) will not have a huge list like this https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/Area.kt of element types that should be interpreted as areas implicitly. Hence, 
Carto only renders this correctly because it renders everything.

To fix that in StreetComplete, one would again need to check if something is really not an area for every single element for every single quest that does this filtering. All that, to avoid that the app crashes on (hopefully) very rare cases of such tagging errors.

An area data type in OSM would fix this by the way. Anyway, even though this crashes the application, with heavy heart I will close this because I see no good way to fix this without massively complicating the code.

**Closed by westnordost** 2022-12-13 21:27 UTC
Labels: bug

**Comment by westnordost** [comment] 2022-12-14 10:36
No, because
- It would only be possible to catch _any_ error, and this is undesirable because it would inhibit that crash reports reach me so that I can fix them
- It is not possible to catch that error at a central location and then open a note about it, the try-catch would need to be added at every place where this may happen. At this point, one might as well add the area-check instead everywhere
- the creation of a note instead would be bothersome to implement because so far, SC does not automatically create notes. And if the app is supposed to just open a note and explain (something??), it would need to be communicated to the user properly - just opening the form does not make sense

The issue as reported exists since version 1, it is not new. Yet, it was only reported now. This should give you an estimate how often this situation actually occurs. Also, on crashing, I think you vastly underestimate how often per day the app is crashing (I mean for all users combined). Most is caused by tangram-es, but there are also other esoteric Android lifecycle (I think) related issues I never understood where they came from and how to fix them.

**Comment by westnordost** [comment] 2022-12-14 11:00
In the last month, there had been about 100 crashes.
- 50% were caused by tangram-es
- 16% by #3858
- 7% by  #4685
- 20% are esoteric Android lifecycle issues
- 7% by others

**Comment by matkoniecz** [comment] 2022-12-14 11:41
One actionable thing is to look through this kind of OSM data and fix it or open notes (as this objects are simply broken anyway).

Maybe ask JOSM and other validators to highlight them and complain about data breakage.

**Comment by mnalis** [comment] 2022-12-14 18:11
>  According to Google Play, 2.4% of all daily sessions include a crash.

Wow, you're correct, I've had no idea the situation was that bad. :open_mouth: 

If all that effort would reduce number of crashes just by a low-single-digit percents, then it is indeed not worth spending time on.

**Comment by westnordost** [comment] 2022-12-14 18:16
Most crashes you won't notice, because I think at least the tangram crashes and the "esoteric Android lifecycle issues" occur when entering/exiting the app (70%) and in that case the Android system just restarts the app. It would only be noticeable by a delay of displaying the map when reentering the app

The crash related to the work manager happens in a background process that is even executed when the app itself is not open (16%), so it is not noticeable at all for the user.
