### ISSUE TITLE
Map goes blank after submitting a note

### ISSUE THREAD

**Issue by nicorikken** [streetcomplete/StreetComplete#2857] opened 2021-05-07 10:19 UTC
After submitting a note, the map goes blank and there is no way to get it back other than restarting the app.

**How to Reproduce**

1. Use StreetComplete
2. Make a note, possibly with a picture in it (I did)
3. Submit the note
4. You get back to the map, but now it is blank and stays blank.

When the map is blank you can zoom, and the out-of-screen marker appears when you scroll to far.
I was only able to get back by terminating StreetComplete and reopening it fresh.

**Versions affected**

StreetComplete version v31.3
Android version 11

**Comment by peternewman** [comment] 2021-05-08 02:13
It's not somehow a regression of #1719 is it? Did you have connectivity at the time @nicorikken or were you offline?

**Comment by westnordost** [comment] 2021-05-08 12:45
Anyway, I am going to close this is old/will not fix because too much code changed for v32.0. If this occurs again for v32+, please open a new issue.

**Closed by westnordost** 2021-05-08 12:45 UTC
Labels: bug

**Comment by nicorikken** [comment] 2021-05-10 06:50
@peternewman connectivity seemed good. Also I waited for a couple of minutes even, and tried walking a bit. So it didn't seem like it was a failing data reload.
@westnordost good, I just downloaded the beta version. I'll report back if it happens again. It feels bad to file testing-notes.

**Comment by nicorikken** [comment] 2021-08-04 14:14
I haven't seen this appear in newer versions.

**Comment by peternewman** [comment] 2021-08-06 12:14
That's odd @nicorikken . FWIW I do still get this in v33.2 (Android 9) @westnordost . When I add a note/answer a quest with one, it clears all the markers for a bit until it redraws them, although the underlying map remains. I'm guessing Nico's issue was more significant from the sounds of things.

**Comment by nicorikken** [comment] 2021-08-11 13:22
@peternewman as this was a one-time occurance without a way to reproduce it is hard to determine if the issue is no longer there. I haven't seen it, but if you do it sounds like there should be an issue on it.
