### ISSUE TITLE
Sometimes quest markers are not shown, but only their dot

### ISSUE THREAD

**Issue by Strubbl** [streetcomplete/StreetComplete#4522] opened 2022-10-17 18:25 UTC
**How to Reproduce**
I experienced sometimes that quest icons are not shown, please see the screenshot below. You can only see the dot, that there is a quest, but not the quest icon. I need to play with the zoom and rotate functions in order to get the quest icon and to be able to solve the quest.

The example from the screenshot is the area https://www.openstreetmap.org/node/2755699329. It was taken when i zoomed to the maximum zoom level.

**Expected Behavior**
Display the quest marker when there is no other quest around.

**Versions affected**
48.0-beta1

![grafik](https://user-images.githubusercontent.com/97055/196253929-f87321e7-fb9c-47e6-a5b0-83a30d892f41.png)

**Comment by Helium314** [comment] 2022-10-17 19:08
I remember there was some similar issue previously, where some labels(?) were causing quests to be hidden, but that was already solved...
Is the quest shown if you disable the overlay?

**Comment by Strubbl** [comment] 2022-10-17 19:29
Unfortunately this quest from the screenshot is solved already. If i see a similar issue, i will try switching off the overlay.

**Comment by Helium314** [comment] 2022-10-17 20:16
Probably no need, I just found a quest being hidden by a label (name of the path).

**Comment by westnordost** [comment] 2022-10-25 11:15
Hm, I've come to the conclusion that this is either a tangram-es issue or I didn't understand something. In either case, this cannot be fixed (by me).

1. In can confirm that indeed the pin is hidden by the label of a road and the housenumber label. [The road](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/map_theme/jawg/layers/labels.yaml#L11) has a [`priority`](https://tangrams.readthedocs.io/en/main/Syntax-Reference/draw/#priority) of 25. Text with a lower priority value are drawn first and occlude others.

2. [The priority of the `streetcomplete-pins` layer](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/map_theme/jawg/streetcomplete.yaml#L136) (the layer in which the quest pins are shown)  however is smaller than 1. So it should always be in front of other labels. Even if I hardcode a priority of 0.5, still the road label occludes the quest pin.

3. The [`blend_order`](https://tangrams.readthedocs.io/en/main/Syntax-Reference/styles/#blend_order) of a drawing style defines what is drawn on top. the `blend_order` of the `pin-icons` style which is used to draw the `streetcomplete_pins` layer as defined in [`streetcomplete.yaml`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/assets/map_theme/jawg/streetcomplete.yaml) is 2. Even if I increase that to an absurdly high number, the road label still occludes the pin.

4. The [`order`](https://tangrams.readthedocs.io/en/main/Syntax-Reference/draw/#order) property is documented to have no effect on styles drawn as an `overlay` (road labels, quest pins), however it is still defined for good measure. But in any case, I can confirm that it has no effect, just like `priority` and `blend_order` seem to have no effect either.

**Comment by westnordost** [comment] 2022-10-25 11:29
But in any case, maybe someone else would like to look at this issue. I propose to do a bisect (i.e. check if older versions had the same issue / in which version it was introduce).

**Comment by hamishmb** [comment] 2022-10-26 19:16
I'll be happy to do a bisect at some point - I was already considering setting up Android Studio for confirming/regression testing bugs soon anyway.

**Comment by westnordost** [comment] 2022-10-26 19:35
No need for that, you could just download the APKs from the releases page from here on GitHub. (It's also faster, because compilation takes so long)

**Comment by hamishmb** [comment] 2022-10-28 16:51
I'll just test them with AVDs then, once I've got those set up.

**Comment by Helium314** [comment] 2022-11-08 16:33
The solution appears to be the same as for the flickering water labels: https://github.com/streetcomplete/streetcomplete-mapstyle/issues/136#issuecomment-1243040877
Including the part where using `0 + feature.scalerank` behaves differently than `feature.scalerank.

**Comment by riQQ** [comment] 2022-12-11 00:36
This can be closed as it was fixed with [release v50.0](https://github.com/streetcomplete/StreetComplete/releases/tag/v50.0), right?

**Comment by westnordost** [comment] 2022-12-11 00:36
ah right, thanks

**Closed by westnordost** 2022-12-11 00:37 UTC
Labels: bug, help wanted
