### ISSUE TITLE
Where is the main entrance?

### ISSUE THREAD

**Issue by Nielkrokodil** [streetcomplete/StreetComplete#3287] opened 2021-09-14 19:53 UTC
### General
Affected tag(s) to be added: a new node on an existing way with [entrance=main](https://wiki.openstreetmap.org/wiki/Tag:entrance%3Dmain)
Question asked: **Where is the main entrance of this church/zoo/museum/...?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one) Well, this could be a problem, if there is no main entrance. Is there a no_main_entrance=yes tag?
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

I dont know if this quest is possible, because it is creating a new node (on an existing way) to tag it as entrance=main. For me as non-expert it looks a little like splitting up ways which is possible. But it is not splitting up so I dont know. 

### Ideas for implementation

**Element selection:** 
Closed ways (mainly buildings, but also outer-lines of bigger areas) of objects which usually attract the public. The objects must not already have an entrance=main node. They could have some other entrance=* nodes. 
Examples: 
building=supermarket/cathedral/church/hospital/civic/...
tourism=zoo/museum/hotel/...
leisure=bowling_alley/amusement_park/...
...

**Metadata needed:** 

**Proposed UI:**
- If there already are entrance=* tags set: Highlight the outline of the area and the entrances to select one. Leave the option "none of the highlighted entrances" to stop highlighting those.
- if the object has no entrance=* tags or "none of the shown entrances" is selected: Highlight just the outline. Let the user tap where it is. 

The idea is that this action adds a new node at this point with entrance=main

**Comment by smichel17** [comment] 2021-09-14 21:49
I think this is a duplicate of #2137

**Closed** 2021-09-14 22:24 UTC
Labels: duplicate
