### ISSUE TITLE
Show surrounding map features to avoid ambiguities

### ISSUE THREAD

**Issue by daniel-j-h** [streetcomplete/StreetComplete#2459] opened 2021-01-06 12:00 UTC
**Use case**

When working on quests, sometimes it is ambiguous if the quest is for a single object in real life or for multiple.

For example see this quest about a bike rack:

![Screenshot](https://user-images.githubusercontent.com/527241/103765811-15357d00-501e-11eb-8f43-eeb2de88cc84.jpg)

in real life it's quite big (10s of meters) and has a gap with a tree in the middle: 

![IMG](https://user-images.githubusercontent.com/527241/103765808-136bb980-501e-11eb-92b5-3b21857a66d1.jpg)

To the user it is not clear if the quest is for the first bike rack, or for all of it. The user has to guess or not map it at all.

The problem boils down to: there is no way of knowing if a second bike rack is tagged in OpenStreetMap from within StreetComplete.

**Proposed Solution**

Would it be possible to highlight the same feature on the map when we work on a quest? Think
- the user clicks the bike rack quest
- the user gets to see the quest description etc.
- the user also gets to see all bike racks in the surrounding and maybe can even check out how they are tagged

This is not specific to bike racks; knowing existing map features would be of graet benefit when working on quests.

**Comment by Helium314** [comment] 2021-01-06 12:41
see #2354

**Comment by westnordost** [comment] 2021-01-06 13:13
Well, in that case I'd leave a note. The bicycle stands should be mapped as an area if they are bigger than just a few stands. If there were mapped as areas, it would have been no problem.

But anyway, a duplicate of #2354

**Closed by westnordost** 2021-01-06 13:13 UTC
