### ISSUE TITLE
New quest idea: viewpoint direction

### ISSUE THREAD

**Issue by markongh** [streetcomplete/StreetComplete#2445] opened 2021-01-02 01:22 UTC
### General
Affected tag(s) to be modified/added: [direction](https://wiki.openstreetmap.org/wiki/Key:direction)
Question asked: **What is the field of view from this viewpoint?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
Useful to hikers, photographers, tourists, etc to determine if a viewpoint will provide them the view they expect without analyzing topographic maps or spending time, money, and/or effort traveling to a location to realize the viewpoint is obstructed in a direction.
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
There are 173,377 'tourism=viewpoint' elements, only 13,823 are tagged with 'direction' leaving about 160,000 to survey.

### Ideas for implementation
**Element selection:** 
This is my recommended Overpass query:
```
[out:json][timeout:25];
(
  // query part for: “tourism=viewpoint and direction!=*”
  node["tourism"="viewpoint"]["direction"!~".*"]({{bbox}});
  way["tourism"="viewpoint"]["direction"!~".*"]({{bbox}});
  relation["tourism"="viewpoint"]["direction"!~".*"]({{bbox}});
);
out body;
>;
out skel qt;
```
Ways and relations may not be necessary as they only make up about 4K of the 173K viewpoint elements. 

**Metadata needed:** 
I'm not exactly sure what metadata you would be looking for since viewpoints are pretty much the same everywhere (you mentioned metadata per country as an example).  However, if you mean metadata like GPS location or other phone data, then one possible implementation would require compass direction from the user's phone (see below for explanation).

**Proposed GUI:**
First the user should be asked, "Does this location provide panoramic views in all directions, 360 degrees (e.g. mountain peak with no/few obstructions)?" 
If yes, then set direction="0-360", task complete.
This question is asked first to prevent the user from spinning around in a complete circle in the next step.

If the answer to the first question is "No", then bring up a compass on the screen and ask the user to essentially record a left-limit to the view, and then a right-limit to the view.  The sense of direction needs to be recorded in a clockwise direction, so going left to right is important and needs to be clear to the user in the instructions.  A simple mock-up of this might look like the following two screens:

![image](https://user-images.githubusercontent.com/76853876/103448487-87af0180-4c9a-11eb-9771-cde3e56330e3.png)

Obviously wording can change and it can be made to look sexier - this was my 5-minute mock-up.  Ideally compass would be dynamic and rotate as the user rotates with the needle pointing in the direction the user is facing, the number in the heading box would change in real time, etc.

I do not think these need to be super accurate, so unless someone's phone is really uncalibrated, it should provide accurate enough data.  It can even probably be rounded to the nearest 5 or 10 degrees to make the data more consistent, or an option could be to use cardinal directions as the 'direction' key will also accept "NNE" for example.  Maybe this is a toggle for the user to decide between degrees or cardinal directions.

Now, what if the user does not have a magnetic sensor/compass feature in their phone? Display a message telling them to upgrade their phone. Just kidding, bad idea. However, there could be a manual data entry option that just asks the user to type in the heading inputs for the viewpoint limits.  This might look something like this:

![image](https://user-images.githubusercontent.com/76853876/103448764-62bc8d80-4c9e-11eb-967e-fec22701ad67.png)

Here the toggle between degrees and cardinal directions might be more useful as a user might not feel as confident with degrees...but I specifically chose that compass image because 'direction' will accept any values displayed.

To check for the case there are more than one contiguous viewable area from the viewpoint, e.g. a vista to the east, and a vista to the west with significant obstructions in the north-south directions, the user could be asked if they need to add an additional view direction and repeat the process until complete. Limited view to the east and west, no view to the north and south would be formatted as "direction=70-110;250-290"

This method of collecting 'direction' values can be applied to other key elements too, such as:
- quest for [benches](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench): "What direction does this bench face (when sitting on bench)?" (only collect one direction). 1,407,588 bench elements exist with only 20,202 having a direction=* meaning about 1,380,000 elements to survey.
- quest for [cave_entrance](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcave_entrance): "What direction does this cave entrance face as seen when looking out from the cave?" (only collect one direction). 44,112 caves
- quest for [hunting_stands](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhunting_stand): "What is the field of view for this hunting stand?" (collect two directions). 154,841 hunting stands

**Comment by Helium314** [comment] 2021-01-02 10:01
Note that some devices may have amagnetic sensor / compass that is simply horribly wrong.
E.g. on my phone, the view cone in SC is always pointing roughly north when holding my phone normally. When tilting it so the camera is pointing higher thanthe horizon, other directions are shown, but never reliably the 'true' direction.

**Comment by markongh** [comment] 2021-01-02 11:03
> 
> 
> Note that some devices may have amagnetic sensor / compass that is simply horribly wrong.
> E.g. on my phone, the view cone in SC is always pointing roughly north when holding my phone normally. When tilting it so the camera is pointing higher thanthe horizon, other directions are shown, but never reliably the 'true' direction.

Yeah, I fully acknowledge this as a possible issue.  When you say "holding your phone normally," though, I am assuming you mean at something like a 45 degree angle to the ground?  I think most phones' compasses work best when the back of the phone is parallel to the ground which is why I included that in the directions.  Maybe the wording "hold the phone flat" could be improved.  But you are still right, even when held "normally" your phone should give at least get you in the right 2- or 3-letter cardinal direction, so compass calibration could be an issue. I think most phones would be at least accurate enough for this purpose, unfortunately I don't have any solid evidence or statistics to back up that hunch.  After all, the difference between N and NNE (the next acceptable entry for cardinal direction in the clockwise direction) is 22.5 degrees, so a 22.5 degree "step" is the sort of accuracy that I'm expecting.
Maybe a quick compass calibration could be an option? I think going into this area takes us too far from the "simplicity" of the data collection though.  Maybe the manual entry option would be default with the "automatic" compass option being available as a toggle for users who know their compass is at least decently accurate.  Like I said, these measurements don't need to be extremely accurate to the degree, and I would even advocate for rounding to the nearest 10 degrees after measurements are taken, but yes, definitely something to consider.

**Comment by Helium314** [comment] 2021-01-02 12:44
I just tested a few apps, and most get my orientation wrong.
However, in OsmAnd it works quite well, indepentent on whether my phone is pointing down or up. My wild guess is that most apps use some basic Android function (if there is any for compass), and OsmAnd does it different... maybe including device orientation.

**Comment by matkoniecz** [comment] 2021-01-02 13:14
See https://github.com/streetcomplete/StreetComplete/issues?q=is%3Aissue+is%3Aopen+viewpoint+direction or more specifically #776

It would be far better to add to #776 what is currently missing there.

**Comment by westnordost** [comment] 2021-01-02 13:34
Right, this is a duplicate of #776.

**Closed by westnordost** 2021-01-02 13:34 UTC
