### ISSUE TITLE
Follow GPS position doesn't always correctly disengage 

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#5824] opened 2024-08-21 13:33 UTC
I noticed that the "follow GPS position" function doesn't always disengage quickly, if the user is panning away. This leads to a "snapping" back to the GPS position, which is unexpected. 

**Screenshot**

https://github.com/user-attachments/assets/1b2d27f0-94f3-409a-9199-382bed6f427c

**How to Reproduce**
- Engage GPS following
- Pan away 
- GPS following does not turn back to black and stays engaged
- on next GPS update the map will snap back to the GPS position

**Expected Behavior**
GPS following should disengage as soon as the user moves the map around. 

**Versions affected**
Android 12
SC 59.0 Alpha 1

**Comment by Helium314** [comment] 2024-08-21 19:41
The problem is [here](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/MapFragment.kt#L159-L163).
MapLibre calls `onMoveBegin` even when there was no move, so the workaround for checking whether there was an actual move is necessary to separate moves from taps. This has the side effect of not registering a move when you tap the map, hold for a while and then move.

**Comment by RubenKelevra** [comment] 2024-08-22 07:18
Okay? 🤔

Is there no way to hook something different to get the actual viewpoint updates? If so you could compare if the new center of the viewpoint is roughly the GPS position.

**Comment by westnordost** [comment] 2024-08-22 15:43
True, but they are really slow in fixing bugs. So it would be good to have a (better working) workaround until then. Has it been reported already?

**Comment by westnordost** [comment] 2024-08-29 11:02
@Helium314 do you have another idea how to workaround this issue? If not, we should just create an issue at MapLibre and close this one. (And if yes, we should implement that workaround and still create an issue at MapLibre.)

**Comment by RubenKelevra** [comment] 2024-08-30 06:59
> If not, we should just create an issue at MapLibre and close this one.

I recommend keeping persistent issues open, even if not actionable. It makes sure that nobody else invests time to create a bug-report which then just gets closed as duplicate.

See https://github.com/streetcomplete/StreetComplete/issues/5572, https://github.com/streetcomplete/StreetComplete/issues/5699, https://github.com/streetcomplete/StreetComplete/issues/5651, https://github.com/streetcomplete/StreetComplete/issues/5584

**Comment by matkoniecz** [comment] 2024-08-30 11:07
well, people should anyway look also at matching closed ones before reporting

**Comment by RubenKelevra** [comment] 2024-08-30 11:10
Why? Github discourages this by only searching for open issues and if a bug is closed its either "completed" or

**Comment by westnordost** [comment] 2024-08-31 18:03
Reported upstream but also found a workaround that might work.

**Closed** 2024-08-31 18:03 UTC
Labels: bug, blocked

**Comment by RubenKelevra** [comment] 2024-09-02 10:10
Will test it as soon as I can start the app again, thanks!

**Comment by mnalis** [comment] 2024-09-06 12:15
> Will test it as soon as I can start the app again, thanks!

the workaround should be included in `v59.0-alpha4` @RubenKelevra so feel free to test it when you have an intermezzo between breaking them :smiling_face_with_tear:

**Comment by RubenKelevra** [comment] 2024-09-06 14:42
@mnalis can confirm, workaround works like a charm in 59 alpha 4 :)
