### ISSUE TITLE
App keeps crashing since v32

### ISSUE THREAD

**Issue by TO-92** [streetcomplete/StreetComplete#3069] opened 2021-07-15 19:22 UTC
After updating from v31 to v32, Street Complete does not start anymore. I sent a crash report through Android's feedback option, not sure if you received it though.

**How to Reproduce**
Nothing. Just (try to) start the app. Crash before the UI appears.

**Versions affected**
v32, v33 on a Sony Xperia V (alias LT25i) running Android 4.3.

![Screenshot_2021-07-15-18-35-01](https://user-images.githubusercontent.com/36824498/125845237-777be6c2-5421-4786-92fe-29934c1a55f8.png)

**Comment by westnordost** [comment] 2021-07-15 19:47
Hm actually, yes I did, but not from you but someone using Samsung galaxy Ace.

The app itself does not use Room, this is a dependency of the androidx.work dependency.

So, this cannot be fixed by me. I suggest you reinstall the app, I am pretty sure this should solve your issue. If not, please leave another comment here.

**Comment by TO-92** [comment] 2021-07-15 20:26
Uninstalled and installed again. No change. Anything else I could try, like downloading the dependencies manually?

**Comment by westnordost** [comment] 2021-07-15 20:49
No, the dependencies are automatically bundled.

Generally I would suggest you get a newer device, support for Android 4.x will be dropped soon. However, till it is dropped, it should still work, so let's look into that.

**Comment by TO-92** [comment] 2021-07-15 21:04
Thanks. It's not my own phone, it's my employer's. While I am allowed to use it privately, I don't think they will buy me a new one just for StreetComplete. ;)

**Comment by westnordost** [comment] 2021-07-15 21:08
Is your employer aware of the security implications of having such an outdated phone with almost as old security updates as Windows XP have access to company data?

**Comment by westnordost** [comment] 2021-07-15 21:14
Okay, I installed an emulator for Android 4.3. I can reproduce that it immediately crashes on startup. Albeit with a yet different exception.

**Comment by TO-92** [comment] 2021-07-15 21:26
Ah, good. Perhaps fixing that exception will magically also fix the other.

Btw., I am not accessing anything, not even my company e-mail. It's just so they can reach me in case of emergency. Actually it was kind of generous that they gave me a smartphone even though my old Nokia 6230 would still serve the purpose. 😄

**Closed** 2021-07-15 22:17 UTC
Labels: bug

**Comment by westnordost** [comment] 2021-07-15 22:23
Ok, turned out that a dependency that is necessary for the app to run below Android 5 was not correctly included since v32. I added it. That's the good news.

**The bad news are:**
- your crash issue is yet a different one that I found, no idea how you could have gotten past the first one that I fixed now 🤷. So maybe your issue is not solved after all
- on both my Android 4.3 and Android 4.4 emulator, the app looked really messed up. Not sure if this is just a problem with the emulator or not
- on the Android 4.4 emulator, the download took ages. TBH it never completed, I just closed the app at one point
- on the Android 4.3 emulator, the download failed because the old device didn't accept the security certificate of openstreetmap.org (by Let's encrypt)

So, fact is that since v32, the app should have crashed immediately on startup for Android 4.2, 4.3 and 4.4. According to the stats on Google Play, no users have 4.2 or 4.3 installed and about 30 users have still Android 4.4 installed. Not sure why noone has filed an issue yet, maybe they just have it installed but do not use the app or even their smartphone.

In any case, I am unsure if I will even release a v33.2 that includes this fix. I think it is finally the time to drop support for Android 4.x. This will not only make it easier to maintain the app in the future, it will have some positive impact for the 99.845% that do have a more current version of Android: The app download size will probably be half or less.

So, I think for v34.0, support will finally be dropped. @TO-92 I recommend you to downgrade the app (deinstall, reinstall) to v31.x if you want to continue to use this app on an Android 4.3. Versions starting with v32+ are more demanding in regards to the smartphone's hardware.

**Comment by TO-92** [comment] 2021-07-15 23:11
Oh well. Thanks for trying anyway. Where do I find the APK for v31? Google Play only has the latest version, right?

However, that will probably bring back another issue: I have not been able to download any quests for quite a while, probably because of the same certificate problem that you mentioned above. I was hoping that an update would help, but got the crash instead. Is there a way around that, once I am back to v31?

**Comment by westnordost** [comment] 2021-07-16 00:16
You can take this: https://github.com/streetcomplete/StreetComplete/releases/download/v31.3/StreetComplete-v31.3.apk

Or you can download F-Droid (like google play but only for open source software) and get it from there - you can choose on F-Droid which version exactly you want to install.

> I have not been able to download any quests for quite a while, probably because of the same certificate problem that you mentioned above.

Uff, okay. Well, I think there is a way around that. You need to google for it: "Let's Encrypt certificate Android 4.3" or something. Maybe there is a place in the settings where you can manually add root certificates your smartphone should trust.
