### ISSUE TITLE
StreetComplete asks for collection times of a postbox first and only then whether it still exists

### ISSUE THREAD

**Issue by AndrewHain** [streetcomplete/StreetComplete#3114] opened 2021-08-03 07:26 UTC
The quest for collection times of postboxes precedes the quest to check their continued existence.

**How to Reproduce**

Find a postbox qualifying for both quests, the collection times are asked for first, resulting in https://www.openstreetmap.org/node/30430126/history

**Versions affected**

StreetComplete 31.3, Android 11.

**Comment by matkoniecz** [comment] 2021-08-03 07:28
Hmmm, if postbox gets edited by SC it is not invalidating last-edited date?

**Comment by westnordost** [comment] 2021-08-03 12:31
I don't understand the description of this issue. Could you elaborate, maybe add a numbered list of steps to reproduce?

**Comment by matkoniecz** [comment] 2021-08-03 12:39
From https://www.openstreetmap.org/node/30430126/history#map=19/51.45804/-0.26624

1) Have " Add postbox collection times" with priority higher than "Check if element still exists" 

2) scan for data including old unmodified postboxes without tagged collection times

3) Answer " Add postbox collection times", modifying it

4) Get "Check if element still exists" quest for just modified element - quest that should be asked for old unmodified objects

**Comment by westnordost** [comment] 2021-08-03 13:02
Ah I understand. Well, if `check_date` is set, it overrides any "last modified" date of the element as a whole. So as much as the check existence quest is concerned, the last time the existence was checked was whatever the check date is set to.

I understand that it may be confusing to users, but in the end, I think it is just a minor inconvenience.

**Comment by 10992-osm** [comment] 2021-08-03 16:38
But in that example, the existence was checked in v5, while the collection times were added in v4 of the node (about 4 seconds between), and `check_date` was only added with v5.  Could the existence quest be put higher up in the priority by default?  (I've moved it to the top of mine, partly for this reason*).  Might it be to do with not re-loading the data, given this report is for SC31.3, which was before offline editing was introduced in SC32.0?

*also partly because sometimes I'd rather solve quicker quests (yes/no), so I've arranged it so they're mostly higher up than longer-answer quests.

**Comment by westnordost** [comment] 2021-08-03 16:48
Maybe. In any case, existence will be higher up starting with the next major  than collection times (if it wasn't already)

On 3 August 2021 18:38:16 CEST, 10992-osm ***@***.***> wrote:
>But in that example, the existence was checked in v5, while the
>collection times were added in v4 of the node (about 4 seconds
>between), and `check_date` was only added with v5.  Could the existence
>quest be put higher up in the priority by default?  (I've moved it to
>the top of mine, partly for this reason*).  Might it be to do with not
>re-loading the data, given this report is for SC31.3, which was before
>offline editing was introduced in SC32.0?
>
>*also partly because sometimes I'd rather solve quicker quests
>(yes/no), so I've arranged it so they're mostly higher up than
>longer-answer quests.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/StreetComplete/issues/3114#issuecomment-891995145

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment] 2021-08-03 21:02
So I'll close this.

**Closed by westnordost** 2021-08-03 21:02 UTC
Labels: bug

**Comment by peternewman** [comment] 2021-08-04 02:29
> Maybe. In any case, existence will be higher up starting with the next major than collection times (if it wasn't already)

It's actually still not in the tweaked list:
https://github.com/streetcomplete/StreetComplete/blob/c1336a4ca5dbd6368d75c2c3332caeac172416ad/app/src/main/java/de/westnordost/streetcomplete/quests/QuestModule.kt#L229-L232

However it also can't be, as otherwise you get back to the issue I previously reported in #2368 (which is what got it put above).

The only relatively simple fix I can think of (which the current query structure might not handle), would be if check existence checked any key based check dates too, so it would hide the existence if check_date:collection_times was recent enough, on the assumption if someone had checked that it still exists.

**Comment by strct** [comment] 2021-08-09 07:12
The same happens for Backrest- & CheckExistence Bench-Quest

**Comment by peternewman** [comment] 2021-08-09 09:53
> The same happens for Backrest- & CheckExistence Bench-Quest

Although as backrest isn't a resurvey AFAIK, you can order them as you prefer with no issues. Because the postbox collection times are a resurvey, if you put them after existence you'd only ever check the postbox existed each time.
