### ISSUE TITLE
Surface of sidewalk: "Side walk is different" is missing

### ISSUE THREAD

**Issue by RubenKelevra** [streetcomplete/StreetComplete#4296] opened 2022-08-18 07:34 UTC
I had a the case where the sidewalk wss mapped wrongly: There's no sidewalk. 

But on the surface of the sidewalk quest, there's no option to remove the info and answer it correctly, like on many other quests. 

**How to Reproduce**
- Be asked for a surface of a sidewalk which does not exist. 
- Have no option to say: The info is wrong. 

![Screenshot_2022-08-18-08-33-06-743_de.westnordost.streetcomplete.jpg~2.png](https://user-images.githubusercontent.com/614929/185336724-c5978ea5-5ed2-4b6f-bcbf-cf478a9022d6.png)

**Expected Behavior**
- Have a button to delete the info about the sidewalk. 

**Versions affected**
V45.2

**Comment by FloEdelmann** [comment] 2022-08-18 08:44
You can always leave a note, so this would be an enhancement rather than a bug fix.

**Comment by legofahrrad** [comment] 2022-08-18 10:27
Use the sidewalk overlay.

**Comment by legofahrrad** [comment] 2022-08-18 10:30
btw, this is a duplicate of #3920

**Closed** 2022-08-18 10:38 UTC
Labels: enhancement

**Comment by peternewman** [comment] 2022-08-18 21:22
Would it be worth an other answer for this (and cycling etc) which tells you to use the relevant overlay or even somehow triggers it?
