### ISSUE TITLE
New map renderer feedback: Harder to rotate map

### ISSUE THREAD

**Issue by laundmo** [streetcomplete/StreetComplete#5901] opened 2024-09-15 18:59 UTC
In the beta with the new map renderer, its harder to rotate the map than before

when using 2 fingers, it tends to lock into zooming mode too quickly, with very precise parallel lines being required for rotation.

if possible, a much more accomodating threshold for how exact the movement should be would probably make sense.

Or just allowing rotating even after starting a zoom.

**Comment by HolgerJeromin** [comment] 2024-09-16 00:17
Ref #5844

**Comment by westnordost** [comment] 2024-09-16 10:54
Thank you for your feedback. I see you already added it to the linked issue this issue is a duplicate of. Note that we also have a discussion forum for general feedback.

**Closed by westnordost** 2024-09-16 10:54 UTC
