### ISSUE TITLE
Confusing message about one way streets when asking for cycling options

### ISSUE THREAD

**Issue by hmartink** [streetcomplete/StreetComplete#4227] opened 2022-07-20 14:32 UTC
I recently travelled to BE/NL and was questioned about what kind of cycling paths are on the street. Most of the time this worked as expected, though the color code of the pictures might be misleading.

However, a few times when I entered "no dedicated cycling paths on the street" I got a warning about one way streets and permissions for cyclists. Sorry, as I was on the bike in the field I did not have anything to to write the exact message down. However, the text did not make sense to me, as I was not handling one way streets or cycling permissions but just entered what was physically on the ground.

And at least in one case the official cycling path (the node system in the Netherlands for cyclists) was using the street in both directions, so the answer made even less sense - if official bike path (and lots of users) are going there, I don't think it is not allowed.

At least in one case (but I think there were several) I noticed that the question was only for a very short path near the crossing, where the marking was absent.

In one case I noticed that this was a "false" one-way street, i.e. permission for cars was denied at one end, but no "one way" street was present on the other end.

**How to Reproduce**
As it occurred multiple times in both NL and BE (I did not see this in DE so far), this is not isolated. But it was so seldom that I could not make a pattern. Probably go to a "false one way street" and the end where only cycelists are allowed and enter "no cyclist paths" when asked for the cyclist path options.

**Expected Behavior**
Simply accepting the answer from the user. If there is no cycling path, then there is none. Or, if there is some dependency, ask this first (like "is this one way street open for cyclists") and only then show this quest (like for buildings and house numbers). 

**Versions affected**
Android: 10
SC: v45.0

**Comment by riQQ** [comment] 2022-07-20 19:47
Likely related to #3984

**Comment by westnordost** [comment] 2022-07-21 08:39
It is certainly no bug that this warning is displayed. Only because it does not seem to make sense to you in that situation does not mean it makes no sense.

Unfortunately, whether or not a street is a one-way also for cyclists is glued together in a(n older) tagging scheme for cycleway infrastructure (`cycleway=opposite`). This makes these two properties inseparable for handling it in the UI.

If you want to refute me closing this issue, then please take screenshots or a video showing the behavior you think is a bug and report for which elements exactly this is reproducible.

**Closed by westnordost** 2022-07-21 08:39 UTC

**Comment by hmartink** [comment] 2022-07-24 06:55
I apologize if my claim "does not make sense" was a bit broad. When I read it it did not make sense to me, but of course I do not want it to be generalized.

If I remember correctly, it was something like "Are you sure there are no cyclist paths here? This one way street ...". So I could 
- Say yes (which I did, because there are no cyclist paths here)
- Say no (then the answer is wrong)
- Leave it open (unsatisfying, refuting the purpose of SC)

From your message I understand that I should have been asked if the street was open for cycling the opposite way. This is not how I read it (sorry) and this not what I could answer (because if there are no cyclist paths and I don't see a sign for an (opened) one way street - I could not tell). But I will carefully read the question next time again (whenever I'm in NL/BE). 

Maybe the rationale of this question could be hinted in the dialog, e.g. by providing a link, like you do in other places. Then I could have at least opened the wiki page for later reading. 

And finally please bear with me. I'm not an (Android) developer. I mainly use the phone for street complete (besides doing calls/SMS, of course). I have really no idea how to make screenshots, videos and (from another bug) tell you "which keyboard" I use (my phone has a touch screen, but this is obviously not what you asked for). I'm reporting issues as best as I can and do not report "one time glitches" and try to be constructive whenever I can (see e.g. my suggestions in the hydrant issue).

**Comment by mnalis** [comment] 2022-07-30 15:28
@hmartink  Probably this text (in default English)?

https://github.com/streetcomplete/StreetComplete/blob/31f2a8a972a74e9743f3d10b113334020bd9ab55/app/src/main/res/values/strings.xml#L892

If _**"Are you sure that cyclists are not allowed to use this one-way street in both directions? If you’re unsure, look for a sign at the end of the street."**_ text is unclear, could you expand on what confuses you there? It is intended to resolve conflicting situations in tags where it is highly likely that current or previous user has done something wrong - which is why its workflow is so different from 99% of the other quests, so it is intentional. 

<details>

<summary> example </summary>

It is like if you selected all documents on your computer and pressed `Delete` - computer might ask you if you are **_really sure_** you want to do that, as it is **_very likely_** something you did not want to do. Your proposal of _"Just irrevocably delete all documents without asking as user asked you"_ is not a very good solution. Neither is refusing to delete good solution -- there is some small chance that the user really wants to delete them all.

</details>


However, if wording could be clearer about what is expected of you, please suggest what text you would find clearer, or more details on what part of it you don't understand (e.g. if that text could mean one thing or another thing and you're not sure which one is meant).

Apart from three choices you mention, there is also `Leave note` option under `Other Answers` / `Can't say` which allows you to **leave a note** (with pictures - press the camera button there) if you are unsure what the correct answer is. Then other users can look into it and answer how it should be mapped and/or map it correctly. I've now added that to the [FAQ](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#I_am_unsure_how_to_answer_some_quest,_what_to_do?).


<details>

<summary>for the help with leaving better bug reports, click here to expand</summary>

First, don't stress too much if bug reporting is too complex to you. Just leave the Notes with pictures as explained above. Rest assured your willingness to help improve the program is appreciated! But if you want to learn to leave better bug reports so developers can more easily understand what is confusing you and perhaps improve the program, here are few tips:

- after you leave notes, when you come home later, you can find all notes you opened at your OSM profile screen (i.e. when  you login on www.openstreetmap.org, and click on your username at top-right, choose `My Profile` and then select `My Notes`. Then find your note and share here `id` of that note you created - then we would know exactly where it happened (and all pictures/text you attached).

- As for the screenshot/video, it is usually found by dragging from the top screen downwards (sometimes twice) to open Android "drawer", and there might be an icon which says `Screenshot` or `Screen recorder` or similar. But leaving note with picture is most important 

- Note that developers use a somewhat different terminology - `bug` means program is doing something that **_programmer did not intend it_** to do. If program is doing exactly what programmer told it to do, but it is confusing to the user or the user did not expect the program would ask them this question, that is called `request for better UX (user experience)`  and would likely fall under `feature requests` instead of `bug report`.

</details>

**Comment by hmartink** [comment] 2022-07-31 15:56
Hello mnalis,
thanks for your very helpful reply.

Yes, this was the message (in German, but this does not matter).

I was standing literally out in the fields. I could see the road quite well, but did not intend to go to the other end. The question sometimes only related to a few meters of the road. The initial question/quest was, if there are any markings for bikes on the ground. I could clearly answer this question ("no"). Then this text came about. It did not reference the question at all, talked about a seemingly different topic ("one-way street") and gave no clear message what to do. If I would go to the other end of the street, then what? I might find a sign or I might find none. And then? 

Therefor I suggest some text along the following lines:
Warning: Due to technical limitations marking of bicycle paths are linked to one-way streets and your answer contradicts the previous data. Leave a note instead of a reply if you don't understand this. More information here.

And then prominently show "Leave note" and only "small" Yes, I know what I'm doing" (or similar). And put some text from Westnordost and you (possibly expanded) behind the link.

I leave lots of notes, but I did not take the option to leave a note here seriously, because I could not make sense of the message (and its relation to the question), because for me bike paths are an orthogonal concept to one-way streets. (I know may one-way streets without them). Thus I considered this a "bug" and did not want to bother other mappers with this "bug". (In the past, some replies to notes indicated potential issues with Street Complete data). 

In my proposal, this is confusion avoided, as the text links to the question (bicycle paths) and hints that this is an unusual situation. In essence, what I learned from you and westnordost. 

Regarding your hints about bug reporting:
They are very helpful. It's nice to have such a list of open Notes so easily available and knowing how to capture the screen. I really did not know this before, my main UI is StreetComplete so far as this is my main "active use app" on the phone.

Regarding bug: For me it is hard to distinguish if it is a bug or a "request for better UX". So kindly reassign if I chose the wrong path. In this case I could hardly imagine this to be a "bug". 

Can you reassign this as "request for better UX"?
