### ISSUE TITLE
Street with quest is not rendered in the map

### ISSUE THREAD

**Issue by mcliquid** [streetcomplete/StreetComplete#4383] opened 2022-09-15 16:53 UTC
Two days ago I noticed a road that was displayed in the app with a quest, but was not visible as a road in the map style.
The road has been around for eight years, so it's not like it usually is with brand new things that haven't been rendered yet.
I also just (two days later) placed the app on this location again and the road is still not there.
Unfortunately, I lack other examples, but I mean something like this has happened before.

**How to Reproduce**
Way: https://www.openstreetmap.org/way/315955492

**Screenshots**
https://user-images.githubusercontent.com/3351668/190461743-17ebdc45-d0e6-499d-b7b9-e2eb20b9b239.png
https://user-images.githubusercontent.com/3351668/190461749-92e62046-5984-466c-9e75-a716f3fa4e02.png

**Versions affected**
v47.0-alpha1

**Comment by Helium314** [comment] 2022-09-15 16:59
Map tiles are provided by jawg, so you may ask there. Though I can't reproduce it, the road just shows up for me.
Did you only scroll back there, or did you actually re-download the data?

**Comment by westnordost** [comment] 2022-09-15 17:10
It's a trunk_link. This was a bug in v46.0 and fixed for v46.1. It will be fixed for v47.0-beta1 too.

https://github.com/streetcomplete/streetcomplete-mapstyle/issues/134

**Closed by westnordost** 2022-09-15 17:10 UTC
Labels: bug
