### ISSUE TITLE
Time Selection - Use keyboard input

### ISSUE THREAD

**Issue by Saturo78** [streetcomplete/StreetComplete#3796] opened 2022-02-22 18:15 UTC
Kann man bitte eine direkte Eingabe der Öffnungszeiten ermöglichen?
Mit dem aktuellen Picker brauche ich immer mindestens 2 Versuche um die richtige Uhrzeit zu treffen.

Warum nicht einfach zwei Eingabefelder
Von - Bis in die ich direkt die Zeit eingeben kann. Das wäre viel einfacher.

**Comment by westnordost** [comment] 2022-02-22 21:02
Der Picker ist die Standardkomponente in Android um eine Uhrzeit auszuwählen. Ich stimme zu dass ein Eingabefeld mit Tastatur besser wäre, dies ist allerdings etwas Aufwand da das Feld natürlich nur valide Eingaben erlauben darf. Dazu war ich bisher noch nie gekommen.

Sollte jemand Interesse haben, daran zu arbeiten, kann ich kurz erklären wie ich mir das Interface vorstelle.

---

The picker is the default component in Android to select a time. I agree that an input field with keyboard would be better, but this is a bit of a hassle since the field must of course only allow valid input. I never got around to this before.

If anyone is interested in working on this, I can briefly explain how I envision the interface.

**Comment by kmpoppe** [comment] 2022-02-23 10:43
Would using an alternative TimePicker, that's already wrapped in a neat class, be helpful?

https://material.io/components/time-pickers/android#using-time-pickers
https://developer.android.com/reference/com/google/android/material/timepicker/MaterialTimePicker

**Comment by kmpoppe** [comment] 2022-02-23 10:47
... which would also be easier ist #3650 was done, if i had seen that earlier 🤦 ...

**Comment by FloEdelmann** [comment] 2022-02-23 10:48
But please none that displays a 24-hour clock on a single circle :see_no_evil: :sweat_smile: 
![image](https://user-images.githubusercontent.com/202916/155304611-e6bd221e-80eb-4124-a781-20ce2a8af4a5.png)

**Comment by westnordost** [comment] 2022-02-23 11:35
The `MaterialTimePicker` is a dialog, not a (compound) view. What we need is a custom view because we want to enter a range:

`[   :   ] - [    :    ]`

Ok, now before there's more forth and back, here is a list of requirements for this view:

- `TimeRangeInput` should be a compound view of two `TimeInput` because the latter would be needed for the postbox collection times.
- `TimeInput` should disallow any non-number input. Implementation-wise, it would possibly be best if it were two `EditText` where the focus automatically changes to the next one when the input is complete. It should be possible to enter
  - "1235" to have "12:35" displayed
  - "12" to have "12:00" displayed. (Maybe 00 in grey that becomes black when leaving the input field)
  - "8" to have "08:00" displayed. This shortcut may not work for "1" and "2" for 24-hrs-clock and "1" for 12-hrs-clock of course
- It should be possible in `TimeRangeInput` to jump into the "to" field when pressing "-" but only if the input in the "from" field is considered complete. The "next" button in the keyboard should have the same function. So, e.g. just typing "8-12" should be possible. Additionally, just completely completing the input (e.g. "835" -> "8:35") should also jump to the "to" field.
- `TimeInput` must have a function on its interface to set 12-hour-clock or 24-hour-clock.

**Comment by KatrinaAS** [comment] 2022-04-03 11:49
It looks like at least on later versions of android, the TimePicker allows for the input through keyboard anyway. 

![image](https://user-images.githubusercontent.com/690546/161426492-d8c5a8fc-05c9-457b-9295-caadb1da070b.png)
Bottom left keyboard icon links to 
![image](https://user-images.githubusercontent.com/690546/161426504-216045ad-eff4-415c-b3dc-fa77c7174f22.png)

**Comment by westnordost** [comment] 2022-04-03 13:10
It didn't work for me though - maybe a Samsung issue. Anyway, that's still a lot of clutter - opening time, closing time, next/previous buttons, "Type in time" label, huge "set time" title etc.

**Comment by dotcs** [comment] 2022-06-11 21:21
I don't think it's a Samsung issue per se. I can confirm that I see the same dialog and option to enter time though the ketboard as described by @KatrinaAS. I'm using a Samsung Galaxy A31 that runs Android 11.

**Comment by westnordost** [comment] 2023-05-01 23:13
I recently fiddled around with this a bit, but it didn't feel good. Just the appearance of the keyboard (and its disappearance when finished inputting) is quite disruptive. Typing 08002000 (08:00-20:00) is not really faster than tapping on 8, next, 20. So, this is no longer planned as enhancement. Anyone is of course invited to experiment with this himself.

**Closed by westnordost** 2023-05-01 23:13 UTC
Labels: enhancement
