### ISSUE TITLE
Save images taken for notes in full resolution locally

### ISSUE THREAD

**Issue by joshinils** [streetcomplete/StreetComplete#5700] opened 2024-06-23 03:36 UTC
**Use case**

The images hosted on westnordost.de are much lower resolution than what my phone can take images at.
At home I sometimes wish to have the full resolution image available to discern more details.

**Proposed Solution**

Save the image taken to the camera roll, as if I'd taken it with the camera app, location metadata included, if available.

**Comment by mnalis** [comment] 2024-06-23 18:57
Related to https://github.com/streetcomplete/StreetComplete/issues/1788

See the workaround at the [bottom of that issue](https://github.com/streetcomplete/StreetComplete/issues/1788#issuecomment-1776837797) which explains how to retain full-quality pictures locally on the device.

Also, somewhat related [SC FAQ: Are the pictures taken with StreetComplete permanent?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Are_the_pictures_taken_with_StreetComplete_permanent?) mentions those quality issues.

**Comment by westnordost** [comment] 2024-06-24 08:34
Yes, they are scaled down to WXGA, for space reasons. I am hosting them on my webspace. If they were hosted on openstreetmap proper (see https://github.com/openstreetmap/openstreetmap-website/issues/395 - someone would need to implement this) , this limitation (along with others) could be dropped. 

See @mnalis, duplicate of #1788.

**Closed** 2024-06-24 08:34 UTC
