### ISSUE TITLE
No Bike lane shows DO NOT ENTER icon instead

### ISSUE THREAD

**Issue by mxxcon** [streetcomplete/StreetComplete#4591] opened 2022-11-01 18:45 UTC
I picked no bike lane on a way. Then on another way I picked preset in the lower left corner and instead it showed me the icon of "do not enter" sign. Ultimately the tags that got applied to that way were correct, so this appears to be just a visual bug local to the client.

![Screenshot_20221030-214519_StreetComplete](https://user-images.githubusercontent.com/847140/199312546-62e175ef-0036-4b60-a1fb-af0b09b3f2e1.png)
![Screenshot_20221030-214524_StreetComplete](https://user-images.githubusercontent.com/847140/199312543-8db8ce17-6f9e-487c-8ede-010151798950.png)

**How to Reproduce**
Apply "no bike lane" on a way, use the same preset on another way.

**Expected Behavior**
Correct icon shows

**Versions affected**
v49-beta1

**Comment by Helium314** [comment] 2022-11-01 19:32
Is this a one way street?

**Comment by mxxcon** [comment] 2022-11-01 19:33
> Is this a one way street?

Yes

**Comment by Helium314** [comment] 2022-11-01 19:37
In that case it's intended, so it's clear that there is no exception for bicycles.
There were some cases where the bicycle exception got deleted by users overlooking this, see #3795.

**Comment by mxxcon** [comment] 2022-11-01 20:29
That doesn't make sense. It supposed to show "none", similar to this. This is the same street a couple of blocks down. 
![Screenshot_20221101-162741_StreetComplete](https://user-images.githubusercontent.com/847140/199334517-549c2927-6572-4abb-8d01-8d7669c583e1.png)
![Screenshot_20221101-162746_StreetComplete](https://user-images.githubusercontent.com/847140/199334521-46794608-d97b-46b8-ad9e-99c2f0c988ed.png)

**Comment by westnordost** [comment] 2022-11-01 21:24
It looks like the logic that decides whether a "none" or a "none, no cycling in this direction" is displayed is botched. The latter should of course only be displayed for the side that would be in the direction that would be against the normal traffic flow. In this case, to the right / the left side

**Comment by westnordost** [comment] 2022-11-01 21:25
@Helium314 in case you are investigating this, please assign it to you for the duration that you are.

**Comment by westnordost** [comment] 2022-11-02 22:10
Uhm, weird. I cannot reproduce that.

![image](https://user-images.githubusercontent.com/4661658/199612127-1d98c866-84af-43e7-9c62-db9a962db39a.png)

**Comment by westnordost** [comment] 2022-11-02 22:12
Oh... it's reproducable if I tap on the "select last answer" button.

So it is a regression from #4524 (@Helium314 )

**Comment by westnordost** [comment] 2022-11-02 22:23
Hmm, the root of the issue might be deeper, #4524 only surfaced it...

**Closed** 2022-11-03 21:36 UTC
Labels: bug
