### ISSUE TITLE
ability to see the already available poi

### ISSUE THREAD

**Issue by BuZZ-dEE** [streetcomplete/StreetComplete#4255] opened 2022-07-30 20:30 UTC
ability to see the already available points of interest, so I can know if it makes sense post a poi hint.

**Comment by riQQ** [comment] 2022-07-30 21:03
Related to #4253

**Comment by westnordost** [comment] 2022-08-03 18:59
Closing as duplicate of #4253

**Closed by westnordost** 2022-08-03 18:59 UTC

**Comment by BuZZ-dEE** [comment] 2022-08-03 19:19
Duplicate of #4253

**Comment by BuZZ-dEE** [comment] 2022-08-03 19:21
@westnordost duplicate, but not planned or what does closed as not planned mean?

**Comment by matkoniecz** [comment] 2022-08-03 19:25
Github shows "Won't fix, can't repro, duplicate, stale" in mouseover of "not planned".

And either way: it was closed as duplicate of open issue that stayed open.

**Comment by BuZZ-dEE** [comment] 2022-08-03 19:30
@matkoniecz why I don't see: "[westnordost](https://github.com/westnordost) marked this as a duplicate of [#4253](https://github.com/streetcomplete/StreetComplete/issues/4253)" like in the other issue?

**Comment by riQQ** [comment] 2022-08-03 19:35
@BuZZ-dEE it only works if the exact phrase "Duplicate of #x" is used. This wasn't the case here.

**Comment by BuZZ-dEE** [comment] 2022-08-03 19:46
@riQQ thx for clarification. It is a little bit confusing, if there is no straight line how to deal with duplicates.
