### ISSUE TITLE
Maxspeed quest tagging in Italy

### ISSUE THREAD

**Issue by Mannivu** [streetcomplete/StreetComplete#2995] opened 2021-06-23 18:10 UTC
On the Italian OSM Telegram channel a user has noted how StreetComplete uses a wrong tagging scheme after a maxspeed quest gets an answer. At the moment, the app adds the tag "maxspeed:type=IT:urban" while, according to the [maxspeed:type wiki page](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type),  _maxspeed:type=* is only in used in certain regions of the world namely the United Kingdom._ and outside the UK the correct tag should be `source:maxspeed=*`. So I'm asking to fix the quest so that the app adds the correct tag `source:maxspeed=IT:urban`.

**Comment by matkoniecz** [comment] 2021-06-23 18:13
Note that wiki is not perfect and ideal, sometimes OSM Wiki should be changed.

**Comment by Mannivu** [comment] 2021-06-23 18:21
> Note that wiki is not perfect and ideal, sometimes OSM Wiki should be changed.

You're right. But as you can see in taginfo, [`maxspeed:type=IT:urban`](https://taginfo.geofabrik.de/europe/italy/tags/maxspeed:type=IT:urban) has 6k uses in Italy, while [`source:maxspeed=IT:urban`](https://taginfo.geofabrik.de/europe/italy/tags/source:maxspeed=IT:urban) has 67k uses

**Comment by westnordost** [comment] 2021-06-23 18:46
This is a duplicate of many similar issues that came before

**Comment by westnordost** [comment] 2021-06-23 18:51
But anyway, in a nutshell:
1. OSM is a global project, it makes no sense to have different tagging schemes for different countries for the same thing (default maxspeeds)
2. neither `source:maxspeed`, `maxspeed:type` and the others are deprecated and neither is approved
3. I am not going to implement using country-specifically different tags only because one tag is more popular than another in different countries as long as none of them is deprecated
4. all those are synonyms, any data consumer that processes the data has to check any of the keys anyway. For data consumers, there is virtually no difference, they have to wade through the maxspeed-tagging mess in any case, no matter what Streetcomplete tags
5. of all the alternatives, `maxspeed:type` is slightly better than `source:maxspeed`, so I chose to use that one for this app

**Closed by westnordost** 2021-06-23 18:51 UTC

**Comment by dieterdreist** [comment] 2021-06-23 19:26
source:maxspeed is much more often used than maxspeed:type, despite your app pushing the fragmentation it is still 1785k vs.  458k 
There’s literally no benefit from pushing a synonymous tag with significantly fewer usage

**Comment by westnordost** [comment] 2021-06-23 19:32
If you think maxspeed:type should not be used, maybe create a proposal then to deprecate it. This is not the right place.

**Comment by Mannivu** [comment] 2021-06-24 11:57
`source:maxspeed=IT:urban` has been in use since [late 2009](https://taginfo.openstreetmap.org/tags/source:maxspeed=IT:urban#chronology), while `maxspeed:type=IT:urban` started being used in [late 2017](https://taginfo.openstreetmap.org/tags/maxspeed:type=IT:urban#chronology). the maxspeed:type tag was added in SC on [v2.2 (14 oct 2017)](https://github.com/streetcomplete/StreetComplete/releases/tag/v2.2), so it's pretty clear that the use of maxspeed:type tag in Italy was forced because of your app.

**Comment by dieterdreist** [comment] 2021-06-24 14:32
I think he is aware of this, it’s a deliberate decision of street complete because he thinks the maxspeed:type tag means the same but is “better”.

**Comment by westnordost** [comment] 2021-06-24 15:25
https://taginfo.openstreetmap.org/tags/source%3Amaxspeed=survey%3Bimage

**Comment by mnalis** [comment] 2021-06-24 15:49
@Mannivu `maxspeed:type` seems to have been in use since [early 2011](https://taghistory.raifer.tech/#***/maxspeed:type/) and documented since [early 2013](https://wiki.openstreetmap.org/w/index.php?title=Key:maxspeed:type&action=history), so it does not seem to me to be some soft of "StreetComplete conspiracy from 2017". Or, if you look from different viewpoint, one could claim that `source:maxspeed` is because some other application/factor is **"forcing"** that tag about September / October 2016 (for [IT:urban](https://taghistory.raifer.tech/#***/maxspeed:type/&***/source:maxspeed/&***/source:maxspeed/IT:urban&***/maxspeed:type/IT:urban&***/maxspeed:type/IT:urban)).

As noted earlier in the thread, there is more to consider when choosing which tag to use then _"which one is the most popular"_ (although that is _certainly_ one of important factors -- just **not the only one**).

**Comment by dieterdreist** [comment] 2021-06-24 16:20
source tags on osm objects for map edit sources are generally discouraged in favor of changeset tags

**Comment by Mannivu** [comment] 2021-06-24 16:24
@mnalis I'm not saying there's a "StreetComplete conspiracy from 2017" but data shows that before the implementation of the `maxspeed:type=IT:urban` answer for the Maxspeed quest there was no use of that tag. This tag was introduced while a more common and widespread `source:maxspeed=IT:urban` was already in use. No, it's not a SC conspiracy theory, but it's clear that the wrong tagging used by SC was forced in OSM.

@westnordost You can clearly see that the global usage prefers `source:maxspeed` ([1 736 149 cases](https://taginfo.openstreetmap.org/keys/source:maxspeed#overview)) instead of `maxspeed:type` ([459 103 cases](https://taginfo.openstreetmap.org/keys/source:maxspeed#overview)). I understand that in the UK the most used one is `maxspeed:type` (even though I don't understand why they prefer that, while everyone prefers `source:maxspeed`), but I think an app that's made to make mapping easier should use the most widespread tag, than force an obscure (or worse, a never-before-used) tag.

**Comment by mnalis** [comment] 2021-06-24 16:57
@Mannivu if you would read the talk wiki pages I linked above, you'd see that if anything, `source:maxspeed` tag is wrong, as it abuses whole `source:*` logic (ie. it does something completely different than all other `source:*` tags). 

Also, in your reply to westnorost you seem to completely ignore my paragraph when I tried to explain that **_most popular_** is **not** the same as **_best_**. Historically, even, the newer (and thus, by definition less used) tag is actually often better one (as people in practice learned problems of the older tag, and made new tag to handle it better). OSM Wiki is full of examples where old tags where replaced by better, newer tags that came later and were less used in start. 

Many of the tags you use today was at some point in time **_never-before-used_**, which you seem to regard as a "bad thing". It's not. As parable: we're not living in caves or at trees as we used to, even if they were quite **popular** back then - but we invented this **new** housing thing, which was **never-before-used** (at that time). And today, we mostly cringe at the idea of going back to living in caves or on the trees. 

But if you really think one of the tags is **better** (not more popular, but better), please do (as suggested before) start a discussion at [tagging mailing list](https://wiki.openstreetmap.org/wiki/Tagging_mailing_list) with your reasonings (but do firstly read what people have written before on that subject), and link to it back in this issue so interested people can jump in. Maybe consensus can be reached, and one (or both) of the tags deprecated. But it will take work and research on both pros and cons of all variants.
