### ISSUE TITLE
Awards and links has disappear

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5580] opened 2024-04-14 14:46 UTC
**How to Reproduce**
- Start app
- Go to your profile -> awards and links is not present (you need to scroll in blank space to see awards and links)

**Expected Behavior**
- Awards and links is visible when we switch to their tab

**Versions affected**
Android 14 - v57.2

**Comment by westnordost** [comment] 2024-04-14 18:10
Hm yeah, can reproduce. It kind of feels like a bug in RecyclerView. A quick search turns up 
https://stackoverflow.com/questions/45167282/recyclerview-doesnt-show-items-until-scrolling

However, maybe the awards and links should just be one of the first things I migrate to Jetpack Compose framework, instead of fixing code that is going to be thrown out, anyway.

**Comment by westnordost** [comment] 2024-04-28 17:10
Will be fixed when I merge the compose1 branch because these views are the first ones I migrated to Jetpack Compose.

**Comment by westnordost** [comment] 2024-05-17 10:57
Fixed by #5607

**Closed by westnordost** 2024-05-17 10:57 UTC
Labels: bug
