### ISSUE TITLE
Notification prompts to answer quests for nearby POIs

### ISSUE THREAD

**Issue by swedneck** [streetcomplete/StreetComplete#3997] opened 2022-04-29 18:31 UTC
Google maps gets a lot of data about POIs by prompting users to answer questions about places they've visited. 
It would be nice to have a similar system that users can opt into, where streetcomplete will run in the background and when the user has spent enough time within a certain distance of a POI (perhaps limited to things like businesses) a notification will pop up asking the user to answer some quests.

Currently one has to actively open streetcomplete to enter data, which means users can forget about it or simply not bother to open it depending on the trip. This system would allow for easier and more reliable contributions.

**Comment by 10992-osm** [comment] 2022-04-30 12:33
This is more or less a duplicate of #177 #48, #2470, and #2590, and possibly some other issues as well.

**Closed** 2022-04-30 12:34 UTC
Labels: duplicate
