### ISSUE TITLE
Sidewalk surface quest: Enable to change the sidewalk tag

### ISSUE THREAD

**Issue by cyclingcat** [streetcomplete/StreetComplete#3920] opened 2022-03-26 12:37 UTC
Hi there,

the sidewalk surface quest currently cannot be solved correctly if the `sidewalk` tag itself is wrong. For example, the quest asks for the sidewalk surfaces on both sides separately although a sidewalk exists on only one side (or vice versa), due to an earlier tagging error or a change at this place. Currently there is no other possibility than to leave a note, but this situation occured surprisingly often, at least during my first attempts with this new quest.

**Ideas:**

1. Give the user the possibility to answer "The sidewalk situation is other than shown here" (or similar, comparing to the "Other surface" menu item in the smoothness quest), which deletes the `sidewalk` tag - the sidewalk quest would immediately reappear and after this one is solved, the sidewalk surface quest reappears, which can be solved correctly afterwards.

2. Add a button "No sidewalk" to the selection of possible surfaces, which changes the `sidewalk` tag appropriately. This approach alone doesn't cover the situation when there are sidewalks on both sides of the street when it's currently mistagged as one-sided.

BTW: Contrary to the road surface quest, the list of the possible surfaces doesn't get reordered by recent choices. Is this a deliberate decision? For example, the fourth item "Concret lanes" (= "Fahrspuren aus Beton") always stays at its quite high position despite the fact that it probably won't get selected very often.

The cycling cat

**Comment by arrival-spring** [comment] 2022-03-26 20:42
(I implemented this quest)

I did think about this when making the quest (see https://github.com/streetcomplete/StreetComplete/issues/1593#issuecomment-1029403540 and https://github.com/streetcomplete/StreetComplete/pull/3735#issuecomment-1038111396)

And using https://ent8r.github.io/NotesReview/ I can find no open notes yet from this quest.

I think option 2 would not be consistent with other quests so would favour option 1.

Regarding reordering it's to do with the interface being used and it would take a fair bit of work to make it order by recently used.

**Comment by mnalis** [comment] 2022-03-27 00:50
I also think option 1 would be ideal.

I actually opened a note several days ago to raise this exact issue (https://www.openstreetmap.org/note/3095650)  after it happened to me several times, but didn't get to reporting it yet. You don't see it in notes list as I've opened note manually, not as answer to a quest (as that seems to block quests on that element, so I tend to avoid doing that)

**Comment by cyclingcat** [comment] 2022-03-27 07:41
> And using https://ent8r.github.io/NotesReview/ I can find no open notes yet from this quest.

Don't forget that this quest is disabled by default and thus probably not very heavily used with SC (yet).

> I think option 2 would not be consistent with other quests so would favour option 1.

So do I, furthermore this option would give the user the possibility to correct the incorrect sidewalk situation in any case while option 2 wouldn't.

> Regarding reordering it's to do with the interface being used and it would take a fair bit of work to make it order by recently used.

Such reordering already happens at the road surface quest - couldn't the approach taken there be reused?

The cycling cat

**Comment by arrival-spring** [comment] 2022-03-27 13:54
> So do I, furthermore this option would give the user the possibility to correct the incorrect sidewalk situation in any case while option 2 wouldn't.

Not every situation as the sidewalk surface quest is asked for any ways from residential to trunk with valid sidewalk tagging but the sidewalk quest has various other conditions to avoid being spammy with places that obviously won't have a sidewalk.

> Such reordering already happens at the road surface quest - couldn't the approach taken there be reused?

Probably, but not immediately straightforward

**Comment by westnordost** [comment] 2022-03-28 13:10
If this is implemented, it should be option 1. But I am not sure if this happens often enough that it is worthwile to implement, translate and maintain.

**Comment by cyclingcat** [comment] 2022-03-29 19:44
The past few days I concentrated on the new sidewalk surface quest and paid special attention on how often the feature mentioned in this ticket would have helped. The result of this survey (which is of course far from being representative):  In approximately 10% of all sidewalk surface quests the real sidewalk situation was different than shown, either for the entire length of the way or at least for some part of it. The latter situation occured surprisingly often; together with the option to split the way all situations I came across so far could be resolved within SC if option 1 was implemented (which would BTW be consistent with the smoothness quest.)

The cycling cat

**Comment by mnalis** [comment] 2022-03-30 00:28
I can confirm it happens here surprisingly often (just in todays relatively short walk I've found 3 wrong sidewalks). What worries me is that I'm not sure simple proposal **_"just remove sidewalk tagging and let SC ask them again"_** is going to work correctly -- many of the sidewalks seem to be tagged outside of SC, and SC seems to limits asking them on much more restricted set of ways then the mappers using other editors. (I've encountered that issue before too, but haven't yet had time to make quest in my fork "more spammy")  

So while that simple solution might remove sidewalk tagging, but then SC would ask for sidewalks again in many cases. Which is probably still better then leaving them incorrect, but far from ideal (which would be having SC user map them correctly).

Is it possible to force-chain another quest instead? I.e. when one answers `"The sidewalk situation is different then depicted here"` on `sidewalk surface quest`, that the `sidewalk quest` is invoked directly (i.e. check whether that road is eligible for `sidewalk quest` is skipped and assumed that this road is always eligible)

**Comment by arrival-spring** [comment] 2022-03-30 19:48
Since #3821 "invalid" sidewalk tagging is always resurveyed (on highway=service to trunk)

However, I think it might be too hacky to set e.g. `sidewalk=unknown`, even though only temporarily and even if in 99% of cases user then immediately tags it correctly.

**Comment by cyclingcat** [comment] 2022-04-13 11:17
Hi there,

the more I answer this quest the more I have to correct my earlier estimation of 10% erroneously tagged sidewalks. It's rather **15-20%**, and additionally to the aforementioned pattern "sidewalk differs along an OSM way" the situation "sidewalk is tagged as present on the left side while it's in fact on the right side" also occurs quite often. Maybe some early mappers haven't paid attention to the OSM way direction and used "left" and "right" in the direction they walked?

(Don't know if this is a local phenomenon though...)

The cycling cat

**Comment by westnordost** [comment] 2022-04-13 12:11
yeah don't worry, I am working on a solution

**Comment by westnordost** [comment] 2022-06-22 23:54
Ah, I can close this now. (Sidewalk layer)

**Closed by westnordost** 2022-06-22 23:54 UTC
Labels: enhancement

**Comment by FloEdelmann** [comment] 2022-06-23 07:33
For reference, see https://github.com/streetcomplete/StreetComplete/releases/tag/v45.0-alpha1

**Comment by peternewman** [comment] 2022-06-24 22:22
So can this only be done by switching to the sidewalk layer and editing it there?

**Comment by westnordost** [comment] 2022-06-24 22:43
Yes
