### ISSUE TITLE
Make it possible to show again “Can't say” notes/the original question

### ISSUE THREAD

**Issue by blipp** [streetcomplete/StreetComplete#1029] opened 2018-04-22 17:00 UTC
As discussed in #962 I am creating a dedicated issue for this, by copy-pasting my original comment, and adding a paragraph.

Some time ago I created some notes via “Can't say” on some road surface questions. Now I gained additional knowledge (ENT8R answered to one of my notes) and could answer the questions and mark the notes as done. But StreetComplete doesn't show neither the questions nor the notes. Which at the time I originally answered the questions was completely reasonable and expected, because back then these questions were done from my point of view. Now however, I would like to see them again.

I have “Show all notes” activated. I think I activated it right away when I installed StreetComplete.

You can see the notes I created here https://www.openstreetmap.org/user/bblipp/notes.
Interestingly, _one_ of the _questions_ I added a note for was shown again. I answered it and marked the note done on the OpenStreetMap website. It was this one https://www.openstreetmap.org/note/1282132.

Maybe StreetComplete could provide a list of notes created, with the option to re-answer them, or add more comments.

@blipp wrote:
>> I have “Show all notes” activated. I think I activated it right away when I installed StreetComplete.

@rugk wrote:
> Then all your notes should be shown. Maybe it takes some days, as they are likely cached.

Is there any knowledge about how many days and if this can be influenced? “Invalidate Quest Cache” in the settings didn't help.

For now I changed what I wanted to change using the editor on the OSM website, which was actually not so hard than I originally thought. There has been a lot of improvement in the online editor during the past years :)

**Comment by rugk** [comment] 2018-04-22 19:58
> Is there any knowledge about how many days and if this can be influenced? 

It depends on how fast new quests are downloaded, i.e. when you [often](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_StreetComplete_show_so_few_quests_when_I_first_start_the_app.3F) click the "Download new quests" button maybe they appaer.
Note that I may be wrong on this, maybe notes have some special handling anyway, compared to other quest types.

**Comment by matkoniecz** [comment] 2018-07-14 14:18
> interestingly, one of the questions I added a note for was shown again

I am not sure why it happened, but it was some bug (or maybe it was not shown in SC?)

https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/OsmNotesDownload.java#L146 specifically excludes notes created in StreetComplete

Maybe it can be an additional setting? Apparently at least some would want to see all notes (I disabled note filtering in my private fork).

@westnordost would you consider it as a good candidate for option?

**Comment by westnordost** [comment] 2018-09-12 21:33
Hmm, forgot about this issue.

So, notes you answered on already and notes you created with StreetComplete are never shown to the you, independent of the _"Show also notes not phrased as questions"_-setting.

Why do you think it makes sense to re-show these in the app?

**Comment by rugk** [comment] 2018-09-13 06:47
This could possibly be a dupe of https://github.com/westnordost/StreetComplete/issues/962, depending on what the reason for showing your own note is.

**Comment by westnordost** [comment] 2019-01-23 11:56
Closing because of inactivity. But to answer you in a bit more detail:

> Some time ago I created some notes via “Can't say” on some road surface questions. Now I gained additional knowledge (ENT8R answered to one of my notes) and could answer the questions and mark the notes as done. But StreetComplete doesn't show neither the questions nor the notes. Which at the time I originally answered the questions was completely reasonable and expected, because back then these questions were done from my point of view. Now however, I would like to see them again.

The quest will be downloaded again after the open note is resolved. Not immediately, but when the app downloads the quest type the note was about next time. If I remember correctly, this should be up to 2 weeks. So, there is a bit of delay, but the quest type will pop up again if it is not solved.

> “Invalidate Quest Cache” in the settings didn't help.

If you press invalidate quest cache, you can cross out the "up to 2 weeks" of my previous statement. The quest will pop up again immediately when this quest type is downloaded again. The quest types are downloaded in the order specified in the settings.

**Comment by smichel17** [comment] 2021-03-28 22:02
I'll add my +1 to this (and take over responding where OP left off). I would like to be able to see my own notes, that were created through SC. I think it would make sense to implement this by changing the notes setting to a 3-choice drop-down, between "Only other people's notes phrased as questions", "Only other people's notes", "All notes".

The reason I would like to see my own notes is that sometimes I want to go back and add more detail to them (or sometimes close them). I seldom edit OSM using any editor besides SC. Maybe once or twice a year I go to openstreetmap.org and try to follow up on some of my notes, but generally I leave that to other people. Also, sometimes I realize something a minute after I leave the note and want to update it before I forget. This results in situations like this: https://www.openstreetmap.org/#map=19/42.32152/-72.67986&layers=N

**Comment by westnordost** [comment] 2021-03-28 22:40
Actually, something like this is being implemented in the dev branch.

- As before, you can "unhide all" in the settings of course.
- You are now able to undo hidings of quests (for up to a day, the default "max history age")
- There shall be a more powerful undo-button - i.e. one that shows the history of the last day. <- this one is not done yet, requires more effort. Maybe will not be part of the first release with the new architecture.

So that covers the use case for which this ticket was created for. The other ("I want to see my own notes, and comment on them etc") is not planned. The reasons for not showing notes one has contributed to already are:
- then the marker does not disappear if / no animation when the user contributed to it. Might be confusing
- when you already contributed, it is unlikely that you can contribute even more.
But anyway, if you really want to see this feature, it would be possible technically to do this but please open a new ticket for that and explain in detail the use case(s) for which it would be useful. Then, other people have the chance to also 👍 that so I have some bearing whether this is actually something that more people would like to have.

**Closed by westnordost** 2021-03-28 22:40 UTC
Labels: feedback required

**Comment by westnordost** [comment] 2021-03-28 22:43
![device-2021-03-29-004244](https://user-images.githubusercontent.com/4661658/112770615-be8d7d00-9027-11eb-85e7-6c13441f90db.png)

**Comment by smichel17** [comment] 2021-03-29 01:10
Ah. I'll be honest, while I've seen a couple notes, I've never actually contributed to one before, so I didn't realize that they disappear like quests once you've added a message to them. I assumed that notes were kind of outside the quest system — that they would remain visible and that I would not get a star for adding a comment.

I guess the way it is makes sense for notes phrased as questions… maybe? What happens if I answer a note with a question, and then the original asker adds a follow-up question (say, because my answer was not detailed enough)? Is it possible to change the behavior so the note is only hidden if you are the *most recent* person to comment on it?

The new behavior is enough for most of my use case, so I won't open a new issue. It *would* be nice if I could manage my notes from SC, but it's rare enough that I don't think it's worth complicating the UI for.

**Comment by mnalis** [comment] 2021-03-29 04:56
I\m quite heavy notes producer (and consumer), so I've opened new issue as suggested, so people should vote on #2692 if they think they would like it.

**Comment by smichel17** [comment] 2021-03-29 11:47
In https://github.com/streetcomplete/StreetComplete/issues/1029#issuecomment-809002077, I said:

> I've never actually contributed to one before, so I didn't realize that they disappear like quests once you've added a message to them. I assumed that notes were kind of outside the quest system — that they would remain visible and that I would not get a star for adding a comment.

My rationale was basically, "Quests are missing tags. You get stars for answering quests (updating tags). Adding a comment to a note doesn't update any tags, so it probably doesn't count as a quest."

Grab bag of random thoughts in no particular order:

- Notes feel more like a meta-level discussion for "power users" (ie people who are already quite involved in OSM).
- I'd almost expect notes to show up in a separate part of the interface (e.g. under my profile), and to get notifications when someone comments on one of my notes, the same way it works for messages (I think)

**Comment by mnalis** [comment] 2021-03-31 23:41
@smichel17, to comment on your random thoughts:

- Notes are basically designed to allow you to use **free-form of natural human language to describe some error or omission on a map** that you (or your app) does not know how (or don't have time) to correct immediately. Then later either more experienced users (or you yourself if you are one of them) can fix it on the map in best way using more advanced editors (when you get to them). So in a way, they are in fact often more oriented towards total newbies (although there is also significant amount of experienced users who prefer to use them in their workflow).

- yes, Notes do show under your profile on www.openstreetmap.org. Click on your username on upper-right corner, then on `My Profile` and then on `My notes` on top-left part of the screen. (and yes, you do get notifications when people act on them (commenting or closing) - they might ask you for clarifications etc.
