### ISSUE TITLE
Multiple copies of same POI added by SC at same location

### ISSUE THREAD

**Issue by rjw62** [streetcomplete/StreetComplete#5608] opened 2024-04-29 22:17 UTC
In the OSM changset at https://www.openstreetmap.org/changeset/149604787 a SC user has added three copies of the same "William Hill" POI with identical coordinates.

I assume this wasn't intentional by the user. I don't know if this is a direct bug in SC (i.e. the user only added it once and SC created the duplicates) or just the interface didn't make it obvious that's what the user was doing. (The fact that two of the node IDs are close but the third is about 10k away makes me wonder if there's some sort of retry-after-apparent-upload-failure issue going on.)

Either way it would be good if SC could prevent such duplication. If it was caused by the user accidentally creating the POI three times, perhaps there could be a check for POIs with the same coordinates, or the interface could make it more obvious if there are overlapping POIs about to be uploaded.

**Comment by westnordost** [comment] 2024-04-29 23:11
Hmm, I imagine the user could have tapped the OK button thrice, maybe in that moment the app was not responding for some reason so he thought the tap did not register.

I tried to reproduce by tapping really fast, but to no avail. I will check in the code, I thought there is already something in place that would not allow any subsequent taps on the button.

**Comment by rjw62** [comment] 2024-04-30 06:33
FYI: here's another example of the same thing happening from the same user: https://www.openstreetmap.org/changeset/136886694 .

**Comment by westnordost** [comment] 2024-04-30 14:57
How do you find these, by the way?

On automatically detecting these: This would not solve the issue if the error is somewhere during the upload. E.g. it gets uploaded twice because an upload error is reported on the first try but for some reason the upload went through regardless. And for preventing that it is a mistake made in the UI, we already have some things in place, such as disabling the OK button after the first tap and only being able to add things at a high zoom level at which all the other shops are also visible on the map.

**Comment by rjw62** [comment] 2024-04-30 19:17
I found those examples because they were detected by an OSM comparison tool I run: https://osm.mathmos.net/chains/ . One of the things it flags is OSM objects with a brand:wikidata tag that can't be matched to a chain's public list of branches, and are close to another OSM object with the same brand:wikidata tag.

I don't know enough about the OSM API or how SC interacts with it. But my guess would be that the cause is some sort of partial upload where the OSM API response either isn't seen or isn't correctly interpreted by SC. Or there's an issue with the OSM API not sending an accurate response.

**Comment by mnalis** [comment] 2024-04-30 21:05
Could it be related to this issues which weren't fixed until `v57.2`  (https://github.com/streetcomplete/StreetComplete/issues/5523, https://github.com/Helium314/SCEE/issues/445)? 

I see @peternewman still used `v56.1` (or `53.0-beta1`) on those reported changesets, so perhaps it could just be due to using old SC versions?

**Comment by mnalis** [comment] 2024-04-30 21:09
> How do you find these, by the way?

One way would be using Keepright's _"multiple nodes on the same spot"_ check, e.g. [here](https://www.keepright.at/report_map.php?zoom=14&lat=48.20808&lon=16.37221). That check isn't specific to StreetComplete, though, so would find all such errors from all editors.

**Comment by westnordost** [comment] 2024-04-30 21:47
> Could it be related to this issues which weren't fixed until v57.2 (https://github.com/streetcomplete/StreetComplete/issues/5523, https://github.com/Helium314/SCEE/issues/445)?

> I see @peternewman still used v56.1 (or 53.0-beta1) on those reported changesets, so perhaps it could just be due to using old SC versions?

Oh! Thank you for finding this! This must be it, i.e. it is a duplicate of #5523!

**Closed by westnordost** 2024-04-30 21:47 UTC
Labels: bug, feedback required
