### ISSUE TITLE
Add postboxes to "Things" layer

### ISSUE THREAD

**Issue by InsertUser** [streetcomplete/StreetComplete#5584] opened 2024-04-17 12:56 UTC
### General
Affected tag(s) to be modified/added: [`amenity=post_box`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box) (on new element)
Question asked: None, just add postboxes to the list of things that can be viewed and added on the Things layer.

I am suggesting this mostly because I thought I'd found a postbox that was missing from OSM data when I didn't see it on the things view, only to find that they weren't on the list for new objects either. Considering the follow-up questions that StreetComplete already asks for these feature and their relative utility to the general public compared with existing "Things" like street cabinets I think this would be a valuable addition. 

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
Existing `amenity=post_box` elements would be shown and the ability to create new ones added to the existing ➕ menu that is on screen for the things layer. 

**Metadata needed:** 
None. Existing rules as to possible follow-up quests should be triggered as normal for a minimally tagged post box as for a new defibrillator. 

**Proposed UI:**
Post boxes could be represented either by the symbol used in OSM carto (![link][1]) or with a simplified version of the existing envelope icon used for other StreetComplete post box quests. 

The listing in the "add feature" menu should surface in the search for common variants in naming this feature, mainly "postbox", "post box", "collection box", "mailbox", "letter box" or "drop box" (per OSM wiki synonyms). For the EN-GB language version "Post box" is probably sufficient text, but for EN-US "Mailbox for sending letters" might be required to avoid ambiguity with `amenity=letter_box`. 

[1]: https://wiki.openstreetmap.org/w/images/thumb/d/d4/Post_box-12.svg/12px-Post_box-12.svg

**Comment by FloEdelmann** [comment] 2024-04-17 13:20
Thanks for the elaborate feature request. Unfortunately, it's a duplicate of #5572, which in turn is basically a duplicate of the blocked #4916.

**Closed by FloEdelmann** 2024-04-17 13:20 UTC
Labels: duplicate, blocked
